import assert from 'node:assert/strict';
import test from 'node:test';

import {
  redactProjectHistoryText,
  resolveProjectHistoryIdentityEntries,
} from './project-history-redaction.ts';
import { renderProjectHistory } from './project-history-cli.ts';
import type { ProjectHistoryDocument } from '@papercusp/plan-parser/project-history';

const ownerName = ['M', 'organ'].join('');
const homeUser = ['private', 'user'].join('');
const machineUser = ['runtime', '-user'].join('');
const machineHost = ['runtime', '-host'].join('');
const machineEmail = ['runtime', '@example.invalid'].join('');
const machineGitName = ['Runtime', ' Person'].join('');

test('redacts owner tags, home paths, and identity literals from generated prose', () => {
  const source = [
    `[owner:${ownerName} 2026-08-15] generated by ${machineGitName}`,
    `OWNER MANDATE (${ownerName}, 2026-08-15): keep the evidence`,
    `/home/${homeUser}/project and /Users/${homeUser}/project`,
    `-home-${homeUser}-project`,
    `${machineUser} ${machineHost} ${machineEmail}`,
  ].join('\n');

  const redacted = redactProjectHistoryText(source, [
    ['build-user-name', machineUser],
    ['build-hostname', machineHost],
    ['build-git-email', machineEmail],
    ['build-git-name', machineGitName],
  ]);

  assert.equal(redacted, [
    '[owner 2026-08-15] generated by owner',
    'OWNER MANDATE (2026-08-15): keep the evidence',
    '/home/builduser/project and /Users/builduser/project',
    '-home-builduser-project',
    'builduser buildhost owner@example.invalid',
  ].join('\n'));
});

test('render-time redaction leaves the source text and safe placeholders intact', () => {
  const source = `/home/${homeUser}/project [owner:${ownerName} 2026-08-15]`;
  const redacted = redactProjectHistoryText(source, [['build-user-name', machineUser]]);

  assert.equal(source, `/home/${homeUser}/project [owner:${ownerName} 2026-08-15]`);
  assert.equal(redacted, '/home/builduser/project [owner 2026-08-15]');
  assert.equal(redactProjectHistoryText('[owner 2026-08-15] /home/builduser/project'),
    '[owner 2026-08-15] /home/builduser/project');
});

test('renderProjectHistory sanitizes both portable output formats without mutating the document', () => {
  const sourceMarkdown = `/home/${homeUser}/project [owner:${ownerName} 2026-08-15]`;
  const document = {
    schemaVersion: 2,
    project: { id: 'demo', name: 'Demo', repository: null },
    source: {
      kind: 'papercusp-plan-export',
      workspace: 'workspace',
      harness: 'demo',
      planPrefix: 'demo-',
      generatedAt: '2026-08-15T00:00:00.000Z',
      planCount: 1,
      generator: 'papercusp project-history generate',
    },
    plans: [{
      slug: 'demo-plan',
      title: 'Demo plan',
      status: 'shipped',
      updatedAt: null,
      contentHash: 'hash',
      markdown: sourceMarkdown,
      frontmatter: {},
      items: [],
      decisions: [],
      completedItems: [],
      validationSummary: { total: 0, passed: 0, failed: 0, validating: 0, todo: 0, requiringTest: 0 },
    }],
  } satisfies ProjectHistoryDocument;
  const entries = [['build-user-name', machineUser]] as const;

  const json = renderProjectHistory(document, 'json', 'PROJECT_HISTORY', entries);
  const typescript = renderProjectHistory(document, 'typescript', 'PROJECT_HISTORY', entries);

  for (const rendered of [json, typescript]) {
    assert.ok(!rendered.includes(ownerName));
    assert.ok(!rendered.includes(homeUser));
    assert.match(rendered, /\/home\/builduser\/project/);
    assert.match(rendered, /\[owner 2026-08-15\]/);
  }
  assert.equal(document.plans[0]?.markdown, sourceMarkdown);
});

test('resolves Git identities through the caller repository without requiring a checkout identity', () => {
  const calls: Array<[string, string]> = [];
  const entries = resolveProjectHistoryIdentityEntries('/portable/repo', (cwd, key) => {
    calls.push([cwd, key]);
    return key === 'user.email' ? machineEmail : machineGitName;
  });

  assert.deepEqual(calls, [
    ['/portable/repo', 'user.email'],
    ['/portable/repo', 'user.name'],
  ]);
  assert.ok(entries.some(([key, literal]) => key === 'build-git-email' && literal === machineEmail));
  assert.ok(entries.some(([key, literal]) => key === 'build-git-name' && literal === machineGitName));
});
