'use client';

/**
 * Visual regression pane for the design tab. Plan §12.
 *
 * Surfaces Lost Pixel baseline / current / diff PNGs from
 * apps/operator/lostpixel-{baseline,current,diff}/. Read-only in
 * v0.1; baseline-update and on-demand re-capture are deferred
 * (those are CI / shell-out concerns, not UI).
 *
 * Items with a non-empty diff PNG (>200 bytes) are flagged as
 * regressions and sort to the top.
 */
import { useState, useMemo } from 'react';
import { useQueryState, parseAsStringEnum } from 'nuqs';
import { useSyncQuery } from '@papercusp/sync';

interface RegressionItem {
  name: string;
  hasBaseline: boolean;
  hasCurrent: boolean;
  hasDiff: boolean;
  hasRegression: boolean;
  baselineMtime: number | null;
  currentMtime: number | null;
  diffMtime: number | null;
}

interface RegressionsResponse {
  counts: { baseline: number; current: number; diff: number; regressions: number };
  items: RegressionItem[];
}

const mutedText = 'var(--fg-mute)';
const dimText = 'var(--fg-dim)';
const panelBorder = 'var(--border)';
const warnText = 'var(--warn)';
const badText = 'var(--bad)';

export default function RegressionPane() {
  const [filter, setFilter] = useQueryState('regressionFilter', parseAsStringEnum<'all' | 'regressions' | 'clean'>(['all', 'regressions', 'clean']).withDefault('all'));

  const q = useSyncQuery<RegressionsResponse>({
    queryName: 'designRegressions.list',
  });
  const payload = q.data?.[0] ?? null;

  const items = useMemo(() => {
    const all = payload?.items ?? [];
    const filtered = filter === 'all'
      ? all
      : filter === 'regressions'
        ? all.filter((i) => i.hasRegression)
        : all.filter((i) => !i.hasRegression);
    // Regressions on top, then alphabetical by name
    return [...filtered].sort((a, b) => {
      if (a.hasRegression !== b.hasRegression) return a.hasRegression ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
  }, [payload, filter]);

  if (q.loading) return <p style={{ color: mutedText }}>Loading regressions…</p>;
  if (q.error) return <p style={{ color: badText }}>Failed: {q.error.message}</p>;

  const counts = payload?.counts ?? { baseline: 0, current: 0, diff: 0, regressions: 0 };

  return (
    <div>
      <header style={{ display: 'flex', alignItems: 'baseline', gap: 16, marginBottom: 12 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, margin: 0 }}>
          Visual regression{' '}
          <span style={{ color: mutedText, fontWeight: 400 }}>
            {counts.baseline} baselines · {counts.current} current
          </span>
        </h2>
        {counts.regressions > 0 && (
          <span
            style={{
              padding: '2px 8px',
              borderRadius: 10,
              background: 'var(--warn-bg)',
              color: warnText,
              fontSize: 12,
              fontWeight: 500,
            }}
          >
            {counts.regressions} regression{counts.regressions === 1 ? '' : 's'}
          </span>
        )}
        <nav style={{ marginLeft: 'auto', display: 'flex', gap: 4 }}>
          {(['all', 'regressions', 'clean'] as const).map((b) => (
            <button
              key={b}
              type="button"
              onClick={() => setFilter(b)}
              style={{
                padding: '4px 8px',
                borderRadius: 4,
                border: `1px solid ${filter === b ? 'var(--accent)' : panelBorder}`,
                background: filter === b ? 'color-mix(in oklab, var(--accent), transparent 84%)' : 'transparent',
                color: filter === b ? 'var(--fg)' : dimText,
                cursor: 'pointer',
                fontSize: 12,
                textTransform: 'capitalize',
              }}
            >
              {b}
            </button>
          ))}
        </nav>
      </header>
      <p style={{ fontSize: 12, color: mutedText, marginTop: 0, marginBottom: 16 }}>
        Generated by Lost Pixel from <code>./storybook-static</code>. Run{' '}
        <code>npm run lostpixel</code> to refresh the current set;{' '}
        <code>npm run lostpixel:update</code> to overwrite baselines.
      </p>
      {items.length === 0 ? (
        <p style={{ color: mutedText }}>No items match.</p>
      ) : (
        <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 16 }}>
          {items.map((it) => (
            <RegressionRow key={it.name} item={it} />
          ))}
        </ul>
      )}
    </div>
  );
}

function RegressionRow({ item }: { item: RegressionItem }) {
  return (
    <li
      style={{
        border: `1px solid ${panelBorder}`,
        borderLeft: item.hasRegression ? `3px solid ${warnText}` : `1px solid ${panelBorder}`,
        borderRadius: 6,
        padding: 12,
        background: item.hasRegression ? 'var(--warn-bg)' : 'var(--bg-1)',
      }}
    >
      <header style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 8 }}>
        <code style={{ fontSize: 13, color: 'var(--fg)', fontWeight: 500 }}>
          {item.name.replace(/\.png$/, '')}
        </code>
        {item.hasRegression && (
          <span style={{ fontSize: 11, color: warnText, fontWeight: 500 }}>regression</span>
        )}
        {!item.hasBaseline && (
          <span style={{ fontSize: 11, color: badText }}>missing baseline</span>
        )}
      </header>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
        <Cell label="Baseline" url={item.hasBaseline ? `/api/design/regressions/baseline/${item.name}` : null} />
        <Cell label="Current" url={item.hasCurrent ? `/api/design/regressions/current/${item.name}` : null} />
        <Cell label="Diff" url={item.hasDiff ? `/api/design/regressions/diff/${item.name}` : null} />
      </div>
    </li>
  );
}

function Cell({ label, url }: { label: string; url: string | null }) {
  return (
    <div>
      <div style={{ fontSize: 11, color: mutedText, marginBottom: 4, textTransform: 'uppercase' }}>
        {label}
      </div>
      {url ? (
        <a href={url} target="_blank" rel="noreferrer" style={{ display: 'block' }}>
          <img
            src={url}
            alt={label}
            style={{
              width: '100%',
              height: 'auto',
              border: `1px solid ${panelBorder}`,
              borderRadius: 4,
              background:
                'repeating-conic-gradient(var(--bg-2) 0% 25%, transparent 0% 50%) 50% / 16px 16px',
              display: 'block',
            }}
          />
        </a>
      ) : (
        <div
          style={{
            border: `1px dashed ${panelBorder}`,
            borderRadius: 4,
            padding: 16,
            textAlign: 'center',
            color: mutedText,
            fontSize: 12,
          }}
        >
          (none)
        </div>
      )}
    </div>
  );
}
