/**
 * greenlit-now-stamp.ts — stamp a plan's `## Now` block when a Blender/Scout
 * DRAFT is greenlit (draft → ready).
 *
 * WHY. This is the mirror image of {@link ./terminal-now-stamp}, and it fails
 * the same way for the same reason: `plans:set-plan-status` rewrites only the
 * frontmatter `status:` line (`flipPlanFrontmatterStatus`, set-plan-status.ts)
 * and never touches `now_state`. The terminal direction was fixed; the
 * GREENLIGHT direction was not.
 *
 * Every Blender-generated draft ships a `## Now` that says, verbatim:
 *
 *   **State:** Draft — autonomously generated by the Blender loop … Awaiting
 *   Mug/owner triage; not active until greenlit.
 *
 * An agent then greenlights the plan the documented way — the exact action that
 * draft's own **Next** names — and that sentence stays. The plan is now live,
 * its items auto-promote into the claimable pool (WI-1574), and the artifact a
 * claiming agent reads to recover intent still tells them the work was never
 * approved.
 *
 * Measured on papercusp 2026-08-18 (WI-39804): SEVEN plans sat at
 * `status='ready'` with `now_state ILIKE '%not active until greenlit%'`. Six
 * were flipped by one agent inside a ~700ms triage pass
 * (`harness_shared.coord_event_log`, `status_changed draft→ready`,
 * 2026-08-16T14:02:48–49Z) — deliberate greenlights, every one. Two of two
 * items I pulled from that population cost a full wake each to re-establish
 * that the plan really was approved.
 *
 * The failure is worse than a stale note, because the stale text speaks to
 * exactly the question the reader is asking. A resuming agent's own caution
 * ("don't build from an un-ratified draft") is the thing that gets weaponised:
 * the more careful the agent, the more likely it refuses live work. This repo
 * already settles the precedence — terminal-now-stamp.ts's banner reads "Read
 * frontmatter `status`, not this prose, to learn whether a plan is live" — but
 * a rule only helps the agent who has already read it, which is why the lie has
 * to be corrected at the artifact instead.
 *
 * DESIGN — deliberately the narrowest thing that works:
 *   • PREPEND-ONLY, like the terminal stamp. The author's text survives verbatim
 *     beneath the banner, so nothing is destroyed and no "does this prose read
 *     as approved?" classifier is needed.
 *   • Fires ONLY on the machine-generated draft marker, never on a hand-written
 *     Now. A human/agent-authored Now block is left completely alone — this
 *     repairs a known autogenerated lie, it does not police prose.
 *   • The `**Next:**` field is rewritten only when it is still the Blender
 *     review-loop note (that step is what just completed). A Next someone
 *     actually wrote is preserved.
 */

import { parsePlan } from './parser';
import { replaceNowBlock } from './set-now';

/**
 * Sentinel that makes the stamp idempotent. Matched against the WHOLE existing
 * Now block, so re-flipping ready→draft→ready never nests a second banner.
 * Deliberately a literal that no human writes by hand.
 */
export const GREENLIT_NOW_STAMP_MARK = '✅ PLAN GREENLIT';

/**
 * The load-bearing false sentence in the Blender draft template
 * (`scout-plan-draft.ts` → `buildScoutPlanTemplate`). This is the claim that
 * misleads a claiming agent once the plan is live, so it is what we detect.
 *
 * Pinned to the real template by greenlit-now-stamp.test.ts: if Scout's wording
 * changes, that test fails rather than this detector silently going quiet.
 */
const DRAFT_NOT_ACTIVE_RE = /not active until greenlit/i;

/**
 * The Blender review-loop **Next** (`SCOUT_DRAFT_LOOP_NOTE`). Detected by its
 * distinctive clause so a plan whose Next was rewritten by hand keeps it.
 */
const REVIEW_LOOP_NEXT_RE = /promotes?\s+it\s+to\s+greenlight/i;

/** Where the first `**State:**` / `**Next:**` marker begins, or -1. */
const FIRST_MARKER_RE = /\*\*(?:State|Next):\*\*/i;

/**
 * Return the plan body with its `## Now` block stamped as greenlit, or `null`
 * when there is nothing to do:
 *   - the target status is not `ready`
 *   - the plan has no `## Now` block (never invent one)
 *   - the Now block does not carry the Blender draft's "not active until
 *     greenlit" marker (a hand-written Now is not ours to rewrite)
 *   - the block is already stamped (idempotent)
 *
 * Pure — no I/O, no clock beyond the injected `today`. Callers splice the result
 * into the same locked write as the status flip, so the stamp and the status can
 * never disagree, not even transiently.
 */
export function stampGreenlitNowBlock(
  body: string,
  status: string,
  today: Date = new Date(),
): string | null {
  if (status !== 'ready') return null;

  const now = parsePlan(body).now;
  if (!now) return null;
  if (now.raw.includes(GREENLIT_NOW_STAMP_MARK)) return null;
  if (!DRAFT_NOT_ACTIVE_RE.test(now.raw)) return null;

  const iso = today.toISOString().slice(0, 10);
  const banner =
    `${GREENLIT_NOW_STAMP_MARK} — APPROVED ${iso}. This plan is LIVE: its open items are ` +
    `real, claimable work and its Design is a ratified spec. Anything below this line is the ` +
    `pre-greenlight draft note, kept for history — it described the plan while it was still ` +
    `awaiting review, so do NOT read it as a reason to leave this work alone or to re-verify ` +
    `that the plan was approved. Read frontmatter \`status\`, not this prose, to learn whether ` +
    `a plan is live (stamped by plans:set-plan-status).`;

  // Content the parser attributes to neither field: prose written between the
  // `## Now` heading and the first **State:**/**Next:** marker. `replaceNowBlock`
  // rewrites the whole section, so carry it or it is dropped.
  const markerAt = now.raw.search(FIRST_MARKER_RE);
  const preamble = markerAt > 0 ? now.raw.slice(0, markerAt).trim() : '';
  // A Now block written as free prose (no markers at all) parses to empty
  // state+next with everything in `raw` — carry the whole thing.
  const freeProse = !now.state && !now.next ? now.raw.trim() : '';

  const state = [banner, preamble, now.state, freeProse].filter(Boolean).join('\n\n');

  // Only the review-loop Next is superseded by the greenlight — that IS the step
  // that just completed. Anything else is someone's real plan; keep it.
  const next =
    !now.next || REVIEW_LOOP_NEXT_RE.test(now.next)
      ? 'Review is COMPLETE — this plan is greenlit. Work its open items (see `plans:items`; ' +
        'a ratified plan\'s open items auto-promote to work-items on start).' +
        (now.next ? ` (Pre-greenlight next, no longer actionable: ${now.next})` : '')
      : now.next;

  return replaceNowBlock(body, state, next);
}
