/**
 * capabilities/pg-stores.ts — the production capability stores over an injected
 * postgres-js handle, backing coord_topics / coord_entity_subscriptions /
 * coord_threads / coord_thread_posts / coord_links (migration 123). Same host
 * couplings as the sibling PG seams: `getSql`, `ensureSchema`, a
 * construction-bound `workspaceId`. They satisfy the SAME conformance suites as
 * the in-memory doubles (capabilities/conformance.ts).
 *
 * `ensureCoordCapabilityTables` mirrors migration 123 so the package's own
 * vitest rig can stand the schema up standalone; the operator passes a no-op
 * ensureSchema (schema is migrations-only — repo storage policy).
 */

import type { Sql } from 'postgres';
import { DEFAULT_COORD_WORKSPACE } from '../event-log/pg-log';
import { newMsgId } from '@papercusp/pubsub-substrate/core';
import {
  type CreateTopicInput,
  type DeliveryMode,
  type LinkableStore,
  type LinkRow,
  type ObjectRef,
  type SubscribableStore,
  type SubscribeInput,
  type SubscriptionRow,
  type SubscriptionTargetKind,
  type ThreadableStore,
  type ThreadPostRow,
  type ThreadRow,
  type TopicRow,
  type TopicStore,
} from './types';
import { LinkBackedTaggable } from './taggable';

export interface PgCapabilityStoreOptions {
  /** The org Postgres handle (postgres-js tagged template). Called per use. */
  getSql: () => Sql;
  /** Ensure the coord_* capability tables exist before first use (no-op in the
   *  operator; ensureCoordCapabilityTables on the package test rig). */
  ensureSchema: () => Promise<void>;
  /** Coordination scope (parity with the sibling coord_* stores). Default 'default'. */
  workspaceId?: string;
  /** Per-call workspace resolver (workspace-data-isolation-leaks F-C1 / engineer-issues
   *  per-workspace). When provided AND non-empty, OVERRIDES `workspaceId` on every
   *  read/write — so a shared store can scope to the request's active workspace. Falls
   *  back to `workspaceId` / 'default'. Additive: unused unless passed. */
  getWorkspaceId?: () => string;
}

/** Normalize a timestamptz (Date under postgres-js, or a string) to ISO. */
function tsToIso(v: unknown): string {
  if (v instanceof Date) return v.toISOString();
  return new Date(v as string).toISOString();
}
function tsToIsoOrNull(v: unknown): string | null {
  return v == null ? null : tsToIso(v);
}

/** Create the five capability tables + their indexes if absent. Idempotent.
 *  Mirrors libs/papercusp/libs/db/sql/123-coordination-substrate.sql.
 *
 *  ONE DELIBERATE DIVERGENCE from that migration (data-scoping-audit-2026-06-22
 *  P-007 / D-005): `workspace_id` carries NO `DEFAULT 'default'` here. The
 *  migration still has it on the live tables; dropping it there is the separate,
 *  owner-attended step. Verified before removing it: of 130 INSERT sites against
 *  the coord tables across the staging AND release trees plus the migration SQL,
 *  ZERO production writers omit the column — every omitter is a test fixture. So
 *  a fresh/embedded DB bootstrapped here behaves identically today, and the
 *  divergence runs in the SAFE direction: a NEW writer that forgets the scope
 *  fails at test time instead of silently writing a cross-tenant 'default' row.
 *  Do not "restore fidelity" by adding the default back — reconcile by dropping
 *  it in the migration instead. */
export async function ensureCoordCapabilityTables(sql: Sql): Promise<void> {
  await sql`CREATE SCHEMA IF NOT EXISTS harness_shared`;
  await sql`
    CREATE TABLE IF NOT EXISTS harness_shared.coord_topics (
      workspace_id text NOT NULL,
      slug         text NOT NULL,
      title        text,
      description  text NOT NULL DEFAULT '',
      created_by   text,
      merged_into  text,
      created_at   timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (workspace_id, slug)
    )`;
  await sql`
    CREATE TABLE IF NOT EXISTS harness_shared.coord_entity_subscriptions (
      id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workspace_id  text NOT NULL,
      subscriber_id text NOT NULL,
      target_kind   text NOT NULL,
      target_ref    text NOT NULL,
      delivery_mode text NOT NULL DEFAULT 'full',
      expires_ts    timestamptz,
      created_at    timestamptz NOT NULL DEFAULT now(),
      cancelled_at  timestamptz,
      follow_blockers boolean NOT NULL DEFAULT FALSE,
      derived_from_kind text,
      derived_from_ref text,
      -- Mirror the migration-created constraint (123-coordination-substrate.sql +
      -- 429-coord-entity-subscriptions-allow-fleet-kind.sql +
      -- 568-coord-entity-subscriptions-allow-event-kind.sql). This bootstrap DDL is
      -- used by tests + fresh embedded DBs; it MUST carry the SAME target_kind check
      -- as prod, or a too-strict/missing constraint drifts undetected — exactly the
      -- gap behind EI-5904, where fleet:delivery ('fleet' kind) passed every test yet
      -- violated the prod check. Keep this list in sync with the migration.
      CONSTRAINT coord_entity_subscriptions_kind_check
        CHECK (target_kind = ANY (ARRAY['topic'::text, 'object'::text, 'fleet'::text, 'event'::text]))
    )`;
  await sql`ALTER TABLE harness_shared.coord_entity_subscriptions ADD COLUMN IF NOT EXISTS follow_blockers boolean NOT NULL DEFAULT FALSE`;
  await sql`ALTER TABLE harness_shared.coord_entity_subscriptions ADD COLUMN IF NOT EXISTS derived_from_kind text`;
  await sql`ALTER TABLE harness_shared.coord_entity_subscriptions ADD COLUMN IF NOT EXISTS derived_from_ref text`;
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS coord_entity_subscriptions_active_uq
      ON harness_shared.coord_entity_subscriptions (workspace_id, subscriber_id, target_kind, target_ref)
      WHERE cancelled_at IS NULL`;
  await sql`
    CREATE INDEX IF NOT EXISTS coord_entity_subscriptions_target_idx
      ON harness_shared.coord_entity_subscriptions (workspace_id, target_kind, target_ref)
      WHERE cancelled_at IS NULL`;
  await sql`
    CREATE TABLE IF NOT EXISTS harness_shared.coord_threads (
      workspace_id text NOT NULL,
      thread_id    text NOT NULL,
      parent_kind  text NOT NULL,
      parent_ref   text NOT NULL,
      title        text,
      created_by   text,
      created_at   timestamptz NOT NULL DEFAULT now(),
      last_post_at timestamptz,
      post_count   integer NOT NULL DEFAULT 0,
      harness_slug text,
      origin       text NOT NULL DEFAULT 'local',
      author_pubkey text,
      PRIMARY KEY (workspace_id, thread_id)
    )`;
  // Federation columns (distributed-coordination-shared-harness-2026-06-04 Track A):
  // idempotently migrate a table that predates them. The federation MIGRATION
  // (149) adds the same columns + capture triggers + fed indexes on the live DB.
  await sql`ALTER TABLE harness_shared.coord_threads ADD COLUMN IF NOT EXISTS harness_slug text`;
  await sql`ALTER TABLE harness_shared.coord_threads ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'local'`;
  await sql`ALTER TABLE harness_shared.coord_threads ADD COLUMN IF NOT EXISTS author_pubkey text`;
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS coord_threads_parent_uq
      ON harness_shared.coord_threads (workspace_id, parent_kind, parent_ref)`;
  await sql`
    CREATE TABLE IF NOT EXISTS harness_shared.coord_thread_posts (
      id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workspace_id text NOT NULL,
      thread_id    text NOT NULL,
      author_id    text,
      body         text NOT NULL DEFAULT '',
      created_at   timestamptz NOT NULL DEFAULT now(),
      harness_slug text,
      origin       text NOT NULL DEFAULT 'local',
      author_pubkey text,
      post_msg_id  text
    )`;
  await sql`ALTER TABLE harness_shared.coord_thread_posts ADD COLUMN IF NOT EXISTS harness_slug text`;
  await sql`ALTER TABLE harness_shared.coord_thread_posts ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'local'`;
  await sql`ALTER TABLE harness_shared.coord_thread_posts ADD COLUMN IF NOT EXISTS author_pubkey text`;
  await sql`ALTER TABLE harness_shared.coord_thread_posts ADD COLUMN IF NOT EXISTS post_msg_id text`;
  await sql`
    CREATE INDEX IF NOT EXISTS coord_thread_posts_thread_idx
      ON harness_shared.coord_thread_posts (workspace_id, thread_id, id)`;
  await sql`
    CREATE TABLE IF NOT EXISTS harness_shared.coord_links (
      id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workspace_id text NOT NULL,
      src_kind     text NOT NULL,
      src_ref      text NOT NULL,
      dst_kind     text NOT NULL,
      dst_ref      text NOT NULL,
      rel          text NOT NULL,
      created_by   text,
      created_at   timestamptz NOT NULL DEFAULT now()
    )`;
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS coord_links_edge_uq
      ON harness_shared.coord_links (workspace_id, src_kind, src_ref, dst_kind, dst_ref, rel)`;
  await sql`
    CREATE INDEX IF NOT EXISTS coord_links_src_idx
      ON harness_shared.coord_links (workspace_id, src_kind, src_ref)`;
  await sql`
    CREATE INDEX IF NOT EXISTS coord_links_dst_idx
      ON harness_shared.coord_links (workspace_id, dst_kind, dst_ref)`;
}

// ─────────────────────────────────────────────────────────────────────────────
// PgTopicStore
// ─────────────────────────────────────────────────────────────────────────────

interface TopicRowDb {
  slug: string;
  title: string | null;
  description: string;
  created_by: string | null;
  merged_into: string | null;
  created_at: unknown;
}
function toTopicRow(r: TopicRowDb): TopicRow {
  return {
    slug: r.slug,
    title: r.title,
    description: r.description,
    created_by: r.created_by,
    merged_into: r.merged_into,
    created_ts: tsToIso(r.created_at),
  };
}

export class PgTopicStore implements TopicStore {
  constructor(private readonly opts: PgCapabilityStoreOptions) {}
  /** The workspace scope NOW (F-C1): the per-call resolver when set + non-empty,
   *  else the construction-time fallback. A getter so `${this.ws}` stays dynamic. */
  private get ws(): string {
    return this.opts.getWorkspaceId?.()?.trim() || (this.opts.workspaceId ?? DEFAULT_COORD_WORKSPACE);
  }

  async create(input: CreateTopicInput): Promise<TopicRow> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      INSERT INTO harness_shared.coord_topics (workspace_id, slug, title, description, created_by, created_at)
      VALUES (${this.ws}, ${input.slug}, ${input.title ?? null}, ${input.description}, ${input.created_by ?? null}, ${input.created_ts})
      ON CONFLICT (workspace_id, slug) DO NOTHING`;
    const row = await this.get(input.slug);
    if (!row) throw new Error(`coord_topics: failed to read back topic ${input.slug}`);
    return row;
  }

  async list(opts: { includeMerged?: boolean } = {}): Promise<TopicRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<TopicRowDb[]>`
      SELECT slug, title, description, created_by, merged_into, created_at
        FROM harness_shared.coord_topics
       WHERE workspace_id = ${this.ws}
         AND ${opts.includeMerged ? sql`TRUE` : sql`merged_into IS NULL`}
       ORDER BY created_at ASC, slug ASC`;
    return rows.map(toTopicRow);
  }

  async get(slug: string): Promise<TopicRow | null> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<TopicRowDb[]>`
      SELECT slug, title, description, created_by, merged_into, created_at
        FROM harness_shared.coord_topics
       WHERE workspace_id = ${this.ws} AND slug = ${slug}`;
    return rows[0] ? toTopicRow(rows[0]) : null;
  }

  async merge(fromSlug: string, intoSlug: string): Promise<void> {
    if (fromSlug === intoSlug) return;
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      UPDATE harness_shared.coord_topics
         SET merged_into = ${intoSlug}
       WHERE workspace_id = ${this.ws} AND slug = ${fromSlug}`;
  }

  async resolve(slug: string): Promise<string> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    let cur = slug;
    const seen = new Set<string>();
    for (let i = 0; i < 16; i++) {
      if (seen.has(cur)) break; // cycle guard
      seen.add(cur);
      const rows = await sql<{ merged_into: string | null }[]>`
        SELECT merged_into FROM harness_shared.coord_topics
         WHERE workspace_id = ${this.ws} AND slug = ${cur}`;
      const next = rows[0]?.merged_into;
      if (!next) return cur;
      cur = next;
    }
    return cur;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PgEntitySubscriptionStore (Subscribable)
// ─────────────────────────────────────────────────────────────────────────────

interface SubRowDb {
  id: string | number;
  subscriber_id: string;
  target_kind: string;
  target_ref: string;
  delivery_mode: string;
  created_at: unknown;
  expires_ts: unknown;
  follow_blockers: boolean | null;
  derived_from_kind: string | null;
  derived_from_ref: string | null;
}
function toSubRow(r: SubRowDb): SubscriptionRow {
  return {
    id: Number(r.id),
    subscriber_id: r.subscriber_id,
    target_kind: r.target_kind as SubscriptionTargetKind,
    target_ref: r.target_ref,
    delivery_mode: r.delivery_mode as DeliveryMode,
    created_ts: tsToIso(r.created_at),
    expires_ts: tsToIsoOrNull(r.expires_ts),
    follow_blockers: r.follow_blockers ?? false,
    derived_from: r.derived_from_kind && r.derived_from_ref
      ? { kind: r.derived_from_kind, ref: r.derived_from_ref }
      : null,
  };
}

export class PgEntitySubscriptionStore implements SubscribableStore {
  constructor(private readonly opts: PgCapabilityStoreOptions) {}
  /** The workspace scope NOW (F-C1): the per-call resolver when set + non-empty,
   *  else the construction-time fallback. A getter so `${this.ws}` stays dynamic. */
  private get ws(): string {
    return this.opts.getWorkspaceId?.()?.trim() || (this.opts.workspaceId ?? DEFAULT_COORD_WORKSPACE);
  }

  async subscribe(input: SubscribeInput): Promise<SubscriptionRow> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const mode: DeliveryMode = input.delivery_mode ?? 'full';
    const rows = await sql<SubRowDb[]>`
      INSERT INTO harness_shared.coord_entity_subscriptions
        (workspace_id, subscriber_id, target_kind, target_ref, delivery_mode, expires_ts, created_at,
         follow_blockers, derived_from_kind, derived_from_ref)
      VALUES (${this.ws}, ${input.subscriber_id}, ${input.target_kind}, ${input.target_ref},
              ${mode}, ${input.expires_ts ?? null}, ${input.created_ts}, ${input.follow_blockers ?? false}, NULL, NULL)
      ON CONFLICT (workspace_id, subscriber_id, target_kind, target_ref) WHERE cancelled_at IS NULL
      DO UPDATE SET delivery_mode = EXCLUDED.delivery_mode, expires_ts = EXCLUDED.expires_ts,
                    follow_blockers = EXCLUDED.follow_blockers,
                    derived_from_kind = NULL, derived_from_ref = NULL
      RETURNING id, subscriber_id, target_kind, target_ref, delivery_mode, created_at, expires_ts,
                follow_blockers, derived_from_kind, derived_from_ref`;
    return toSubRow(rows[0]);
  }

  /** Insert a generated blocker follow without overwriting a direct subscription. */
  async subscribeDerived(input: {
    subscriber_id: string;
    target: ObjectRef;
    derived_from: ObjectRef;
    delivery_mode?: DeliveryMode;
    created_ts: string;
  }): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      INSERT INTO harness_shared.coord_entity_subscriptions
        (workspace_id, subscriber_id, target_kind, target_ref, delivery_mode, created_at,
         follow_blockers, derived_from_kind, derived_from_ref)
      VALUES (${this.ws}, ${input.subscriber_id}, 'object', ${`${input.target.kind}:${input.target.ref}`},
              ${input.delivery_mode ?? 'full'}, ${input.created_ts}, FALSE,
              ${input.derived_from.kind}, ${input.derived_from.ref})
      ON CONFLICT (workspace_id, subscriber_id, target_kind, target_ref) WHERE cancelled_at IS NULL
      DO NOTHING`;
  }

  /** Remove generated follows created by one dependent→blocker edge. */
  async unsubscribeDerivedForEdge(derivedFrom: ObjectRef, target: ObjectRef): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      UPDATE harness_shared.coord_entity_subscriptions
         SET cancelled_at = now()
       WHERE workspace_id = ${this.ws} AND target_kind = 'object'
         AND target_ref = ${`${target.kind}:${target.ref}`}
         AND derived_from_kind = ${derivedFrom.kind} AND derived_from_ref = ${derivedFrom.ref}
         AND cancelled_at IS NULL`;
  }

  /** Remove every generated blocker follow owned by one direct subscription. */
  async unsubscribeDerivedForDependent(subscriberId: string, derivedFrom: ObjectRef): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      UPDATE harness_shared.coord_entity_subscriptions
         SET cancelled_at = now()
       WHERE workspace_id = ${this.ws} AND subscriber_id = ${subscriberId}
         AND derived_from_kind = ${derivedFrom.kind} AND derived_from_ref = ${derivedFrom.ref}
         AND cancelled_at IS NULL`;
  }

  /** Remove every generated follow whose blocker just settled. */
  async unsubscribeDerivedForTarget(target: ObjectRef): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      UPDATE harness_shared.coord_entity_subscriptions
         SET cancelled_at = now()
       WHERE workspace_id = ${this.ws} AND target_kind = 'object'
         AND target_ref = ${`${target.kind}:${target.ref}`}
         AND derived_from_kind IS NOT NULL AND cancelled_at IS NULL`;
  }

  async unsubscribe(subscriberId: string, targetKind: SubscriptionTargetKind, targetRef: string): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      UPDATE harness_shared.coord_entity_subscriptions
         SET cancelled_at = now()
       WHERE workspace_id = ${this.ws} AND subscriber_id = ${subscriberId}
         AND target_kind = ${targetKind} AND target_ref = ${targetRef}
         AND cancelled_at IS NULL`;
  }

  async listSubscriptions(subscriberId: string): Promise<SubscriptionRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    // Migration 602 is additive, but the event-await fan-out can run against a
    // candidate database before pending migrations apply. Project the optional
    // fields from the row JSON so pre-602 tables return their contract defaults
    // instead of failing while naming columns that do not exist yet.
    const rows = await sql<SubRowDb[]>`
      SELECT id, subscriber_id, target_kind, target_ref, delivery_mode, created_at, expires_ts,
             COALESCE((to_jsonb(sub)->>'follow_blockers')::boolean, FALSE) AS follow_blockers,
             to_jsonb(sub)->>'derived_from_kind' AS derived_from_kind,
             to_jsonb(sub)->>'derived_from_ref' AS derived_from_ref
        FROM harness_shared.coord_entity_subscriptions AS sub
       WHERE workspace_id = ${this.ws} AND subscriber_id = ${subscriberId}
         AND cancelled_at IS NULL AND (expires_ts IS NULL OR expires_ts > now())
       ORDER BY created_at ASC, id ASC`;
    return rows.map(toSubRow);
  }

  async listTargetSubscribers(targetKind: SubscriptionTargetKind, targetRef: string): Promise<SubscriptionRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<SubRowDb[]>`
      SELECT id, subscriber_id, target_kind, target_ref, delivery_mode, created_at, expires_ts,
             COALESCE((to_jsonb(sub)->>'follow_blockers')::boolean, FALSE) AS follow_blockers,
             to_jsonb(sub)->>'derived_from_kind' AS derived_from_kind,
             to_jsonb(sub)->>'derived_from_ref' AS derived_from_ref
        FROM harness_shared.coord_entity_subscriptions AS sub
       WHERE workspace_id = ${this.ws} AND target_kind = ${targetKind} AND target_ref = ${targetRef}
         AND cancelled_at IS NULL AND (expires_ts IS NULL OR expires_ts > now())
       ORDER BY created_at ASC, id ASC`;
    return rows.map(toSubRow);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PgLinkStore (Linkable) + Taggable via LinkBackedTaggable
// ─────────────────────────────────────────────────────────────────────────────

interface LinkRowDb {
  id: string | number;
  src_kind: string;
  src_ref: string;
  dst_kind: string;
  dst_ref: string;
  rel: string;
  created_by: string | null;
  created_at: unknown;
}
function toLinkRow(r: LinkRowDb): LinkRow {
  return {
    id: Number(r.id),
    src: { kind: r.src_kind, ref: r.src_ref },
    dst: { kind: r.dst_kind, ref: r.dst_ref },
    rel: r.rel,
    created_by: r.created_by,
    created_ts: tsToIso(r.created_at),
  };
}

export class PgLinkStore implements LinkableStore {
  constructor(private readonly opts: PgCapabilityStoreOptions) {}
  /** The workspace scope NOW (F-C1): the per-call resolver when set + non-empty,
   *  else the construction-time fallback. A getter so `${this.ws}` stays dynamic. */
  private get ws(): string {
    return this.opts.getWorkspaceId?.()?.trim() || (this.opts.workspaceId ?? DEFAULT_COORD_WORKSPACE);
  }

  async link(src: ObjectRef, dst: ObjectRef, rel: string, opts: { created_by?: string; created_ts: string }): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      INSERT INTO harness_shared.coord_links
        (workspace_id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at)
      VALUES (${this.ws}, ${src.kind}, ${src.ref}, ${dst.kind}, ${dst.ref}, ${rel}, ${opts.created_by ?? null}, ${opts.created_ts})
      ON CONFLICT (workspace_id, src_kind, src_ref, dst_kind, dst_ref, rel) DO NOTHING`;
  }

  async unlink(src: ObjectRef, dst: ObjectRef, rel: string): Promise<void> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    await sql`
      DELETE FROM harness_shared.coord_links
       WHERE workspace_id = ${this.ws} AND src_kind = ${src.kind} AND src_ref = ${src.ref}
         AND dst_kind = ${dst.kind} AND dst_ref = ${dst.ref} AND rel = ${rel}`;
  }

  async listOut(src: ObjectRef, opts: { rel?: string } = {}): Promise<LinkRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<LinkRowDb[]>`
      SELECT id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
        FROM harness_shared.coord_links
       WHERE workspace_id = ${this.ws} AND src_kind = ${src.kind} AND src_ref = ${src.ref}
         AND ${opts.rel == null ? sql`TRUE` : sql`rel = ${opts.rel}`}
       ORDER BY created_at ASC, id ASC`;
    return rows.map(toLinkRow);
  }

  async listIn(dst: ObjectRef, opts: { rel?: string } = {}): Promise<LinkRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<LinkRowDb[]>`
      SELECT id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
        FROM harness_shared.coord_links
       WHERE workspace_id = ${this.ws} AND dst_kind = ${dst.kind} AND dst_ref = ${dst.ref}
         AND ${opts.rel == null ? sql`TRUE` : sql`rel = ${opts.rel}`}
       ORDER BY created_at ASC, id ASC`;
    return rows.map(toLinkRow);
  }

  /** WI-10003631: `listOut(ref, {rel})` for each of `outRels` plus `listIn(ref, {rel})`
   *  for each of `inRels`, in ONE statement. Each branch keeps its own index predicate
   *  (UNION ALL, not an OR), and the rows come back tagged by direction so the caller
   *  can partition them exactly as the separate reads would have returned them. */
  async listAround(
    ref: ObjectRef,
    opts: { outRels: readonly string[]; inRels: readonly string[] },
  ): Promise<{ out: LinkRow[]; in: LinkRow[] }> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const outRels = [...opts.outRels];
    const inRels = [...opts.inRels];
    const rows = await sql<Array<LinkRowDb & { dir: 'out' | 'in' }>>`
      SELECT 'out'::text AS dir, id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
        FROM harness_shared.coord_links
       WHERE workspace_id = ${this.ws} AND src_kind = ${ref.kind} AND src_ref = ${ref.ref}
         AND rel = ANY(${outRels})
      UNION ALL
      SELECT 'in'::text AS dir, id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
        FROM harness_shared.coord_links
       WHERE workspace_id = ${this.ws} AND dst_kind = ${ref.kind} AND dst_ref = ${ref.ref}
         AND rel = ANY(${inRels})
       ORDER BY created_at ASC, id ASC`;
    return {
      out: rows.filter((r) => r.dir === 'out').map(toLinkRow),
      in: rows.filter((r) => r.dir === 'in').map(toLinkRow),
    };
  }

  async listOutMany(srcs: ObjectRef[], opts: { rel?: string } = {}): Promise<LinkRow[]> {
    if (srcs.length === 0) return [];
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    // Group by kind so each query is a clean `src_ref = ANY(...)` over a single
    // kind (avoids a tuple-IN; distinct kinds are ~1 in practice). postgres-js
    // binds the JS array as a PG text[] param, so `= ANY(${refs})` is the correct
    // raw idiom (the array footgun is drizzle-only). Per-src ordering within a
    // kind is preserved (ORDER BY created_at, id), matching listOut.
    const byKind = new Map<string, string[]>();
    for (const s of srcs) {
      const arr = byKind.get(s.kind);
      if (arr) arr.push(s.ref);
      else byKind.set(s.kind, [s.ref]);
    }
    const out: LinkRow[] = [];
    for (const [kind, refs] of byKind) {
      const rows = await sql<LinkRowDb[]>`
        SELECT id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
          FROM harness_shared.coord_links
         WHERE workspace_id = ${this.ws} AND src_kind = ${kind} AND src_ref = ANY(${refs})
           AND ${opts.rel == null ? sql`TRUE` : sql`rel = ${opts.rel}`}
         ORDER BY created_at ASC, id ASC`;
      out.push(...rows.map(toLinkRow));
    }
    return out;
  }

  async listInMany(dsts: ObjectRef[], opts: { rel?: string } = {}): Promise<LinkRow[]> {
    if (dsts.length === 0) return [];
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    // The reverse-direction twin of listOutMany — same kind-grouped ANY() batching.
    const byKind = new Map<string, string[]>();
    for (const d of dsts) {
      const arr = byKind.get(d.kind);
      if (arr) arr.push(d.ref);
      else byKind.set(d.kind, [d.ref]);
    }
    const out: LinkRow[] = [];
    for (const [kind, refs] of byKind) {
      const rows = await sql<LinkRowDb[]>`
        SELECT id, src_kind, src_ref, dst_kind, dst_ref, rel, created_by, created_at
          FROM harness_shared.coord_links
         WHERE workspace_id = ${this.ws} AND dst_kind = ${kind} AND dst_ref = ANY(${refs})
           AND ${opts.rel == null ? sql`TRUE` : sql`rel = ${opts.rel}`}
         ORDER BY created_at ASC, id ASC`;
      out.push(...rows.map(toLinkRow));
    }
    return out;
  }
}

/** Taggable over a PgLinkStore (the production wiring). */
export class PgTaggableStore extends LinkBackedTaggable {
  constructor(opts: PgCapabilityStoreOptions) {
    super(new PgLinkStore(opts));
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PgThreadStore (Threadable)
// ─────────────────────────────────────────────────────────────────────────────

interface ThreadRowDb {
  thread_id: string;
  parent_kind: string;
  parent_ref: string;
  title: string | null;
  created_by: string | null;
  created_at: unknown;
  last_post_at: unknown;
  post_count: number;
}
function toThreadRow(r: ThreadRowDb): ThreadRow {
  return {
    thread_id: r.thread_id,
    parent: { kind: r.parent_kind, ref: r.parent_ref },
    title: r.title,
    created_by: r.created_by,
    created_ts: tsToIso(r.created_at),
    last_post_ts: tsToIsoOrNull(r.last_post_at),
    post_count: Number(r.post_count),
  };
}

export class PgThreadStore implements ThreadableStore {
  constructor(private readonly opts: PgCapabilityStoreOptions) {}
  /** The workspace scope NOW (F-C1): the per-call resolver when set + non-empty,
   *  else the construction-time fallback. A getter so `${this.ws}` stays dynamic. */
  private get ws(): string {
    return this.opts.getWorkspaceId?.()?.trim() || (this.opts.workspaceId ?? DEFAULT_COORD_WORKSPACE);
  }

  async getOrCreateThread(
    parent: ObjectRef,
    opts: { thread_id: string; title?: string; created_by?: string; created_ts: string; harness_slug?: string },
  ): Promise<ThreadRow> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    // harness_slug (federation): set from the parent's harness when the caller is
    // harness-scoped (a harness conversation); NULL = operator-scope / local
    // (workspace engineer-issues) → the thread + its posts stay local.
    // Bare `ON CONFLICT DO NOTHING` (no arbiter) so EITHER unique constraint is tolerated: the
    // parent index (coord_threads_parent_uq) AND the thread_id PRIMARY KEY (coord_threads_pkey).
    // thread_id is derived from the item's STABLE id, but parent_ref can change as the item mutates
    // (e.g. work_items `workItemObjectRef`), so a re-derived thread_id can collide with the SAME
    // thread_id sitting under a now-stale parent — get-or-create must RETURN that existing thread,
    // not crash on coord_threads_pkey (EI-1743: work_items:comment errored 5× on exactly this — a
    // named-arbiter ON CONFLICT only swallows the parent conflict, letting the PK conflict throw).
    await sql`
      INSERT INTO harness_shared.coord_threads
        (workspace_id, thread_id, parent_kind, parent_ref, title, created_by, created_at, harness_slug)
      VALUES (${this.ws}, ${opts.thread_id}, ${parent.kind}, ${parent.ref}, ${opts.title ?? null}, ${opts.created_by ?? null}, ${opts.created_ts}, ${opts.harness_slug ?? null})
      ON CONFLICT DO NOTHING`;
    // Idempotency is keyed on the PARENT (the get-or-create semantic key) — a second call for the
    // same parent with a DIFFERENT thread_id returns the existing thread. Fall back to the thread_id
    // when the parent moved off a stable id-derived thread_id (the PK-collision path above): the
    // thread_id IS that item's thread, so returning it is correct; posts attach by thread_id.
    const existing = (await this.getThreadByParent(parent)) ?? (await this.getThreadById(opts.thread_id));
    if (!existing) throw new Error(`coord_threads: failed to read back thread for ${parent.kind}:${parent.ref} / ${opts.thread_id}`);
    return existing;
  }

  async addPost(input: { thread_id: string; author_id?: string; body: string; created_ts: string }): Promise<ThreadPostRow> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    // post_msg_id (federation): a global key — the bigserial id is machine-local.
    // harness_slug is INHERITED from the post's thread (subquery), so a post on a
    // harness-scoped thread federates; a post on a local thread stays local.
    const postMsgId = newMsgId();
    const rows = await sql<{ id: string | number; created_at: unknown }[]>`
      INSERT INTO harness_shared.coord_thread_posts (workspace_id, thread_id, author_id, body, created_at, post_msg_id, harness_slug)
      VALUES (${this.ws}, ${input.thread_id}, ${input.author_id ?? null}, ${input.body}, ${input.created_ts}, ${postMsgId},
        (SELECT harness_slug FROM harness_shared.coord_threads WHERE workspace_id = ${this.ws} AND thread_id = ${input.thread_id}))
      RETURNING id, created_at`;
    await sql`
      UPDATE harness_shared.coord_threads
         SET post_count = post_count + 1, last_post_at = ${input.created_ts}
       WHERE workspace_id = ${this.ws} AND thread_id = ${input.thread_id}`;
    return {
      id: Number(rows[0].id),
      thread_id: input.thread_id,
      author_id: input.author_id ?? null,
      body: input.body,
      created_ts: tsToIso(rows[0].created_at),
    };
  }

  async listPosts(threadId: string, opts: { afterId?: number } = {}): Promise<ThreadPostRow[]> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const after = opts.afterId ?? null;
    const rows = await sql<{ id: string | number; thread_id: string; author_id: string | null; body: string; created_at: unknown }[]>`
      SELECT id, thread_id, author_id, body, created_at
        FROM harness_shared.coord_thread_posts
       WHERE workspace_id = ${this.ws} AND thread_id = ${threadId}
         AND ${after == null ? sql`TRUE` : sql`id > ${after}`}
       ORDER BY id ASC`;
    return rows.map((r) => ({
      id: Number(r.id),
      thread_id: r.thread_id,
      author_id: r.author_id,
      body: r.body,
      created_ts: tsToIso(r.created_at),
    }));
  }

  /**
   * The LAST `limit` posts of a thread, plus the thread's TOTAL post count, in ONE query.
   *
   * ── WHY NOT `listPosts(id).slice(-3)` ──────────────────────────────────────
   * `listPosts` is unbounded by design — it backs a full thread render. A cell
   * resolver runs on a hot read path, so pulling a 121-post thread (the largest
   * in this workspace as of 2026-08-03) to display 3 is the serial/over-fetch
   * anti-pattern CLAUDE.md's performance doc lists. This is index-scoped to the
   * window and stops there.
   *
   * ── WHY THE COUNT RIDES THE SAME QUERY ─────────────────────────────────────
   * `total` MUST come from the same snapshot as the rows. A second round-trip can
   * be overtaken by a concurrent post and yield `shown: 3, total: 2` — a count
   * that indicts the very messages printed beside it. `COUNT(*) OVER ()` is
   * evaluated over the whole filtered set BEFORE `LIMIT`, so one scan yields both
   * and they cannot disagree.
   *
   * ── WHY NOT `coord_threads.post_count` ─────────────────────────────────────
   * That denormalized header is bumped by `addPost` locally, but a FEDERATED post
   * is applied by the coord-thread-post projection, which explicitly does NOT bump
   * it — the count rides the separate thread-header projection instead (see
   * sync/hyperbee/projections/coord-thread.ts). The two converge but are not
   * guaranteed equal at any instant, and `total` is a number a reader trusts to
   * decide whether they have seen the whole story. Counting the rows that actually
   * back the messages cannot drift from them by construction. Measured 2026-08-03
   * on this workspace: 5,220 threads with posts, ZERO disagreeing — so preferring
   * the row count costs nothing today and cannot quietly start lying later.
   *
   * `limit` is clamped to >= 1: `LIMIT 0` would drop the window-function row too,
   * taking `total` with it.
   */
  async listRecentPosts(threadId: string, limit: number): Promise<{ posts: ThreadPostRow[]; total: number }> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const take = Math.max(1, Math.floor(limit));
    const rows = await sql<
      { id: string | number; thread_id: string; author_id: string | null; body: string; created_at: unknown; total: string | number }[]
    >`
      SELECT id, thread_id, author_id, body, created_at, COUNT(*) OVER () AS total
        FROM harness_shared.coord_thread_posts
       WHERE workspace_id = ${this.ws} AND thread_id = ${threadId}
       ORDER BY id DESC
       LIMIT ${take}`;
    // No rows ⇒ the thread has no posts (or does not exist). Both are a genuine
    // ZERO, not an unmeasured value — an unreadable store throws instead.
    if (rows.length === 0) return { posts: [], total: 0 };
    // The window is read newest-first so the LIMIT can stop early; hand it back
    // OLDEST-FIRST, which is the order a reader consumes a conversation in.
    const posts = rows
      .slice()
      .reverse()
      .map((r) => ({
        id: Number(r.id),
        thread_id: r.thread_id,
        author_id: r.author_id,
        body: r.body,
        created_ts: tsToIso(r.created_at),
      }));
    return { posts, total: Number(rows[0].total) };
  }

  async getThreadByParent(parent: ObjectRef): Promise<ThreadRow | null> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<ThreadRowDb[]>`
      SELECT thread_id, parent_kind, parent_ref, title, created_by, created_at, last_post_at, post_count
        FROM harness_shared.coord_threads
       WHERE workspace_id = ${this.ws} AND parent_kind = ${parent.kind} AND parent_ref = ${parent.ref}`;
    return rows[0] ? toThreadRow(rows[0]) : null;
  }

  /** Read a thread by its thread_id (the PK). Used by getOrCreateThread's fallback when a stable
   *  id-derived thread_id outlives a changed parent_ref (EI-1743). */
  async getThreadById(thread_id: string): Promise<ThreadRow | null> {
    await this.opts.ensureSchema();
    const sql = this.opts.getSql();
    const rows = await sql<ThreadRowDb[]>`
      SELECT thread_id, parent_kind, parent_ref, title, created_by, created_at, last_post_at, post_count
        FROM harness_shared.coord_threads
       WHERE workspace_id = ${this.ws} AND thread_id = ${thread_id}`;
    return rows[0] ? toThreadRow(rows[0]) : null;
  }
}
