/**
 * @papercusp/deployment-driver — provider-agnostic harness/Hive deployment.
 *
 * See `./types` for the model. The cloud-deployment plan
 * (`cloud-deployment-layer-2026-06-06`) is the consumer.
 */
export type {
  DeploymentTarget,
  DeploymentPlacement,
  FrameKind,
  DesktopConfig,
  DeploymentConfig,
  Frame,
  FrameService,
  FrameBootstrapInput,
  LogLevel,
  DeploymentContext,
  DeploymentDriver,
} from "./types";
export { LOCAL_DEPLOYMENT } from "./types";
export { LocalDriver, LOCAL_FRAME } from "./local-driver";
export {
  registerDeploymentDriver,
  configureDeployment,
  resolveDeploymentDriver,
  registeredDeploymentTargets,
  isLocalDeployment,
  _resetDeploymentDriversForTests,
} from "./registry";

export type {
  WorkspaceHostProviderTarget,
  WorkspaceHostScopeKind,
  WorkspaceHostResourceKind,
  WorkspaceHostCredentialReference,
  CloudCredentialRef,
  GitCredentialRef,
  AgentCredentialRef,
  WorkspaceHostCredentialRefs,
  WorkspaceHostProviderConnection,
  WorkspaceHostScopeRef,
  WorkspaceHostScope,
  WorkspaceHostRegion,
  WorkspaceHostSize,
  WorkspaceHostImageRef,
  WorkspaceHostImage,
  WorkspaceHostPriceLineItem,
  WorkspaceHostPriceEstimate,
  WorkspaceHostConnectionValidation,
  WorkspaceHostLifecycleAction,
  WorkspaceHostDiscoveryCapabilities,
  WorkspaceHostLifecycleCapabilities,
  WorkspaceHostProviderCapabilities,
  WorkspaceHostTransportFeatureSet,
  WorkspaceHostTransportFeature,
  WorkspaceHostTransportTrafficClass,
  WorkspaceHostTransportSuitability,
  WorkspaceHostTransportRequirementKind,
  WorkspaceHostTransportRequirement,
  WorkspaceHostTransportLimitKind,
  WorkspaceHostTransportLimits,
  WorkspaceHostTransportProxyPolicy,
  WorkspaceHostTransportCostPolicy,
  WorkspaceHostTransportAuditPolicy,
  WorkspaceHostTransportHostKeyPolicy,
  WorkspaceHostTransportFallback,
  WorkspaceHostTransportCompatibilityContract,
  WorkspaceHostTransportProfile,
  WorkspaceHostDataPolicy,
  WorkspaceHostDesiredSpec,
  WorkspaceHostResourceRef,
  WorkspaceHostRef,
  WorkspaceHostSnapshotRef,
  WorkspaceHostPlanRequest,
  WorkspaceHostPlanStep,
  WorkspaceHostPlanStepRollback,
  WorkspaceHostPlan,
  WorkspaceHostApplyRequest,
  WorkspaceHostApplyResult,
  WorkspaceHostReconcileRequest,
  WorkspaceHostDestroyConfirmation,
  WorkspaceHostLifecycleState,
  WorkspaceHostObservation,
  WorkspaceHostHealthCheck,
  WorkspaceHostHealthStatus,
  WorkspaceHostHealthAttestation,
  WorkspaceHostLogLevel,
  WorkspaceHostProviderContext,
  WorkspaceHostCatalogQuery,
  WorkspaceHostProvider,
} from "./workspace-host-types";
export {
  WORKSPACE_HOST_LIFECYCLE_ACTIONS,
  WORKSPACE_HOST_HEALTH_STATUSES,
} from "./workspace-host-types";
export type {
  WorkspaceHostIdentity,
  WorkspaceHostAuthenticatedConnection,
  WorkspaceHostRuntimeRelease,
  WorkspaceHostControllerAuthority,
  WorkspaceHostDomainState,
  WorkspaceHostVendorControlMetadataField,
  WorkspaceHostVendorControlScalar,
  WorkspaceHostVendorControlMetadata,
} from "./workspace-host-domain";
export {
  WORKSPACE_HOST_VENDOR_CONTROL_METADATA_FIELDS,
  workspaceHostRuntimeRelease,
  assertWorkspaceHostDomainState,
  assertWorkspaceHostReplacement,
  projectWorkspaceHostVendorControlMetadata,
} from "./workspace-host-domain";
export {
  resolveWorkspaceHostHealthStatus,
  unmeasuredHealthCheck,
} from "./workspace-host-health";
export {
  WORKSPACE_HOST_INITIALIZATION_INVALIDATING_ACTIONS,
  workspaceHostActionInvalidatesInitialization,
} from "./workspace-host-initialization-validity";
export type { WorkspaceHostInitializationInvalidatingAction } from "./workspace-host-initialization-validity";
export type {
  WorkspaceHostTransportRequirementObservation,
  WorkspaceHostTransportClientEnvironment,
  WorkspaceHostTransportCompatibilityRequest,
  WorkspaceHostTransportCompatibilityIssueCode,
  WorkspaceHostTransportCompatibilityIssue,
  WorkspaceHostTransportCompatibilityResult,
} from "./workspace-host-transport";
export { evaluateWorkspaceHostTransportCompatibility } from "./workspace-host-transport";
export type {
  WorkspaceHostCredentialChannel,
  WorkspaceHostImportUnit,
  WorkspaceHostCredentialDeliveryKind,
  WorkspaceHostCredentialDelivery,
  WorkspaceHostCredentialDeliverySet,
  WorkspaceHostDeliveryCapabilities,
  WorkspaceHostPairingReference,
  WorkspaceHostInitializationSource,
  WorkspaceHostInitializationRequest,
  WorkspaceHostInitializationStepKind,
  WorkspaceHostInitializationSupportedStepKind,
  WorkspaceHostInitializationStep,
  WorkspaceHostInitializationPlan,
  WorkspaceHostInitializationStepReceipt,
  WorkspaceHostInitializationExecutor,
  WorkspaceHostInitializationHostOperationResult,
  WorkspaceHostInitializationHostOperations,
  WorkspaceHostBootstrapReadinessOptions,
  WorkspaceHostBootstrapReadinessProgress,
  WorkspaceHostBootstrapReadinessResult,
  WorkspaceHostInitializationReplayIdentity,
  WorkspaceHostInitializationReplayStore,
  ReplaySafeWorkspaceHostInitializationExecutorDeps,
  WorkspaceHostBackupCredentialManifest,
  WorkspaceHostBackupCredentialBindingState,
  WorkspaceHostBackupRestoreCredentialRebindRequest,
  WorkspaceHostCredentialLifecycleRequest,
  WorkspaceHostCredentialLifecycleStepKind,
  WorkspaceHostCredentialLifecycleStep,
  WorkspaceHostCredentialLifecyclePlan,
  WorkspaceHostInitializationCanaryEvidence,
  WorkspaceHostInitializationCanaryValidation,
} from "./workspace-host-initialization";
export {
  WORKSPACE_HOST_INITIALIZATION_CONTRACT_VERSION,
  WORKSPACE_HOST_INITIALIZATION_STEP_KINDS,
  WORKSPACE_HOST_CREDENTIAL_LIFECYCLE_STEP_KINDS,
  WORKSPACE_HOST_CREDENTIAL_CHANNELS,
  WORKSPACE_HOST_CHANNELS_REQUIRING_FILE_DELIVERY,
  WorkspaceHostCredentialDeliveryCapabilityError,
  WORKSPACE_HOST_IMPORT_UNITS,
  ReplaySafeWorkspaceHostInitializationExecutor,
  workspaceHostInitializationStepFingerprint,
  planWorkspaceHostInitialization,
  executeWorkspaceHostInitialization,
  buildWorkspaceHostBackupCredentialManifest,
  buildWorkspaceHostBackupRestoreCredentialRebindRequest,
  planWorkspaceHostCredentialLifecycle,
  validateWorkspaceHostInitializationCanary,
} from "./workspace-host-initialization";
export type {
  WorkspaceHostDestroyCanaryEvidenceContract,
  WorkspaceHostCredentialTeardownObservation,
  WorkspaceHostDestroyOperationObservation,
  AdaptWorkspaceHostDestroyEvidenceInput,
} from "./workspace-host-destroy-evidence";
export {
  WorkspaceHostDestroyEvidenceError,
  adaptWorkspaceHostDestroyCanaryEvidence,
} from "./workspace-host-destroy-evidence";
export type {
  WorkspaceHostWorkflowIdentity,
  WorkspaceHostWorkflowKeys,
  WorkspaceHostRetryClass,
  WorkspaceHostCompensationPlan,
  WorkspaceHostDurableResourcePlan,
  WorkspaceHostDurableWorkflowSpec,
  WorkspaceHostResourceCheckpointState,
  WorkspaceHostResourceCheckpoint,
  WorkspaceHostRecoveryAction,
  WorkspaceHostWorkflowValidation,
  WorkspaceHostControllerAction,
} from "./workspace-host-workflow";
export {
  WORKSPACE_HOST_RETRY_CLASSES,
  WORKSPACE_HOST_RESOURCE_CHECKPOINT_STATES,
  workspaceHostWorkflowKeys,
  workspaceHostRecoveryAction,
  validateWorkspaceHostWorkflow,
  workspaceHostCompensationOrder,
  workspaceHostDestroyIsConfirmed,
  nextWorkspaceHostControllerAction,
} from "./workspace-host-workflow";
export type {
  WorkspaceHostChaosProbe,
  WorkspaceHostChaosClass,
} from "./workspace-host-chaos-classes";
export {
  WORKSPACE_HOST_CHAOS_CLASSES,
  WORKSPACE_HOST_CHAOS_MAX_APPLY_ATTEMPTS,
  workspaceHostProviderRetryClass,
  resolveWorkspaceHostChaosRecovery,
} from "./workspace-host-chaos-classes";
export type {
  WorkspaceHostProviderContractCheck,
  FakeWorkspaceHostProviderContractFixture,
  WorkspaceHostProviderContractReport,
  WorkspaceHostInjectedFaultTiming,
  WorkspaceHostInjectedFaultClass,
  WorkspaceHostInjectedFaultSpec,
  WorkspaceHostFaultHistoryEntry,
  WorkspaceHostContractApproval,
  WorkspaceHostFailedRunTeardown,
  WorkspaceHostSpendSettlement,
  WorkspaceHostSpendObservationInput,
  WorkspaceHostSpendObservation,
  WorkspaceHostSpendFinality,
  WorkspaceHostLiveCanarySpec,
  WorkspaceHostCanarySpendReservation,
  WorkspaceHostCanaryCostEvidence,
  WorkspaceHostCanaryResource,
  WorkspaceHostObservedCanaryResource,
  WorkspaceHostCanaryOrphanCensus,
  WorkspaceHostTeardownWatchdogStatus,
  WorkspaceHostManualDestroyReceipt,
  WorkspaceHostCanaryCompletionReceipt,
} from "./workspace-host-test-harness";
export {
  WORKSPACE_HOST_PROVIDER_CONTRACT_VERSION,
  WORKSPACE_HOST_LIVE_CANARY_MAX_SPEND_CENTS,
  WORKSPACE_HOST_PROVIDER_CONTRACT_CHECKS,
  WorkspaceHostContractAssertionError,
  WorkspaceHostInjectedFault,
  DeterministicWorkspaceHostFaultInjector,
  WorkspaceHostLiveCanaryHarness,
  assertWorkspaceHostSecretIsolation,
  runFakeWorkspaceHostProviderContractSuite,
  createWorkspaceHostManualDestroyReceipt,
  createWorkspaceHostSpendObservation,
  appendWorkspaceHostSpendObservation,
  evaluateWorkspaceHostSpendFinality,
  fakeWorkspaceHostCapabilities,
  makeFakeWorkspaceHostProvider,
} from "./workspace-host-test-harness";
export {
  WORKSPACE_HOST_CANARY_TAG_KEYS,
  workspaceHostCanaryIdentityLabels,
  workspaceHostCanaryIdentityAudit,
  workspaceHostCanaryIdentityProblems,
  isWorkspaceHostCanaryIdentityLabelKey,
} from "./workspace-host-canary-identity";
export type {
  WorkspaceHostCanaryIdentity,
  WorkspaceHostCanaryIdentityAudit,
} from "./workspace-host-canary-identity";
export {
  registerWorkspaceHostProvider,
  registerWorkspaceHostProviderFactory,
  configureWorkspaceHostProviders,
  resolveWorkspaceHostProvider,
  registeredWorkspaceHostProviderTargets,
  _resetWorkspaceHostProvidersForTests,
} from "./workspace-host-registry";
export type { WorkspaceHostProviderFactory } from "./workspace-host-registry";
export type {
  WorkspaceHostBuildParameterValue,
  WorkspaceHostBuilderKind,
  WorkspaceHostBuildMaterial,
  WorkspaceHostBuildParameter,
  WorkspaceHostBuildTarget,
  WorkspaceHostBuildManifestInput,
  WorkspaceHostBuildManifestPayload,
  WorkspaceHostBuildManifest,
  WorkspaceHostBuildManifestVerification,
  WorkspaceHostBuilderTemplateShape,
} from "./workspace-host-build-manifest";
export {
  WORKSPACE_HOST_BUILD_INPUT_CONTRACT_VERSION,
  WORKSPACE_HOST_BUILD_MANIFEST_SCHEMA_VERSION,
  WORKSPACE_HOST_PACKER_BUILDER_KIND,
  WORKSPACE_HOST_SIDECAR_BUILDER_KIND,
  WORKSPACE_HOST_BOOTC_BUILDER_KIND,
  WORKSPACE_HOST_BUILDER_KINDS,
  WORKSPACE_HOST_BUILDER_TEMPLATE_SHAPES,
  WORKSPACE_HOST_IMAGE_FAMILY_BUILDER_KINDS,
  WORKSPACE_HOST_SHARED_BUILDER_KIND,
  WorkspaceHostBuildManifestError,
  normalizeWorkspaceHostBuildManifestInput,
  canonicalWorkspaceHostBuildManifestPayload,
  buildWorkspaceHostBuildManifest,
  verifyWorkspaceHostBuildManifest,
  verifyWorkspaceHostReleaseProvenance,
  WORKSPACE_HOST_REMOTE_INITIALIZER_ENTRYPOINT,
  WORKSPACE_HOST_CREDENTIAL_DELIVERY_ENTRYPOINT,
  WORKSPACE_HOST_DESKTOP_SESSION_ENTRYPOINT,
  WORKSPACE_HOST_PUI_ENTRYPOINT,
  WORKSPACE_HOST_PUI_COMPANION_PATH,
  WORKSPACE_HOST_PUI_INSTALL_MANIFEST_PATH,
  WORKSPACE_HOST_REQUIRED_RELEASE_MATERIALS,
  WORKSPACE_HOST_ARTIFACT_ORIGIN,
  WORKSPACE_HOST_ARTIFACT_PATH_PREFIX,
  deriveWorkspaceHostCanonicalArtifactUrls,
} from "./workspace-host-build-manifest";
export type {
  WorkspaceHostReleasePins,
  WorkspaceHostReleaseProvenanceResult,
  WorkspaceHostCanonicalArtifactUrls,
  WorkspaceHostRequiredReleaseMaterial,
} from "./workspace-host-build-manifest";
export { workspaceHostRequiredReleaseMaterialFixtures } from "./workspace-host-required-material-fixtures";
export type { WorkspaceHostRequiredMaterialFixtureOverrides } from "./workspace-host-required-material-fixtures";
export type {
  WorkspaceHostImageAction,
  WorkspaceHostImageLifecycleState,
  WorkspaceHostImageCompatibilityRule,
  WorkspaceHostImageLifecycleMetadata,
  WorkspaceHostBootcImageIdentity,
  WorkspaceHostImageArtifact,
  WorkspaceHostImageCompatibilityIssueCode,
  WorkspaceHostImageCompatibilityIssue,
  WorkspaceHostImageCompatibilityRequest,
  WorkspaceHostImageCompatibilityResult,
  WorkspaceHostCleanRoomInstallSpec,
  WorkspaceHostCleanRoomInstallFixture,
  WorkspaceHostCleanRoomExecutor,
  WorkspaceHostCleanRoomAcceptanceCheck,
  WorkspaceHostCleanRoomAcceptanceReport,
} from "./workspace-host-image";
export {
  WORKSPACE_HOST_CLEAN_ROOM_AUTHORIZED_KEY,
  WORKSPACE_HOST_IMAGE_ACCEPTANCE_CONTRACT_VERSION,
  workspaceHostImageModel,
  WORKSPACE_HOST_IMAGE_ACTIONS,
  WORKSPACE_HOST_IMAGE_LIFECYCLE_STATES,
  validateWorkspaceHostImageArtifact,
  evaluateWorkspaceHostImageCompatibility,
  buildWorkspaceHostCleanRoomInstallFixture,
  runWorkspaceHostCleanRoomAcceptance,
  workspaceHostCleanRoomFixtureAttestation,
} from "./workspace-host-image";
export type {
  WorkspaceHostBootstrapPhase,
  WorkspaceHostBootstrapCheckName,
  WorkspaceHostModel,
  WorkspaceHostUpdateMode,
  WorkspaceHostBootcRelease,
  WorkspaceHostBootstrapAttestationShape,
  WorkspaceHostBootstrapRelease,
  WorkspaceHostBootstrapEntrypoints,
  WorkspaceHostBootstrapService,
  WorkspaceHostBootstrapIsolation,
  WorkspaceHostAgentRuntimeInstall,
  WorkspaceHostBootstrapInput,
  WorkspaceHostBootstrapHostedConnector,
  WorkspaceHostBootstrapAttestationCheck,
  WorkspaceHostBootstrapAttestation,
  WorkspaceHostBootstrapAttestationValidation,
  WorkspaceHostNativeSoname,
  WorkspaceHostNativeDependencyProvider,
  WorkspaceHostNativeDependencyCoverageInput,
  WorkspaceHostNativeDependencyCoverage,
  WorkspaceHostBootstrapStatusChannel,
  WorkspaceHostBootstrapReportedStatus,
} from "./workspace-host-bootstrap";
export {
  WORKSPACE_HOST_BOOTSTRAP_CONTRACT_VERSION,
  WORKSPACE_HOST_BOOTSTRAP_UBUNTU_VERSION,
  WORKSPACE_HOST_BOOTSTRAP_ATTESTATION_PREFIX,
  DEFAULT_WORKSPACE_HOST_SERVICE_USER,
  DEFAULT_WORKSPACE_HOST_WORKSPACE_USER,
  WORKSPACE_HOST_CUSTOMER_AGENT_TOOLCHAIN_ROOT,
  WORKSPACE_HOST_CUSTOMER_AGENT_TOOLCHAIN_BIN,
  WORKSPACE_HOST_TSC_SERVICE_UNIT_TEMPLATE,
  WORKSPACE_HOST_TSC_SERVICE_SOCKET_UNIT_FILE,
  WORKSPACE_HOST_TSC_SERVICE_UNIT_FILE,
  customerTscServiceInstallLines,
  DEFAULT_WORKSPACE_HOST_AGENT_USER,
  WORKSPACE_HOST_RUNTIME_ROOT,
  WORKSPACE_HOST_STATE_ROOT,
  WORKSPACE_HOST_DATA_ROOT,
  WORKSPACE_HOST_HOSTED_PTY_SSH_KEY,
  WORKSPACE_HOST_HOSTED_PTY_KNOWN_HOSTS,
  WORKSPACE_HOST_BOOTC_RELEASE_REGISTRY_SCOPE_PATH,
  WORKSPACE_HOST_BOOTC_USR_LOCAL_TARGET,
  WORKSPACE_HOST_OLLAMA_HOME_BY_MODEL,
  WORKSPACE_HOST_REMOTE_INITIALIZER_CONDUIT,
  WORKSPACE_HOST_CREDENTIAL_DELIVERY_CONDUIT,
  WORKSPACE_HOST_PRIVILEGED_CONDUIT_SUDOERS,
  WORKSPACE_HOST_CONNECTOR_ENROLLMENT_CONDUIT,
  WORKSPACE_HOST_CONNECTOR_ENROLLMENT_PROGRAM,
  WORKSPACE_HOST_CONNECTOR_ENROLLMENT_PROTOCOL_VERSION,
  WORKSPACE_HOST_CONNECTOR_ENROLLMENT_ARGV,
  WORKSPACE_HOST_CONNECTOR_ENVIRONMENT_FILE,
  WORKSPACE_HOST_BOOTSTRAP_PHASES,
  WORKSPACE_HOST_BOOTSTRAP_CHECK_NAMES,
  WORKSPACE_HOST_BOOTSTRAP_SHARED_CHECKS,
  WORKSPACE_HOST_BOOTSTRAP_MODEL_CHECKS,
  workspaceHostBootstrapChecks,
  WORKSPACE_HOST_MODELS,
  DEFAULT_WORKSPACE_HOST_MODEL,
  WORKSPACE_HOST_BOOTC_BASE_IMAGE,
  workspaceHostBootcImageRepository,
  workspaceHostBootcPinnedImageRef,
  WORKSPACE_HOST_CONTAINERS_POLICY_PATH,
  WORKSPACE_HOST_UPDATE_MODE_BY_MODEL,
  WORKSPACE_HOST_BOOTSTRAP_STAGED_PREFIX,
  WORKSPACE_HOST_BOOTSTRAP_CHECK_EVIDENCE,
  WORKSPACE_HOST_GLIBC_SONAMES,
  WORKSPACE_HOST_NATIVE_SONAME_TO_APT_PACKAGE,
  WORKSPACE_HOST_BOOTSTRAP_SYSTEM_APT_PACKAGES,
  WORKSPACE_HOST_BOOTSTRAP_NATIVE_RUNTIME_APT_PACKAGES,
  WORKSPACE_HOST_BOOTSTRAP_APT_PACKAGES,
  DEFAULT_WORKSPACE_HOST_BOOTSTRAP_ENTRYPOINTS,
  buildWorkspaceHostBootstrap,
  normalizeWorkspaceHostSoname,
  parseWorkspaceHostReadelfNeeded,
  evaluateWorkspaceHostNativeDependencyCoverage,
  parseWorkspaceHostBootstrapAttestation,
  validateWorkspaceHostBootstrapAttestation,
  WORKSPACE_HOST_BOOTSTRAP_STATUS_CHANNELS,
  WORKSPACE_HOST_BOOTSTRAP_STATUS_GUEST_ATTRIBUTE_NAMESPACE,
  WORKSPACE_HOST_BOOTSTRAP_STATUS_GUEST_ATTRIBUTE_KEY,
  WORKSPACE_HOST_BOOTSTRAP_STATUS_ERROR_MAX_CHARS,
  WORKSPACE_HOST_BOOTSTRAP_STATUS_CONSOLE_MARKER,
  parseWorkspaceHostBootstrapReportedStatus,
  parseEc2ConsoleBootstrapStatus,
} from "./workspace-host-bootstrap";
export type {
  WorkspaceHostDesktopPackArtifact,
  WorkspaceHostDesktopPackPhase,
  WorkspaceHostDesktopPackCheckName,
  WorkspaceHostDesktopPackIsolation,
  WorkspaceHostDesktopPackInput,
  WorkspaceHostDesktopPackAttestation,
} from "./workspace-host-desktop-pack";
export {
  WORKSPACE_HOST_DESKTOP_PACK_CONTRACT_VERSION,
  WORKSPACE_HOST_DESKTOP_PACK_ATTESTATION_PREFIX,
  WORKSPACE_HOST_DESKTOP_PACK_PHASES,
  WORKSPACE_HOST_DESKTOP_PACK_CHECKS,
  WORKSPACE_HOST_DESKTOP_PACK_APT,
  WORKSPACE_HOST_DESKTOP_BROWSER_REPO,
  DEFAULT_WORKSPACE_HOST_DESKTOP_USER,
  DEFAULT_WORKSPACE_HOST_DESKTOP_GROUP,
  WORKSPACE_HOST_DESKTOP_ROOT,
  PINNED_KASMVNC_ARTIFACT,
  buildWorkspaceHostDesktopPackScript,
  parseWorkspaceHostDesktopPackAttestation,
} from "./workspace-host-desktop-pack";
export type {
  WorkspaceHostApplicationBackupRef,
  WorkspaceHostProviderSnapshotPolicy,
  WorkspaceHostSchemaRecoveryContract,
  WorkspaceHostRestoreProofPolicy,
  WorkspaceHostRecoverySpec,
  WorkspaceHostRecoveryPhase,
  WorkspaceHostRecoveryStep,
  WorkspaceHostRecoveryPlan,
  WorkspaceHostRestoreProof,
  WorkspaceHostRestoreProofValidation,
} from "./workspace-host-recovery";
export {
  WORKSPACE_HOST_RECOVERY_CONTRACT_VERSION,
  WORKSPACE_HOST_RECOVERY_MAX_PROOF_CADENCE_DAYS,
  WORKSPACE_HOST_RECOVERY_PHASES,
  assertWorkspaceHostRuntimeRollbackSafe,
  planWorkspaceHostRecovery,
  validateWorkspaceHostRestoreProof,
} from "./workspace-host-recovery";
export type {
  WorkspaceHostCredentialFamily,
  WorkspaceHostCredentialFamilySpec,
  ParsedWorkspaceHostCredentialReference,
  ParsedWorkspaceHostCredentialRevocationReference,
  WorkspaceHostCredentialBindingDescriptor,
  DescribeWorkspaceHostCredentialBindingInput,
  WorkspaceHostCredentialMaterializer,
  WorkspaceHostCredentialOperation,
  WorkspaceHostCredentialEvidence,
  WorkspaceHostCredentialLifecycleReceipt,
} from "./workspace-host-credential-namespace";
export {
  WORKSPACE_HOST_CREDENTIAL_NAMESPACE_VERSION,
  WORKSPACE_HOST_CREDENTIAL_FAMILIES,
  WORKSPACE_HOST_CREDENTIAL_FAMILY_SPECS,
  WORKSPACE_HOST_CHANNELS_REQUIRING_FILE_DELIVERY as WORKSPACE_HOST_CHANNELS_REQUIRING_FILE_DELIVERY_DERIVED,
  WorkspaceHostCredentialReferenceError,
  UnknownWorkspaceHostCredentialFamilyError,
  WorkspaceHostCredentialResolver,
  parseWorkspaceHostCredentialReference,
  parseWorkspaceHostCredentialRevocationReference,
  buildWorkspaceHostCredentialReference,
  buildWorkspaceHostCredentialRevocationReference,
  describeWorkspaceHostCredentialBinding,
  assertNoResolvedAuthorizationMaterial,
  workspaceHostCredentialReferenceDigest,
  executeWorkspaceHostCredentialLifecycle,
} from "./workspace-host-credential-namespace";
export type {
  WorkspaceHostCanaryAgent,
  WorkspaceHostAgentVerificationKind,
  WorkspaceHostAgentSubjectDisclosure,
  WorkspaceHostAgentVerificationProbeSpec,
  WorkspaceHostAgentProbeInvocation,
  WorkspaceHostAgentProbeOutcome,
  WorkspaceHostAgentProbeRunner,
  WorkspaceHostAgentVerificationEvidence,
  WorkspaceHostAgentProbeFailureReason,
  WorkspaceHostAgentVerificationReport,
  ProbeWorkspaceHostAgentInput,
  ProbeWorkspaceHostAgentsInput,
} from "./workspace-host-agent-authentication";
export {
  WORKSPACE_HOST_AGENT_VERIFICATION_CONTRACT_VERSION,
  WORKSPACE_HOST_CANARY_AGENTS,
  WORKSPACE_HOST_OMP_LOCAL_MODEL,
  WORKSPACE_HOST_OMP_LOCAL_INFERENCE_MARKER,
  DEFAULT_WORKSPACE_HOST_AGENT_PROBE_TIMEOUT_MS,
  DEFAULT_WORKSPACE_HOST_AGENT_VERIFICATION_PROBES,
  DEFAULT_WORKSPACE_HOST_AGENT_VERIFICATION_TIMEOUT_BUDGET_MS,
  NodeWorkspaceHostAgentProbeRunner,
  workspaceHostAgentSubjectDigest,
  workspaceHostAgentSpecSatisfiesReadiness,
  workspaceHostAgentAllowedVerificationKinds,
  workspaceHostAgentVerificationKindIsAllowed,
  applyWorkspaceHostAgentRuntimePath,
  probeWorkspaceHostAgentVerification,
  probeWorkspaceHostAgents,
  resolveWorkspaceHostRequestedAgents,
} from "./workspace-host-agent-authentication";
export type {
  WorkspaceHostRemoteInitializerRequest,
  WorkspaceHostRemoteInitializerResponse,
  WorkspaceHostRemoteInitializerStep,
  WorkspaceHostRemoteInitializerStepKind,
  WorkspaceHostRemoteStepEvidence,
  WorkspaceHostCreateWorkspaceInput,
  WorkspaceHostCloneRepositoryInput,
  WorkspaceHostPairWorkspaceInput,
  WorkspaceHostImportWorkspaceInput,
  WorkspaceHostVerifyInitializationInput,
  WorkspaceHostRemoteInitializerHost,
  WorkspaceHostRemoteInitializerDeps,
  BuildWorkspaceHostInitializationCanaryEvidenceInput,
} from "./workspace-host-remote-initializer";
export {
  WORKSPACE_HOST_REMOTE_INITIALIZER_PROTOCOL_VERSION,
  WORKSPACE_HOST_REMOTE_INITIALIZER_STEP_KINDS,
  WORKSPACE_HOST_REMOTE_INITIALIZER_ARGV,
  encodeWorkspaceHostCredentialLifecycleStep,
  WorkspaceHostRemoteInitializerProtocolError,
  UnsupportedWorkspaceHostInitializationStepKindError,
  WorkspaceHostInitializationCanaryEvidenceError,
  parseWorkspaceHostRemoteInitializerRequest,
  executeWorkspaceHostRemoteInitializerStep,
  handleWorkspaceHostRemoteInitializerPayload,
  assertWorkspaceHostRemoteInitializerArgv,
  buildWorkspaceHostInitializationCanaryEvidence,
} from "./workspace-host-remote-initializer";
// The CLI is the program PAPERCUSP_WORKSPACE_HOST_REMOTE_ENTRYPOINT points at, so the bin file
// that wires it lives OUTSIDE this package. The package `exports` map exposes "." alone, which
// makes a deep import of the CLI module unresolvable — without these two names the entrypoint
// could never be wired at all.
export type { WorkspaceHostRemoteInitializerCliIo } from "./workspace-host-remote-initializer-cli";
export {
  readAllStdin,
  runWorkspaceHostRemoteInitializerCli,
} from "./workspace-host-remote-initializer-cli";

// The PRODUCTION adapter behind that CLI (D-110). Exported through "." for the same reason the
// CLI is: the bin file lives outside this package and the exports map offers no deep import, so
// without these names the entrypoint could be wired only to a test double.
export type {
  WorkspaceHostCommandInput,
  WorkspaceHostCommandResult,
  WorkspaceHostSystem,
  ProductionWorkspaceHostOptions,
  ProductionWorkspaceHostRemoteInitializerOptions,
} from "./workspace-host-remote-initializer-host";
export {
  WORKSPACE_HOST_DEFAULT_WORKSPACE_ROOT,
  WORKSPACE_HOST_DEFAULT_WORKSPACE_COMMAND,
  WORKSPACE_HOST_DEFAULT_COMMAND_TIMEOUT_MS,
  WORKSPACE_HOST_DEFAULT_AGENT_PROBE_PATH,
  WORKSPACE_HOST_RELEASE_BIN_DIR,
  WORKSPACE_HOST_BOOTSTRAP_ATTESTATION_FILE,
  WORKSPACE_HOST_CREDENTIAL_MATERIAL_ROOT,
  WorkspaceHostOperationError,
  NodeWorkspaceHostSystem,
  ProductionWorkspaceHostRemoteInitializerHost,
  ProductionWorkspaceHostCredentialMaterializer,
  createProductionWorkspaceHostCredentialMaterializers,
  createProductionWorkspaceHostRemoteInitializerDeps,
  workspaceHostGetOnlyGitCredentialEnvironment,
} from "./workspace-host-remote-initializer-host";

export type {
  WorkspaceHostAgentHomeFamily,
  WorkspaceHostAgentHomeFile,
  WorkspaceHostAgentHomeBundle,
  WorkspaceHostAgentHomeBundleFiles,
  WorkspaceHostAgentHomeState,
  WorkspaceHostAgentHomeFilesystem,
  WorkspaceHostAgentHomeConsumerOptions,
  WorkspaceHostAgentHomeConsumerEvidence,
} from "./workspace-host-agent-home";
export {
  WORKSPACE_HOST_AGENT_HOME_BUNDLE_VERSION,
  WORKSPACE_HOST_AGENT_HOME_MUTABLE_CACHE_BUNDLE_VERSION,
  WORKSPACE_HOST_AGENT_HOME_LEGACY_BUNDLE_VERSION,
  WORKSPACE_HOST_AGENT_HOME_FILES,
  WORKSPACE_HOST_AGENT_HOME_OMP_MODELS_RELATIVE_PATH,
  WORKSPACE_HOST_AGENT_HOME_OLLAMA_BASE_URL,
  WORKSPACE_HOST_AGENT_HOME_OMP_LOCAL_MODELS_YML,
  WORKSPACE_HOST_AGENT_HOME_STATE_VERSION,
  WORKSPACE_HOST_AGENT_HOME_FAMILIES,
  WorkspaceHostAgentHomeStateError,
  WorkspaceHostAgentHomeBundleError,
  WorkspaceHostAgentHomeConsumer,
  parseWorkspaceHostAgentHomeBundle,
  encodeWorkspaceHostAgentHomeBundle,
  projectWorkspaceHostCodexAccessToken,
  assertWorkspaceHostCodexAccessTokenProjection,
  assertWorkspaceHostCodexProjectionCliReadable,
  WORKSPACE_HOST_CODEX_NEUTRALIZED_REFRESH_TOKEN,
  projectWorkspaceHostClaudeAccessToken,
  assertWorkspaceHostClaudeAccessTokenProjection,
  assertWorkspaceHostClaudeProjectionCliReadable,
  WORKSPACE_HOST_CLAUDE_NEUTRALIZED_REFRESH_TOKEN,
  assertWorkspaceHostAgentHomeBundleAdmissionEligible,
  workspaceHostAgentHomePaths,
  workspaceHostAgentHomeOmpModelsPath,
  workspaceHostAgentHomeDirectories,
  workspaceHostAgentHomeStatePath,
  encodeWorkspaceHostAgentHomeState,
  parseWorkspaceHostAgentHomeState,
  requireExplicitWorkspaceHostHome,
} from "./workspace-host-agent-home";

// Credential MATERIAL DELIVERY (D-215). A separate protocol, entrypoint and bin from the remote
// initializer above, because the two programs have opposite relationships with secret material:
// that one must never carry any, this one carries it by definition.
export type {
  WorkspaceHostCredentialDeliveryRequest,
  WorkspaceHostCredentialDeliveryReceipt,
  WorkspaceHostCredentialDeliveryFilesystem,
  WorkspaceHostCredentialDeliveryDeps,
} from "./workspace-host-credential-delivery";
export {
  WORKSPACE_HOST_CREDENTIAL_DELIVERY_PROTOCOL_VERSION,
  WORKSPACE_HOST_CREDENTIAL_DELIVERY_ARGV,
  WORKSPACE_HOST_CREDENTIAL_MATERIAL_MAX_BYTES,
  WorkspaceHostCredentialMaterial,
  WorkspaceHostCredentialDeliveryProtocolError,
  WorkspaceHostAmbientCredentialDeliveryError,
  WorkspaceHostRevokedCredentialGenerationError,
  WorkspaceHostCredentialGenerationConflictError,
  NodeWorkspaceHostCredentialDeliveryFilesystem,
  workspaceHostCredentialGenerationDirectory,
  workspaceHostCredentialMaterialPath,
  workspaceHostCredentialRevocationLedgerPath,
  readWorkspaceHostCredentialRevokedThrough,
  recordWorkspaceHostCredentialRevocation,
  parseWorkspaceHostCredentialDeliveryRequest,
  executeWorkspaceHostCredentialDelivery,
  handleWorkspaceHostCredentialDeliveryPayload,
  assertWorkspaceHostCredentialDeliveryArgv,
  encodeWorkspaceHostCredentialDeliveryRequest,
} from "./workspace-host-credential-delivery";
export type { WorkspaceHostCredentialDeliveryCliIo } from "./workspace-host-credential-delivery-cli";
export {
  readDeliveryStdin,
  runWorkspaceHostCredentialDeliveryCli,
  createProductionWorkspaceHostCredentialDeliveryDeps,
} from "./workspace-host-credential-delivery-cli";
export {
  APPARMOR_PROFILE_DIR,
  APPARMOR_RESTRICT_UNPRIVILEGED_USERNS_SYSCTL,
  BWRAP_BIN,
  BWRAP_USERNS_GRANT_FUNCTION,
  BWRAP_USERNS_PROBE_ARGS,
  bwrapUsernsAppArmorProfileLines,
  bwrapUsernsGrantShellLines,
} from "./bwrap-userns-grant";
