/**
 * Read-only local GCP onboarding and workspace-host preflight.
 *
 * Authentication is resolved through Application Default Credentials (ADC).
 * This module never creates, accepts, or stores service-account key material:
 * local users authenticate as themselves or use an impersonated-service-account
 * ADC file generated by gcloud. Provider calls use short-lived bearer tokens and
 * the same injected raw-REST seam as the existing Google Pub/Sub provisioner.
 */
import { execFile } from 'node:child_process';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { promisify } from 'node:util';
import type { CloudCredentialRef } from '@papercusp/deployment-driver';
import { describeFetchError } from '../loopback-fetch';

const requireCjs = createRequire(import.meta.url);
type ExecFileP = (
  file: string,
  args: string[],
  opts: Record<string, unknown>,
) => Promise<{ stdout: string; stderr: string }>;
let cachedExecFileP: ExecFileP | null = null;
function execFileP(
  file: string,
  args: string[],
  opts: Record<string, unknown>,
): Promise<{ stdout: string; stderr: string }> {
  if (!cachedExecFileP) cachedExecFileP = promisify(execFile) as unknown as ExecFileP;
  return cachedExecFileP(file, args, opts);
}

export const GCP_CLOUD_PLATFORM_SCOPE = 'https://www.googleapis.com/auth/cloud-platform';
/**
 * Resolve a short-lived token from the one active human gcloud account.
 *
 * This is deliberately explicit instead of silently falling back from ADC: a process may carry a
 * forbidden service-account key in GOOGLE_APPLICATION_CREDENTIALS while the operator selected the
 * human gcloud chain. The reference keeps that choice durable without persisting a bearer token.
 */
export const GCP_GCLOUD_ACTIVE_USER_CREDENTIAL_REF = 'gcloud://active-user';
export const GCP_WORKSPACE_HOST_REQUIRED_SERVICES = [
  'compute.googleapis.com',
  'iap.googleapis.com',
  'oslogin.googleapis.com',
] as const;

/** Project-scoped permissions exercised by the first isolated-host vertical slice. */
export const GCP_WORKSPACE_HOST_REQUIRED_PERMISSIONS = [
  'resourcemanager.projects.get',
  'serviceusage.services.get',
  'compute.projects.get',
  'compute.regions.list',
  'compute.zones.list',
  'compute.machineTypes.get',
  'compute.machineTypes.list',
  'compute.networks.create',
  'compute.networks.get',
  'compute.networks.list',
  'compute.networks.delete',
  'compute.subnetworks.create',
  'compute.subnetworks.get',
  'compute.subnetworks.list',
  'compute.subnetworks.delete',
  'compute.subnetworks.use',
  'compute.subnetworks.useExternalIp',
  'compute.firewalls.create',
  'compute.firewalls.get',
  'compute.firewalls.list',
  'compute.firewalls.delete',
  'compute.routers.create',
  'compute.routers.get',
  'compute.routers.list',
  'compute.routers.update',
  'compute.routers.delete',
  'compute.disks.create',
  'compute.disks.get',
  'compute.disks.list',
  'compute.disks.delete',
  'compute.disks.createSnapshot',
  'compute.disks.use',
  'compute.disks.setLabels',
  // The workspace-host release path mints and promotes images (gcp-image-family-adapter POSTs
  // /global/images for both the candidate build and the family promote), and the offline image
  // scan creates its candidate disk from an image. Without these the preflight passes and the
  // first image operation fails instead.
  'compute.images.create',
  'compute.images.delete',
  'compute.images.get',
  'compute.images.list',
  'compute.images.setLabels',
  'compute.images.useReadOnly',
  'compute.instances.create',
  'compute.instances.get',
  'compute.instances.getGuestAttributes',
  'compute.instances.list',
  'compute.instances.start',
  'compute.instances.stop',
  'compute.instances.delete',
  'compute.instances.setLabels',
  'compute.instances.setMetadata',
  'compute.instances.setServiceAccount',
  'compute.instances.setTags',
  'compute.instances.osLogin',
  'compute.snapshots.get',
  'compute.snapshots.list',
  'compute.snapshots.delete',
  'compute.zoneOperations.get',
  'compute.regionOperations.get',
  'compute.globalOperations.get',
  'iap.tunnelInstances.accessViaIAP',
] as const;

export const GCP_DEFAULT_WORKSPACE_HOST_IMAGE = {
  project: 'ubuntu-os-cloud',
  family: 'ubuntu-2404-lts-amd64',
} as const;

const PROJECT_ID = /^[a-z][a-z0-9-]{4,28}[a-z0-9]$/;
// User-managed service accounts use `<name>@<project>.iam.gserviceaccount.com`, while
// Compute Engine's Google-managed default identity uses the distinct
// `<project-number>-compute@developer.gserviceaccount.com` form.  Keep the latter exact — an
// arbitrary address on developer.gserviceaccount.com must not become a service-account bypass.
const SERVICE_ACCOUNT_EMAIL =
  /^(?:[^@\s]+@[^@\s]+\.iam\.gserviceaccount\.com|\d+-compute@developer\.gserviceaccount\.com)$/;
const SAFE_CREDENTIAL_TYPES = new Set([
  'authorized_user',
  'impersonated_service_account',
  'external_account',
  'external_account_authorized_user',
]);

export type GcpLocalCredentialType =
  | 'authorized_user'
  | 'impersonated_service_account'
  | 'external_account'
  | 'external_account_authorized_user'
  | 'service_account'
  | 'metadata_or_unknown'
  | 'missing';

export interface GcpOnboardingCommand {
  argv: readonly string[];
  purpose: string;
}

export interface GcpLocalCredentialOnboarding {
  gcloudInstalled: boolean;
  adcPresent: boolean;
  credentialType: GcpLocalCredentialType;
  credentialSource: 'environment' | 'well-known' | 'runtime' | 'missing';
  credentialRef?: CloudCredentialRef;
  impersonatedServiceAccount?: string;
  commands: readonly GcpOnboardingCommand[];
  warnings: readonly string[];
}

export type GcpPreflightStatus = 'pass' | 'fail' | 'warn' | 'skipped';

export interface GcpPreflightRemediation {
  code:
    | 'install-gcloud'
    | 'create-authorized-user-adc'
    | 'create-impersonated-adc'
    | 'remove-service-account-key'
    | 'select-project'
    | 'activate-project'
    | 'enable-billing'
    | 'enable-services'
    | 'grant-project-permissions'
    | 'grant-service-account-user'
    | 'increase-quota'
    | 'choose-region'
    | 'choose-machine-type'
    | 'grant-image-access';
  summary: string;
  commands?: readonly (readonly string[])[];
  suggestedRoles?: readonly string[];
  missingPermissions?: readonly string[];
}

export interface GcpPreflightCheck {
  id: string;
  status: GcpPreflightStatus;
  summary: string;
  remediation?: GcpPreflightRemediation;
}

export interface GcpQuotaSnapshot {
  metric: string;
  limit: number;
  usage: number;
  remaining: number;
}

export interface GcpWorkspaceHostPreflightInput {
  projectId?: string;
  impersonateServiceAccount?: string;
  runtimeServiceAccount?: string;
  region?: string;
  zone?: string;
  machineType?: string;
  image?: { project: string; family: string };
  requiredPermissions?: readonly string[];
}

export interface GcpWorkspaceHostPreflightReport {
  ok: boolean;
  checkedAt: string;
  projectId?: string;
  identity?: string;
  credential: GcpLocalCredentialOnboarding;
  checks: readonly GcpPreflightCheck[];
  enabledServices: readonly string[];
  missingPermissions: readonly string[];
  regions: readonly string[];
  machineTypeCount: number;
  selectedImage?: { project: string; family: string; name: string };
  quotas: readonly GcpQuotaSnapshot[];
}

interface GcpAdcDescriptor {
  present: boolean;
  source: 'environment' | 'well-known' | 'runtime' | 'missing';
  credentialType: GcpLocalCredentialType;
  impersonatedServiceAccount?: string;
}

export interface GcpResolvedAuth {
  accessToken: string;
  projectId?: string;
  identity?: string;
}

export interface GcpPreflightDeps {
  exec?: (file: string, args: readonly string[]) => Promise<{ stdout: string; stderr?: string }>;
  readFile?: (file: string) => Promise<string>;
  acquireAuth?: () => Promise<GcpResolvedAuth>;
  fetch?: typeof fetch;
  env?: NodeJS.ProcessEnv;
  homedir?: () => string;
  now?: () => string;
}

export interface ApiError extends Error {
  status?: number;
  /** Redacted, field-level provider reason. Safe to persist and surface; see gcpFailureReason. */
  reason?: string;
  /**
   * The provider stated, OUT OF BAND, that this refusal is a THROTTLE rather than a verdict.
   *
   * Google answers Compute rate limiting with HTTP **403**, not 429, so the status code alone
   * classifies a transient throttle as a settled refusal — and a retry classifier that maps 4xx to
   * `terminal` then halts a durable workflow permanently on a fault a short backoff would clear.
   * Any classifier reading `status` must read this first. {@link gcpRateLimitThrottle} owns which
   * reasons set it, and deliberately excludes `quotaExceeded`.
   */
  throttled?: boolean;
}

function normalizeProjectId(value: string | undefined): string | undefined {
  const projectId = value?.trim();
  if (!projectId) return undefined;
  if (!PROJECT_ID.test(projectId)) throw new Error('gcp_preflight_invalid_project_id');
  return projectId;
}

function normalizeServiceAccount(value: string | undefined, field: string): string | undefined {
  const email = value?.trim();
  if (!email) return undefined;
  if (!SERVICE_ACCOUNT_EMAIL.test(email)) throw new Error(`gcp_preflight_invalid_${field}`);
  return email;
}

function impersonatedEmail(raw: Record<string, unknown>): string | undefined {
  const direct = typeof raw.service_account_email === 'string' ? raw.service_account_email : undefined;
  if (direct && SERVICE_ACCOUNT_EMAIL.test(direct)) return direct;
  const url = typeof raw.service_account_impersonation_url === 'string' ? raw.service_account_impersonation_url : '';
  const match = url.match(/serviceAccounts\/([^/:]+@[^/:]+\.iam\.gserviceaccount\.com)(?::|\/)/);
  return match?.[1];
}

async function defaultExec(file: string, args: readonly string[]): Promise<{ stdout: string; stderr?: string }> {
  const result = await execFileP(file, [...args], { encoding: 'utf8', timeout: 15_000, maxBuffer: 1024 * 1024 });
  return { stdout: String(result.stdout ?? ''), stderr: String(result.stderr ?? '') };
}

async function inspectAdc(deps: GcpPreflightDeps): Promise<GcpAdcDescriptor> {
  const env = deps.env ?? process.env;
  const readFile = deps.readFile ?? ((file: string) => fs.readFile(file, 'utf8'));
  const explicit = env.GOOGLE_APPLICATION_CREDENTIALS?.trim();
  const configHome = env.CLOUDSDK_CONFIG?.trim() || path.join((deps.homedir ?? os.homedir)(), '.config', 'gcloud');
  const candidates = explicit
    ? [{ file: explicit, source: 'environment' as const }]
    : [{ file: path.join(configHome, 'application_default_credentials.json'), source: 'well-known' as const }];

  for (const candidate of candidates) {
    try {
      const raw = JSON.parse(await readFile(candidate.file)) as Record<string, unknown>;
      const type = typeof raw.type === 'string' ? raw.type : 'metadata_or_unknown';
      const credentialType = (
        SAFE_CREDENTIAL_TYPES.has(type) || type === 'service_account' ? type : 'metadata_or_unknown'
      ) as GcpLocalCredentialType;
      return {
        present: true,
        source: candidate.source,
        credentialType,
        impersonatedServiceAccount:
          credentialType === 'impersonated_service_account' ? impersonatedEmail(raw) : undefined,
      };
    } catch (error) {
      const code = (error as NodeJS.ErrnoException)?.code;
      if (code === 'ENOENT') continue;
      if (error instanceof SyntaxError) throw new Error('gcp_preflight_adc_file_invalid_json');
      throw error;
    }
  }
  return { present: false, source: 'missing', credentialType: 'missing' };
}

function credentialRefFor(descriptor: GcpAdcDescriptor): CloudCredentialRef | undefined {
  if (!descriptor.present || descriptor.credentialType === 'service_account') return undefined;
  const suffix = descriptor.impersonatedServiceAccount
    ? `impersonated/${descriptor.impersonatedServiceAccount}`
    : descriptor.credentialType;
  return { kind: 'cloud', ref: `adc://${suffix}` };
}

/** Inspect local prerequisites and return official, argv-safe onboarding commands. */
export async function inspectGcpLocalCredentialOnboarding(
  input: Pick<GcpWorkspaceHostPreflightInput, 'impersonateServiceAccount'> = {},
  deps: GcpPreflightDeps = {},
): Promise<GcpLocalCredentialOnboarding> {
  const exec = deps.exec ?? defaultExec;
  const requestedImpersonation = normalizeServiceAccount(
    input.impersonateServiceAccount,
    'impersonate_service_account',
  );
  let gcloudInstalled = false;
  try {
    await exec('gcloud', ['version', '--format=json']);
    gcloudInstalled = true;
  } catch {
    // Missing gcloud is represented in the report; onboarding remains read-only.
  }
  const descriptor = await inspectAdc(deps);
  const commands: GcpOnboardingCommand[] = [];
  const warnings: string[] = [];

  if (!gcloudInstalled) warnings.push('Install the Google Cloud CLI before creating local ADC.');
  if (descriptor.credentialType === 'service_account') {
    warnings.push(
      'Service-account key files are not accepted; replace the key with user ADC or service-account impersonation.',
    );
  }
  if (!descriptor.present || descriptor.credentialType === 'service_account') {
    const argv = ['gcloud', 'auth', 'application-default', 'login'];
    if (requestedImpersonation) argv.push(`--impersonate-service-account=${requestedImpersonation}`);
    commands.push({
      argv,
      purpose: requestedImpersonation
        ? 'Create short-lived impersonated-service-account ADC without downloading a key.'
        : 'Create authorized-user ADC for local development.',
    });
  }

  return {
    gcloudInstalled,
    adcPresent: descriptor.present,
    credentialType: descriptor.credentialType,
    credentialSource: descriptor.source,
    credentialRef: credentialRefFor(descriptor),
    impersonatedServiceAccount: descriptor.impersonatedServiceAccount ?? requestedImpersonation,
    commands,
    warnings,
  };
}

/** Resolve one short-lived ADC access token without retaining credential material. */
export async function acquireGcpAdcAuth(): Promise<GcpResolvedAuth> {
  const { GoogleAuth } = requireCjs('google-auth-library') as typeof import('google-auth-library');
  const auth = new GoogleAuth({ scopes: [GCP_CLOUD_PLATFORM_SCOPE] });
  const client = await auth.getClient();
  const [{ token }, projectId, credentials] = await Promise.all([
    client.getAccessToken(),
    auth.getProjectId().catch(() => undefined),
    auth.getCredentials().catch(() => ({})),
  ]);
  if (!token) throw new Error('gcp_preflight_access_token_empty');
  const identity =
    'client_email' in credentials && typeof credentials.client_email === 'string'
      ? credentials.client_email
      : undefined;
  return {
    accessToken: token,
    projectId: projectId || undefined,
    identity,
  };
}

export interface GcpWorkspaceHostAuthResolverDeps extends Pick<
  GcpPreflightDeps,
  'exec' | 'readFile' | 'env' | 'homedir'
> {
  acquireAdcAuth?: () => Promise<GcpResolvedAuth>;
  /** Injectable delay for the bounded gcloud-exec retry below (EI-22191286944372582);
   *  tests pass a no-op so the retry schedule costs nothing in CI. */
  sleep?: (ms: number) => Promise<void>;
}

/**
 * Bounded backoff schedule for a MOMENTARY gcloud exec failure — e.g. several concurrent
 * `gcloud compute start-iap-tunnel` processes contending for the shared config/credential
 * DB (EI-22191286944372582's observed shape: the same two commands succeeded from a shell
 * seconds later with no credential change). Short and few on purpose: a GENUINE credential
 * problem (revoked grant, missing account) must still surface promptly, not be masked
 * behind a long retry that only delays an unrecoverable failure.
 */
const GCLOUD_TOKEN_EXEC_RETRY_BACKOFF_MS = [250, 750] as const;

/**
 * The evidence a collapsed `catch {}` was erasing: which exit code the failing gcloud
 * invocation returned and a bounded stderr excerpt, distinct from `err.message` (which for
 * a promisified `execFile` failure is usually just "Command failed: gcloud ..." with the
 * actually useful detail sitting in `.stderr`). Bounded to keep a runaway/binary stderr
 * blob out of a thrown error; this is diagnostic evidence, not user-facing prose.
 */
function describeGcloudExecFailure(error: unknown): { code: unknown; stderrExcerpt: string } {
  const err = error as { code?: unknown; stderr?: unknown; message?: unknown } | undefined;
  const raw =
    (typeof err?.stderr === 'string' && err.stderr.trim()) ||
    (error instanceof Error ? error.message : String(error));
  return { code: err?.code, stderrExcerpt: raw.length > 400 ? `${raw.slice(0, 400)}…` : raw };
}

const defaultSleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Mint one short-lived token from the selected human gcloud account.
 *
 * Account discovery happens first and the token call is pinned with --account, so a concurrent
 * gcloud config change cannot switch identities between discovery and issuance. Service-account
 * identities are refused: importing a key into gcloud must not become a bypass around the local
 * workspace-host key ban.
 */
export async function acquireGcpGcloudActiveUserAuth(
  deps: Pick<GcpWorkspaceHostAuthResolverDeps, 'exec' | 'sleep'> = {},
): Promise<GcpResolvedAuth> {
  const exec = deps.exec ?? defaultExec;
  const sleep = deps.sleep ?? defaultSleep;
  // Discovery gets the same bounded retry as the token pair below. Measured 2026-09-24: a
  // completed canary destroy (p318-r39-destroy-20260924-1) deleted every resource and then
  // failed its terminal evidence on a single `count_invalid`, while the same command in the same
  // environment returned exactly one account before and after. The observed account list rides
  // on `.cause`, so the next occurrence says whether it was zero accounts or several.
  let identity: string;
  for (let attempt = 0; ; attempt += 1) {
    let failure: Error;
    try {
      const { stdout } = await exec('gcloud', ['auth', 'list', '--filter=status:ACTIVE', '--format=value(account)']);
      const accounts = stdout
        .split(/\r?\n/)
        .map((account) => account.trim())
        .filter(Boolean);
      if (accounts.length === 1) {
        identity = accounts[0]!;
        break;
      }
      failure = new Error('gcp_gcloud_active_user_count_invalid', {
        cause: new Error(
          `gcloud auth list returned ${accounts.length} active account(s) on attempt ${attempt + 1}` +
            (accounts.length > 0 ? `: ${accounts.join(', ')}` : ''),
        ),
      });
    } catch (error) {
      const { code, stderrExcerpt } = describeGcloudExecFailure(error);
      failure = new Error('gcp_gcloud_active_user_unavailable', {
        cause: new Error(
          `gcloud auth list failed on attempt ${attempt + 1} (exit ${code ?? 'unknown'}): ${stderrExcerpt}`,
        ),
      });
    }
    if (attempt >= GCLOUD_TOKEN_EXEC_RETRY_BACKOFF_MS.length) throw failure;
    await sleep(GCLOUD_TOKEN_EXEC_RETRY_BACKOFF_MS[attempt]!);
  }
  if (SERVICE_ACCOUNT_EMAIL.test(identity)) {
    throw new Error('gcp_gcloud_active_user_service_account_forbidden');
  }

  // EI-22191286944372582: a momentary exec failure here (observed cause: several concurrent
  // `gcloud` processes contending for the shared config/credential DB) used to collapse
  // straight to the terminal `..._token_unavailable` error and abandon an expensive, stateful
  // live-cloud run — with the underlying exit code and stderr discarded, so the reader had
  // nothing to distinguish "momentary contention" from "genuinely revoked credential" and went
  // looking for a credential problem that never existed. Retry a BOUNDED, short number of times
  // (both execs together, since either failing invalidates the pairing) before giving up, and
  // when every attempt fails, preserve the exact taxonomy `.message` every downstream caller
  // matches on (see gcp-api-client.ts's SAFE_CONNECTION_VALIDATION_PROBLEMS) while attaching the
  // last attempt's exit code + a bounded stderr excerpt as `.cause` for whoever investigates next.
  let tokenOutput: string;
  let projectOutput: string;
  for (let attempt = 0; ; attempt += 1) {
    try {
      const [token, project] = await Promise.all([
        exec('gcloud', ['auth', 'print-access-token', `--account=${identity}`, '--quiet']),
        exec('gcloud', ['config', 'get-value', 'project', '--quiet']),
      ]);
      tokenOutput = token.stdout.trim();
      projectOutput = project.stdout.trim();
      break;
    } catch (error) {
      if (attempt >= GCLOUD_TOKEN_EXEC_RETRY_BACKOFF_MS.length) {
        const { code, stderrExcerpt } = describeGcloudExecFailure(error);
        throw new Error('gcp_gcloud_active_user_token_unavailable', {
          cause: new Error(
            `gcloud token/project exec failed after ${attempt + 1} attempt(s) (exit ${code ?? 'unknown'}): ${stderrExcerpt}`,
          ),
        });
      }
      await sleep(GCLOUD_TOKEN_EXEC_RETRY_BACKOFF_MS[attempt]!);
    }
  }
  if (!tokenOutput) throw new Error('gcp_gcloud_active_user_token_empty');
  const projectId = projectOutput && projectOutput !== '(unset)' ? normalizeProjectId(projectOutput) : undefined;
  return {
    accessToken: tokenOutput,
    identity,
    ...(projectId ? { projectId } : {}),
  };
}

/** Resolve the selected non-secret connection reference to a token supplier. */
export function createGcpWorkspaceHostAcquireAuth(
  credentialRef: string,
  deps: GcpWorkspaceHostAuthResolverDeps = {},
): () => Promise<GcpResolvedAuth> {
  const ref = credentialRef.trim();
  if (ref === GCP_GCLOUD_ACTIVE_USER_CREDENTIAL_REF) {
    return () => acquireGcpGcloudActiveUserAuth(deps);
  }
  if (!ref.startsWith('adc://')) throw new Error('gcp_workspace_host_cloud_credential_ref_unsupported');

  // Inspect once per composed provider. Token acquisition can repeat as tokens expire, but the
  // credential class is invariant for that provider and must be proven safe before the first call.
  let safeAdc: Promise<void> | undefined;
  const assertSafeAdc = () =>
    (safeAdc ??= inspectAdc(deps).then((descriptor) => {
      if (descriptor.credentialType === 'service_account') {
        throw new Error('gcp_workspace_host_service_account_key_forbidden');
      }
    }));
  const acquireAdcAuth = deps.acquireAdcAuth ?? acquireGcpAdcAuth;
  return async () => {
    await assertSafeAdc();
    return acquireAdcAuth();
  };
}

async function gcloudProject(deps: GcpPreflightDeps): Promise<string | undefined> {
  const exec = deps.exec ?? defaultExec;
  try {
    const { stdout } = await exec('gcloud', ['config', 'get-value', 'project', '--quiet']);
    const value = stdout.trim();
    return value && value !== '(unset)' ? normalizeProjectId(value) : undefined;
  } catch {
    return undefined;
  }
}

const REASON_MAX = 300;
/** Anything token-shaped: `Bearer x`, a JWT, or a long opaque secret-like run of base64url. */
const TOKEN_LIKE = /\b(?:Bearer\s+\S+|ya29\.\S+|[A-Za-z0-9_-]{40,}(?:\.[A-Za-z0-9_-]{20,})*)/g;

/**
 * Extract a REDACTED, field-level reason from a Google API error body.
 *
 * The transport below refuses to copy the raw body, which is right — but dropping it entirely
 * left every provisioning failure reading as a bare `gcp_preflight_http_400` with no way to learn
 * WHAT the provider rejected. Diagnosing one cost a hand-replay of the request against the live
 * API. So copy the STRUCTURED diagnostic fields only (never the whole body, never headers), cap
 * the length, and scrub anything token-shaped: `error.message` and `error.errors[].message` are
 * field-level validation text ("Requested disk size cannot be smaller than the image size"), not
 * credentials.
 */
function gcpFailureReason(body: unknown): string | undefined {
  const error = (body as { error?: unknown } | null)?.error;
  if (!error || typeof error !== 'object') return undefined;
  const { message, errors } = error as { message?: unknown; errors?: unknown };
  const parts: string[] = [];
  if (typeof message === 'string' && message.trim()) parts.push(message.trim());
  if (Array.isArray(errors)) {
    for (const entry of errors) {
      const text = (entry as { message?: unknown } | null)?.message;
      if (typeof text === 'string' && text.trim() && !parts.includes(text.trim())) parts.push(text.trim());
    }
  }
  if (parts.length === 0) return undefined;
  const joined = parts.join(' | ').replace(TOKEN_LIKE, '[redacted]').replace(/\s+/g, ' ');
  return joined.length > REASON_MAX ? `${joined.slice(0, REASON_MAX - 1)}…` : joined;
}

/**
 * Google's machine-readable reasons for RATE limiting — the ones a retry actually clears.
 *
 * These arrive as HTTP 403, which is why they need naming at all: a status-only classifier reads
 * them as a settled permission refusal. The reason code is the only stable discriminator, because
 * the human `message` beside it ("Rate Limit Exceeded") is display text, not contract.
 *
 * Deliberately NOT `quotaExceeded`: a spent quota does not refill on a backoff, so retrying it
 * burns the retry schedule against a wall and hides a condition that needs an operator. That is
 * the same line `YouTubeRateLimited` draws for the Data API, for the same reason.
 */
const GCP_RATE_LIMIT_REASONS: ReadonlySet<string> = new Set([
  'rateLimitExceeded',
  'userRateLimitExceeded',
  'rateLimitExceededByUser',
]);

/**
 * Whether a Google API error body says "you are going too fast" rather than "no".
 *
 * Reads `error.errors[].reason` only — the canonical `error.status` is NOT consulted, because
 * `RESOURCE_EXHAUSTED` covers rate limits and spent quota alike, so keying on it would sweep the
 * quota case into the retry path the set above deliberately excludes.
 */
function gcpRateLimitThrottle(body: unknown): boolean {
  const error = (body as { error?: unknown } | null)?.error;
  if (!error || typeof error !== 'object') return false;
  const { errors } = error as { errors?: unknown };
  if (!Array.isArray(errors)) return false;
  return errors.some((entry) => {
    const reason = (entry as { reason?: unknown } | null)?.reason;
    return typeof reason === 'string' && GCP_RATE_LIMIT_REASONS.has(reason);
  });
}

/**
 * Socket teardowns where the connection died without delivering a response. Google's frontend
 * closes pooled keep-alive sockets on its own idle timeout, and undici only observes the close
 * when it next reaches for that socket — so it hands a dead one to the following request and the
 * fetch rejects before anything is written. A single un-retried call turns that routine pool
 * eviction into a hard provisioning failure.
 *
 * Deliberately NOT here: timeouts. Under the event-loop stall that made this failure visible
 * (WI-10001862) a retried timeout just pays the same multi-second wait again.
 */
const GCP_RETRYABLE_TRANSPORT_CODES = new Set(['UND_ERR_SOCKET', 'ECONNRESET', 'EPIPE']);
const GCP_TRANSPORT_RETRY_DELAYS_MS = [100, 300] as const;

/** `fetch` wraps the real cause, so walk the chain rather than reading only the surface error. */
function gcpTransportCloseFailure(error: unknown): boolean {
  for (let node: unknown = error, depth = 0; node != null && depth < 4; depth += 1) {
    const { code, message, name } = node as { code?: unknown; message?: unknown; name?: unknown };
    if (name === 'AbortError') return false;
    if (typeof code === 'string' && GCP_RETRYABLE_TRANSPORT_CODES.has(code)) return true;
    if (typeof message === 'string' && /other side closed|socket hang up/i.test(message)) return true;
    if (gcpConnectPhaseFailure(node)) return true;
    node = (node as { cause?: unknown }).cause;
  }
  return false;
}

/**
 * A failure while CONNECTING: no request byte reached Google, so a replay cannot duplicate
 * anything. The measured case (WI-10003516): with Node's happy-eyeballs connect, a main-thread
 * stall of 500ms or more lets the per-address attempt timer abort an IPv4 connect that had
 * already succeeded; the IPv6 fallback has no route, and the socket fails with an
 * `AggregateError` (code ETIMEDOUT, empty message) whose attempts are all `syscall: 'connect'`.
 * That turned a finished teardown's census read into a failed operation. A mid-request timeout
 * (`syscall: 'read'`) is deliberately NOT matched here — its request may have been applied.
 */
function gcpConnectPhaseFailure(node: unknown): boolean {
  const { code, syscall, errors } = node as { code?: unknown; syscall?: unknown; errors?: unknown };
  if (code === 'UND_ERR_CONNECT_TIMEOUT') return true;
  if (syscall === 'connect') return true;
  return (
    Array.isArray(errors) &&
    errors.length > 0 &&
    errors.every((attempt) => (attempt as { syscall?: unknown } | null)?.syscall === 'connect')
  );
}

/**
 * The error a caller sees once replays are exhausted (or the failure was not replayable). undici's
 * `TypeError: fetch failed` names no request, so four census failures could not be attributed to
 * a URL (WI-10003516). Name the method and host+path — never the query string, headers, or token —
 * and keep the original as `cause` so chain-walking classifiers still see the undici code. The
 * message keeps `describeFetchError`'s text, so message-based transient detection is unchanged.
 */
function gcpTransportFailure(error: unknown, url: string, init: RequestInit): Error {
  if (init.signal?.aborted || (error as { name?: unknown } | null)?.name === 'AbortError') {
    return error instanceof Error ? error : new Error(String(error));
  }
  let target = 'unparseable-url';
  try {
    const parsed = new URL(url);
    target = `${parsed.host}${parsed.pathname}`;
  } catch {
    // keep the placeholder: a malformed URL must not turn the transport error into a TypeError
  }
  const method = (init.method ?? 'GET').toUpperCase();
  return new Error(`gcp_transport_failed ${method} ${target}: ${describeFetchError(error)}`, { cause: error });
}

/**
 * Whether replaying this request is safe. GET/HEAD are safe by the HTTP spec; for everything else
 * the signal is Google's OWN idempotency token — a Compute request carrying `requestId` is
 * deduplicated provider-side, which is exactly the guarantee a replay needs. An unannotated
 * mutation is never replayed, because "other side closed" cannot distinguish a request that was
 * dropped from one that was applied with its response lost.
 */
function gcpRequestReplayable(url: string, init: RequestInit): boolean {
  if (typeof init.body !== 'string' && init.body !== undefined) return false; // a stream body cannot be re-read
  const method = (init.method ?? 'GET').toUpperCase();
  if (method === 'GET' || method === 'HEAD') return true;
  return /[?&]requestId=/.test(url);
}

/**
 * Shared authenticated Google API JSON transport. The raw error body is never copied into the
 * thrown error, so bearer tokens and provider internals cannot leak through logs or persisted
 * workflow failures; only the redacted field-level reason above travels with it.
 */
export async function fetchGcpApiJson<T>(
  fetchImpl: typeof fetch,
  token: string,
  url: string,
  init: RequestInit = {},
  transport: { sleep?: (ms: number) => Promise<void> } = {},
): Promise<T> {
  const sleep = transport.sleep ?? ((ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms)));
  const replays = gcpRequestReplayable(url, init) ? GCP_TRANSPORT_RETRY_DELAYS_MS.length : 0;
  const send = async (): Promise<Response> => {
    for (let attempt = 0; ; attempt += 1) {
      try {
        return await fetchImpl(url, {
          ...init,
          headers: {
            authorization: `Bearer ${token}`,
            accept: 'application/json',
            ...(init.body === undefined ? {} : { 'content-type': 'application/json' }),
            ...(init.headers ?? {}),
          },
        });
      } catch (error) {
        if (attempt >= replays || init.signal?.aborted || !gcpTransportCloseFailure(error)) {
          throw gcpTransportFailure(error, url, init);
        }
        await sleep(GCP_TRANSPORT_RETRY_DELAYS_MS[attempt]!);
      }
    }
  };
  const response = await send();
  if (!response.ok) {
    // Parsed ONCE and read twice: the redacted human reason, and the machine throttle signal.
    const body = await response.json().catch(() => undefined);
    const reason = gcpFailureReason(body);
    const error = new Error(
      reason ? `gcp_preflight_http_${response.status}: ${reason}` : `gcp_preflight_http_${response.status}`,
    ) as ApiError;
    error.status = response.status;
    if (reason) error.reason = reason;
    if (gcpRateLimitThrottle(body)) error.throttled = true;
    throw error;
  }
  return (await response.json()) as T;
}

function checkFailure(id: string, summary: string, remediation?: GcpPreflightRemediation): GcpPreflightCheck {
  return { id, status: 'fail', summary, remediation };
}

function suggestedRoles(missing: readonly string[]): string[] {
  const roles = new Set<string>();
  if (missing.some((permission) => permission.startsWith('serviceusage.')))
    roles.add('roles/serviceusage.serviceUsageViewer');
  if (
    missing.some(
      (permission) => permission.startsWith('compute.networks.') || permission.startsWith('compute.subnetworks.'),
    )
  )
    roles.add('roles/compute.networkAdmin');
  if (missing.some((permission) => permission.startsWith('compute.routers.'))) roles.add('roles/compute.networkAdmin');
  if (missing.some((permission) => permission.startsWith('compute.firewalls.')))
    roles.add('roles/compute.securityAdmin');
  if (missing.some((permission) => permission.startsWith('compute.images.')))
    roles.add('roles/compute.storageAdmin');
  // Read-only compute metadata. compute.projects.get is a DIFFERENT permission from the
  // resourcemanager.projects.get handled below, and roles/browser does not grant it.
  if (
    missing.some(
      (permission) =>
        permission.startsWith('compute.projects.') ||
        permission.startsWith('compute.regions.') ||
        permission.startsWith('compute.zones.') ||
        permission.startsWith('compute.machineTypes.'),
    )
  )
    roles.add('roles/compute.viewer');
  if (
    missing.some(
      (permission) =>
        permission.startsWith('compute.instances.') ||
        permission.startsWith('compute.disks.') ||
        permission.startsWith('compute.snapshots.') ||
        permission.endsWith('Operations.get'),
    )
  )
    roles.add('roles/compute.instanceAdmin.v1');
  if (missing.includes('iap.tunnelInstances.accessViaIAP')) roles.add('roles/iap.tunnelResourceAccessor');
  if (missing.includes('compute.instances.osLogin')) roles.add('roles/compute.osLogin');
  if (missing.includes('resourcemanager.projects.get')) roles.add('roles/browser');
  return [...roles];
}

function quotaSnapshot(raw: { metric?: string; limit?: number; usage?: number }): GcpQuotaSnapshot | null {
  if (!raw.metric || !Number.isFinite(raw.limit) || !Number.isFinite(raw.usage)) return null;
  const limit = Number(raw.limit);
  const usage = Number(raw.usage);
  return { metric: raw.metric, limit, usage, remaining: Math.max(0, limit - usage) };
}

/**
 * Run the complete read-only local GCP preflight. Each provider surface gets a
 * separate check so the UI can show exact, least-privilege remediation.
 */
export async function runGcpWorkspaceHostPreflight(
  input: GcpWorkspaceHostPreflightInput = {},
  deps: GcpPreflightDeps = {},
): Promise<GcpWorkspaceHostPreflightReport> {
  const now = deps.now ?? (() => new Date().toISOString());
  const checkedAt = now();
  const credential = await inspectGcpLocalCredentialOnboarding(input, deps);
  const checks: GcpPreflightCheck[] = [];
  const empty = () => ({
    ok: false,
    checkedAt,
    credential,
    checks,
    enabledServices: [] as string[],
    missingPermissions: [] as string[],
    regions: [] as string[],
    machineTypeCount: 0,
    quotas: [] as GcpQuotaSnapshot[],
  });

  if (credential.credentialType === 'service_account') {
    checks.push(
      checkFailure('credential', 'Service-account key ADC is forbidden for local workspace-host management.', {
        code: 'remove-service-account-key',
        summary: 'Remove GOOGLE_APPLICATION_CREDENTIALS for the key and create authorized-user or impersonated ADC.',
        commands: credential.commands.map((entry) => entry.argv),
      }),
    );
    return empty();
  }

  let auth: GcpResolvedAuth;
  try {
    auth = await (deps.acquireAuth ?? acquireGcpAdcAuth)();
    checks.push({ id: 'credential', status: 'pass', summary: `ADC resolved through ${credential.credentialType}.` });
  } catch {
    checks.push(
      checkFailure('credential', 'Application Default Credentials could not produce a short-lived access token.', {
        code: input.impersonateServiceAccount ? 'create-impersonated-adc' : 'create-authorized-user-adc',
        summary: 'Create local ADC with the official gcloud application-default login flow.',
        commands: credential.commands.map((entry) => entry.argv),
      }),
    );
    return empty();
  }

  const projectId =
    normalizeProjectId(input.projectId) ?? normalizeProjectId(auth.projectId) ?? (await gcloudProject(deps));
  if (!projectId) {
    checks.push(
      checkFailure('project', 'No GCP project was selected by input, ADC, or the active gcloud configuration.', {
        code: 'select-project',
        summary: 'Choose the billing project explicitly; do not infer a project from a credential filename.',
        commands: [['gcloud', 'config', 'set', 'project', '<PROJECT_ID>']],
      }),
    );
    return { ...empty(), identity: auth.identity };
  }

  const fetchImpl = deps.fetch ?? fetch;
  const token = auth.accessToken;
  const encodedProject = encodeURIComponent(projectId);
  let enabledServices: string[] = [];
  let missingPermissions: string[] = [];
  let regions: string[] = [];
  let machineTypeCount = 0;
  let selectedImage: GcpWorkspaceHostPreflightReport['selectedImage'];
  let quotas: GcpQuotaSnapshot[] = [];

  try {
    const project = await fetchGcpApiJson<{ state?: string }>(
      fetchImpl,
      token,
      `https://cloudresourcemanager.googleapis.com/v3/projects/${encodedProject}`,
    );
    if (project.state === 'ACTIVE')
      checks.push({ id: 'project', status: 'pass', summary: `Project ${projectId} is active.` });
    else
      checks.push(
        checkFailure('project', `Project ${projectId} is not active (state ${project.state ?? 'unknown'}).`, {
          code: 'activate-project',
          summary: 'Restore or select an active project before provisioning.',
        }),
      );
  } catch (error) {
    checks.push(checkFailure('project', `Project lookup failed (${(error as ApiError).status ?? 'unavailable'}).`));
  }

  try {
    const billing = await fetchGcpApiJson<{ billingEnabled?: boolean }>(
      fetchImpl,
      token,
      `https://cloudbilling.googleapis.com/v1/projects/${encodedProject}/billingInfo`,
    );
    if (billing.billingEnabled) checks.push({ id: 'billing', status: 'pass', summary: 'Project billing is enabled.' });
    else
      checks.push(
        checkFailure('billing', 'Project billing is disabled or attached to a closed billing account.', {
          code: 'enable-billing',
          summary: 'Link the project to an open billing account before creating billable resources.',
        }),
      );
  } catch (error) {
    checks.push(
      checkFailure('billing', `Billing verification failed (${(error as ApiError).status ?? 'unavailable'}).`),
    );
  }

  const requiredServices: string[] = [...GCP_WORKSPACE_HOST_REQUIRED_SERVICES];
  if (credential.credentialType === 'impersonated_service_account' || input.impersonateServiceAccount) {
    requiredServices.push('iamcredentials.googleapis.com');
  }
  const serviceResults = await Promise.all(
    requiredServices.map(async (service) => {
      try {
        const result = await fetchGcpApiJson<{ state?: string }>(
          fetchImpl,
          token,
          `https://serviceusage.googleapis.com/v1/projects/${encodedProject}/services/${encodeURIComponent(service)}`,
        );
        return { service, enabled: result.state === 'ENABLED' };
      } catch {
        return { service, enabled: false };
      }
    }),
  );
  enabledServices = serviceResults.filter((entry) => entry.enabled).map((entry) => entry.service);
  const missingServices = serviceResults.filter((entry) => !entry.enabled).map((entry) => entry.service);
  if (missingServices.length === 0) {
    checks.push({
      id: 'services',
      status: 'pass',
      summary: `Required APIs are enabled: ${requiredServices.join(', ')}.`,
    });
  } else {
    checks.push(
      checkFailure('services', `Required APIs are not enabled or visible: ${missingServices.join(', ')}.`, {
        code: 'enable-services',
        summary: 'Enable only the missing APIs in the selected project.',
        commands: [['gcloud', 'services', 'enable', ...missingServices, `--project=${projectId}`]],
      }),
    );
  }

  const requiredPermissions = [...new Set(input.requiredPermissions ?? GCP_WORKSPACE_HOST_REQUIRED_PERMISSIONS)];
  try {
    const granted = await fetchGcpApiJson<{ permissions?: string[] }>(
      fetchImpl,
      token,
      `https://cloudresourcemanager.googleapis.com/v1/projects/${encodedProject}:testIamPermissions`,
      { method: 'POST', body: JSON.stringify({ permissions: requiredPermissions }) },
    );
    const grantedSet = new Set(granted.permissions ?? []);
    missingPermissions = requiredPermissions.filter((permission) => !grantedSet.has(permission));
    if (missingPermissions.length === 0) {
      checks.push({
        id: 'iam.project',
        status: 'pass',
        summary: 'The active identity has every required project permission.',
      });
    } else {
      checks.push(
        checkFailure(
          'iam.project',
          `The active identity is missing ${missingPermissions.length} required permission(s).`,
          {
            code: 'grant-project-permissions',
            summary: 'Grant the smallest role set that covers the listed permissions; avoid Owner/Editor.',
            missingPermissions,
            suggestedRoles: suggestedRoles(missingPermissions),
          },
        ),
      );
    }
  } catch (error) {
    checks.push(
      checkFailure(
        'iam.project',
        `Project permission verification failed (${(error as ApiError).status ?? 'unavailable'}).`,
      ),
    );
  }

  const runtimeServiceAccount = normalizeServiceAccount(input.runtimeServiceAccount, 'runtime_service_account');
  if (runtimeServiceAccount) {
    try {
      const result = await fetchGcpApiJson<{ permissions?: string[] }>(
        fetchImpl,
        token,
        `https://iam.googleapis.com/v1/projects/-/serviceAccounts/${encodeURIComponent(runtimeServiceAccount)}:testIamPermissions`,
        { method: 'POST', body: JSON.stringify({ permissions: ['iam.serviceAccounts.actAs'] }) },
      );
      if (result.permissions?.includes('iam.serviceAccounts.actAs')) {
        checks.push({
          id: 'iam.serviceAccount',
          status: 'pass',
          summary: 'The runtime service account can be attached to a VM.',
        });
      } else {
        checks.push(
          checkFailure(
            'iam.serviceAccount',
            'The active identity cannot attach the selected runtime service account.',
            {
              code: 'grant-service-account-user',
              summary: 'Grant Service Account User on this service account, not project-wide.',
              suggestedRoles: ['roles/iam.serviceAccountUser'],
              missingPermissions: ['iam.serviceAccounts.actAs'],
            },
          ),
        );
      }
    } catch (error) {
      checks.push(
        checkFailure(
          'iam.serviceAccount',
          `Service-account permission verification failed (${(error as ApiError).status ?? 'unavailable'}).`,
        ),
      );
    }
  }

  try {
    const computeProject = await fetchGcpApiJson<{
      quotas?: Array<{ metric?: string; limit?: number; usage?: number }>;
    }>(
      fetchImpl,
      token,
      // Compute's project endpoint answers the nested selector
      // `fields=quotas(metric,limit,usage)` with HTTP 200 + `{}`. Requesting the repeated field
      // itself preserves all three quota members and avoids turning a malformed partial-response
      // selector into a false-green zero-row census.
      `https://compute.googleapis.com/compute/v1/projects/${encodedProject}?fields=quotas`,
    );
    quotas = (computeProject.quotas ?? []).map(quotaSnapshot).filter((entry): entry is GcpQuotaSnapshot => !!entry);
    const exhausted = quotas.filter((quota) => quota.limit > 0 && quota.remaining <= 0);
    if (quotas.length === 0)
      checks.push(checkFailure('quotas', 'Compute quota verification returned no parseable quota metrics.'));
    else if (exhausted.length === 0)
      checks.push({
        id: 'quotas',
        status: 'pass',
        summary: `Read ${quotas.length} Compute quota metrics; none are exhausted.`,
      });
    else
      checks.push(
        checkFailure('quotas', `Compute quota is exhausted: ${exhausted.map((quota) => quota.metric).join(', ')}.`, {
          code: 'increase-quota',
          summary: 'Choose a project/region with capacity or request only the exhausted quota increases.',
        }),
      );
  } catch (error) {
    checks.push(
      checkFailure('quotas', `Compute quota verification failed (${(error as ApiError).status ?? 'unavailable'}).`),
    );
  }

  try {
    const result = await fetchGcpApiJson<{ items?: Array<{ name?: string; status?: string }> }>(
      fetchImpl,
      token,
      `https://compute.googleapis.com/compute/v1/projects/${encodedProject}/regions?maxResults=500&fields=items(name,status)`,
    );
    regions = (result.items ?? []).filter((entry) => entry.status === 'UP' && !!entry.name).map((entry) => entry.name!);
    if (input.region && !regions.includes(input.region)) {
      checks.push(
        checkFailure('regions', `Selected region ${input.region} is not available to the project.`, {
          code: 'choose-region',
          summary: 'Select an available region returned by Compute Engine.',
        }),
      );
    } else
      checks.push({ id: 'regions', status: 'pass', summary: `Found ${regions.length} available Compute regions.` });
  } catch (error) {
    checks.push(checkFailure('regions', `Region discovery failed (${(error as ApiError).status ?? 'unavailable'}).`));
  }

  try {
    if (input.zone && input.machineType) {
      const machine = await fetchGcpApiJson<{ name?: string }>(
        fetchImpl,
        token,
        `https://compute.googleapis.com/compute/v1/projects/${encodedProject}/zones/${encodeURIComponent(input.zone)}/machineTypes/${encodeURIComponent(input.machineType)}`,
      );
      machineTypeCount = machine.name ? 1 : 0;
    } else {
      const result = await fetchGcpApiJson<{
        items?: Record<string, { machineTypes?: Array<{ name?: string }> }>;
      }>(
        fetchImpl,
        token,
        `https://compute.googleapis.com/compute/v1/projects/${encodedProject}/aggregated/machineTypes?maxResults=500&fields=items/*/machineTypes/name`,
      );
      machineTypeCount = Object.values(result.items ?? {}).reduce(
        (count, scope) => count + (scope.machineTypes?.length ?? 0),
        0,
      );
    }
    if (machineTypeCount > 0)
      checks.push({
        id: 'machineTypes',
        status: 'pass',
        summary: `Verified ${machineTypeCount} accessible machine type(s).`,
      });
    else
      checks.push(
        checkFailure('machineTypes', 'No accessible machine type matched the selected project and zone.', {
          code: 'choose-machine-type',
          summary: 'Choose a machine type available in the selected zone.',
        }),
      );
  } catch (error) {
    checks.push(
      checkFailure(
        'machineTypes',
        `Machine-type verification failed (${(error as ApiError).status ?? 'unavailable'}).`,
      ),
    );
  }

  const image = input.image ?? GCP_DEFAULT_WORKSPACE_HOST_IMAGE;
  try {
    const result = await fetchGcpApiJson<{ name?: string }>(
      fetchImpl,
      token,
      `https://compute.googleapis.com/compute/v1/projects/${encodeURIComponent(image.project)}/global/images/family/${encodeURIComponent(image.family)}`,
    );
    if (!result.name) throw new Error('gcp_preflight_image_name_missing');
    selectedImage = { ...image, name: result.name };
    checks.push({
      id: 'image',
      status: 'pass',
      summary: `Image family ${image.project}/${image.family} is accessible.`,
    });
  } catch (error) {
    checks.push(
      checkFailure(
        'image',
        `Image family ${image.project}/${image.family} is not accessible (${(error as ApiError).status ?? 'unavailable'}).`,
        {
          code: 'grant-image-access',
          summary: 'Choose an accessible signed image family or grant compute.images.get/useReadOnly on its project.',
          suggestedRoles: ['roles/compute.imageUser'],
          missingPermissions: ['compute.images.get', 'compute.images.useReadOnly'],
        },
      ),
    );
  }

  return {
    ok: !checks.some((check) => check.status === 'fail'),
    checkedAt,
    projectId,
    identity: auth.identity,
    credential: credential.credentialRef
      ? credential
      : {
          ...credential,
          credentialType: 'metadata_or_unknown',
          credentialSource: 'runtime',
          credentialRef: { kind: 'cloud', ref: 'adc://default' },
        },
    checks,
    enabledServices,
    missingPermissions,
    regions,
    machineTypeCount,
    selectedImage,
    quotas,
  };
}
