/**
 * Frame-side desktop capture loop generator
 * (`hive-frame-desktops-live-view-2026-06-06` P-005, transport per D-003).
 *
 * Pure generator (like `frame-bootstrap.ts`): emits the bash script the desktop
 * bootstrap section installs at `/usr/local/bin/papercusp-desktop-capture` and
 * runs in the background on a desktop-enabled frame. Every interval it captures
 * ONE JPEG per active display (`ffmpeg -f x11grab -frames:v 1`) into
 * `/run/papercusp/desktop/display-<n>.jpg` (tmp + `mv -f` so readers never see a
 * torn frame). A display with no X clients beyond its window manager is SKIPPED
 * (pause-when-no-agent-active) — its stale jpeg is removed so the operator's
 * pull doesn't show a dead screen as live.
 *
 * D-003 (decided): the operator PULLS these files over the existing SSH channel
 * while ≥1 viewer is subscribed, and fans out to the UI via SSE. Media never
 * touches PG; nothing on the frame listens on a port for this.
 */

/** Where the capture loop writes its latest-frame JPEGs + lease metadata. */
export const DESKTOP_CAPTURE_DIR = '/run/papercusp/desktop';
/** Where the bootstrap installs the loop script. */
export const DESKTOP_CAPTURE_SCRIPT_PATH = '/usr/local/bin/papercusp-desktop-capture';
/** Default seconds between captures (override via PAPERCUSP_DESKTOP_CAPTURE_INTERVAL). */
export const DESKTOP_CAPTURE_DEFAULT_INTERVAL_SEC = 5;

export interface DesktopCaptureOpts {
  /** Display numbers to capture (e.g. [99, 100, 101, 102]). */
  displays: number[];
  /** X geometry (`WxHxDEPTH`) — the capture uses the WxH part. */
  geometry: string;
  /** Seconds between capture sweeps (default 5; env-overridable on the frame). */
  intervalSec?: number;
}

/** The `WxH` video size for ffmpeg from a `WxHxDEPTH` X geometry. */
export function captureVideoSize(geometry: string): string {
  const m = /^(\d+)x(\d+)x\d+$/.exec(geometry);
  return m ? `${m[1]}x${m[2]}` : '1920x1080';
}

/**
 * Build the standalone capture-loop bash script. One static line set per
 * display (no runtime display discovery) so tests can assert per-display
 * emission, mirroring the frame-bootstrap contract style.
 */
export function buildDesktopCaptureScript(opts: DesktopCaptureOpts): string {
  const interval = opts.intervalSec ?? DESKTOP_CAPTURE_DEFAULT_INTERVAL_SEC;
  const size = captureVideoSize(opts.geometry);
  const perDisplay = opts.displays.map((d) =>
    [
      `  if [ "$(DISPLAY=:${d} xlsclients 2>/dev/null | grep -civ 'openbox' || true)" -gt 0 ]; then`,
      // -q:v 6 ≈ visually-fine thumbnail quality at ~30-60KB/1080p frame.
      // -f mjpeg is REQUIRED: the atomic-write `.jpg.tmp` name defeats ffmpeg's
      // extension-based format inference ("Unable to choose an output format")
      // and the failure would be silently swallowed by the `|| true`.
      `    ffmpeg -loglevel error -y -f x11grab -video_size ${size} -i :${d} -frames:v 1 -q:v 6 -f mjpeg "${DESKTOP_CAPTURE_DIR}/display-${d}.jpg.tmp" 2>/dev/null \\`,
      `      && mv -f "${DESKTOP_CAPTURE_DIR}/display-${d}.jpg.tmp" "${DESKTOP_CAPTURE_DIR}/display-${d}.jpg" || true`,
      '  else',
      // No agent on this display — remove the stale frame so the live view
      // shows "idle", not a frozen screenshot pretending to be current.
      `    rm -f "${DESKTOP_CAPTURE_DIR}/display-${d}.jpg"`,
      '  fi',
    ].join('\n'),
  );
  return [
    '#!/usr/bin/env bash',
    '# Generated by desktop-capture.ts — hive-frame-desktops-live-view P-005.',
    '# Latest-frame JPEG per active display; the operator pulls over SSH (D-003).',
    'set -u',
    `mkdir -p "${DESKTOP_CAPTURE_DIR}"`,
    `INTERVAL="\${PAPERCUSP_DESKTOP_CAPTURE_INTERVAL:-${interval}}"`,
    'while true; do',
    ...perDisplay,
    '  sleep "$INTERVAL"',
    'done',
    '',
  ].join('\n');
}
