/**
 * Pack the local checkout into a runtime tarball for frame delivery
 * (`cloud-deployment-layer-2026-06-06` P-010, private-repo path).
 *
 * The runtime repo is PRIVATE, so the frame bootstrap's anonymous `git clone`
 * can never work — and shipping a git credential to a disposable frame is the
 * wrong trade. Instead the operator packs its own working tree (sources only —
 * the frame re-resolves deps from the public registry via `npm ci`) and scp's
 * the tarball; `frame-installer` stages it and the bootstrap untars it.
 */
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { statSync } from 'node:fs';

const execFileP = promisify(execFile);

/** Heavy/derived trees the frame never needs — it re-installs deps itself.
 *  `.env*` is a SECURITY exclude: the dev box's .env.local carries live secrets
 *  and host-specific config (a pinned DATABASE_URL would override the frame's
 *  embedded-pg discovery; BIND_HOST=0.0.0.0 would expose the frame's operator).
 *  The bootstrap's exported env is the frame's ONLY env authority. */
export const DEFAULT_RUNTIME_EXCLUDES = [
  './.git',
  '.git', // submodule .git files/dirs at any depth
  'node_modules',
  'target', // rust build trees (papercusp-desktop)
  '.next',
  '.turbo',
  // ROOT-anchored: bare 'backups' ate apps/operator/app/settings/backups (a
  // SOURCE dir) and broke the frame's SPA build — found live 2026-06-06.
  './backups',
  // Desktop sidecar build output (a ~500MB omp binary + bundled node/code-server
  // runtimes) — tripled the tarball (222MB → 562MB) when a peer's sidecar build
  // landed in the shared tree (found 2026-06-09). A frame never runs the desktop.
  './papercusp-desktop/src-tauri/sidecar',
  // Vite build output (the served docs mirror inside it is REGENERATED by the
  // build-watch while tar reads — "file shrank" aborts the pack; found live
  // 2026-06-12). Generated content a frame never imports.
  './apps/operator-vite/dist',
  'test-results',
  'playwright-report',
  '*.log',
  '.env*', // secrets + host-specific config — never ship to a frame
];

export interface PackResult {
  outPath: string;
  bytes: number;
}

/** Pack `repoRoot` into a gzipped tarball at `outPath` (tar must be on PATH).
 *
 *  The shared dev tree is LIVE while we pack (git-sync, build-watches, peer
 *  agents) — GNU tar exits 1 ("file changed/shrank as we read it") when a file
 *  mutates mid-read. That class is tolerated: the affected file is padded or
 *  truncated, every other entry is intact, and the frame never imports
 *  mid-churn build outputs anyway. Exit 2 (fatal) still throws. */
export async function packRuntimeTarball(
  repoRoot: string,
  outPath: string,
  excludes: string[] = DEFAULT_RUNTIME_EXCLUDES,
): Promise<PackResult> {
  const args = [
    '-czf',
    outPath,
    ...excludes.flatMap((e) => ['--exclude', e]),
    '-C',
    repoRoot,
    '.',
  ];
  try {
    await execFileP('tar', args, { maxBuffer: 16 * 1024 * 1024 });
  } catch (err) {
    const code = (err as { code?: number | string }).code;
    if (code !== 1) throw err; // tar exit 1 = files changed while reading — tolerated
  }
  return { outPath, bytes: statSync(outPath).size };
}
