// GENERATED by `npm run gen:declarations` from apps/operator/scripts/operator-discovery.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// apps/operator/scripts/operator-discovery.mjs and regenerate.
/** @typedef {Record<string, string | undefined>} EnvironmentMap */
/**
 * The desktop operator's recorded address from ~/.papercusp/operator.json,
 * or null when the file is missing/unreadable (the dev box).
 */
export function discoverOperatorUrl({ home }?: {
    home?: string | undefined;
}): any;
/**
 * Standard CLI precedence: explicit --operator-url arg → PAPERCUSP_OPERATOR_URL
 * env override → live desktop discovery (operator.json) → dev-box :3070.
 * Callers that run inside an operator host can opt into self-host precedence;
 * that inserts the host's valid PAPERCUSP_HONO_PORT before the inherited env
 * override, preventing a staging process from routing its writes to green.
 *
 * Returns a BASE ORIGIN — callers append their own path (ptool posts to
 * `base + '/api/mcp'`). `PAPERCUSP_OPERATOR_URL` is OVERLOADED and cannot be
 * assumed to be one: `apps/operator/.env.local` unconditionally exports it WITH
 * the endpoint path (`http://localhost:3070/api/mcp`) because MCP-config
 * consumers want the full endpoint, and every operator process that sources
 * `.env.local` — including bg-host — inherits that form. Appending `/api/mcp`
 * to it yields `/api/mcp/api/mcp`, which the host answers `404 {"error":"not_found"}`,
 * so the CLI reports "could not reach the operator" for a host that is perfectly
 * healthy. Strip the suffix here, exactly as operator-core's
 * `resolveInheritedOperatorBaseUrl` / `resolveSpawnHostOperatorBaseUrl` already do
 * for the same overloaded variable (the WI-6154 bug class).
 *
 * @param {{operatorUrl?: string | null}} [args]
 * @param {EnvironmentMap} [env]
 * @param {{home?: string, preferSelfPort?: boolean}} [opts]
 * @returns {string}
 */
export function resolveOperatorBase(args?: {
    operatorUrl?: string | null;
}, env?: EnvironmentMap, opts?: {
    home?: string;
    preferSelfPort?: boolean;
}): string;
/**
 * Swap `url`'s origin for `freshBase`, keeping path/query/hash. Returns null
 * when either side is unparseable or the origin is already `freshBase` (no
 * move). Exported for tests.
 */
export function rebaseUrl(url: any, freshBase: any): string | null;
/**
 * Resilient fetch for the sidecar CLIs — the shared, smaller sibling of
 * psu-launcher's fetchWithResilience (WI-3141). A packaged desktop operator is
 * routinely MID-BOOT when the user first opens the app and immediately clicks
 * the Setup/Tutorial icon: serve.mjs starts embedded-PG + runs migrations +
 * boots the Hono host, a multi-second window during which a plain fetch fails
 * "connection refused". The onboarding launchers used a bare fetch with NO
 * retry, so that unavoidable first-boot window surfaced as a hard "I can't reach
 * the Papercusp server" and the user had to relaunch until the boot finished
 * (owner 2026-07-05: "after 3 attempts the tutorial FINALLY showed up"). This
 * rides THROUGH it: CONNECTION failures (refused/reset — undici "fetch failed")
 * are retried on a short backoff until `connectBudgetMs` elapses; a bounded
 * per-request timeout stops a wedged host hanging forever; TIMEOUTs are retried
 * a small fixed number of times.
 *
 * A caller-supplied `init.signal` (e.g. the docs-qa stream's AbortController)
 * OWNS abort — once it fires we stop and rethrow — but a CONNECTION failure that
 * happens BEFORE it fires still retries within the budget, so a streamed call
 * also rides through a brief operator blip. `onRetry` fires once, the first time
 * a retry is scheduled, so a caller can show a "still starting…" note.
 *
 * `rediscover` (WI-3283): the operator may RESTART ONTO A DIFFERENT PORT while
 * we retry — packaged installs re-pick the port when the sticky one is taken,
 * and a `--operator-url` argv/env pin captured at spawn then points at a dead
 * socket for the rest of the process's life (the long-running tutorial shell is
 * the victim: "can't reach the papercusp server" mid-tutorial). Pass
 * `rediscover: discoverOperatorUrl` and every CONNECTION-failure retry re-reads
 * the live discovery file and FOLLOWS the move; `onRebase(newBase)` lets the
 * caller update its own long-lived base. The common same-port mid-boot window
 * stays a plain retry (discovery returns the same origin → no rebase), and a
 * TIMEOUT (reachable-but-slow) never rebases.
 *
 * Deps injected for tests (operator-discovery.test.ts) — fetchImpl/sleep/now
 * make the retry timing deterministic without real sockets or timers.
 *
 * @param {string} url
 * @param {RequestInit} [init]
 * @param {{
 *   fetchImpl?: (url: string, init: RequestInit) => Promise<any>,
 *   sleep?: (ms: number) => Promise<unknown>,
 *   now?: () => number,
 *   timeoutMs?: number,
 *   connectBudgetMs?: number,
 *   timeoutRetries?: number,
 *   onRetry?: (() => void) | null,
 *   rediscover?: (() => string | null) | null,
 *   onRebase?: ((base: string) => void) | null,
 * }} [deps]
 * @returns {Promise<any>}
 */
export function fetchResilient(url: string, init?: RequestInit, { fetchImpl, sleep, now, timeoutMs, connectBudgetMs, timeoutRetries, onRetry, rediscover, onRebase, }?: {
    fetchImpl?: (url: string, init: RequestInit) => Promise<any>;
    sleep?: (ms: number) => Promise<unknown>;
    now?: () => number;
    timeoutMs?: number;
    connectBudgetMs?: number;
    timeoutRetries?: number;
    onRetry?: (() => void) | null;
    rediscover?: (() => string | null) | null;
    onRebase?: ((base: string) => void) | null;
}): Promise<any>;
export type EnvironmentMap = Record<string, string | undefined>;
