// GENERATED by `npm run gen:declarations` from apps/operator/scripts/psu-recovery.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// apps/operator/scripts/psu-recovery.mjs and regenerate.
/** Does argv request recovery before the backend passthrough delimiter? */
export function hasRecoveryCliFlag(argv: any): boolean;
/**
 * Recovery is a closed CLI namespace. A connection/account/agent flag must not
 * be silently ignored while the launcher takes its no-control-plane branch.
 */
export function validateRecoveryCliArgv(argv: any): void;
/** @typedef {{ uid: number | null, username: string, hostname: string }} RecoveryIdentity */
/** @typedef {{ name: "psu", version: string }} RecoveryClient */
/**
 * @typedef {{
 *   capability: typeof RECOVERY_CAPABILITY_DIAGNOSTIC,
 *   argv: string[],
 *   cwd: string,
 *   reason: string,
 *   ttlMs?: number,
 *   maxRuntimeMs?: number,
 * }} RecoveryGrantInput
 */
/**
 * @typedef {{
 *   version: 1,
 *   grantId: string,
 *   capability: typeof RECOVERY_CAPABILITY_DIAGNOSTIC,
 *   argv: string[],
 *   cwd: string,
 *   reason: string,
 *   issuedAt: string,
 *   issuedAtMs: number,
 *   expiresAtMs: number,
 *   maxRuntimeMs: number,
 *   maxUses: 1,
 *   terminalId: string,
 *   identity: RecoveryIdentity,
 *   client: RecoveryClient,
 *   signature: string,
 * }} RecoveryGrant
 */
/**
 * @typedef {{
 *   eventId: string,
 *   event: string,
 *   grantId: string,
 *   [key: string]: unknown,
 * }} RecoveryAuditRow
 */
/**
 * @typedef {{
 *   file: string,
 *   args: string[],
 *   cwd: string,
 *   env: NodeJS.ProcessEnv,
 *   timeoutMs: number,
 * }} RecoveryExecutionSpec
 */
/**
 * @typedef {{
 *   exitCode: number | null,
 *   signal: NodeJS.Signals | null,
 *   timedOut: boolean,
 *   error?: string,
 * }} RecoveryExecutionResult
 */
/** @param {string} [home] */
export function recoveryPaths(home?: string): {
    root: string;
    grants: string;
    consumed: string;
    audit: string;
};
/**
 * @param {RecoveryGrantInput} input
 * @param {{
 *   home?: string,
 *   token: string,
 *   nowMs?: number,
 *   terminalId: string,
 *   identity?: RecoveryIdentity,
 *   clientVersion?: string,
 *   grantId?: string,
 *   env?: NodeJS.ProcessEnv,
 *   resolveExecutable?: (command: string, context: { cwd: string, env: NodeJS.ProcessEnv }) => string,
 * }} opts
 * @returns {RecoveryGrant}
 */
export function issueRecoveryGrant(input: RecoveryGrantInput, opts: {
    home?: string;
    token: string;
    nowMs?: number;
    terminalId: string;
    identity?: RecoveryIdentity;
    clientVersion?: string;
    grantId?: string;
    env?: NodeJS.ProcessEnv;
    resolveExecutable?: (command: string, context: {
        cwd: string;
        env: NodeJS.ProcessEnv;
    }) => string;
}): RecoveryGrant;
/** @param {NodeJS.ProcessEnv} [env] @returns {NodeJS.ProcessEnv} */
export function sanitizeRecoveryEnvironment(env?: NodeJS.ProcessEnv): NodeJS.ProcessEnv;
/** Recovery authority never crosses into an ordinary psu launch/resume/wake. */
/** @param {NodeJS.ProcessEnv} [env] @returns {NodeJS.ProcessEnv} */
export function stripRecoveryMarkers(env?: NodeJS.ProcessEnv): NodeJS.ProcessEnv;
/** @param {RecoveryGrant} grant */
export function renderRecoveryBanner(grant: RecoveryGrant): string;
/**
 * @param {RecoveryExecutionSpec} spec
 * @param {{
 *   spawnImpl?: typeof import("node:child_process").spawn,
 *   platform?: NodeJS.Platform,
 *   kill?: (pid: number, signal?: NodeJS.Signals | number) => boolean,
 * }} [opts]
 * @returns {Promise<RecoveryExecutionResult>}
 */
export function executeExactRecoveryCommand({ file, args, cwd, env, timeoutMs }: RecoveryExecutionSpec, { spawnImpl, platform, kill }?: {
    spawnImpl?: typeof import("node:child_process").spawn;
    platform?: NodeJS.Platform;
    kill?: (pid: number, signal?: NodeJS.Signals | number) => boolean;
}): Promise<RecoveryExecutionResult>;
/**
 * @param {string} grantId
 * @param {{
 *   home?: string,
 *   token: string,
 *   nowMs?: number,
 *   now?: () => number,
 *   terminalId: string,
 *   baseEnv?: NodeJS.ProcessEnv,
 *   identity?: RecoveryIdentity,
 *   clientVersion?: string,
 *   execute?: (spec: RecoveryExecutionSpec) => Promise<RecoveryExecutionResult>,
 *   writeBanner?: (text: string) => void,
 * }} opts
 */
export function runRecoveryGrant(grantId: string, opts: {
    home?: string;
    token: string;
    nowMs?: number;
    now?: () => number;
    terminalId: string;
    baseEnv?: NodeJS.ProcessEnv;
    identity?: RecoveryIdentity;
    clientVersion?: string;
    execute?: (spec: RecoveryExecutionSpec) => Promise<RecoveryExecutionResult>;
    writeBanner?: (text: string) => void;
}): Promise<{
    ok: boolean;
    reason: string | undefined;
} | {
    exitCode: number | null;
    signal: NodeJS.Signals | null;
    timedOut: boolean;
    error?: string;
    ok: boolean;
    grant: any;
    reason?: undefined;
}>;
/**
 * @param {{ home?: string }} [opts]
 * @returns {Promise<RecoveryAuditRow[]>}
 */
export function readRecoveryAudit({ home }?: {
    home?: string;
}): Promise<RecoveryAuditRow[]>;
/**
 * @param {{
 *   home?: string,
 *   send: (events: RecoveryAuditRow[]) => Promise<{ reconciledEventIds?: string[] }>,
 * }} opts
 */
export function reconcileRecoveryAudit({ home, send }: {
    home?: string;
    send: (events: RecoveryAuditRow[]) => Promise<{
        reconciledEventIds?: string[];
    }>;
}): Promise<{
    ok: boolean;
    reconciled: number;
    pending: number;
}>;
/**
 * @param {{
 *   env?: NodeJS.ProcessEnv,
 *   stdinIsTTY?: boolean,
 *   stdoutIsTTY?: boolean,
 *   ancestorCmdlines?: string[] | null,
 * }} [opts]
 */
export function recoveryAuthorizationEligibility({ env, stdinIsTTY, stdoutIsTTY, ancestorCmdlines, }?: {
    env?: NodeJS.ProcessEnv;
    stdinIsTTY?: boolean;
    stdoutIsTTY?: boolean;
    ancestorCmdlines?: string[] | null;
}): {
    ok: boolean;
    reason: string;
} | {
    ok: boolean;
    reason?: undefined;
};
/**
 * @param {{
 *   startPid?: number,
 *   maxDepth?: number,
 *   platform?: NodeJS.Platform,
 *   run?: typeof import("node:child_process").spawnSync,
 * }} [opts]
 * @returns {string[] | null}
 */
export function readRecoveryAncestorCmdlines({ startPid, maxDepth, platform, run, }?: {
    startPid?: number;
    maxDepth?: number;
    platform?: NodeJS.Platform;
    run?: typeof import("node:child_process").spawnSync;
}): string[] | null;
export const RECOVERY_PROTOCOL_VERSION: 1;
export const RECOVERY_CAPABILITY_DIAGNOSTIC: "diagnostic-command";
export const RECOVERY_DISABLED_REASON: "native-recovery-disabled-external-owner-trust-root-required";
export const DEFAULT_RECOVERY_TTL_MS: number;
export const MAX_RECOVERY_TTL_MS: number;
export const DEFAULT_RECOVERY_RUNTIME_MS: 60000;
export const MAX_RECOVERY_RUNTIME_MS: number;
export const MIN_RECOVERY_RUNTIME_MS: 100;
export const RECOVERY_RECONCILE_BATCH: 100;
export type RecoveryIdentity = {
    uid: number | null;
    username: string;
    hostname: string;
};
export type RecoveryClient = {
    name: "psu";
    version: string;
};
export type RecoveryGrantInput = {
    capability: typeof RECOVERY_CAPABILITY_DIAGNOSTIC;
    argv: string[];
    cwd: string;
    reason: string;
    ttlMs?: number;
    maxRuntimeMs?: number;
};
export type RecoveryGrant = {
    version: 1;
    grantId: string;
    capability: typeof RECOVERY_CAPABILITY_DIAGNOSTIC;
    argv: string[];
    cwd: string;
    reason: string;
    issuedAt: string;
    issuedAtMs: number;
    expiresAtMs: number;
    maxRuntimeMs: number;
    maxUses: 1;
    terminalId: string;
    identity: RecoveryIdentity;
    client: RecoveryClient;
    signature: string;
};
export type RecoveryAuditRow = {
    eventId: string;
    event: string;
    grantId: string;
    [key: string]: unknown;
};
export type RecoveryExecutionSpec = {
    file: string;
    args: string[];
    cwd: string;
    env: NodeJS.ProcessEnv;
    timeoutMs: number;
};
export type RecoveryExecutionResult = {
    exitCode: number | null;
    signal: NodeJS.Signals | null;
    timedOut: boolean;
    error?: string;
};
