#!/usr/bin/env bash
# Mirror monaco-editor's runtime asset tree into apps/operator/public/monaco/ so
# the code-editor surfaces load it from LOCALHOST instead of the public internet.
#
# WHY THIS EXISTS (cdn-egress-fixes-2026-08-02 P-001). `@monaco-editor/react`
# resolves the editor at runtime through an AMD loader whose base path defaults
# to `https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs`
# (@monaco-editor/loader/lib/es/config/index.js). We never called
# `loader.config()`, so every first mount of a Monaco surface fetched the editor
# across the internet before it could paint:
#
#     editor-<hash>.js              2333 KB
#     toggleHighContrast-<hash>.js  1234 KB
#     editor/editor.main.css         342 KB
#     ...plus, once a language is used:
#     assets/ts.worker-<hash>.js    6867 KB   (TypeScript)
#     assets/css.worker-<hash>.js   1027 KB
#     assets/html.worker-<hash>.js   697 KB
#
# ~4 MB to open a code editor, ~11 MB once the TypeScript worker loads. Live on
# the Gym dashboard, the harness Plugins section and the dev SQL tab.
#
# It was ALSO a correctness bug, which is the part that is easy to miss: the CDN
# default pins 0.55.1 while package.json installs 0.56.0, so the app RAN a
# version we never typechecked or tested against. Mirroring the installed tree
# fixes the egress and the version skew in one move — the bytes served are now
# by construction the bytes we tested.
#
# WHY THE WHOLE min/vs AND NOT JUST THE MEASURED FILES. Identical reasoning to
# the vditor mirror next door (setup-vditor-runtime.sh): the files one screen
# happens to request are not the files every screen requests. Monaco lazily
# pulls a language grammar the moment a buffer is opened in that language, and
# a worker the moment a language service is needed. A partial mirror turns
# "slow" into "404 — the editor never appears" for exactly those paths, which is
# strictly worse than the bug and intermittent enough to look fixed. 24 MB into
# a public/ that is already ~490 MB, gitignored and generated, removes the class
# rather than the instance.
#
# Run after `npm install` (chained from apps/operator's postinstall next to
# setup-wake-runtime / setup-vad-runtime / setup-vditor-runtime) and again from
# operator-vite's `prebuild`, so a build whose install was skipped still gets the
# assets. Idempotent: a version stamp makes a no-op re-run essentially free.
set -euo pipefail

cd "$(dirname "$0")/.."

# shellcheck source=lib/mirror-tree.sh
. scripts/lib/mirror-tree.sh

ROOT="public/monaco"
DEST="$ROOT/vs"
STAMP="$ROOT/.version"

# `public/monaco` is wholly generated by this script. Reconcile its top-level
# layout before checking the stamp so a previous layout (for example
# public/monaco/monaco/vs) cannot survive the cheap, already-current path and
# get copied into a release alongside the current mirror.
prune_owned_root() {
  if [ ! -d "$ROOT" ]; then
    return
  fi

  find "$ROOT" -mindepth 1 -maxdepth 1 \
    ! -path "$DEST" \
    ! -path "$STAMP" \
    -exec rm -rf -- {} +
}

# Same require.resolve('pkg/package.json') trap as the sibling setup scripts —
# probe paths directly instead of asking node to resolve them.
SRC=""
for cand in \
  "$(pwd)/node_modules/monaco-editor/min/vs" \
  "$(pwd)/../../node_modules/monaco-editor/min/vs"; do
  if [ -d "$cand" ]; then
    SRC="$cand"
    break
  fi
done

if [ -z "$SRC" ]; then
  echo "ERR: can't find monaco-editor/min/vs; install monaco-editor first" >&2
  exit 1
fi

VERSION="$(node -p "require('$SRC/../../package.json').version" 2>/dev/null || echo unknown)"

prune_owned_root

# Skip the copy when the mirror already matches the installed monaco. The stamp
# is written LAST, so an interrupted copy leaves it stale/absent and the next run
# redoes the work rather than trusting a half-populated tree.
#
# A matching stamp is NOT sufficient on its own (WI-10004074): the mirror must
# also hold exactly the package's file set. Otherwise hashed chunks left behind
# by an older monaco build survive every "already current" run and ship in the
# release SPA (28 of them did in 0.0.25). See scripts/lib/mirror-tree.sh.
if [ -f "$STAMP" ] && [ "$(cat "$STAMP")" = "$VERSION" ] && [ -f "$DEST/loader.js" ]; then
  if mirror_matches "$SRC" "$DEST"; then
    echo "monaco-runtime: already current (v$VERSION) — skipping copy"
    exit 0
  fi
  echo "monaco-runtime: v$VERSION stamp is current but $DEST/ file set differs from monaco-editor — re-copying"
fi

rm -rf "$DEST"
mkdir -p "$DEST"
cp -r "$SRC"/. "$DEST"/

# Sanity-check the two assets every single mount needs. A silently-empty mirror
# would now fall back to nothing (a 404, not the old CDN), so fail loudly here
# rather than at paint time in the desktop app.
for required in loader.js editor/editor.main.css; do
  if [ ! -f "$DEST/$required" ]; then
    echo "ERR: monaco mirror is missing $required after copy" >&2
    exit 1
  fi
done

# The stamp sits OUTSIDE the rm'd $DEST, so a `>` redirect would truncate the
# existing inode in place and rewrite every tree that hard-links it (WI-10004321).
# Unlink first so the new stamp is this tree's own file.
rm -f "$STAMP"
echo "$VERSION" > "$STAMP"
echo "monaco-runtime: mirrored monaco-editor v$VERSION into $DEST/ ($(du -sh "$DEST" | cut -f1))"
