/**
 * url-scheme — parse `papercusp://harness?...` links (P-009a).
 *
 * Canonical URL shape per v5 §3 Entry 4:
 *   papercusp://harness?topic=<64-char-hex>&github=<owner>/<repo>&repo_id=<n>
 *
 * Strict rules:
 *   - Protocol must be `papercusp:`.
 *   - Host must be `harness` (the Hyperswarm bootstrap authority keyword).
 *   - Required params: `topic`, `github`, `repo_id`. The optional shared-hive
 *     owner-binding params (below) MAY also be present; any OTHER key → null.
 *   - `topic`: 64 lowercase hex chars (32-byte Hyperswarm topic).
 *   - `github`: `<owner>/<repo>` both matching GitHub's actual rules
 *     (1-100 chars, alphanum/dash/underscore/dot, no leading/trailing dot).
 *   - `repo_id`: positive integer (GitHub's stable numeric repository id).
 *
 * Optional shared-hive owner-binding params (D-007, from-repo-seed receive-side
 * fix): a hive MEMBER link generated by the from-repo publish ALSO carries the
 * owner identity so a DIRECT-LINK joiner can seed its `hive_directory_cache`
 * (`hivePubkey → ownerDevicePubkey`) at join — instead of depending on catching
 * the live announce beacon (the run-20 "0 announce activity" receive failure that
 * left the joiner's roster empty → `decideMemberContentOp` dropped all owner
 * content). The link is TRANSPORT, NOT the trust anchor: a joiner that wants
 * channel-2 assurance re-verifies `owner_device_pubkey` against the
 * `attestation_gist_id` (github-anchored, Ed25519) before trusting/seeding it.
 *
 * THE BINDING GROUP IS THE THREE CHANNEL-1 FIELDS — the gist id rides ALONE
 * (WI-38345). These three are present together or not at all:
 *   - `hive_pubkey`: base64 raw-32 Ed25519 hive pubkey (the cache key; the boot
 *     path re-derives the swarm topic from it, so it cannot be inferred from `topic`).
 *   - `owner_device_pubkey`: base64 (optionally algorithm-tagged) owner device pubkey.
 *   - `owner_github_user_id`: the owner's numeric GitHub user id (channel-2 verify target).
 * and SEPARATELY, when the owner has one:
 *   - `attestation_gist_id`: the owner's device-attestation gist id (channel-2 anchor).
 *
 * WHY THE GIST IS NOT IN THE CONJUNCTION (WI-38345, live A→B stall). It used to be,
 * and an owner whose gist create 422s (no verified GitHub email) resolves an identity
 * with `attestationGistId: ''` — so the falsy fourth conjunct silently deleted the
 * whole binding and every member link it published carried NO `owner_device_pubkey`.
 * That is the deterministic source `join-hive.ts` reads at every real join, so the
 * joiner had nothing left: `resolveJoinedHiveOwnerDevice()` → null, the WI-787/WI-780
 * owner-bootstrap admit could not fire, and the owner's announce was conclusively
 * rejected `binding_invalid` — permanently, since announces are never re-delivered.
 *
 * Relaxing the conjunction costs no security, because it was never a verification:
 * every one of the four fields is attacker-controlled to the SAME degree (anyone who
 * can hand you a link can fabricate a well-formed gist id too), so requiring the
 * fourth adds zero adversarial cost. What actually makes a forged binding inert is
 * downstream and unchanged: the owner-bootstrap admit (`boot.ts`, WI-787) admits ONLY
 * the one device whose announce already passed channel-1 `verifyAnnounceDetailed`, so
 * a link naming a device that cannot produce a validly-signed announce for this hive
 * admits nothing. Dropping the channel-1 binding to protect a channel-2 anchor that
 * no parse-side consumer even reads back is a category error, not a defence.
 *
 * Returns `null` on any malformed REQUIRED input — callers display a human-readable
 * error by checking for null. A malformed/partial OPTIONAL owner binding is IGNORED
 * (the binding just isn't threaded → the joiner falls back to the beacon), never a
 * hard reject. Never throws on invalid input.
 */

/** Parsed representation of a `papercusp://harness?...` link. */
export interface HarnessLink {
  /** 64-char lowercase hex Hyperswarm topic. */
  topic: string;
  /** Full `owner/repo` GitHub name (GitHub-rename-fragile; use `repoId`
   * for stable lookup). */
  github: string;
  /** Derived from `github`. */
  repoOwner: string;
  /** Derived from `github`. */
  repoName: string;
  /** GitHub's stable numeric repository id (never recycled on renames). */
  repoId: number;
  /** D-007 shared-hive owner binding (optional; these THREE are present together).
   *  base64 raw-32 Ed25519 hive pubkey — the `hive_directory_cache` key. */
  hivePubkey?: string;
  /** D-007 owner device pubkey (base64, optionally algorithm-tagged). */
  ownerDevicePubkey?: string;
  /** D-007 owner numeric GitHub user id (channel-2 verify target). */
  ownerGithubUserId?: number;
  /** D-007 owner device-attestation gist id (channel-2 anchor). Rides ALONE
   *  (WI-38345): an owner with no gist still publishes the channel-1 binding
   *  above, so a gist-less hive stays joinable. See the file header. */
  attestationGistId?: string;
  /**
   * A3 (EI-18788176839043286): the pot-git repoKey the OWNER's store for this
   * member is actually named — the federated identity a joiner ADOPTS instead
   * of deriving its own (`adoptRepoKey`, pot-git/repo-identity.ts).
   *
   * Independent of the D-007 owner-binding block above: it rides alone, and a
   * malformed value is dropped rather than rejecting the link (the joiner just
   * falls back to deriving, i.e. today's behaviour).
   */
  repoKey?: string;
}

/** Exact set of accepted query-param keys. Any extra key → null. */
const ALLOWED_PARAMS = new Set([
  'topic',
  'github',
  'repo_id',
  // D-007 optional shared-hive owner-binding params (the first three are
  // all-or-nothing; attestation_gist_id rides alone — WI-38345):
  'hive_pubkey',
  'owner_device_pubkey',
  'owner_github_user_id',
  'attestation_gist_id',
  // A3: the owner's minted pot-git repoKey (optional, stands alone).
  'repo_key',
]);

/** Same charset `pot-git/storage.ts`'s `assertSafeComponent` enforces — a
 *  repoKey is used verbatim as a path AND git-ref component. Duplicated here
 *  (rather than imported) to keep this module dependency-free; `repo-identity`'s
 *  `isValidRepoKey` is the authority and the two are asserted equal in tests. */
const REPO_KEY_RE = /^[A-Za-z0-9._-]{1,200}$/;

/** 64-char lowercase hex. */
const TOPIC_RE = /^[0-9a-f]{64}$/;

/**
 * GitHub owner/repo segment: 1–100 chars, alphanum + hyphen + underscore + dot,
 * no leading or trailing dot. Intentionally permissive for org names; the
 * upstream GitHub API rejects truly invalid names.
 */
const GH_SEGMENT_RE = /^[A-Za-z0-9_-][A-Za-z0-9._-]{0,98}[A-Za-z0-9_-]$|^[A-Za-z0-9_-]$/;

/**
 * D-007: permissive base64-ish guard for the optional owner-binding values
 * (standard base64 +/=, an optional `alg:` tag, and base64url -/_). This only
 * rejects obviously-junk values; the channel-2 attestation verify at the joiner
 * is the real trust gate. base64 `+` round-trips safely because both
 * format/parse go through URLSearchParams (encodes `+` as %2B).
 */
const BASE64ISH_RE = /^[A-Za-z0-9+/=:_-]{1,256}$/;

/**
 * Parse a `papercusp://harness?...` URL. Returns `HarnessLink` on success,
 * `null` on any malformed input. Never throws.
 */
export function parseHarnessLink(url: string): HarnessLink | null {
  if (typeof url !== 'string') return null;

  // Fast prefix check before constructing a URL object.
  if (!url.startsWith('papercusp://')) return null;

  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }

  if (parsed.protocol !== 'papercusp:') return null;
  if (parsed.host !== 'harness') return null;

  // Reject extra params.
  for (const key of parsed.searchParams.keys()) {
    if (!ALLOWED_PARAMS.has(key)) return null;
  }

  const topic = parsed.searchParams.get('topic');
  const github = parsed.searchParams.get('github');
  const repoIdStr = parsed.searchParams.get('repo_id');

  if (!topic || !TOPIC_RE.test(topic)) return null;
  if (!github) return null;

  const slashIdx = github.indexOf('/');
  if (slashIdx <= 0 || slashIdx === github.length - 1) return null;
  const repoOwner = github.slice(0, slashIdx);
  const repoName = github.slice(slashIdx + 1);

  if (!GH_SEGMENT_RE.test(repoOwner) || !GH_SEGMENT_RE.test(repoName)) return null;
  // Reject extra slashes in the github param.
  if (repoName.includes('/')) return null;

  if (!repoIdStr || !/^\d+$/.test(repoIdStr)) return null;
  const repoId = parseInt(repoIdStr, 10);
  if (!Number.isFinite(repoId) || repoId <= 0 || repoId > Number.MAX_SAFE_INTEGER) return null;

  const link: HarnessLink = { topic, github, repoOwner, repoName, repoId };

  // D-007 optional shared-hive owner binding — the CHANNEL-1 group is
  // all-or-nothing, and the channel-2 gist anchor rides alone (WI-38345). A
  // missing or malformed field leaves that part off the link (joiner falls back
  // to the beacon) rather than rejecting the whole link.
  const hivePubkey = parsed.searchParams.get('hive_pubkey');
  const ownerDevicePubkey = parsed.searchParams.get('owner_device_pubkey');
  const ownerGithubUserIdStr = parsed.searchParams.get('owner_github_user_id');
  if (hivePubkey && ownerDevicePubkey && ownerGithubUserIdStr) {
    const ownerGithubUserId = parseInt(ownerGithubUserIdStr, 10);
    if (
      BASE64ISH_RE.test(hivePubkey) &&
      BASE64ISH_RE.test(ownerDevicePubkey) &&
      /^\d+$/.test(ownerGithubUserIdStr) &&
      Number.isFinite(ownerGithubUserId) &&
      ownerGithubUserId > 0 &&
      ownerGithubUserId <= Number.MAX_SAFE_INTEGER
    ) {
      link.hivePubkey = hivePubkey;
      link.ownerDevicePubkey = ownerDevicePubkey;
      link.ownerGithubUserId = ownerGithubUserId;
    }
  }

  // WI-38345: the channel-2 anchor stands alone. It is only MEANINGFUL alongside
  // the channel-1 binding (it attests that device to that GitHub id), so it is
  // dropped when the binding above did not land — but its ABSENCE never costs us
  // the binding, which is the whole point of the split.
  const attestationGistId = parsed.searchParams.get('attestation_gist_id');
  if (attestationGistId && BASE64ISH_RE.test(attestationGistId) && link.ownerDevicePubkey) {
    link.attestationGistId = attestationGistId;
  }

  // A3: the owner's minted repoKey. Stands alone (NOT part of the D-007
  // all-or-nothing block) and is dropped when malformed — a joiner that cannot
  // read it simply derives its own key, which is the pre-A3 behaviour.
  const repoKey = parsed.searchParams.get('repo_key');
  if (repoKey && REPO_KEY_RE.test(repoKey) && repoKey !== '.' && repoKey !== '..') {
    link.repoKey = repoKey;
  }

  return link;
}

/**
 * Build a `papercusp://harness?...` URL from a HarnessLink. Inverse of
 * `parseHarnessLink`. Caller is responsible for providing valid values.
 */
export function formatHarnessLink(link: HarnessLink): string {
  const p = new URLSearchParams({
    topic: link.topic,
    github: link.github,
    repo_id: String(link.repoId),
  });
  // D-007: emit the CHANNEL-1 owner binding when all three of it are present.
  // WI-38345: `attestation_gist_id` is deliberately NOT a conjunct here — an
  // owner whose gist create 422'd has `attestationGistId: ''`, and gating the
  // binding on it published links no joiner could bootstrap from.
  if (link.hivePubkey && link.ownerDevicePubkey && typeof link.ownerGithubUserId === 'number') {
    p.set('hive_pubkey', link.hivePubkey);
    p.set('owner_device_pubkey', link.ownerDevicePubkey);
    p.set('owner_github_user_id', String(link.ownerGithubUserId));
    // The channel-2 anchor rides alone, but only alongside the binding it
    // attests — a gist id with no owner device names nothing (mirrors parse).
    if (link.attestationGistId) p.set('attestation_gist_id', link.attestationGistId);
  }
  // A3: emit the minted repoKey when the caller supplies a well-formed one.
  if (link.repoKey && REPO_KEY_RE.test(link.repoKey) && link.repoKey !== '.' && link.repoKey !== '..') {
    p.set('repo_key', link.repoKey);
  }
  return 'papercusp://harness?' + p.toString();
}
