/**
 * Client-safe runtime contracts for event payloads that cross process or SSE
 * boundaries. Producers and consumers import these types instead of declaring
 * parallel shapes; parsers stay fail-soft while emitting bounded drift telemetry.
 */

import type { OperatorDeadPayload } from './tauri-bindings';

/** Generated by Tauri Specta from the Rust producer; re-exported here so
 * consumers use this module as the single cross-boundary contract seam. */
export type { OperatorDeadPayload } from './tauri-bindings';

export type ContractDrift = {
  contract: 'operator-dead' | 'ui-intent-message' | 'agent-timeline-entry';
  reason: string;
};

export type ContractDriftReporter = (drift: ContractDrift) => void;

const reportToConsole: ContractDriftReporter = (drift) => {
  // Payload values are deliberately excluded: this is shape telemetry, and
  // event bodies can contain user/tool content.
  console.warn('[cross-boundary-contract-drift]', drift.contract, drift.reason);
};

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function invalid(
  contract: ContractDrift['contract'],
  reason: string,
  report: ContractDriftReporter,
): null {
  report({ contract, reason });
  return null;
}

export interface UiIntentMessage {
  id: number;
  intent: string;
  args: Record<string, unknown>;
}

export function parseUiIntentMessage(
  value: unknown,
  report: ContractDriftReporter = reportToConsole,
): UiIntentMessage | null {
  if (!record(value)) return invalid('ui-intent-message', 'payload is not an object', report);
  if (!Number.isSafeInteger(value.id) || Number(value.id) <= 0) {
    return invalid('ui-intent-message', 'id is not a positive safe integer', report);
  }
  if (typeof value.intent !== 'string' || value.intent.length === 0) {
    return invalid('ui-intent-message', 'intent is not a non-empty string', report);
  }
  if (!record(value.args)) return invalid('ui-intent-message', 'args is not an object', report);
  return { id: Number(value.id), intent: value.intent, args: value.args };
}

export type AgentTimelineEntry = {
  kind: 'text' | 'tool_use' | 'tool_result' | 'status' | 'result' | 'prompt';
  /** Only a native terminal record can attest this; ordinary text is not completion. */
  outcome?: 'succeeded' | 'failed';
  text?: string;
  toolName?: string;
  toolInput?: unknown;
  toolId?: string;
  costUsd?: number;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
  ts?: string;
};

const TIMELINE_KINDS = new Set<AgentTimelineEntry['kind']>([
  'text', 'tool_use', 'tool_result', 'status', 'result', 'prompt',
]);
const OPTIONAL_STRINGS = ['text', 'toolName', 'toolId', 'ts'] as const;
const OPTIONAL_NUMBERS = ['costUsd', 'inputTokens', 'outputTokens', 'durationMs'] as const;

export function parseAgentTimelineEntry(
  value: unknown,
  report: ContractDriftReporter = reportToConsole,
): AgentTimelineEntry | null {
  if (!record(value)) return invalid('agent-timeline-entry', 'payload is not an object', report);
  if (typeof value.kind !== 'string' || !TIMELINE_KINDS.has(value.kind as AgentTimelineEntry['kind'])) {
    return invalid('agent-timeline-entry', 'kind is unknown', report);
  }
  if (value.outcome !== undefined && (value.kind !== 'result' || !['succeeded', 'failed'].includes(String(value.outcome)))) {
    return invalid('agent-timeline-entry', 'invalid terminal outcome', report);
  }
  for (const key of OPTIONAL_STRINGS) {
    if (value[key] !== undefined && typeof value[key] !== 'string') {
      return invalid('agent-timeline-entry', `${key} is not a string`, report);
    }
  }
  for (const key of OPTIONAL_NUMBERS) {
    if (value[key] !== undefined && (typeof value[key] !== 'number' || !Number.isFinite(value[key]))) {
      return invalid('agent-timeline-entry', `${key} is not a finite number`, report);
    }
  }
  return value as AgentTimelineEntry;
}

export function parseAgentTimelineEntries(
  value: unknown,
  report: ContractDriftReporter = reportToConsole,
): AgentTimelineEntry[] | null {
  if (!Array.isArray(value)) return invalid('agent-timeline-entry', 'backfill is not an array', report);
  const entries: AgentTimelineEntry[] = [];
  for (const candidate of value) {
    const parsed = parseAgentTimelineEntry(candidate, report);
    if (parsed) entries.push(parsed);
  }
  return entries;
}

export function parseOperatorDeadPayload(
  value: unknown,
  report: ContractDriftReporter = reportToConsole,
): OperatorDeadPayload | null {
  if (!record(value)) return invalid('operator-dead', 'payload is not an object', report);
  const fieldChecks = {
    reason: typeof value.reason === 'string' && value.reason.length > 0,
    respawns: Number.isSafeInteger(value.respawns) && Number(value.respawns) >= 0,
    window_secs: Number.isSafeInteger(value.window_secs) && Number(value.window_secs) >= 0,
  } satisfies Record<keyof OperatorDeadPayload, boolean>;
  const failed = Object.entries(fieldChecks).find(([, ok]) => !ok)?.[0];
  if (failed) return invalid('operator-dead', `${failed} has an invalid type`, report);
  return value as unknown as OperatorDeadPayload;
}
