/**
 * datatype-firstclass-scaffold — PURE codegen for a FIRST-CLASS datatype's SQL backing
 * (reflexive-platform-extensibility-datatypes-2026-06-24 P-001 first-class tier, D-002).
 *
 * generic-kind datatypes need no migration (a work_item kind + validated payload). A datatype
 * GRADUATES to first-class only when it is load-bearing enough to want a native SQL table.
 * That migration must NOT be applied at runtime — it ships through the reviewed PR rail
 * (D-003), exactly like `tools:scaffold` (P-004). This module derives the migration + CRUD
 * tooldef pointers from the datatype's `payload_schema` and returns them as TEXT for review.
 * It writes/executes nothing. Pure → exhaustively unit-testable.
 */

/** Map a JSON-Schema property to a Postgres column type (conservative; jsonb is the catch-all). */
export function sqlColumnType(prop: Record<string, unknown> | undefined): string {
  const t = prop?.type;
  if (t === 'string') return prop?.format === 'date-time' ? 'timestamptz' : 'text';
  if (t === 'integer') return 'bigint';
  if (t === 'number') return 'numeric';
  if (t === 'boolean') return 'boolean';
  if (t === 'object' || t === 'array') return 'jsonb';
  // union / enum-without-type / unknown → jsonb (lossless catch-all the writer narrows later).
  return 'jsonb';
}

export interface FirstClassDatatypeSpec {
  /** datatype id/slug (e.g. 'bet'). */
  id: string;
  /** human title. */
  title: string;
  /** the datatype's payload_schema (JSON Schema) → the table's domain columns. */
  payloadSchema?: Record<string, unknown> | null;
  /** table name; defaults to the id underscored (e.g. 'bet-thesis' → 'bet_thesis'). */
  table?: string;
  /** suggested migration number; placeholder NNN when absent (reserve via db:next-migration). */
  suggestedMigrationNumber?: number;
}

export interface ScaffoldFile {
  path: string;
  action: 'create';
  contents: string;
}

export type FirstClassScaffoldResult =
  | { ok: true; files: ScaffoldFile[]; reviewNotes: string[]; nextSteps: string[] }
  | { ok: false; reason: 'invalid_spec'; message: string };

const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function snake(s: string): string {
  return s.replace(/-/g, '_');
}

/** Identifier-safe column name from a JSON-Schema property key; '' when unusable. */
function columnName(key: string): string {
  const c = key.trim().toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return /^[a-z_][a-z0-9_]*$/.test(c) ? c : '';
}

function domainColumns(payloadSchema: Record<string, unknown> | null | undefined): string[] {
  const props = (payloadSchema?.properties ?? {}) as Record<string, Record<string, unknown>>;
  const required = new Set(Array.isArray(payloadSchema?.required) ? (payloadSchema!.required as string[]) : []);
  const reserved = new Set(['id', 'workspace_id', 'created_at', 'updated_at']);
  const lines: string[] = [];
  for (const [key, prop] of Object.entries(props)) {
    const col = columnName(key);
    if (!col || reserved.has(col)) continue; // skip unusable / reserved names (the writer maps them)
    const nn = required.has(key) ? ' NOT NULL' : '';
    lines.push(`  ${col.padEnd(18)} ${sqlColumnType(prop)}${nn},`);
  }
  return lines;
}

/**
 * Scaffold the first-class backing for a datatype: a reviewable, idempotent CREATE TABLE
 * migration (workspace-scoped + the RLS/grant TODO) derived from `payload_schema`. Returns
 * the file as TEXT — nothing is written or applied (it rides the PR rail, D-003).
 */
export function scaffoldFirstClassDatatype(spec: FirstClassDatatypeSpec): FirstClassScaffoldResult {
  if (!KEBAB.test(spec.id)) {
    return { ok: false, reason: 'invalid_spec', message: `datatype id must be kebab-case (got ${JSON.stringify(spec.id)})` };
  }
  if (!spec.title.trim()) return { ok: false, reason: 'invalid_spec', message: 'title is required' };

  const table = (spec.table ?? snake(spec.id)).toLowerCase();
  if (!/^[a-z_][a-z0-9_]*$/.test(table)) {
    return { ok: false, reason: 'invalid_spec', message: `table name ${JSON.stringify(table)} is not a valid identifier` };
  }
  const num =
    typeof spec.suggestedMigrationNumber === 'number' && Number.isFinite(spec.suggestedMigrationNumber)
      ? String(Math.floor(spec.suggestedMigrationNumber)).padStart(3, '0')
      : 'NNN';

  const cols = domainColumns(spec.payloadSchema);
  const colBlock = cols.length > 0 ? cols.join('\n') + '\n' : '  -- TODO: domain columns (payload_schema had none)\n';

  const contents = `-- ${num}-datatype-${table}.sql — first-class backing table for the "${spec.id}" datatype.
-- ${spec.title}. Generated by datatype-firstclass-scaffold (P-001 first-class tier).
--
-- RESERVE the real migration number via \`db:next-migration\` before merging (NNN is a
-- placeholder — concurrent agents reserve numbers). Idempotent + additive (CREATE TABLE IF
-- NOT EXISTS) so it is fresh-migrate-safe and cannot wedge operator boot. Columns are derived
-- conservatively from the datatype's payload_schema; refine types/constraints as needed.
CREATE TABLE IF NOT EXISTS harness_shared.datatype_${table} (
  id                 text NOT NULL,
  workspace_id       text NOT NULL,
${colBlock}  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, id)
);
-- TODO: GRANTs + ENABLE ROW LEVEL SECURITY + the workspace-isolation policy — copy the tail
-- of 421-datatype-registry.sql (the canonical workspace-scoped idiom).
`;

  return {
    ok: true,
    files: [{ path: `libs/papercusp/libs/db/sql/${num}-datatype-${table}.sql`, action: 'create', contents }],
    reviewNotes: [
      'A first-class datatype migration ships through the reviewed PR rail (D-003) — it is NOT applied at runtime.',
      'Verify it applies against the embedded PG (the datatype-registry integration fixture pattern) before merging.',
    ],
    nextSteps: [
      'Reserve the migration number via `db:next-migration`, rename the file, and open a PR.',
      'Add the RLS + grants tail (copy 421-datatype-registry.sql).',
      'Author the CRUD tooldefs for the table (or keep the generic-kind work_items path) and re-declare the datatype tier:"first-class".',
    ],
  };
}
