/**
 * Boot-time migration apply for the NATIVE :5432 operator
 * (handoff-coordination-dx-followups-2026-06-04 §A1).
 *
 * Embedded-pg applies pending `libs/papercusp/libs/db/sql/*.sql` when ITS
 * server boots; the native dev box has no such runner, so a migration added
 * since the last restart stayed unapplied until a manual `psql -f` + a manual
 * `schema_migrations` INSERT — the long-flagged gap that let a colliding
 * migration number go silently dark (one of two same-numbered files never ran).
 *
 * This runs the SAME idempotent runner against the operator's admin DB on host
 * boot, in LOG-AND-CONTINUE mode: a migration that fails to apply is logged +
 * coord-broadcast and left pending (retried next boot) rather than halting the
 * dev-api the whole fleet shares. (Embedded-pg keeps the fail-loud default —
 * only this shared-box boot opts into continueOnError.)
 */
import postgres from 'postgres';
// Types come from the package's generated `src/index.d.ts` (EI-18804531117413708).
// This import used to carry a `@ts-expect-error` plus a hand-written
// `ApplyPendingMigrations` type it cast to — a local projection of a signature
// in another package, kept in sync by nothing, and duplicated verbatim in
// release-preflight-migration-boot-smoke.integration.test.ts. The suppression
// also meant the cast was unchecked: it could have drifted from the real
// function silently.
// WI-3307: import from the migration-runner MODULE, not the package barrel. Both
// symbols are DEFINED in src/migration-runner.js (index.js merely re-exports them),
// but the barrel also carries a top-level `import EmbeddedPostgres from
// 'embedded-postgres'` — which resolves the platform binary package
// `@embedded-postgres/<platform>` at module-load time. That made a pure-migration
// code path depend on a Postgres BINARY, and it is a STATIC import, so no env knob
// (PAPERCUSP_USE_EMBEDDED_PG=0 included) can gate it.
//
// Measured on the packaged mac dogfood bundle: the `dev` env operator bound :3270
// and then died with `ERR_MODULE_NOT_FOUND: Cannot find package
// '@embedded-postgres/darwin-x64'`, because source.tar.zst ships no
// @embedded-postgres/<platform> package at all. Chain was:
//   agent-tools registry -> agent-tools/release/checkpoint-run.ts (static)
//     -> this file (static) -> embedded-postgres-server/src/index.js
//       -> embedded-postgres/dist/binary.js -> @embedded-postgres/<platform>  [MISSING]
// Types are unaffected: src/migration-runner.d.ts is generated by the same
// `gen:types` script as src/index.d.ts (EI-18804531117413708).
import { applyPendingMigrations, defaultSkipFile } from '@papercusp/embedded-postgres-server/src/migration-runner.js';
import { getHarnessAdminUrl } from './embedded-pg-discovery';
import { isRetryableLockFailure } from './pg-retryable-failure';
import { checkMigrationDrift, resolveSqlDir, sqlDirCandidates } from './migration-drift';
import { resolveDeployedReleaseRoot, verifyPendingCodeDeployMigration } from './migration-deploy-guard';
import { assertMigrationPassesPreApplyLints } from './migration-preapply-lint';
import { sendMessage } from './agent-tools/coordination/messages';
import type { AgentIdentity } from './agent-tools/coordination/identity';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  RESERVATION_ENFORCED_FROM,
  assertMigrationReservation,
  migrationNumberOf,
  reservationFilenameConflicts,
} from './migration-reservation';
import { BACKUP_MIGRATION_ADVISORY_LOCK_KEY } from '@papercusp/backup/application-names';
import {
  describeConflicts,
  findBackupLockConflicts,
  readBackupLockedRelationNames,
} from './backup-lock-migration-proof';
import {
  preDestructiveSnapshotAdmissionGuardSql,
  requiresPreDestructiveSnapshotAdmission,
} from '@papercusp/backup/snapshot-admission';
import { activeWorkspaceId } from './workspace-registry';

export { RESERVATION_ENFORCED_FROM, assertMigrationReservation, migrationNumberOf } from './migration-reservation';

const BOOT_MIGRATE_IDENTITY: AgentIdentity = {
  ownerId: 'boot-migrate',
  ownerLabel: 'boot-migrate',
  source: 'static-client',
  workspaceId: null,
  userId: null,
};

let _ran = false;

// EI-19320461261471579: ride out a transaction-CONTENTION failure instead of
// leaving the migration pending. This path is not only operator boot — the
// green-checkpoint gate calls it as its migration PREFLIGHT, and a preflight
// that leaves a migration pending aborts the whole run as INCONCLUSIVE
// (`green: null`, reason 'migrations-pending'), holding main for the entire
// fleet. Observed live twice in 11 minutes on 2026-08-02 (05:50Z, 06:01Z):
// migration 721 alters harness_shared.work_items, whose two dependent views
// make an `ALTER TABLE …; CREATE OR REPLACE VIEW …` a guaranteed lock-order
// inversion against ordinary fleet readers.
//
// The budget is deliberately MUCH tighter than db:migrate's (2s→30s over 5
// attempts): that tool is an agent waiting on one deliberate apply, whereas
// this runs on the operator's boot path, where a 30s stall delays the dev-api
// the whole fleet shares. A deadlock does not need a long wait — Postgres has
// ALREADY broken the cycle by killing one side, so the retry is about letting
// the surviving transaction commit, not about waiting out a long-lived holder.
// ~1.2s worst case, then fall through to the existing leave-it-pending path.
const CONTENTION_RETRY_MAX_ATTEMPTS = 3;
const CONTENTION_RETRY_BASE_DELAY_MS = 400;
const CONTENTION_RETRY_MAX_DELAY_MS = 2000;

/** Exponential backoff for contention retry attempt N (1-based): 400ms, 800ms,
 *  capped at 2s. Pure — unit tested. */
export function contentionRetryBackoffMs(attempt: number): number {
  return Math.min(CONTENTION_RETRY_BASE_DELAY_MS * 2 ** (attempt - 1), CONTENTION_RETRY_MAX_DELAY_MS);
}

// ---------------------------------------------------------------------------
// WI-38354: keep harness_shared.migration_reservations DERIVED from what is
// actually applied, instead of maintained in parallel by hand.
//
// THE CLASS THIS CLOSES. `lint:migrations` check 5 fails any on-disk
// `<NNN>-*.sql` with NNN >= ENFORCED_FROM that has no `migration_reservations`
// row. It is a GATE lint, so ONE hand-numbered migration red-pins
// green-checkpoint AND every agent's `release:cut` — hours after the file
// landed, in somebody else's lane. That has now happened six times (EI-6843,
// WI-3052, EI-10999 — nine files at once, EI-12709, EI-20224121418388370,
// WI-38348/WI-38350), and every previous fix was a one-off backfill migration,
// which leaves the trap armed. On 2026-08-13 migration 815 held the gate ~2h,
// killed a 0.0.16-alpha release cut, and then FOUR agents independently raced
// four backfill migrations in 48 seconds (816/817/818 all applied, near
// byte-identical) — permanently spending three migration numbers to repair one
// missing row.
//
// WHY BACKFILLING HERE IS SAFE, i.e. why this does not weaken the allocator.
// The reservation table is NOT what makes numbering collision-safe.
// `scripts/next-migration.mjs:171` (the EI-6852 TOCTOU fix) scans
// `maxNumberOnDisk(SCAN_DIRS)` INSIDE the pg advisory lock, immediately before
// the reservation INSERT, and allocates
// `GREATEST(fsMax, maxReserved, maxApplied) + 1`. So a number already present
// on disk can never be handed out again, row or no row. What the table uniquely
// protects is the RESERVE-BEFORE-WRITE window — a number claimed whose file does
// not exist yet — and this reconcile never touches that: it only ever inserts
// rows for migrations that are ALREADY APPLIED, i.e. whose files certainly
// exist. `ON CONFLICT (num) DO NOTHING` means an existing reservation (someone
// else's, with their intent) is never overwritten.
//
// WHERE IT RUNS. This function is the one chokepoint every apply path funnels
// through: native boot-apply, `applyPendingMigrationsNow()`, and the
// green-checkpoint migration PREFLIGHT (green-checkpoint.ts calls it before it
// lints). So the gate reconciles the ledger in the same run that would
// otherwise red on it.
//
// FAIL-SOFT, ALWAYS. Bookkeeping must never be able to break booting. Every
// failure here is logged and swallowed: the caller's migration result is
// unaffected, and the pre-existing lint still catches anything this misses.

/**
 * Mirror of ENFORCED_FROM in `scripts/lint-migrations.mjs` — the number at
 * which reservation discipline began. Numbers below it are grandfathered
 * legacy history and are deliberately left alone.
 *
 * Pinned against the linter by `db-boot-migrate-reservations.test.ts` so the
 * two cannot drift into disagreeing about which migrations are enforced.
 */
/**
 * PURE — the whole decision, with no DB, so it is unit-testable and so the
 * SQL below stays a dumb executor of an already-made choice.
 *
 * Given the applied migration filenames and the reservation numbers that
 * already exist, return the rows that must be inserted to make the ledger
 * complete. Deduplicates by number (two applied files sharing a prefix — the
 * EI-12709 collision shape — yields ONE row, the first seen, rather than a
 * conflicting pair).
 */
export function missingReservationRows(
  appliedFilenames: readonly string[],
  reservedNums: readonly number[],
  enforcedFrom: number = RESERVATION_ENFORCED_FROM,
): { num: number; filename: string }[] {
  const reserved = new Set(reservedNums);
  const out = new Map<number, string>();
  for (const filename of appliedFilenames) {
    const num = migrationNumberOf(filename);
    if (num === null || num < enforcedFrom || reserved.has(num) || out.has(num)) continue;
    out.set(num, filename);
  }
  return [...out].map(([num, filename]) => ({ num, filename }));
}

/**
 * Insert a reservation row for every APPLIED migration >= ENFORCED_FROM that
 * lacks one. Fail-soft: returns 0 and logs on any error.
 *
 * `client` is the postgres-js handle the caller already holds.
 */
export async function reconcileMigrationReservations(
  client: postgres.Sql,
  log: (s: string) => void = (s) => console.log(`[boot-migrate] ${s}`),
  activeFilenames?: ReadonlySet<string>,
): Promise<number> {
  try {
    const applied = await client<{ filename: string }[]>`
      SELECT filename FROM harness_shared.schema_migrations`;
    const reserved = await client<{ num: number; filename: string | null }[]>`
      SELECT num, filename FROM harness_shared.migration_reservations`;
    const conflicts = reservationFilenameConflicts(
      applied.map((row) => row.filename),
      reserved,
      RESERVATION_ENFORCED_FROM,
      activeFilenames,
    );
    if (conflicts.length > 0) {
      log(
        `CRITICAL migration reservation filename conflict(s): ${conflicts
          .map(
            (conflict) => `${conflict.num} applied ${conflict.file}, reserved ${conflict.reservedFilename ?? '<null>'}`,
          )
          .join('; ')}`,
      );
    }
    const rows = missingReservationRows(
      applied.map((r) => r.filename),
      reserved.map((r) => Number(r.num)),
    );
    if (rows.length === 0) return 0;
    const reservationRows = rows.map((row) => ({
      ...row,
      reserved_by: 'reconcile-on-apply',
      intent: 'auto-reconciled (WI-38354): applied without a db:next-migration reservation row',
    }));
    await client`
      INSERT INTO harness_shared.migration_reservations
        ${client(reservationRows, 'num', 'filename', 'reserved_by', 'intent')}
      ON CONFLICT (num) DO NOTHING`;
    log(
      `reconciled ${rows.length} migration_reservations row(s) from applied history ` +
        `(${rows.map((r) => r.num).join(', ')}) — lint:migrations check 5 would otherwise red the shared gate`,
    );
    return rows.length;
  } catch (e) {
    // Bookkeeping must never break the boot or the gate preflight.
    log(`migration_reservations reconcile skipped: ${(e as Error)?.message ?? String(e)}`);
    return 0;
  }
}

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/** How often a boot blocked on a busy backup rendezvous re-tries it and re-runs the proof. */
export const BACKUP_RENDEZVOUS_POLL_MS = 5_000;

type BusyRendezvousProof =
  | { safe: true; migrationFiles: string[]; pendingFiles: string[]; message: string }
  | { safe: false; message: string };

/**
 * WI-10003357 — may boot apply its pending migrations while a backup holds
 * the rendezvous? Yes when nothing is pending, or when no pending file names a
 * relation the backup currently holds (see backup-lock-migration-proof.ts).
 * Any failure to prove it is a "no", so the caller keeps waiting safely.
 */
async function proveBusyRendezvousSafe(client: postgres.Sql, sqlDir: string): Promise<BusyRendezvousProof> {
  try {
    const migrationFiles = (await readdir(sqlDir))
      .filter((file) => file.endsWith('.sql'))
      .filter((file) => !defaultSkipFile(file));
    const appliedRows = await client<{ filename: string }[]>`
      SELECT filename FROM harness_shared.schema_migrations`;
    const applied = new Set(appliedRows.map((row) => row.filename));
    const pendingFiles = migrationFiles.filter((file) => !applied.has(file));
    if (pendingFiles.length === 0) {
      return {
        safe: true,
        migrationFiles,
        pendingFiles,
        message: `backup rendezvous busy, but all ${migrationFiles.length} migration(s) in this tree are already applied`,
      };
    }
    const pending = await Promise.all(
      pendingFiles.map(async (file) => ({ file, sqlText: await readFile(join(sqlDir, file), 'utf8') })),
    );
    const conflicts = findBackupLockConflicts(pending, await readBackupLockedRelationNames(client));
    if (conflicts.length > 0) {
      return {
        safe: false,
        message: `pending migrations: ${pendingFiles.join(', ')}; ${describeConflicts(conflicts)}`,
      };
    }
    return {
      safe: true,
      migrationFiles,
      pendingFiles,
      message: `backup rendezvous busy, but pending migration(s) ${pendingFiles.join(', ')} name no relation the backup holds`,
    };
  } catch (error) {
    return {
      safe: false,
      message: `pending migration set could not be proven safe (${
        error instanceof Error ? error.message : String(error)
      })`,
    };
  }
}

// EI-19403856469813053: a CROSS-BOOT cooldown for a migration file that keeps
// failing. The original symptom this closes: migration 727 (an ALTER on
// harness_shared.work_items — a table with dependent VIEWS, per the
// engineer_issues/harness_features_consolidated pattern) sat pending and
// FAILING (a NOT NULL abort) for ~30 minutes on 2026-08-03. Every single
// operator boot AND every green-checkpoint gate preflight during that window
// (this function is that preflight — see checkpoint-run.ts / green-checkpoint.ts)
// called applyPendingMigrationsNow() fresh, which re-attempted the SAME known-
// broken ALTER — taking a real ACCESS EXCLUSIVE lock on work_items each time,
// before failing and rolling back. Under fleet load (frequent operator boots +
// frequent gate re-fires), that repeats every few minutes for as long as the
// migration stays broken, each time stalling every reader of work_items (and
// its dependent views) for up to their own lock_timeout.
//
// This does NOT change retry-until-fixed semantics — a broken migration still
// gets retried once the cooldown elapses, and a human/agent fixing the file
// still gets it applied promptly (cooldown, not a permanent skip). It only
// stops the SAME known-broken file from re-taking a full-strength lock on
// literally every boot within a short window. Deliberately file-based (not a
// DB table): this path runs BEFORE we know the schema is even healthy, so it
// must not depend on schema state of its own to bootstrap, and a shared file
// under ~/.papercusp naturally scopes the cooldown to "this box", matching
// where the amplification (many agents booting on the SAME shared PG) occurs.
// Best-effort throughout: a read/write failure here must never affect whether
// migrations actually apply — this is a rate-limiting optimization, not a
// correctness mechanism (the schema_migrations ledger stays the sole source of
// truth for what's applied).
export const MIGRATION_FAILURE_COOLDOWN_MS = 5 * 60 * 1000; // 5 minutes

/** Resolve the cooldown duration. Overridable (PAPERCUSP_MIGRATION_COOLDOWN_MS)
 *  purely for test isolation (a real cooldown run would otherwise take 5 real
 *  minutes to observe expiry) — not intended as an operational tuning knob. */
export function resolveMigrationFailureCooldownMs(env: NodeJS.ProcessEnv = process.env): number {
  const raw = env.PAPERCUSP_MIGRATION_COOLDOWN_MS;
  const parsed = raw ? Number(raw) : NaN;
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : MIGRATION_FAILURE_COOLDOWN_MS;
}

interface MigrationCooldownEntry {
  lastFailedAt: number;
  error: string;
  attempts: number;
}
type MigrationCooldownState = Record<string, MigrationCooldownEntry>;

/** Resolve the cooldown state file path. Overridable (PAPERCUSP_MIGRATION_COOLDOWN_FILE)
 *  for test isolation — mirrors the PAPERCUSP_PG_DATA_DIR override convention already
 *  used by @papercusp/embedded-postgres-server for the same reason. */
export function resolveMigrationCooldownFilePath(env: NodeJS.ProcessEnv = process.env): string {
  return env.PAPERCUSP_MIGRATION_COOLDOWN_FILE || join(homedir(), '.papercusp', 'migration-failure-cooldown.json');
}

async function readMigrationCooldownState(path: string): Promise<MigrationCooldownState> {
  try {
    const parsed: unknown = JSON.parse(await readFile(path, 'utf8'));
    return parsed && typeof parsed === 'object' ? (parsed as MigrationCooldownState) : {};
  } catch {
    return {}; // missing file / corrupt JSON — treat as "nothing cooling down"
  }
}

async function writeMigrationCooldownState(path: string, state: MigrationCooldownState): Promise<void> {
  try {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, JSON.stringify(state), 'utf8');
  } catch {
    /* best-effort — see module-level rationale above */
  }
}

export interface BootMigrateResult {
  applied: number;
  failed: { file: string; error: string }[];
}

export interface ApplyPendingMigrationsNowOptions {
  /**
   * Exact migration directory to apply. Callers that have already pinned and
   * prepared a candidate must pass its sql directory instead of re-resolving
   * from this process's ambient cwd/env (WI-41490).
   */
  sqlDir?: string;
  /**
   * Coord-broadcast a failed migration and schema-ahead-of-code drift (default
   * true). WI-10002822: the bg-host boot-gate retry loop re-checks every minute
   * while the background plane is withheld and owns ONE episode alarm of its
   * own, so it passes `false` — otherwise the same failure would be re-broadcast
   * to every inbox once a minute for as long as the migration stays pending.
   * Failures are still console-logged either way.
   */
  broadcast?: boolean;
}

/** Apply pending sql/*.sql on operator boot (native box). Idempotent per
 *  process (the schema_migrations tracker also makes a re-run a no-op).
 *  Never throws — a failure leaves migrations pending, it never wedges boot. */
export async function applyPendingMigrationsAtBoot(): Promise<BootMigrateResult | null> {
  if (_ran) return null;
  _ran = true;
  return applyPendingMigrationsNow();
}

/**
 * EI-13992: the UNGUARDED core of {@link applyPendingMigrationsAtBoot} — no
 * `_ran` singleton, safe to call from any per-invocation caller (not just
 * once-per-process boot). Extracted so the green-checkpoint gate can apply
 * pending migrations to the live dev PG as a PREFLIGHT, independent of
 * operator boot: the self-sustaining deadlock this closes is "gate red →
 * main frozen → db-boot-migrate (boot-only) never re-fires → dev PG stays
 * behind → tests asserting new columns fail → gate stays red". A gate run
 * happens on its own schedule regardless of whether main is frozen, so
 * applying migrations HERE — every run, not just at boot — means the dev PG
 * can never drift far enough behind to red-pin the gate on missing-column
 * failures again. Same idempotent runner (the schema_migrations tracker
 * makes a re-run with nothing pending a fast no-op); never throws. */
export async function applyPendingMigrationsNow(
  options: ApplyPendingMigrationsNowOptions = {},
): Promise<BootMigrateResult | null> {
  const sqlDir = options.sqlDir ?? resolveSqlDir();
  const broadcast = options.broadcast !== false;
  if (!sqlDir) {
    // EI-18737837917400418: this used to be a console.warn — easy to miss on a
    // packaged/headless boot where nobody is watching the console, and the
    // silence let the EI-13992 safety net stay dark for a real deploy for days.
    // Log LOUD, with exactly what was tried, so a misconfigured
    // PAPERCUSP_PG_SQL_DIR (or a genuinely missing sql dir) is diagnosable from
    // the boot log alone instead of requiring a live repro.
    console.error(
      `[boot-migrate] sql dir not found — skipping boot apply. Candidates tried: ${sqlDirCandidates().join(', ')}`,
    );
    return null;
  }

  // A parked code/data migration remains recognizable after its filename is
  // armed because the SQL body carries both PENDING-CODE-DEPLOY and
  // REQUIRES-DEPLOYED markers. Check the release checkout's git HEAD at the
  // runner's last safe point before the file can execute. The callback runs
  // only for files absent from schema_migrations, so an already-applied file
  // is never re-blocked merely because its companion later moved on.
  const deployedReleaseRoot = resolveDeployedReleaseRoot(sqlDir);
  const guardPendingMigration = async (file: string, sqlText: string): Promise<void> => {
    assertMigrationPassesPreApplyLints({ filename: file, sqlText, sqlDir });
    const verdict = verifyPendingCodeDeployMigration({
      filename: file,
      sqlText,
      releaseRoot: deployedReleaseRoot,
    });
    if (!verdict.ok) throw new Error(`[migration-deploy-guard] ${verdict.error}`);
    await assertMigrationReservation(client, file);
    if (requiresPreDestructiveSnapshotAdmission(file)) {
      await client.unsafe(preDestructiveSnapshotAdmissionGuardSql(activeWorkspaceId()));
    }
    // WI-10003357: when boot proved the pending set safe WITHOUT the backup
    // rendezvous, a backup can still start a new pg_dump between that proof and
    // this file. Re-prove this one file against the live lock set right before
    // it runs; a late conflict surfaces as lock contention so the bounded
    // contention retry below waits it out instead of queueing DDL behind the dump.
    if (unlockedWithPending) {
      const conflicts = findBackupLockConflicts(
        [{ file, sqlText }],
        await readBackupLockedRelationNames(client),
      );
      if (conflicts.length > 0) {
        throw new Error(
          `canceling statement due to lock timeout (backup pg_dump now holds a lock this migration needs: ${describeConflicts(conflicts)})`,
        );
      }
    }
  };
  // Set once boot proceeds past a busy backup rendezvous with migrations still
  // pending (see the rendezvous poll below); read by guardPendingMigration.
  let unlockedWithPending = false;

  // A DEDICATED max:1 client — the runner applies each file as a raw
  // `BEGIN; <ddl>; COMMIT;` via .unsafe(), which postgres-js rejects with
  // UNSAFE_TRANSACTION on a pooled (max>1) connection (it can't guarantee the
  // BEGIN/COMMIT land on the same socket). getOrgPg's shared handle is max:2,
  // so we use a throwaway single-connection client (mirrors the embedded-pg
  // boot runner + the migration tests) and close it after.
  // lock_timeout (root-caused 2026-06-08): fail-fast on lock contention instead
  // of queuing. A boot `ALTER TABLE … ADD COLUMN` needs ACCESS EXCLUSIVE; queued
  // behind a pg_dump backup's ACCESS SHARE it would block ALL access to the
  // table for the dump's duration (the coord_event_log → coord → psu-bootstrap
  // wedge). Boot apply is already continueOnError, so a lock_timeout abort just
  // leaves the (idempotent) migration pending for next boot. application_name
  // self-identifies a stuck boot migration in pg_stat_activity.
  const client = postgres(getHarnessAdminUrl(), {
    max: 1,
    prepare: false,
    onnotice: () => {},
    connection: { lock_timeout: 15_000, application_name: 'papercusp-boot-migrate' },
  });
  // Hold the same session advisory lock used by workspace backups. The
  // connection-level lock_timeout above is intentionally disabled while
  // acquiring this rendezvous: a long pg_dump must finish before boot can
  // apply the armed migration, rather than timing out and leaving the next
  // restart as the only retry. Restore the normal fail-fast timeout before
  // entering the migration runner.
  let backupMigrationLockHeld = false;
  // EI-19403856469813053: load the cross-boot cooldown BEFORE attempting
  // anything, so a file that failed recently (elsewhere: a prior boot, or a
  // prior gate-preflight call) is excluded from this attempt entirely — it
  // never takes the ACCESS EXCLUSIVE lock at all this call, rather than
  // taking it again only to fail the same way. See the module-level comment
  // above MIGRATION_FAILURE_COOLDOWN_MS for the full rationale.
  const cooldownPath = resolveMigrationCooldownFilePath();
  const cooldownMs = resolveMigrationFailureCooldownMs();
  const cooldownState = await readMigrationCooldownState(cooldownPath);
  const cooldownNow = Date.now();
  // A host may deliberately pin a different immutable migration tree via
  // PAPERCUSP_PG_SQL_DIR (for example a current-code request host using the
  // deployed release SQL baseline). The cooldown file is shared per workspace,
  // so failures recorded by a staging tree must not be re-injected as pending
  // migrations into a selected tree that does not contain those files. When the
  // directory cannot be read, preserve the old fail-closed behavior and let the
  // migration runner surface the underlying filesystem failure.
  let selectedMigrationFilenames: ReadonlySet<string> | null = null;
  try {
    selectedMigrationFilenames = new Set(
      (await readdir(sqlDir)).filter((file) => file.endsWith('.sql')),
    );
  } catch {
    selectedMigrationFilenames = null;
  }
  const coolingDownEntries = Object.entries(cooldownState).filter(
    ([filename, entry]) =>
      (selectedMigrationFilenames === null || selectedMigrationFilenames.has(filename)) &&
      cooldownNow - entry.lastFailedAt < cooldownMs,
  );
  const coolingDown = new Map(coolingDownEntries);
  // When a backup owns the migration rendezvous but this exact immutable code
  // tree has no pending migration, waiting serves no safety purpose: the
  // runner can only perform its idempotent tracker read/bootstrap. Preserve a
  // snapshot of the filenames we proved applied so a migration that appears in
  // a mutable dev tree after the preflight can never be applied without the
  // rendezvous.
  let noPendingUnlockedSnapshot: ReadonlySet<string> | null = null;
  const skipFile = (f: string): boolean =>
    defaultSkipFile(f) ||
    coolingDown.has(f) ||
    (noPendingUnlockedSnapshot !== null && !noPendingUnlockedSnapshot.has(f));
  try {
    // WI-1194246 — this rendezvous must be UNBOUNDED IN BOTH DIMENSIONS.
    //
    // `lock_timeout = 0` alone is not enough. `statement_timeout` also cancels a
    // `pg_advisory_lock` wait (verified empirically 2026-08-30: with
    // statement_timeout=1s against a held advisory lock, the acquisition aborts with
    // "canceling statement due to statement timeout"). Today harness_admin carries no
    // role-level statement_timeout, so this SET is inert — but WI-1194246 proposes
    // `ALTER ROLE harness_admin SET statement_timeout` to bound bare pool checkouts,
    // and a role default reaches THIS statement too.
    //
    // Measured on the live box: this rendezvous legitimately waits 253.7s and 118.4s
    // (sampled `pg_advisory_lock` / `pg_advisory_xact_lock` on the backup-migration
    // key), far beyond any plausible cap. Without the line below, introducing that role
    // default would turn a valid in-flight snapshot into a failed safety rail — the
    // exact outcome the sibling comment in backup/configure.ts says this code exists to
    // prevent, reintroduced through the other timeout.
    //
    // Deliberately NOT reset after acquisition: the migration application that follows
    // is itself long-running and must not inherit a future role-level cap. `lock_timeout`
    // IS restored below, because lock WAITS during migration should stay bounded.
    await client`SET lock_timeout = 0`;
    await client`SET statement_timeout = 0`;

    // A workspace backup can legitimately hold this lock for many minutes.
    // Request-only operators (:3170 and cluster workers) must not stay dark
    // for that whole window when every migration in THEIR pinned tree is
    // already applied. Try the rendezvous first (the ordinary path remains one
    // query); only when it is busy do the cheap applied-set preflight.
    //
    // WI-10003357: the wait is a POLL, not one blocking pg_advisory_lock. A
    // backup holds the rendezvous through its whole run, including a ~99 GiB
    // transcript tier that locks only the session-archive tables, so a blocking
    // wait kept request-only hosts dark for the entire backup even when the
    // pending migrations touched nothing the dump still held. Each iteration
    // re-tries the lock and re-runs the relation-scoped proof, so boot resumes
    // the moment the dump stops holding what the pending migrations name.
    let announcedWait = false;
    for (;;) {
      const tryLock = await client<{ acquired: boolean }[]>`
        SELECT pg_try_advisory_lock(hashtext(${BACKUP_MIGRATION_ADVISORY_LOCK_KEY})) AS acquired`;
      if (tryLock[0]?.acquired === true) {
        backupMigrationLockHeld = true;
        if (announcedWait) {
          console.log('[boot-migrate] backup migration rendezvous acquired — resuming migration preflight');
        }
        break;
      }
      const proof = await proveBusyRendezvousSafe(client, sqlDir);
      if (proof.safe) {
        noPendingUnlockedSnapshot = new Set(proof.migrationFiles);
        unlockedWithPending = proof.pendingFiles.length > 0;
        console.log(`[boot-migrate] ${proof.message} — continuing without a migration lock`);
        break;
      }
      if (!announcedWait) {
        // Request-only hosts cannot open HTTP until this safety wait finishes.
        // Name the barrier before entering the intentionally unbounded wait so
        // a desktop startup deadline does not look like an unexplained hang.
        console.log(
          `[boot-migrate] waiting for backup migration rendezvous; ${proof.message} — waiting until the backup releases it or stops locking what the pending migrations touch`,
        );
        announcedWait = true;
      }
      await sleep(BACKUP_RENDEZVOUS_POLL_MS);
    }
    await client`SET lock_timeout = '15s'`;
    // Retry ONLY pure transaction contention (lock timeout / deadlock /
    // serialization). Any other failure — a syntax error, a constraint
    // violation, a genuinely broken migration — is a real defect that no
    // amount of retrying fixes, so it breaks out immediately and lands in the
    // existing leave-it-pending + broadcast path below, unchanged. Re-calling
    // applyPendingMigrations is safe and cheap: the schema_migrations tracker
    // makes already-applied files a no-op, so a retry re-attempts ONLY what is
    // still pending.
    let appliedCount = 0;
    let totalKnown = 0;
    let failed: { file: string; error: string }[] = [];
    for (let attempt = 1; attempt <= CONTENTION_RETRY_MAX_ATTEMPTS; attempt++) {
      const pass = await applyPendingMigrations({
        client,
        sqlDir,
        continueOnError: true,
        skipFile,
        beforeApply: guardPendingMigration,
        log: (s) => console.log(`[boot-migrate] ${s}`),
      });
      appliedCount += pass.appliedCount;
      totalKnown = pass.totalKnown;
      failed = pass.failed;
      if (failed.length === 0) break;
      const contentionOnly = failed.every((f) => isRetryableLockFailure(f.error ?? ''));
      if (!contentionOnly || attempt >= CONTENTION_RETRY_MAX_ATTEMPTS) break;
      const delayMs = contentionRetryBackoffMs(attempt);
      console.warn(
        `[boot-migrate] ${failed.length} migration(s) hit transaction contention ` +
          `(${failed.map((f) => `${f.file}: ${f.error}`).join('; ')}) — retrying in ${delayMs}ms ` +
          `(attempt ${attempt + 1}/${CONTENTION_RETRY_MAX_ATTEMPTS}); a deadlock is normally gone on the next try.`,
      );
      await sleep(delayMs);
    }
    // Merge the cooling-down files (skipped this call — never attempted, so
    // `failed` above has no entry for them) back in, so callers (the
    // green-checkpoint / checkpoint-run preflight included) still see them as
    // pending rather than silently vanishing from the report.
    if (coolingDown.size > 0) {
      // EI-23139733173512725: db:migrate (or another operator) can apply a file
      // while an earlier boot failure for it is still cooling down. The applied
      // ledger is authoritative: never re-inject that settled file as a synthetic
      // failure, which otherwise keeps request-serving hosts crash-looping until
      // the wall-clock cooldown expires despite the schema already being current.
      const appliedRows = await client<{ filename: string }[]>`
        SELECT filename FROM harness_shared.schema_migrations`;
      const appliedFilenames = new Set(appliedRows.map((row) => row.filename));
      const retryAfterEntries = coolingDownEntries.filter(([file]) => !appliedFilenames.has(file)).map(([file, entry]) => {
        const retryInSec = Math.max(1, Math.ceil((entry.lastFailedAt + cooldownMs - cooldownNow) / 1000));
        return {
          file,
          error: `skipped — cooling down after ${entry.attempts} prior boot-time failure(s) (last: ${entry.error}); retry in ~${retryInSec}s`,
        };
      });
      failed = [...retryAfterEntries, ...failed];
    }
    // Persist the cooldown: refresh every file that's freshly failing this
    // call (skips the just-merged cooling-down entries, which are unchanged),
    // and drop any tracked file that's no longer in `failed` at all (applied —
    // by this call, another boot, or db:migrate — the ledger is the source of
    // truth; this cooldown state is just an optimization on top of it).
    let cooldownChanged = false;
    for (const f of failed) {
      if (coolingDown.has(f.file)) continue;
      cooldownState[f.file] = {
        lastFailedAt: cooldownNow,
        error: f.error,
        attempts: (cooldownState[f.file]?.attempts ?? 0) + 1,
      };
      cooldownChanged = true;
    }
    for (const filename of Object.keys(cooldownState)) {
      if (!failed.some((f) => f.file === filename)) {
        delete cooldownState[filename];
        cooldownChanged = true;
      }
    }
    if (cooldownChanged) await writeMigrationCooldownState(cooldownPath, cooldownState);
    if (appliedCount > 0) {
      console.log(`[boot-migrate] applied ${appliedCount} pending migration(s) (of ${totalKnown} known)`);
    }
    // WI-38354: keep the reservation ledger DERIVED from applied history. Runs
    // UNCONDITIONALLY, not only when appliedCount > 0 — the migration that
    // needs reconciling is usually one a DIFFERENT process already applied
    // (that is exactly the 815 case: applied by a peer's boot at 23:05Z, then
    // red-pinning the gate for two hours), so gating this on "did I apply
    // something just now" would skip the case it exists for. Fail-soft inside.
    let activeFilenames: Set<string> | undefined;
    try {
      activeFilenames = new Set((await readdir(sqlDir)).filter((file) => file.endsWith('.sql')));
    } catch (e) {
      // Keep the reconciliation fail-soft if the tree disappears between
      // resolveSqlDir() and the directory read; without a trustworthy active
      // set, the DB-only diagnostics remain the safer signal.
      console.warn(`[boot-migrate] active migration filename read skipped: ${(e as Error)?.message ?? String(e)}`);
    }
    await reconcileMigrationReservations(client, undefined, activeFilenames);
    if (failed.length > 0) {
      const files = failed.map((f) => f.file).join(', ');
      console.error(
        `[boot-migrate] ⚠ ${failed.length} migration(s) FAILED and were left pending (retried next boot): ${files}\n` +
          failed.map((f) => `    ${f.file}: ${f.error}`).join('\n'),
      );
      // Loud coord broadcast so peers see the broken migration (the dev-api
      // booted anyway). Ambient-categorised so it doesn't spam every inbox by
      // default but is opt-in visible (include_ambient) + in the coord stream.
      if (broadcast) await sendMessage(BOOT_MIGRATE_IDENTITY, {
        to: ['*'],
        summary: `⚠ ${failed.length} migration(s) failed to apply on operator boot — left pending: ${files}`,
        body: `The native-box boot apply (A1) skipped these so the dev-api could start; they will retry next restart. Fix the SQL then restart the operator (or db:migrate). Errors:\n${failed
          .map((f) => `- ${f.file}: ${f.error}`)
          .join('\n')}`,
        category: 'service-health',
        // P-033 (d): `boot-migrate` does not match the conservative
        // MACHINE_SENDER_PATTERN — mark it machine chatter explicitly so the
        // sendMessage seam stamps `expects:'none'` (D-072).
        extra: { auto: true },
      }).catch(() => {});
    }
    // WI-5050 (WI-4070 class): detect the INVERSE drift — the shared DB was
    // migrated by a NEWER code tree than the one booting. Renames/drops that
    // newer tree performed have already executed, so THIS tree's queries can
    // hit `relation does not exist` at runtime and (worst case) the federation
    // plane dies silently — exactly how a stale dev-source tree (hives→pots,
    // mig-557) killed the VM peer with nothing but scattered PG errors. Loud
    // log + ambient coord broadcast; the operator still boots (the stale tree
    // may serve read paths fine and a refusal would take the whole box down).
    try {
      const drift = await checkMigrationDrift();
      if (drift.schemaAhead.length > 0) {
        const head = drift.schemaAhead.slice(0, 5).join(', ');
        console.error(
          `[boot-migrate] 🚨 SCHEMA AHEAD OF CODE: the DB has ${drift.schemaAhead.length} migration(s) NEWER than anything this code tree ships (${head}${drift.schemaAhead.length > 5 ? ', …' : ''}). ` +
            'This operator is running STALE CODE against a newer-migrated shared DB — expect `relation does not exist` failures on renamed tables and a silently-dead federation plane (WI-4070 class). ' +
            'Update/redeploy this code tree (stale dev-source / old bundle / lagging checkout) before trusting this host.',
        );
        if (broadcast) await sendMessage(BOOT_MIGRATE_IDENTITY, {
          to: ['*'],
          summary: `🚨 schema AHEAD of code on operator boot: DB carries ${drift.schemaAhead.length} migration(s) newer than this code tree — stale operator (WI-4070 class), update/redeploy it`,
          body: `Newest DB-side migrations unknown to this tree: ${head}${drift.schemaAhead.length > 5 ? ', …' : ''}. A stale tree against a newer-migrated DB fails as scattered "relation does not exist" errors and can silently kill federation. Refresh the running code (dev-source tree / bundle / checkout), then restart.`,
          category: 'service-health',
        }).catch(() => {});
      }
    } catch {
      /* detection is best-effort — never blocks boot */
    }
    return { applied: appliedCount, failed };
  } catch (err) {
    console.error('[boot-migrate] boot apply failed (non-fatal):', err instanceof Error ? err.message : err);
    return null;
  } finally {
    if (backupMigrationLockHeld) {
      await client`SELECT pg_advisory_unlock(hashtext(${BACKUP_MIGRATION_ADVISORY_LOCK_KEY}))`.catch((error) => {
        console.warn(
          `[boot-migrate] backup migration rendezvous unlock failed: ${error instanceof Error ? error.message : String(error)}`,
        );
      });
    }
    await client.end({ timeout: 5 }).catch(() => {});
  }
}
