// ── prepended by the specta exporter's `header` hook, NOT hand-written ──────────
// Everything below this block is generated too — see the Tauri Specta banner. The
// text of THIS block lives in the generator config, at the `.header(...)` call in
// papercusp-desktop/src-tauri/src/main.rs. Edit it there; an edit here is lost on
// the next regeneration exactly like an edit to the generated body.
//
// WHY `Value` IS DECLARED HERE. `Value` is `serde_json::Value`. specta
// 2.0.0-rc.24 expands it INLINE at each use site, but its recursive arms cannot be
// inlined, so the exporter emits the bare NAME (`Value[]`,
// `{ [key in string]: Value }`) while never emitting the declaration — leaving the
// generated file referencing a type it does not define (TS2304).
//
// Declaring it in generator CONFIG rather than in the generated OUTPUT is the whole
// point: a hand-added declaration in the output was already dropped once by a
// regeneration (typecheck-ratchet.test.ts's history note records restoring the
// "dropped terminal-layout/Value entries", after which regeneration dropped it
// again). Fix the generator, never its output.
//
// EI-18899708711154370 · no-http-anywhere-2026-07-28 D-014.
export type Value = "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never };
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	workspacesList: () => __TAURI_INVOKE<Registry>("workspaces_list"),
	workspacesCreate: (name: string) => typedError<Workspace, string>(__TAURI_INVOKE("workspaces_create", { name })),
	workspacesRename: (id: string, name: string) => typedError<null, string>(__TAURI_INVOKE("workspaces_rename", { id, name })),
	workspacesDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("workspaces_delete", { id })),
	/**
	 *  Switch the *registry default* workspace (Phase E, P-050).
	 * 
	 *  Pre-Phase-E this killed the sidecar + per-workspace PG and `app.restart()`'d
	 *  — the only way to swap a per-process fake-HOME. Now ONE shared sidecar
	 *  serves every workspace and scoping is per-request (`?ws=` / the workspace
	 *  header → ALS → RLS GUC), so a switch is just a per-WINDOW navigation that
	 *  the frontend performs (`switchWorkspace` → navigate to `/harness?ws=<id>`).
	 *  This command only persists `registry.current` so a fresh launch / the first
	 *  window defaults to it. It NO LONGER restarts — other windows are untouched
	 *  (P-031).
	 */
	workspacesSwitch: (id: string) => typedError<null, string>(__TAURI_INVOKE("workspaces_switch", { id })),
	/**
	 *  Open an ADDITIONAL window pinned to a workspace (Phase E, P-053).
	 * 
	 *  The one shared sidecar serves it; the window self-identifies via `?ws=<id>`
	 *  in its URL, so `getBrowserWorkspaceId()` + the header/`?ws=` stamping scope
	 *  every request — and the RLS `app.workspace_id` GUC — to this workspace. The
	 *  window is labeled `ws-<id>` so it matches the `ws-*` capability pattern that
	 *  grants IPC (see capabilities/default.json); re-opening focuses the existing
	 *  one.
	 */
	workspacesOpenWindow: (id: string) => typedError<null, string>(__TAURI_INVOKE("workspaces_open_window", { id })),
	/**
	 *  Raise a native OS notification (planning-attention-importance D-007).
	 *  Invoked from the webview's DesktopAttentionNotifier on `attention.notify`
	 *  SSE events (escalation / smoke-fail / plan-review / needs-human≥high).
	 *  The webview already shows an in-app toast, so a failure here is non-fatal
	 *  — it's returned as a string and the caller swallows it.
	 */
	showAttentionNotification: (title: string, body: string) => typedError<null, string>(__TAURI_INVOKE("show_attention_notification", { title, body })),
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	checkForUpdate: () => typedError<UpdateInfo, string>(__TAURI_INVOKE("check_for_update")),
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	/**
	 *  Roll the desktop app BACK to an older, already-released `tag` — the Update
	 *  Center "Revert" action (desktop-update-center-and-release-tooling P-4). It is the
	 *  deliberate-downgrade sibling of `install_update`: the SAME download → plugin
	 *  minisign-verify (against the updater pubkey baked into `tauri.conf.json`) →
	 *  sidecar-safe teardown → atomic swap → relaunch path, but pointed at
	 *  `/api/updates/rollback?tag=…` and with the updater's default "remote must be
	 *  NEWER" gate overridden so an OLDER target is accepted (`version_comparator`).
	 * 
	 *  The rollback route (P-5 Unit A) already bounds the tag to the caller's channel
	 *  window, so a stable user can't land on an alpha build; here we only need to tell
	 *  the plugin to install exactly the release the route resolved. The post-update
	 *  self-check (P-013, `run_update_self_check`) keys off the INSTALLED build's OWN
	 *  baked `PAPERCUSP_BUILD_SHA`, so after the downgrade the running operator's sha
	 *  matches the now-current (older) build — a rollback does not false-alarm (D-002).
	 */
	revertTo: (tag: string) => typedError<null, string>(__TAURI_INVOKE("revert_to", { tag })),
	/**
	 *  Spawn a new native pty and start a reader thread that emits
	 *  `pty-data` events as bytes arrive. Returns an id the renderer uses
	 *  for subsequent write/resize/kill calls.
	 */
	ptySpawn: (opts: PtySpawnOpts) => typedError<PtySpawnResult, string>(__TAURI_INVOKE("pty_spawn", { opts })),
	ptyWrite: (id: string, data: string) => typedError<null, string>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("pty_resize", { id, cols, rows })),
	ptyKill: (id: string) => typedError<null, string>(__TAURI_INVOKE("pty_kill", { id })),
	/**
	 *  Return the persistent history buffer for a pty as base64. Used by
	 *  PiPanel on remount: the new xterm starts blank and replays history
	 *  to reach the same on-screen state. Empty string if the pty is
	 *  unknown or the history is empty.
	 */
	ptyHistory: (id: string) => typedError<string, string>(__TAURI_INVOKE("pty_history", { id })),
	/**
	 *  Whether a pty id is still alive. Lets the renderer fall through to
	 *  a fresh spawn when the resume id is stale.
	 */
	ptyIsAlive: (id: string) => __TAURI_INVOKE<boolean>("pty_is_alive", { id }),
	wslStatus: () => __TAURI_INVOKE<WslStatus>("wsl_status"),
	wslInstall: () => typedError<null, WslOpError>(__TAURI_INVOKE("wsl_install")),
	/**
	 *  Re-launch the desktop app with admin elevation via PowerShell's
	 *  `Start-Process -Verb RunAs`. The current process exits as soon as
	 *  the elevated child is spawned. The user sees the UAC prompt,
	 *  approves, and the app reopens with admin rights — `wsl --install`
	 *  will then succeed.
	 */
	wslRelaunchElevated: () => typedError<null, string>(__TAURI_INVOKE("wsl_relaunch_elevated")),
	wslImport: () => typedError<null, string>(__TAURI_INVOKE("wsl_import")),
	wslBootstrap: () => typedError<string, string>(__TAURI_INVOKE("wsl_bootstrap")),
	/**
	 *  Restart the desktop app after WSL onboarding completes. The
	 *  sidecar spawn in setup() short-circuits while WSL state isn't
	 *  Ready, so a clean restart picks up the now-Ready state and routes
	 *  the sidecar through `wsl.exe`. Frontend calls this immediately
	 *  after `wsl_bootstrap` succeeds and a follow-up `wsl_status` returns
	 *  Ready.
	 * 
	 *  Windows: do NOT use `app.restart()` directly — when the app was
	 *  launched inside a job object (the NSIS installer's "run app" checkbox,
	 *  Task Scheduler, some corporate launchers), the job kills the relaunched
	 *  child the moment this process exits, leaving the user on a dead app
	 *  (found live 2026-06-11, runs 11/13: onboarding completed but the
	 *  restarted instance vanished). Spawn the new instance with
	 *  CREATE_BREAKAWAY_FROM_JOB first; fall back to a plain spawn, then to
	 *  app.restart().
	 */
	wslFinalizeReady: () => typedError<null, string>(__TAURI_INVOKE("wsl_finalize_ready")),
	wslUninstall: () => typedError<null, string>(__TAURI_INVOKE("wsl_uninstall")),
	consoleLaunch: (envelope: ConsoleEnvelope) => __TAURI_INVOKE<ConsoleLaunchResult>("console_launch", { envelope }),
	/**
	 *  Enumerate visible top-level desktop windows, optionally filtered to titles
	 *  starting with `prefix` (pass `"Papercup — "` for session terminals). Runs
	 *  natively in this Session-1 process — the ONLY place window enumeration works
	 *  on Windows (D-002). Returns `[]` on non-Windows (Linux uses the operator's
	 *  wmctrl path) so the binding exists cross-platform and is always fail-soft.
	 */
	listWindowsByTitle: (prefix: string | null) => __TAURI_INVOKE<DesktopWindow[]>("list_windows_by_title", { prefix }),
	/**
	 *  Bring the window whose title EXACTLY equals `title` to the foreground
	 *  (restoring it first if minimized). USER-INITIATED ONLY — mirrors the
	 *  `feedback_e2e_no_focus_steal` memory; never call from an automated driver.
	 *  Returns true iff a matching window was found and the foreground call issued.
	 *  No-op returning false on non-Windows (Linux focus stays the wmctrl path).
	 */
	focusWindowByTitle: (title: string) => __TAURI_INVOKE<boolean>("focus_window_by_title", { title }),
	/**
	 *  Run `spec` in a new external NATIVE terminal window.
	 * 
	 *   - Windows: a new Windows Terminal window (conhost fallback) — WI-3033
	 *     (the embedded ConPTY path wedges on legacy inbox WSL).
	 *   - Linux: a new terminal window — the BUNDLED ghostty first (always shipped
	 *     with the desktop, so a barebones install needs no system emulator), then
	 *     $TERMINAL / the known-emulator cascade. Owner directive 2026-07-05: the
	 *     onboarding tutorial runs in a real native terminal window, not an
	 *     embedded webview pane.
	 *   - macOS: unchanged (the embedded SwiftTerm pane works and stays the UX).
	 * 
	 *  Returns the launcher pid when one is observable.
	 */
	externalConsoleRun: (spec: ExternalConsoleSpec) => typedError<number | null, string>(__TAURI_INVOKE("external_console_run", { spec })),
	nativeTerminalStatus: () => __TAURI_INVOKE<NativeTerminalStatus>("native_terminal_status"),
	/**
	 *  Show/hide the native sibling terminal. Returns the new running state.
	 *  D-004: refuses while the FLAGS.TESTING gate is closed — the dock is
	 *  testing-gated (flip the flag via /admin/features, then relaunch or let
	 *  the webview relay re-open the gate live).
	 */
	nativeTerminalToggle: () => typedError<boolean, string>(__TAURI_INVOKE("native_terminal_toggle")),
	/**
	 *  D-004 (operator-chat-sidebar-revival P-014): the webview relays its
	 *  resolved FLAGS.TESTING across the seam here, once flags load and again on
	 *  any live flip. Rust no longer spawns the dock at boot — this is the ONLY
	 *  path that opens the gate. Enabled + not running ⇒ spawn (restores today's
	 *  dock exactly); disabled + running ⇒ shutdown (a live flag-off flip hides
	 *  the dock without a relaunch). Returns the new running state.
	 */
	nativeTerminalSetEnabled: (enabled: boolean) => typedError<boolean, string>(__TAURI_INVOKE("native_terminal_set_enabled", { enabled })),
	/**
	 *  WI-3388 — the terminal's current user layout (divider width fraction +
	 *  collapsed/rail state). Read on mount by the web UI's `<TerminalDivider>`
	 *  so it renders the persisted position instead of flashing a default.
	 */
	terminalGetLayout: () => __TAURI_INVOKE<TerminalLayout>("terminal_get_layout"),
	/**
	 *  WI-3388 — set the terminal's layout (either field optional — pass just
	 *  `collapsed` for the rail toggle, or just `fraction` for a divider drag),
	 *  persist it, and apply it LIVE to whichever backend is running. A no-op
	 *  apply (persisted only) for NewWindow/Disabled — there's no native surface
	 *  to resize.
	 */
	terminalSetLayout: (fraction: number | null, collapsed: boolean | null) => typedError<TerminalLayout, string>(__TAURI_INVOKE("terminal_set_layout", { fraction, collapsed })),
	/**
	 *  Tauri command — invoked from the webview. The wire shape mirrors
	 *  what `apps/operator/lib/transport-adapters/ipc-stream.ts` sends.
	 */
	endpointInvoke: (toolName: string, input: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never }, channel: Channel<EndpointEvent>) => typedError<number, string>(__TAURI_INVOKE("endpoint_invoke", { toolName, input, channel })),
	// Tauri command — cancel an in-flight call.
	endpointCancel: (callId: number) => typedError<null, string>(__TAURI_INVOKE("endpoint_cancel", { callId })),
	/**
	 *  Tauri command — IPC bridge health, for humans and agents.
	 * 
	 *  The observability hole this fills (WI-6512): when `/api` silently stayed on
	 *  the capped HTTP transport there was no way to ask the app *why*. The only
	 *  signal was a startup line that named the wrong cause, so the actual state —
	 *  which discovery file was consulted, whether the pid it named was alive,
	 *  whether a dial had even been attempted — had to be reconstructed by hand
	 *  from `ss`, `/proc` and the JSON files, per investigation.
	 * 
	 *  Cheap and side-effect-free (one small filesystem read); safe to poll.
	 */
	endpointIpcStatus: () => typedError<IpcStatus, string>(__TAURI_INVOKE("endpoint_ipc_status")),
	// Tauri command invoked from injected JS to deliver eval results back to Rust.
	devBridgeResult: (id: string, value: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never }) => __TAURI_INVOKE<void>("__dev_bridge_result", { id, value }),
	/**
	 *  The canonical env set the in-webview `EnvSwitcherBar` renders — the
	 *  AUTHORITATIVE source. The bar reads THIS (never a routable `/api` fetch), so
	 *  it can't self-hide on a `/api` routing glitch. On the dev box it returns all
	 *  4 TARGETS (the never-hide floor — unreachable ones render greyed). On a
	 *  packaged (release) build it returns only the REACHABLE envs (+ the one we're
	 *  on): "ALL INSTALLS ARE DOGFOOD INSTALLS" (owner, 2026-07-06), so a user
	 *  install legitimately runs multiple envs (bundled per-branch sidecars —
	 *  prod/staging), but must not paint ghost dev/local buttons for envs that need a
	 *  source tree it doesn't ship. Reachability is probed here because Rust can
	 *  reach the sibling operators a webview can't (CORS).
	 */
	listEnvs: () => __TAURI_INVOKE<EnvInfo[]>("list_envs"),
	/**
	 *  Tauri command form — for an in-webview trigger (menu item, button), not just
	 *  the global shortcut.
	 */
	openDocsSearchPalette: () => __TAURI_INVOKE<void>("open_docs_search_palette"),
	/**
	 *  WI-4827 — open a same-origin app `route` in the MAIN operator window and
	 *  dismiss the Quick Panel palette (Spotlight-style). Invoked from the panel
	 *  webview when a control would otherwise navigate the small palette window into
	 *  the full app. In dev the `main` window is in THIS process — focus +
	 *  soft-navigate it. In every packaged Server (Linux/macOS/Windows), the GUI is
	 *  a separate product process — persist the route and launch/focus the GUI
	 *  bundle, which applies it via `apply_pending_route`.
	 */
	openRouteInApp: (route: string) => __TAURI_INVOKE<void>("open_route_in_app", { route }),
};

/** Events */
export const events = {
	operatorDead: makeEvent<OperatorDeadPayload>("operator-dead"),
};

/* Types */
/**
 *  Mirror of the TS-side `ConsoleEnvelope` from
 *  packages/operator-core/lib/console-launcher.ts.
 */
export type ConsoleEnvelope = {
	cwd: string,
	env: { [key in string]: string },
	mcpJsonContents: string,
	greetingCmd: string,
	needsSuperuserBootstrap: boolean,
	/**
	 *  windows-desktop-feature-parity-2026-07-02 P-010: a fresh UUID minted
	 *  per launch (console-launcher.ts `buildConsoleEnvelope`) — the WINDOW's
	 *  own identity. Every spawner titles the OS window
	 *  `Papercup — <session_id>` (see `window_title_for` below) so a
	 *  launched terminal can be found + focused by TITLE, which matters most
	 *  on Windows: the agent runs inside the `papercup-runtime` WSL2 distro
	 *  while the terminal window is a native Win32 process, so there is no
	 *  Windows window-ancestor for a WSL pid and pid->window mapping is
	 *  structurally impossible — title is the only durable link.
	 */
	sessionId: string,
};

export type ConsoleLaunchResult = { status: "ok"; pid: number | null; displaced_mcp_json: boolean; bootstrapped: boolean } | { status: "err"; error: string };

/**
 *  A visible top-level desktop window. `hwnd` is the raw handle as a decimal
 *  string (opaque to JS — only round-tripped back into `focus_window_by_title`).
 *  Mirrors the TS `WindowsDesktopWindow` shape in windows-desktop-windows.ts.
 */
export type DesktopWindow = {
	title: string,
	pid: number,
	hwnd: string,
};

/**
 *  One event surfaced to the webview JS. Tagged JSON via Serde.
 * 
 *  The TS shape (apps/operator):
 *    { kind: 'event', name: string, data: unknown }
 *    | ArrayBuffer // raw EVENT_BIN payload; decoded by ipc-stream.ts
 *    | { kind: 'done', result: ToolResult }
 *    | { kind: 'error', code: string, message: string }
 */
export type EndpointEvent = 
// JSON-valued event (delta, tool_call, suggestion, cost, etc.).
{ kind: "event"; name: string; data: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | 
/**
 *  Binary event. `payload` is the original EVENT_BIN wire payload:
 *  `[8B call id BE][4B name length BE][name UTF-8][binary]`.
 * 
 *  Its custom `IpcResponse` implementation sends this variant as
 *  `InvokeResponseBody::Raw`, so Tauri delivers an ArrayBuffer without a
 *  base64 or JSON-array round trip. Keeping control and raw messages on the
 *  SAME Channel preserves Tauri's per-channel ordering index; a second raw
 *  channel would let a small JSON `done` overtake a large binary fetch.
 */
{ kind: "binary"; payload: number[] } | 
// Tool returned successfully.
{ kind: "done"; result: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | 
// Dispatch or handler failed (role gate, quota, timeout, throw).
{ kind: "error"; code: string; message: string };

// One env button the in-webview bar renders. Serialized camelCase for JS.
export type EnvInfo = {
	id: string,
	label: string,
	port: number,
	origin: string,
	tooltip: string,
	reachable: boolean,
	isSelf: boolean,
};

/**
 *  A command to run in an external native terminal window. Mirror of the
 *  TS-side spec assembled in OnboardingConsole.tsx (camelCase over the wire).
 */
export type ExternalConsoleSpec = {
	command: string,
	args?: string[],
	// Linux path INSIDE the WSL distro (the operator + command live there).
	cwd: string,
	env?: { [key in string]: string },
	/**
	 *  Exact window title — the frontend focuses the window by this title
	 *  later (focus_window_by_title), so it must be stable per surface.
	 */
	title: string,
};

/**
 *  A snapshot of IPC bridge health, as returned by `endpoint_ipc_status`.
 * 
 *  This is the answer to "is /api actually riding IPC right now, and if not
 *  what precisely is stopping it" — a question that previously could only be
 *  answered by correlating `ss`, the discovery JSON files, and process
 *  liveness by hand.
 */
export type IpcStatus = {
	// Live re-resolution performed at status time (a pure filesystem read).
	resolvedPath: string | null,
	resolutionDetail: string,
	/**
	 *  `connected` · `dead` · `never-connected` · `dial-in-flight` · `disabled`.
	 * 
	 *  `dial-in-flight` means the connection lock was held when we looked.
	 *  Seeing it persist across repeated calls is itself the diagnosis: a
	 *  dial is hung, and every `/api` call is queued behind it.
	 */
	client: string,
	attempts: number,
	reuses: number,
	resolveMisses: number,
	connectErrors: number,
	connects: number,
	invokes: number,
	msSinceLastAttempt: number | null,
	msSinceLastConnect: number | null,
	lastError: string | null,
	connectedPath: string | null,
	/**
	 *  Whether the operator owning the IPC socket is provably the one that served
	 *  this webview — see [`SocketResolution::owner_is_content_origin`]. The
	 *  webview reads this to decide whether content-origin-scoped paths
	 *  (`/api/desktop/*`) may ride IPC, instead of excluding them unconditionally.
	 */
	ownerIsContentOrigin: boolean,
};

export type NativeTerminalStatus = {
	// One of glued-ghostty-x11 / new-window / embedded-* / disabled.
	strategy: string,
	running: boolean,
};

/**
 *  Payload for the `operator-dead` webview event (WI-1878 / critical-process-
 *  supervisor-2026-07-04 P-005). Emitted once per operator-dead EPISODE: since
 *  WI-3270 made give-up recoverable (respawns resume when the cap window
 *  drains), GiveUp can recur across retry cycles — the callers gate this
 *  notify on a once-per-episode flag that resets on recovery, so it still
 *  never floods the webview. `reason` distinguishes which supervisor gave up,
 *  since the two watchers cover different roles (GUI-side Server-bundle
 *  respawn vs. the Server's own in-process serve.mjs child respawn).
 */
export type OperatorDeadPayload = {
	reason: string,
	respawns: number,
	window_secs: number,
};

export type PtySpawnOpts = {
	command: string,
	args?: string[],
	cwd: string | null,
	env?: { [key in string]: string },
	cols?: number,
	rows?: number,
};

export type PtySpawnResult = {
	id: string,
	pid: number | null,
};

export type Registry = {
	current: string,
	workspaces: Workspace[],
};

/**
 *  The terminal's user-controlled layout. `fraction` is resolution-
 *  independent (a fraction of the GUI window's docking-axis size, like
 *  `GlueConfig::fraction`) so it's meaningful after a relaunch on a
 *  differently-sized display; `collapsed` fully hides the terminal's native
 *  surface, leaving only the webview's rail control. Persisted as "a
 *  setting" (native window chrome — the owner explicitly ruled out a nuqs
 *  URL param, which the webview's location bar has no reach into anyway).
 */
export type TerminalLayout = {
	fraction: number,
	collapsed: boolean,
};

export type UpdateInfo = {
	available: boolean,
	current_version: string,
	new_version: string | null,
	notes: string | null,
	/**
	 *  The update check could not actually be performed — the release host was
	 *  unreachable, throttled, or never configured. DISTINCT from `available:
	 *  false`, which means "checked, and you are current".
	 * 
	 *  The Tauri updater protocol has no slot for this: a 204 means "no update",
	 *  and the plugin hands back `Ok(None)` whether we compared versions or
	 *  never got an answer at all. So an unreachable host reads to the user as
	 *  "you are up to date" — silently, forever, and indistinguishable from
	 *  success. That is the worst failure mode an updater can have, and it is
	 *  exactly how a 0.0.8 with no release host baked in would present: eternally
	 *  current, never updating, saying nothing.
	 */
	check_failed: boolean,
	/**
	 *  Why the check could not be performed (`no_token` / `fetch_failed` /
	 *  `no_candidate` / `manifest_unconfigured`), when the sidecar reports one.
	 */
	check_reason: string | null,
};

export type Workspace = {
	id: string,
	name: string,
	// Unix epoch milliseconds.
	createdAt: number,
};

/**
 *  Typed error for the install commands. Frontend uses the variant tag
 *  to decide whether to re-launch with elevation, retry, or show a
 *  generic error.
 */
export type WslOpError = 
/**
 *  `wsl --install` returned 740 (ERROR_ELEVATION_REQUIRED). User
 *  must re-launch the app with admin privileges. Message is the
 *  stderr we got back, mostly for diagnostics.
 */
{ kind: "NeedsElevation"; message: string } | 
// Generic failure — exit code + stderr.
{ kind: "Failed"; message: string };

export type WslState = 
/**
 *  Not on Windows; nothing to do.
 * 
 *  Note: NO `rename_all = "camelCase"` here. The frontend
 *  (apps/operator/lib/wsl-tauri.ts) and the WslOnboardingGate
 *  component check `state.kind === 'NotSupported' | 'NotInstalled'
 *  | …` in PascalCase. Adding camelCase here makes the gate's
 *  pass-through check fail on Linux — the wizard then shows on
 *  machines that should never see it.
 */
{ kind: "NotSupported" } | 
// `wsl.exe` not on PATH, or `wsl --status` errored.
{ kind: "NotInstalled" } | 
// User has launched the install but reboot hasn't happened yet.
{ kind: "PendingReboot" } | 
// WSL works, but our papercup-runtime distro hasn't been imported.
{ kind: "InstalledNoDistro" } | 
// Distro exists, papercup bootstrap hasn't run.
{ kind: "PendingBootstrap" } | 
// Ready to use.
{ kind: "Ready" } | 
/**
 *  Something went wrong. `message` carries detail; frontend shows a
 *  retry button.
 */
{ kind: "Error"; message: string };

export type WslStatus = {
	state: WslState,
	/**
	 *  `true` if `wsl.exe` exists on PATH at all (regardless of version
	 *  / install state).
	 */
	wslExeAvailable: boolean,
	// Listed via `wsl --list --quiet`. Empty before WSL is installed.
	distros: string[],
	// Default WSL version (1 or 2). 0 if unknown.
	defaultVersion: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

