/**
 * The su.md DECOMPOSITION — kernel / identity / instance boundary extraction as
 * SLOT ASSIGNMENTS over the live su base (`identities-v1-2026-08-30` P-002;
 * rulings D-003 as narrowed by D-007, the D-017 registry, D-018 §4 dedupe).
 *
 * WHAT THIS IS. `blueprints/base/prompts/su.md` is the LIVE su render source
 * (`role-launch-spec → resolvePromptFiles('su') → renderSuPlaybook`), and P-002
 * does NOT cut it — P-003 switches the render. What P-002 delivers is the
 * CLASSIFICATION: every line of su.md belongs to exactly one TILE, every tile is
 * assigned to one PART — the sealed `kernel`, the reserved `instance` layer, or
 * a declarable slot from `slots.ts` — and the parts are materialised as VERBATIM
 * documents (`SU_PART_DOCUMENTS`) that P-003's renderer composes and P-020 /
 * P-021 promote into identities. D-007: the output is slot assignments, not a
 * profession/facet type split.
 *
 * HOW A TILE IS ADDRESSED — by ANCHOR, not by line number. A tile is the run of
 * lines from its anchor (the exact text of its first line, unique in su.md) up
 * to the line before the next tile's anchor; the last tile runs to EOF. So the
 * tiling is complete by construction, an edit INSIDE a tile moves nothing, and
 * only a removed / duplicated / reordered anchor breaks it (`suTilingProblems`
 * says which). Two guards keep the classification honest as su.md evolves:
 * every `## ` / `### ` heading and every `<!-- PAPERCUSP-SU:… -->` splice
 * marker MUST be an anchor, so a NEW top-level section fails the test until it
 * is classified rather than silently inheriting its neighbour's slot. (A new
 * BULLET inside an existing tile does inherit — that is the granularity limit,
 * and the one place a reviewer still has to look.)
 *
 * THE PART DOCUMENTS ARE DERIVED, NOT AUTHORED. Each is byte-equal to the
 * concatenation of its tiles (`extractSuPart`), so the union of every part
 * document plus the seam tiles IS su.md — the lossless pin. They are committed
 * so an identity has a real file on disk (`papercusp-engineer`'s
 * `prompts/agent-base-overlay.md` is the coding hive's future `domain` leaf,
 * D-018 §5 / EI-22285277325728666), regenerated by
 * `npm run gen:su-decomposition`, and drift-checked by `su-decomposition.test.ts`
 * (derived-truth ladder: DERIVE, then PIN).
 *
 * D-018 §4 DEDUPE. `agent-base-preamble.md` is the kernel's BASE text rendered
 * on EVERY tier; su.md's ring-0 paragraphs are kernel EXTENSIONS of the
 * interactive tier. Where a tile duplicates a preamble section it carries
 * `dedupeWithPreamble` naming that heading — the text is KEPT here (su.md is
 * still the live render) and P-003 keeps it once, in the preamble.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { harnessPath } from '@papercusp/harness/paths';
import { SLOT_IDS, type SlotId } from './slots.js';

/** Harness-relative path of the live su render source. */
export const SU_SOURCE_REL = 'blueprints/base/prompts/su.md';
/** Harness-relative path of the kernel's base text (D-018). */
export const SU_PREAMBLE_REL = 'blueprints/base/prompts/agent-base-preamble.md';
/** The base role library — every prompt in it gets a disposition row below. */
export const BASE_ROLE_LIBRARY_REL = 'blueprints/base/prompts';

/** A tile's destination: a declarable slot, or one of the two reserved layers. */
export type SuPart = SlotId | 'kernel' | 'instance';
export const SU_PARTS: readonly SuPart[] = ['kernel', ...SLOT_IDS, 'instance'];
export function isSuPart(x: unknown): x is SuPart {
  return typeof x === 'string' && (SU_PARTS as readonly string[]).includes(x);
}

/** The two v1 fleet postures (D-003 scope guard: exactly these, no third before v1 ships). */
export type FleetPostureRole = 'member' | 'leader';

export interface SuTile {
  /** The EXACT text of the tile's first line in su.md — must occur exactly once. */
  anchor: string;
  part: SuPart;
  /** `fleet-posture` tiles only: which posture document the tile feeds. */
  posture?: FleetPostureRole;
  /** What the tile says, in a few words (the doc table's label). */
  label: string;
  /** Why it lands in `part` — the ruling it applies. */
  rationale: string;
  /**
   * D-018 §4: the `agent-base-preamble.md` heading (without `# `) this tile
   * duplicates. Kept here; P-003 keeps it ONCE, in the preamble.
   */
  dedupeWithPreamble?: string;
  /** The tile IS a `<!-- PAPERCUSP-SU:<seam> -->` splice marker, not prose. */
  seam?: string;
}

/**
 * The tiling, in su.md order. Anchors are copied VERBATIM from the file — an
 * anchor that no longer matches is the signal to re-read that section and
 * re-classify it, never to loosen the match.
 */
export const SU_TILES: readonly SuTile[] = [
  {
    anchor: '# Superuser engineer-collaborator (su) — domain-neutral base persona',
    part: 'kernel',
    label: 'title + provenance blockquote',
    rationale:
      'The document’s own framing — "the universal how-we-work-together spine … for ANY pot" — is the kernel’s self-description; P-003’s seal restates it for the composed stack.',
  },
  {
    anchor: '## Who you are',
    part: 'kernel',
    label: 'authority grant (operator + admin) · "the domain comes from the pot"',
    rationale:
      'The su tier’s authority level is a safety rail every layer inherits, and "the domain of that work comes from the pot" is the composition statement itself (D-002 kernel + overlay).',
  },
  {
    anchor: '**Address the owner by name.** When you speak TO the owner — a report, a question, a',
    part: 'collaboration-stance',
    label: 'address the owner by name',
    rationale: 'D-017 names "address by name" as the collaboration-stance slot’s content.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:CLIENT-TOOLING-OVERLAY -->',
    part: 'client',
    seam: 'CLIENT-TOOLING-OVERLAY',
    label: 'client-overlay splice seam',
    rationale:
      'su.md carries only the seam; the `client` slot’s documents are the per-client overlays `apps/operator/prompts/papercusp-su.{claude,codex,omp}.md` that `renderSuPlaybook` splices here (D-007 amendment; audit S2).',
  },
  {
    anchor: '## Working in a shared environment — coordination is enforced',
    part: 'kernel',
    label: 'locks · claim-before-edit · await-don’t-poll · wake the owner · yield · directed messages outrank',
    rationale:
      'Lock discipline, claims, event/wake semantics and the directed-message priority are D-003’s protocol invariants — everything whose violation harms OTHER agents.',
  },
  {
    anchor: '## Working as a fleet MEMBER — the member operating loop',
    part: 'fleet-posture',
    posture: 'member',
    label: 'member loop: wake bootstrap · pull via scheduler:get_next · claim via wip-flip',
    rationale: 'D-003: the member PULL-LOOP operating style leaves the kernel and becomes the member posture (P-020).',
  },
  {
    anchor: "- **Finish with `work_items:complete { id, completion, state:'done', assumptions:'none' }`",
    part: 'kernel',
    label: 'completion evidence is a structured object; assumptions required',
    rationale: 'D-007’s narrowed kernel: "completion evidence required" is an invariant, not member style.',
  },
  {
    anchor: '- **Persist with `loop:arm`; each wake pull + advance one unit. Lane drained? Register',
    part: 'fleet-posture',
    posture: 'member',
    label: 'member loop: persist with loop:arm · register the pool-refill watch · push beats polling · report exceptions to the leader',
    rationale: 'Member operating style (D-003); the await/emit PROTOCOL it uses is already kernel in the shared-environment section.',
  },
  {
    anchor: "- **Never contest a live peer's claim** — a `claim_conflict` means coordinate with the",
    part: 'kernel',
    label: 'claims honoured · a gate opens on the leader’s event (latch) · wind-down on stand-down',
    rationale:
      'D-007’s kernel invariants verbatim: claims honoured, gate events, stand-down obeyed. Phrased for members, binding for every agent.',
  },
  {
    anchor: '## Git — a background routine owns commit + push',
    part: 'domain',
    label: 'git-sync owns commit + push · edit only the canonical staging tree',
    rationale:
      'Source-control convention of the software-engineering profession (D-007: the domain slot = "what the work IS and how it is judged"); the named worktrees are instance colour the project guide already carries.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:WORKSPACE-MAP -->',
    part: 'kernel',
    seam: 'WORKSPACE-MAP',
    label: 'workspace-map splice seam',
    rationale: 'The map is derived from the live workspace-path contract; the marker is kernel addressing, never copied domain prose.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:PROMOTION-MODEL -->',
    part: 'kernel',
    seam: 'PROMOTION-MODEL',
    label: 'promotion-model splice seam',
    rationale: 'The promotion section is derived from release configuration; its seam stays in the kernel so the domain identity remains marker-free when used as a standalone system-prompt overlay.',
  },
  {
    anchor: '## Engineering discipline',
    part: 'domain',
    label: 'section heading',
    rationale: 'The domain document’s own heading; its kernel-classified bullets are tiled out individually below.',
  },
  {
    anchor: '- **Plan before non-trivial work.** Durable plans live in the plan store (shared,',
    part: 'kernel',
    label: 'plan-store lifecycle: plan-before-work tiers · activation audit · encode real deps',
    rationale:
      'Registration + plan-lifecycle discipline holds for ANY domain (a potato-salesman pot plans too); it is the "Registering work" tier rule stated at plan scope.',
  },
  {
    anchor: "- **Tests ship WITH the feature**, in the project's testing framework — not an ad-hoc",
    part: 'domain',
    label: 'tests ship with the feature',
    rationale: 'How engineering work is judged (D-007 domain).',
  },
  {
    anchor: '- **Raw forensic output (journalctl, psql dumps, proc scans) never enters agent context** —',
    part: 'kernel',
    label: 'raw forensic output never enters agent context',
    rationale: 'Context hygiene is a ring-0 concern (the preamble’s "Context management" family), domain-neutral.',
  },
  {
    anchor: "- **A blocker is work, not a stop sign — resolve it, don't relay it.** Hit a blocker (a",
    part: 'kernel',
    label: 'a blocker is work, not a stop sign',
    rationale: 'Ring-0; near-verbatim in the preamble — kept once there (D-018 §4).',
    dedupeWithPreamble: 'Blockers',
  },
  {
    anchor: '- **Before you report a number, find the code that WRITES it.** A metric, a count, a score, a',
    part: 'kernel',
    label: 'read the writer before reporting a number · a retraction is owed fast',
    rationale:
      'Faithful reporting is the interactive tier’s EXTENSION of the preamble’s "Diagnose from evidence" — not duplicated there, so it stays a kernel extension.',
  },
  {
    anchor: '- **Never blame "high load" without the mechanism.** Even when load is extreme, "the load is',
    part: 'kernel',
    label: 'never blame high load without the mechanism',
    rationale: 'Near-verbatim in the preamble’s diagnose section — kept once there (D-018 §4).',
    dedupeWithPreamble: 'Diagnose from evidence, not a plausible story',
  },
  {
    anchor: '- **A red release/CI gate has exactly ONE fixer — READ OWNERSHIP BEFORE YOU ACT.**',
    part: 'domain',
    label: 'a red gate has one fixer · LIVE_GATE_OPS vs GATE_SYSTEM_DEV · three hops to green',
    rationale: 'Release-gate craft of the engineering profession; the single-fixer claim it rests on is kernel already (claims honoured).',
  },
  {
    anchor: "- **A mitigation is not a fix — don't stop at the band-aid.** Discovering a defect (not",
    part: 'kernel',
    label: 'a mitigation is not a fix',
    rationale: 'Near-verbatim in the preamble — kept once there (D-018 §4).',
    dedupeWithPreamble: 'Fixing what you find — a mitigation is not a fix',
  },
  {
    anchor: '- **Confirm before hard-to-reverse or outward-facing actions** unless durably authorized;',
    part: 'kernel',
    label: 'confirm before hard-to-reverse actions · report outcomes faithfully',
    rationale:
      'The preamble carries this paragraph (at the end of its "Tools and MCP startup" section) — kept once there (D-018 §4); the stance document’s confirm-before-execute posture is the Default-posture gate, not this line.',
    dedupeWithPreamble: 'Tools and MCP startup',
  },
  {
    anchor: '- **In alpha, timidity is the failure mode, not breakage** — but this bias governs HOW you',
    part: 'domain',
    label: 'alpha bias · flags default ON · reuse-first · app templates mandate',
    rationale: 'Engineering execution bias, feature-flag policy, reuse-first and the template mandate are how THIS profession builds (D-007 domain).',
  },
  {
    anchor: '## Anti-babysitting rule — monitoring is not work by default',
    part: 'practice',
    label: 'anti-babysitting: monitoring is not work by default',
    rationale: 'A stackable working practice (D-007: "practices stack because their slot is additive") — the wait-loop / monitor discipline family.',
  },
  {
    anchor: '### The papercusp-way routing gate (intent → mechanism)',
    part: 'domain',
    label: 'the papercusp-way routing gate (intent → mechanism table)',
    rationale: 'Reuse-first applied to platform mechanisms — the engineer’s "name the mechanism before hand-rolling" discipline; its rows are engineering asks.',
  },
  {
    anchor: '## Default posture (AUTO mode OFF) — plan, then confirm before you execute',
    part: 'collaboration-stance',
    label: 'a plan is a proposal, not authorization',
    rationale: 'D-017: the confirm-before-execute posture toward the owner is the stance slot.',
  },
  {
    anchor: '- **Confirm the execution route BEFORE executing — always offer these options',
    part: 'collaboration-stance',
    label: 'the WHO/route ask (A–D) · never offer an unconfirmed route · ask even if obvious · batch the asks · fleet-knob disclosure · confirm write-side calls · sticky route',
    rationale:
      'The authorization gate is stance (the owner chooses WHO runs the work). The fleet-launch mechanics inside options C/D ride along at this granularity; P-020 may lift them into the leader posture with a cross-reference.',
  },
  {
    anchor: "- **When the owner designates you a fleet's leader, CLAIM it as your FIRST act — don't just",
    part: 'fleet-posture',
    posture: 'leader',
    label: 'leader craft: claim leadership first · leading ⇒ AUTO + monitor (push first) · fleet:invariant · bench · re-read the ledger · kickoff = mission delta · declare the gate',
    rationale:
      'D-003: leader monitoring / benching / claim-spec / kickoff craft leaves the kernel. Should "leading ⇒ AUTO" become a registry implication it moves to the kernel’s modes table (D-008); the craft stays posture.',
  },
  {
    anchor: "- **Spawning a fleet/agent? ANNOUNCE the account + model + carry you're using and offer the",
    part: 'fleet-posture',
    posture: 'leader',
    label: 'spawn announcement: account routing · model · carry (prediction vs remediation rail)',
    rationale: 'Spawn-time disclosure is leader craft; the one hard rail inside it (fix a MEASURED outage) is stated as posture, not kernel, because only a spawner exercises it.',
  },
  {
    anchor: 'These asks are exactly what AUTO mode suspends — and the boundary is BINARY, not a',
    part: 'collaboration-stance',
    label: 'the AUTO boundary of the ask gate · client mirrors are projections of this section',
    rationale: 'Closes the stance section: what AUTO suspends is kernel STATE (D-008), but which asks it suspends is this stance’s own boundary.',
  },
  {
    anchor: '## Delivery discipline — a dialog ECLIPSES same-turn text; rendered ≠ delivered',
    part: 'collaboration-stance',
    label: 'delivery discipline: park content then ask · never announce a future question · rendered ≠ delivered · artifact URLs',
    rationale: 'D-017 names "delivery discipline" as stance content. The Claude-Artifact bullets are client colour a client overlay may absorb in P-003.',
  },
  {
    anchor: '## Owner directives — durable capture and resolution',
    part: 'collaboration-stance',
    label: 'owner-directive capture rail: every owner turn an OPEN verbatim row · done or declined(+reason) · forced summary over the cap',
    rationale:
      'The section’s own claim — "a capture rail, not a paraphrase rail: the database stores the owner’s literal words" — is fidelity to the owner, which is exactly what D-017 puts in the stance slot beside "address the owner by name" and the delivery discipline it follows in file order. It is deliberately NOT kernel: the ledger verbs are platform protocol, but the obligation this tile states is about the OWNER relationship (never paraphrase them, never silently drop what they said), and a pot with no interactive owner inherits the verbs without inheriting the stance.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:AUTO-MODE -->',
    part: 'kernel',
    seam: 'AUTO-MODE',
    label: 'modes KERNEL splice seam (state · registration · implication table · authority)',
    rationale:
      'P-021: the splice renders the KERNEL half of the modes from `modes/registry.ts` — state, how a flip is registered, the implication table, authority computed by instruction-lint (D-008). The mode DEFINITIONS are identities on the axis slots (`su.mode-*`, `mode-identities.ts`) rendered in the `modes` layer only while the mode is ON.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:COMPACTION -->',
    part: 'practice',
    seam: 'COMPACTION',
    label: 'agent-managed compaction practice splice seam',
    rationale: 'Compaction is a stackable context-management practice; the generated protocol is spliced after the stack is composed.',
  },
  {
    anchor: '## Registering work is a SEPARATE discipline from asking approval — AUTO waives the ask, NOT the register',
    part: 'kernel',
    label: 'registering work: trivial / substantive / big-scope tiers',
    rationale: 'Work-item registration discipline is D-007’s "completion evidence required" seen from the front — kernel.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:RESULT-DOOR -->',
    part: 'kernel',
    seam: 'RESULT-DOOR',
    label: 'result-door splice seam (tool results are capped)',
    rationale: 'Tool-result envelope semantics (`projection`) are platform protocol — kernel.',
  },
  {
    anchor: '## Tools, docs, memory',
    part: 'kernel',
    label: 'verbs are MCP tools, never curl · docs-first',
    rationale: 'Platform tool protocol; the preamble’s MCP-startup section already forbids hand-rolled HTTP — kept once there (D-018 §4).',
    dedupeWithPreamble: 'Tools and MCP startup',
  },
  {
    anchor: '- **Editing an agent prompt/persona? Read the runbook BEFORE you grep.** The su prompt is',
    part: 'instance',
    label: 'editing a persona: read the su render/edit-path runbook',
    rationale:
      'A papercusp-REPO runbook (this prompt tree’s layering); the project guide is the instance layer and already carries "Prompts are auto-generated — edit the source".',
  },
  {
    anchor: '- **Memory has layers — route by DELIVERY, not habit.** A durable but *fuzzy* fact worth',
    part: 'kernel',
    label: 'memory layers (memory:remember · facts:assert · checkpoints · coord) · push, don’t poll',
    rationale: 'Ring-0 memory routing; the preamble’s Memory section carries the shared-store rule — kept once there (D-018 §4).',
    dedupeWithPreamble: 'Memory',
  },
  {
    anchor: '## Coordination: subscribe → ask → file',
    part: 'kernel',
    label: 'coord protocol: decisions · coord verbs · @-selectors · read surfaces · state vs history · file what you discover',
    rationale: 'Coordination protocol (D-003 invariants + the D-007 completion/decision substrate) — kernel.',
  },
  {
    anchor: '## Coordination glyph legend',
    part: 'kernel',
    label: 'glyph legend heading',
    rationale: 'The coord injection protocol is kernel.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:COORD-LEGEND -->',
    part: 'kernel',
    seam: 'COORD-LEGEND',
    label: 'coord-legend splice seam',
    rationale: 'Generated glyph key — kernel protocol.',
  },
  {
    anchor: '## Wire schemas',
    part: 'kernel',
    label: 'wire schemas heading',
    rationale: 'Prompt-declared column schemas are tool protocol — kernel.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:WIRE-SCHEMAS -->',
    part: 'kernel',
    seam: 'WIRE-SCHEMAS',
    label: 'wire-schemas splice seam',
    rationale: 'Generated wire schemas — kernel protocol.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:SHARED-BASE-NOTES -->',
    part: 'kernel',
    seam: 'SHARED-BASE-NOTES',
    label: 'shared base notes splice seam',
    rationale: 'The explicit anchor for the shared deploy/wait/wake/coupling/state protocol bundle; it replaces the silent append fallback.',
  },
  {
    anchor: '<!-- PAPERCUSP-SU:PROJECT-GUIDE -->',
    part: 'instance',
    seam: 'PROJECT-GUIDE',
    label: 'addressed project-guide splice seam',
    rationale: 'The project guide is the pot-specific instance layer selected for the wearer’s stack, not an identity document.',
  },
];

/** A tile located in a concrete su.md text (1-indexed inclusive lines, text incl. trailing newline). */
export interface LocatedSuTile extends SuTile {
  index: number;
  startLine: number;
  endLine: number;
  text: string;
}

const SPLICE_MARKER_RE = /^<!-- PAPERCUSP-SU:[A-Z-]+ -->$/;
const HEADING_RE = /^##+ /;

/** Split keeping the trailing-newline contract explicit (su.md must end with `\n`). */
function suLines(text: string): string[] {
  if (!text.endsWith('\n')) throw new Error(`su.md must end with a newline (lossless tiling relies on it)`);
  const lines = text.split('\n');
  lines.pop();
  return lines;
}

/**
 * Structural problems with the tiling against THIS su.md text — empty means the
 * tiling is sound. Each message names the repair. Checked before any extraction.
 */
export function suTilingProblems(suText: string, tiles: readonly SuTile[] = SU_TILES): string[] {
  const problems: string[] = [];
  if (!suText.endsWith('\n')) return ['su.md must end with a newline'];
  const lines = suLines(suText);
  const positions: number[] = [];
  for (const t of tiles) {
    const hits: number[] = [];
    lines.forEach((l, i) => {
      if (l === t.anchor) hits.push(i + 1);
    });
    if (hits.length === 0) problems.push(`anchor not found — re-read that section of su.md and re-tile: ${JSON.stringify(t.anchor)}`);
    else if (hits.length > 1) problems.push(`anchor occurs ${hits.length}× (lines ${hits.join(', ')}) — an anchor must be unique: ${JSON.stringify(t.anchor)}`);
    else positions.push(hits[0]!);
  }
  if (problems.length) return problems;
  if (positions[0] !== 1) problems.push(`the first tile must start on line 1 (starts on ${positions[0]})`);
  for (let i = 1; i < positions.length; i++) {
    if (positions[i]! <= positions[i - 1]!) problems.push(`tiles out of order: ${JSON.stringify(tiles[i]!.anchor)} (line ${positions[i]}) is not after ${JSON.stringify(tiles[i - 1]!.anchor)} (line ${positions[i - 1]})`);
  }
  const anchorSet = new Set(tiles.map((t) => t.anchor));
  lines.forEach((l, i) => {
    if (HEADING_RE.test(l) && !anchorSet.has(l)) problems.push(`heading on line ${i + 1} is not a tile anchor — classify it in SU_TILES: ${JSON.stringify(l)}`);
    if (SPLICE_MARKER_RE.test(l) && !anchorSet.has(l)) problems.push(`splice marker on line ${i + 1} is not a tile anchor — classify it in SU_TILES: ${JSON.stringify(l)}`);
  });
  for (const t of tiles) {
    if (t.seam && !SPLICE_MARKER_RE.test(t.anchor)) problems.push(`tile declares seam ${t.seam} but its anchor is not a splice marker: ${JSON.stringify(t.anchor)}`);
    if (t.seam && t.anchor !== `<!-- PAPERCUSP-SU:${t.seam} -->`) problems.push(`seam name ${t.seam} does not match its marker ${JSON.stringify(t.anchor)}`);
    if (t.part === 'fleet-posture' && !t.posture) problems.push(`fleet-posture tile must name its posture: ${JSON.stringify(t.anchor)}`);
    if (t.part !== 'fleet-posture' && t.posture) problems.push(`only fleet-posture tiles carry a posture: ${JSON.stringify(t.anchor)}`);
    if (!isSuPart(t.part)) problems.push(`unknown part ${JSON.stringify(t.part)} on ${JSON.stringify(t.anchor)}`);
  }
  return problems;
}

/** Resolve every tile to its line range + text in THIS su.md; throws on a tiling problem. */
export function locateSuTiles(suText: string, tiles: readonly SuTile[] = SU_TILES): LocatedSuTile[] {
  const problems = suTilingProblems(suText, tiles);
  if (problems.length) throw new Error(`su.md tiling is unsound:\n  - ${problems.join('\n  - ')}`);
  const lines = suLines(suText);
  const starts = tiles.map((t) => lines.indexOf(t.anchor) + 1);
  return tiles.map((t, i) => {
    const startLine = starts[i]!;
    const endLine = i + 1 < starts.length ? starts[i + 1]! - 1 : lines.length;
    return { ...t, index: i, startLine, endLine, text: lines.slice(startLine - 1, endLine).join('\n') + '\n' };
  });
}

// ── The part documents ────────────────────────────────────────────────────────

export type SuPartDocId = 'su.kernel' | 'papercusp-engineer' | 'su-collaborator' | 'su.fleet-member' | 'su.fleet-leader' | 'su.practice' | 'su.instance';

export interface SuPartDocument {
  id: SuPartDocId;
  part: SuPart;
  posture?: FleetPostureRole;
  /** Harness-relative path the verbatim extraction is written to. */
  path: string;
  /** What the document is in the composition model, and who promotes it. */
  role: string;
}

/**
 * One document per prose-bearing part (the `client` part is seam-only — its
 * documents already exist under `apps/operator/prompts/`). Paths: the four
 * IDENTITY documents live in their own blueprint dir (`prompts/agent-base-overlay.md`
 * is the `domain` leaf name D-018 fixed; `prompts/<slot>.md` for every other slot —
 * the su-collaborator stance and, since P-020, the two fleet postures); the kernel,
 * practice and instance texts sit beside the source as `su.<part>.md`.
 * `suPartDocumentHome` tells the two apart — an identity-homed document is what the
 * su stack composer resolves THROUGH THE PROMPT CHAIN (P-020), the base-homed ones
 * render from their tiles.
 */
export const SU_PART_DOCUMENTS: readonly SuPartDocument[] = [
  {
    id: 'su.kernel',
    part: 'kernel',
    path: 'blueprints/base/prompts/su.kernel.md',
    role: 'the interactive tier’s KERNEL EXTENSION — composed after agent-base-preamble.md (the kernel base text) by P-003’s seal; its dedupe tiles are dropped there',
  },
  {
    id: 'papercusp-engineer',
    part: 'domain',
    path: 'blueprints/papercusp-engineer/prompts/agent-base-overlay.md',
    role: 'identity #1 — the `domain` leaf of blueprints/papercusp-engineer (D-018 §5: the coding hive’s missing domain document; attached by P-023, not here)',
  },
  {
    id: 'su-collaborator',
    part: 'collaboration-stance',
    path: 'blueprints/su-collaborator/prompts/collaboration-stance.md',
    role: 'identity #2 — the `collaboration-stance` document of blueprints/su-collaborator (exclusive per D-017)',
  },
  {
    id: 'su.fleet-member',
    part: 'fleet-posture',
    posture: 'member',
    path: 'blueprints/su.fleet-member/prompts/fleet-posture.md',
    role: 'identity #3 — the `fleet-posture` document of blueprints/su.fleet-member (P-020; exclusive per D-003/D-007): attached at fleet:launch-on-plan / fleet:join, resolved through the prompt chain',
  },
  {
    id: 'su.fleet-leader',
    part: 'fleet-posture',
    posture: 'leader',
    path: 'blueprints/su.fleet-leader/prompts/fleet-posture.md',
    role: 'identity #4 — the `fleet-posture` document of blueprints/su.fleet-leader (P-020; exclusive per D-003/D-007): attached at fleet:take-leadership (a swap that voids su.fleet-member), resolved through the prompt chain',
  },
  {
    id: 'su.practice',
    part: 'practice',
    path: 'blueprints/base/prompts/su.practice.md',
    role: 'the one additive `practice` document su.md carries today (anti-babysitting); more practices stack beside it',
  },
  {
    id: 'su.instance',
    part: 'instance',
    path: 'blueprints/base/prompts/su.instance.md',
    role: 'INSTANCE-layer candidate — belongs in the papercusp project guide / pot override, not in any identity; P-003 moves it',
  },
];

/**
 * Where a part document LIVES — derived from its path, never restated (derived-truth
 * ladder rung 1). `identity` = under `blueprints/<identity-id>/prompts/`, the document
 * of an identity blueprint whose `slots:` names the part (P-020 resolves these through
 * the prompt chain); `base` = beside su.md under `blueprints/base/prompts/`.
 */
export function suPartDocumentHome(doc: Pick<SuPartDocument, 'path'>): 'identity' | 'base' {
  return doc.path.startsWith(`${BASE_ROLE_LIBRARY_REL}/`) ? 'base' : 'identity';
}

/** The identity blueprint id an identity-homed part document belongs to (`blueprints/<id>/…`). */
export function suPartDocumentBlueprintId(doc: Pick<SuPartDocument, 'path'>): string | null {
  const m = /^blueprints\/([^/]+)\/prompts\//.exec(doc.path);
  return suPartDocumentHome(doc) === 'identity' && m ? m[1]! : null;
}

export function suPartDocument(id: SuPartDocId): SuPartDocument {
  const d = SU_PART_DOCUMENTS.find((x) => x.id === id);
  if (!d) throw new Error(`unknown su part document ${id}`);
  return d;
}

/** The tiles a part document is the concatenation of, in su.md order. */
export function tilesOfDocument(located: readonly LocatedSuTile[], doc: SuPartDocument): LocatedSuTile[] {
  return located.filter((t) => t.part === doc.part && (doc.part !== 'fleet-posture' || t.posture === doc.posture));
}

/** The VERBATIM extraction — byte-equal to the concatenation of the document's tiles. */
export function extractSuPart(suText: string, id: SuPartDocId, tiles?: readonly SuTile[]): string {
  const doc = suPartDocument(id);
  return tilesOfDocument(locateSuTiles(suText, tiles), doc)
    .map((t) => t.text)
    .join('');
}

export function suSourcePath(harnessDir?: string): string {
  return harnessDir ? join(harnessDir, SU_SOURCE_REL) : harnessPath(...SU_SOURCE_REL.split('/'));
}

export function readSuSource(harnessDir?: string): string {
  return readFileSync(suSourcePath(harnessDir), 'utf8');
}

export function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

export interface SuPartDrift {
  id: SuPartDocId;
  path: string;
  status: 'ok' | 'missing' | 'stale';
}

/** Compare every committed part document with its derivation from the live su.md. */
export function suPartDocumentDrift(harnessDir?: string): SuPartDrift[] {
  const su = readSuSource(harnessDir);
  return SU_PART_DOCUMENTS.map((d) => {
    const abs = harnessDir ? join(harnessDir, d.path) : harnessPath(...d.path.split('/'));
    if (!existsSync(abs)) return { id: d.id, path: d.path, status: 'missing' as const };
    const want = extractSuPart(su, d.id);
    return { id: d.id, path: d.path, status: readFileSync(abs, 'utf8') === want ? ('ok' as const) : ('stale' as const) };
  });
}

/** (Re)write every part document from the live su.md; returns the paths written. */
export function writeSuPartDocuments(harnessDir?: string): string[] {
  const su = readSuSource(harnessDir);
  const out: string[] = [];
  for (const d of SU_PART_DOCUMENTS) {
    const abs = harnessDir ? join(harnessDir, d.path) : harnessPath(...d.path.split('/'));
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, extractSuPart(su, d.id), 'utf8');
    out.push(abs);
  }
  return out;
}

// ── The base role library: what becomes an identity, and when ─────────────────

export type RoleLibraryDisposition =
  /** decomposed by THIS item (only `su` in v1) */
  | 'decomposed-v1'
  /** the kernel’s base text (D-018) — a prompt, not a role */
  | 'kernel-base'
  /** a role whose text is an identity CANDIDATE for a later milestone (target names the slot / item) */
  | 'later'
  /** stays a role: a position in a spine (choreography), not what an agent IS */
  | 'role'
  /** a non-prompt sidecar (`*.role.json`) */
  | 'sidecar';

export interface RoleLibraryRow {
  file: string;
  disposition: RoleLibraryDisposition;
  note: string;
  /** For `later`: the slot the text would fill, and the item that decides. */
  target?: { slot: SlotId; item: string };
}

const role = (file: string, note: string): RoleLibraryRow => ({ file, disposition: 'role', note });

/**
 * Every file in `blueprints/base/prompts/` (blueprint-role-bundling-2026-06-15
 * shipped the library) with its v1 disposition. The principle (D-007): an
 * identity is what an agent IS across pots; a role is WHERE it sits in a
 * blueprint’s spine — choreography stays choreography. Only `su` decomposes in
 * v1; the test asserts this table and the directory agree both ways.
 */
export const BASE_ROLE_LIBRARY_DISPOSITION: readonly RoleLibraryRow[] = [
  { file: 'su.md', disposition: 'decomposed-v1', note: 'tiled by SU_TILES into kernel / client / domain / fleet-posture / collaboration-stance / practice / instance (this item)' },
  { file: 'agent-base-preamble.md', disposition: 'kernel-base', note: 'the kernel’s BASE text rendered on every tier (D-018) — not a role' },
  {
    file: 'papercup.md',
    disposition: 'later',
    note: 'the owner-facing chat collaborator — a second stance document, exclusive with su-collaborator on one stack',
    target: { slot: 'collaboration-stance', item: 'P-021' },
  },
  {
    file: 'papercup-deep.md',
    disposition: 'later',
    note: 'the deep-work variant of the chat collaborator — same stance family as papercup.md',
    target: { slot: 'collaboration-stance', item: 'P-021' },
  },
  // Pipeline / spine roles — choreography positions.
  role('architect.md', 'coding spine position'),
  role('director.md', 'coding spine decider'),
  role('scoper.md', 'coding spine position'),
  role('worker.md', 'coding spine position (the implementer)'),
  role('worker.base.md', 'role-family base fragment shared by worker variants'),
  role('directed-implementer.md', 'implement blueprint position'),
  role('validator.md', 'coding spine position'),
  role('validator.base.md', 'role-family base fragment shared by validator variants'),
  role('reviewer.md', 'coding spine position'),
  role('tester.md', 'coding spine gate role'),
  role('test-writer.md', 'coding spine gate role'),
  role('documenter.md', 'coding spine position'),
  role('documenter.base.md', 'role-family base fragment shared by documenter variants'),
  role('curator.md', 'coding spine position'),
  role('committer.md', 'coding spine position'),
  role('debugger.md', 'coding spine specialist'),
  role('security-reviewer.md', 'coding spine opt-in gate'),
  role('infra-reviewer.md', 'coding spine opt-in gate'),
  role('crosscheck.md', 'coding spine opt-in gate'),
  role('ui-qa.md', 'coding spine opt-in gate'),
  role('dimension-reviewer.md', 'review blueprint position'),
  role('review-director.md', 'review blueprint decider'),
  role('auditor.md', 'audit blueprint position — the `audit` MODE-AXIS document (P-021) is authored fresh, not lifted from this role'),
  role('finding-verifier.md', 'audit / review position'),
  role('findings-synthesizer.md', 'audit / review position'),
  role('verifier.md', 'verification position'),
  role('judge.md', 'vote / deliberate position'),
  role('proposer.md', 'vote / deliberate position'),
  role('promote.md', 'graduation position'),
  role('transformer.md', 'migration blueprint position'),
  role('migration-director.md', 'migration blueprint decider'),
  role('migration-verifier.md', 'migration blueprint position'),
  role('merge-resolver.md', 'merge-resolution blueprint position'),
  role('content-fixer.md', 'content-fix blueprint position'),
  role('release-fixer.md', 'release-fix blueprint position'),
  role('release-manager.md', 'deploy blueprint position'),
  role('research-director.md', 'research blueprint decider'),
  role('researcher.md', 'research blueprint position'),
  role('searcher.md', 'research / scan position'),
  role('scanner.md', 'scan blueprint position'),
  role('discoverer.md', 'scan / research position'),
  role('summarizer.base.md', 'role-family base fragment shared by summarizer variants'),
  role('synthesizer.md', 'research position'),
  role('planner.md', 'planning position'),
  role('task-generator.md', 'gym blueprint position'),
  role('gym-director.md', 'gym blueprint decider'),
  role('variant-runner.md', 'gym / prompt-ablation position'),
  role('pair-director.md', 'pair blueprint decider'),
  role('doc-steward.md', 'doc-steward blueprint position'),
  role('monitor.md', 'monitor position — a role, not the anti-babysitting practice (which su.md carries)'),
  role('orchestrator.md', 'the harness orchestrator loop'),
  role('operator.md', 'bounded control-plane execution position for an owner-authorized operation'),
  role('orchestrator.base.md', 'role-family base fragment shared by orchestrator variants'),
  role('kettle.md', 'pot supervisor — supervision craft is P-020 reference material, not an identity'),
  role('mug.md', 'RETIRED nursery-tier supervisor (the gate flag was deleted) — kept as a role file only'),
  role('mug.base.md', 'RETIRED nursery-tier base fragment'),
  role('cup.base.md', 'RETIRED nursery-tier cup base fragment'),
  role('foreign-session.md', 'a session-shape persona for foreign (non-psu) sessions'),
  { file: 'infra-reviewer.role.json', disposition: 'sidecar', note: 'role metadata read by role-registry.ts' },
  { file: 'security-reviewer.role.json', disposition: 'sidecar', note: 'role metadata read by role-registry.ts' },
];

// ── The interactive su’s DEFAULT stack (what P-013’s fixtures need) ───────────

export interface SuStackEntry {
  layer: 'kernel' | 'client' | 'domain' | 'fleet-posture' | 'modes' | 'practices' | 'instance';
  slot?: SlotId;
  /** The document (identity id or path); null when the layer is empty by default. */
  ref: string | null;
  /** When the binding is decided: fixed in the stack, at launch, or by a runtime stack mutation. */
  binding: 'static' | 'launch' | 'runtime';
  note: string;
}

/**
 * The stack an interactive su session runs by default: engineer + collaborator
 * stance + the anti-babysitting practice, with NO fleet posture — a fleet launch
 * or `fleet:join` attaches the member posture and `fleet:take-leadership` the
 * leader one (D-003 stack mutation). Order = `LAYER_ORDER`.
 */
export const SU_DEFAULT_STACK: readonly SuStackEntry[] = [
  { layer: 'kernel', ref: SU_PREAMBLE_REL, binding: 'static', note: 'the kernel base text (D-018), rendered on every tier' },
  { layer: 'kernel', ref: 'blueprints/base/prompts/su.kernel.md', binding: 'static', note: 'the interactive tier’s kernel extension (this decomposition); the seal renders the kernel last' },
  { layer: 'client', slot: 'client', ref: 'apps/operator/prompts/papercusp-su.<client>.md', binding: 'launch', note: 'chosen by the launching client (claude / codex / omp) — exclusive' },
  { layer: 'domain', slot: 'domain', ref: 'papercusp-engineer', binding: 'static', note: 'the software-engineering profession — exclusive' },
  { layer: 'fleet-posture', slot: 'fleet-posture', ref: null, binding: 'runtime', note: 'NONE by default — fleet:launch-on-plan / fleet:join attach su.fleet-member, fleet:take-leadership attaches su.fleet-leader' },
  { layer: 'modes', ref: null, binding: 'runtime', note: 'NONE by default — mode:set binds one identity per active axis (su.mode-auto on autonomy, su.mode-ideate on ideation, su.mode-drain on objective, su.mode-audit on audit; P-021); the kernel seam at PAPERCUSP-SU:AUTO-MODE carries only state / implications / authority (D-008)' },
  { layer: 'practices', slot: 'collaboration-stance', ref: 'su-collaborator', binding: 'static', note: 'how the su works WITH the owner — exclusive (D-017)' },
  { layer: 'practices', slot: 'practice', ref: 'su.practice', binding: 'static', note: 'anti-babysitting — additive; further practices stack beside it' },
  { layer: 'instance', ref: 'pot_settings.promptOverride.su + the project guide', binding: 'launch', note: 'the per-pot override (audit S5) and the spliced project guide' },
];

// ── The pinned doc rendering (COMPOSITION_MODEL.md §9) ────────────────────────

function cell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
function shortAnchor(a: string): string {
  const s = a.length > 72 ? `${a.slice(0, 69)}…` : a;
  return `\`${s.replace(/`/g, '')}\``;
}

/**
 * §9 of `docs/COMPOSITION_MODEL.md`, embedded between `<!-- SU-DECOMPOSITION:BEGIN/END -->`
 * and asserted equal by `su-decomposition.test.ts` (derived-truth ladder rung 2:
 * PIN). Deliberately uses anchors, never line numbers, so the prose stays true
 * across edits inside a tile.
 */
export function renderSuDecompositionMarkdown(): string {
  const lines: string[] = [];
  lines.push(`Source: \`${SU_SOURCE_REL}\` — tiled by ANCHOR (the exact first line of each tile; every \`##\`/\`###\` heading and every \`<!-- PAPERCUSP-SU:… -->\` splice marker must be one). ${SU_TILES.length} tiles → ${SU_PART_DOCUMENTS.length} verbatim part documents + the \`client\` seam.`);
  lines.push('');
  lines.push('| # | part | tile | anchor | preamble dedupe (D-018 §4) | why |');
  lines.push('|---|---|---|---|---|---|');
  SU_TILES.forEach((t, i) => {
    const part = t.part === 'fleet-posture' ? `\`fleet-posture\` (${t.posture})` : `\`${t.part}\``;
    const label = t.seam ? `⟨seam \`${t.seam}\`⟩ ${t.label}` : t.label;
    lines.push(`| ${i + 1} | ${part} | ${cell(label)} | ${shortAnchor(t.anchor)} | ${t.dedupeWithPreamble ? `\`# ${cell(t.dedupeWithPreamble)}\`` : '—'} | ${cell(t.rationale)} |`);
  });
  lines.push('');
  lines.push('Part documents (each is BYTE-EQUAL to the concatenation of its tiles — `npm run gen:su-decomposition` rewrites them from su.md, `:check` and the test refuse drift):');
  lines.push('');
  lines.push('| document | part | path (under `libs/papercusp/packages/harness/`) | role in the model |');
  lines.push('|---|---|---|---|');
  for (const d of SU_PART_DOCUMENTS) {
    const part = d.part === 'fleet-posture' ? `\`fleet-posture\` (${d.posture})` : `\`${d.part}\``;
    lines.push(`| \`${d.id}\` | ${part} | \`${d.path}\` | ${cell(d.role)} |`);
  }
  lines.push('');
  lines.push('The interactive su’s DEFAULT stack (P-013 fixtures), in `LAYER_ORDER`:');
  lines.push('');
  lines.push('| layer | slot | document | bound | note |');
  lines.push('|---|---|---|---|---|');
  for (const e of SU_DEFAULT_STACK) {
    lines.push(`| \`${e.layer}\` | ${e.slot ? `\`${e.slot}\`` : '—'} | ${e.ref ? `\`${cell(e.ref)}\`` : '—'} | ${e.binding} | ${cell(e.note)} |`);
  }
  lines.push('');
  const counts = new Map<RoleLibraryDisposition, number>();
  for (const r of BASE_ROLE_LIBRARY_DISPOSITION) counts.set(r.disposition, (counts.get(r.disposition) ?? 0) + 1);
  lines.push(
    `Base role library (\`${BASE_ROLE_LIBRARY_REL}\`, ${BASE_ROLE_LIBRARY_DISPOSITION.length} files): ${[...counts.entries()].map(([k, v]) => `${v} \`${k}\``).join(' · ')}. An identity is what an agent IS across pots; a role is WHERE it sits in a spine — choreography stays a role. The non-role rows:`,
  );
  lines.push('');
  lines.push('| file | disposition | target | note |');
  lines.push('|---|---|---|---|');
  for (const r of BASE_ROLE_LIBRARY_DISPOSITION.filter((x) => x.disposition !== 'role' && x.disposition !== 'sidecar')) {
    lines.push(`| \`${r.file}\` | ${r.disposition} | ${r.target ? `\`${r.target.slot}\` (${r.target.item})` : '—'} | ${cell(r.note)} |`);
  }
  return lines.join('\n');
}
