/**
 * _work-items-schema.ts — the ONE canonical `harness_features_consolidated` DDL
 * for integration-test fixtures. NOT a test file (no `.integration.test.ts`
 * suffix), so the glob never collects it — it is imported by the engine's
 * real-Postgres integration tests.
 *
 * WHY THIS EXISTS (fixture-completeness debt, D-014 @ autoloop-pot-operator-rebuild):
 * ~36 integration tests used to hand-roll their own `CREATE TABLE
 * harness_features_consolidated (...)` DDL, each including only the column SUBSET
 * it happened to touch. The real prod table (000-baseline + incrementals) has the
 * full set. So any time the engine's shared `FEATURE_COLS` select/returning list in
 * work-items.ts widened by one column (e.g. surfacing `feature_order` as the
 * WorkItem `priority`), every test whose hand-rolled DDL omitted that column broke
 * with `column "X" does not exist` — turning a one-line engine change into a
 * 25-file fixture chase (memory: feature-cols-widen-breaks-fixtures).
 *
 * THE FIX: one complete, prod-faithful column superset, imported everywhere. It is
 * the full current `harness_features_consolidated` column set (live :5432 columns +
 * `swarm_affinity` from migration 191, which the dev box's native PG hadn't applied
 * yet) with test-friendly DEFAULTs that let the engine's column-omitting INSERTs
 * succeed without the prod BEFORE-INSERT fill triggers (which the bare test schema
 * lacks). Adding a column to `FEATURE_COLS` from now on means adding it HERE, once.
 *
 * Keep it a SUPERSET of prod: a test can never reference a column it doesn't have.
 * Check constraints are intentionally omitted — this fixes column completeness, not
 * constraint enforcement, and the prod triggers/constraints aren't what the engine
 * reads exercise. If you genuinely need a constraint or trigger, add it in the
 * specific test, not here.
 */

/**
 * Complete `harness_features_consolidated` DDL — apply with `sql.unsafe(...)` (it is
 * `CREATE TABLE IF NOT EXISTS`, so it composes into a multi-table bootstrap block).
 *
 * Test-friendly DEFAULTs that differ from prod and why:
 *   • workspace_id DEFAULT 'default' — prod fills it via the BEFORE-INSERT
 *     `fill_ws_features` trigger (absent in the bare test schema); the engine's
 *     createWorkItem INSERT omits the column on purpose.
 *   • status DEFAULT 'todo', attempts DEFAULT 0, item_kind DEFAULT 'feature' —
 *     convenience for hand-written test inserts that omit them.
 */
export const HARNESS_FEATURES_CONSOLIDATED_DDL = `
  CREATE EXTENSION IF NOT EXISTS vector;
  -- migration 632 (event-key-fire-latch): every real awaited-event emission
  -- upserts this per-key latch. The claim-path integration tests emit
  -- work-item:claimed events, so omitting the table turns an unrelated
  -- console.warn into a vitest-fail-on-console failure.
  CREATE TABLE IF NOT EXISTS harness_shared.event_key_fires (
    workspace_id     TEXT        NOT NULL DEFAULT 'default',
    event_key        TEXT        NOT NULL,
    first_fired_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_fired_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_fired_by    TEXT,
    last_payload     JSONB,
    fire_count       BIGINT      NOT NULL DEFAULT 1,
    PRIMARY KEY (workspace_id, event_key)
  );
  -- claimWorkItem reads the latest post id when it stamps a new holder. Keep
  -- the claim-path fixture aligned with the production coordination table so
  -- this provenance query does not fail before the claim predicates run.
  CREATE TABLE IF NOT EXISTS harness_shared.coord_thread_posts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  TEXT NOT NULL,
    thread_id     TEXT NOT NULL,
    author_id     TEXT,
    body          TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    harness_slug  TEXT,
    origin        TEXT NOT NULL DEFAULT 'local',
    author_pubkey TEXT,
    post_msg_id   TEXT
  );
  CREATE SEQUENCE IF NOT EXISTS harness_shared.work_item_seq;
  CREATE OR REPLACE FUNCTION harness_shared.next_work_item_id() RETURNS text LANGUAGE sql VOLATILE AS $wiid$ SELECT 'WI-' || nextval('harness_shared.work_item_seq')::text $wiid$;
  -- migration 1325 (P-009 / D-022): the one work predicate. Body copied from
  -- 1325-work-item-is-agent-work.sql; work-predicate-lint.test.ts pins the two equal.
  CREATE OR REPLACE FUNCTION harness_shared.work_item_is_agent_work(
    p_nature text, p_audience text, p_lane text, p_needs_owner_action boolean
  ) RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $wiaw$
    SELECT p_nature = 'work'
       AND p_audience = 'agent'
       AND p_lane IS DISTINCT FROM 'observation'
       AND p_needs_owner_action IS NOT TRUE
  $wiaw$;
  CREATE TABLE IF NOT EXISTS harness_shared.work_item_release_cooldowns (
    workspace_id text NOT NULL,
    harness_slug text NOT NULL,
    feature_id text NOT NULL,
    agent_id text NOT NULL,
    released_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, harness_slug, feature_id, agent_id)
  );
  CREATE TABLE IF NOT EXISTS harness_shared.work_items (
    harness_slug text NOT NULL,
    feature_id text NOT NULL,
    title text,
    summary text,
    status text DEFAULT 'todo',
    attempts bigint DEFAULT 0,
    claims text,
    notes text,
    metadata jsonb,
    kind text,
    project_id text,
    expected_cost_cents bigint,
    tags jsonb,
    needs_human_review boolean NOT NULL DEFAULT false,
    ts bigint,
    created_ts bigint,
    updated_ts bigint,
    parent_id text,
    goal_id text,
    taken_by text,
    taken_at timestamptz,
    last_progress_at timestamptz,
    expires_at timestamptz,
    workspace_id text NOT NULL DEFAULT 'default',
    deprecation_reason text,
    see_also text[] NOT NULL DEFAULT '{}'::text[],
    needs_design boolean NOT NULL DEFAULT false,
    design_status text,
    design_spec_id text,
    discarded_design_work boolean NOT NULL DEFAULT false,
    completion_ref jsonb,
    created_by_github_user_id bigint,
    working_users bigint[] NOT NULL DEFAULT '{}'::bigint[],
    worked_by_history jsonb NOT NULL DEFAULT '[]'::jsonb,
    wave text,
    verified_done_at_remote_ts timestamptz,
    verifier_last_error text,
    verifier_last_checked_at timestamptz,
    source_plan_slug text,
    source_plan_item_ids text[],
    feature_order integer,
    author_pubkey text,
    origin text NOT NULL DEFAULT 'local',
    audit_verdict text,
    audit_reasons text,
    audited_at timestamptz,
    verified_author_github_user_id bigint,
    item_kind text NOT NULL DEFAULT 'feature',
    payload jsonb,
    assignee_rank integer,
    rank_writer text,
    rank_updated_at timestamptz,
    swarm_affinity text,
    fed_ts bigint,
    fed_hlc text,
    redundancy integer,
    requeue_count integer NOT NULL DEFAULT 0,
    terminal_owner text,
    terminal_completion_ref text,
    -- work-item-status-full-unify (mig 638): preserves the passed/resolved (→done) and
    -- deprecated/closed (→dropped) nuance across the status-vocab collapse. Base-table
    -- column only (the compat views auto-reflect it); the P-003 writer stamps it on a
    -- legacy-spelled terminal and the reopen-clear nulls it — a fixture missing it made
    -- that whole UPDATE throw (silently swallowed), leaving terminal_owner uncleared.
    terminal_reason text,
    -- agent-protocol-authority-semantics-2026-07-26 P-003 (migration 677): the AUTHORITY
    -- axis — how trustworthy a terminal claim is, orthogonal to lifecycle status.
    -- (No backticks anywhere in this file: the whole DDL is one TS template literal,
    -- so a backtick in a SQL comment silently ends the string and breaks the parse.)
    -- proposed|validated|committed|pending_human|invalid; NULL on a terminal row means a
    -- legacy pre-authority close (D-005/D-008). Live carries a CHECK constraint on the
    -- value set; it is omitted here for the same reason the other CHECKs are — fixtures
    -- insert deliberately-odd rows, and the enum is asserted against the migration by
    -- work-item-completion-authority.test.ts rather than by this fixture.
    -- NOT the plan-item authority axis (system|owner = who may act) — see D-009. The
    -- column keeps this short name because the consolidated views make it rename-proof;
    -- the API surface disambiguates it as completionAuthority.
    authority text,
    -- migration 698 (work-items-closed-ts): the terminal timestamp. FEATURE_COLS selects
    -- it on EVERY feature read and claim, so a fixture without it fails the claim UPDATE
    -- outright with 'column "closed_ts" does not exist' — which is what
    -- claim-respects-blocking.integration.test.ts was doing (8/8 red) before this line.
    -- Same trap the terminal_reason comment above records: when a migration adds a column
    -- to FEATURE_COLS, this fixture must gain it too or every claim-path suite goes red
    -- for a reason that has nothing to do with what it is testing.
    closed_ts bigint,
    last_released_by text,
    last_released_at timestamptz,
    -- migration 944 (plan work-queue-admission-and-bulk-dedup-2026-08-24, P-002): the
    -- admission-gate axis, orthogonal to status. NULL = pre-gate legacy row, which
    -- isAdmitted() reads as ADMITTED — so a fixture row that omits it behaves exactly as
    -- it did before the gate, which is what keeps every existing suite green.
    -- These three MUST be here as well as on the two compat views: 946 appends them to
    -- engineer_issues (view + INSTEAD OF trigger) and a view cannot select a base column
    -- that does not exist, so without this line every integration test that files an
    -- issue dies on 'column "admission" does not exist'. The live CHECK constraint
    -- (admission IN ('pending','admitted','auto','unreviewed')) is deliberately omitted
    -- here for the same reason the other CHECKs are — fixtures insert deliberately-odd
    -- rows, and the enum is asserted against the migration by its own unit test.
    admission text,
    admitted_at timestamptz,
    admitted_by text,
    -- migration 896 (EI-21200252620921832): the state-age clock. This fixture was left
    -- one behind by 896 — a latent strand, harmless only while nothing NAMED the column,
    -- and mig 896 patches the production view by pg_get_viewdef anchor-replace so there
    -- is no "CREATE VIEW ... state_changed_at" text in that migration to grep for (the
    -- same invisibility the 946 note above records). EI-21467654382027859 federates the
    -- column, so the engineer-issues projection INSERT now names it and every suite that
    -- applies a federated issue op would die on 'column "state_changed_at" does not
    -- exist'. The live stamp TRIGGER is deliberately NOT recreated here: fixtures insert
    -- explicit values, and the trigger's COALESCE/freeze semantics are asserted against
    -- the migration by its own tests.
    state_changed_at timestamptz,
    -- migration 721 (WI-6934): payload->>'lane' materialised as a STORED generated column
    -- so the observation-lane floor filters without detoasting payload. work-items.ts's
    -- observationLaneExclusionSql now emits "wi.lane IS DISTINCT FROM 'observation'", and
    -- that floor is ANDed into EVERY claim path — so a fixture without this column fails
    -- the claim UPDATE outright with 'column "wi.lane" does not exist', exactly as the
    -- closed_ts and terminal_reason comments above record for their own migrations.
    -- (Observed: claim-respects-blocking.integration.test.ts went 4/17 red on this.)
    -- GENERATED ALWAYS — never write it directly; write payload.lane.
    lane text GENERATED ALWAYS AS (payload ->> 'lane') STORED,
    -- migration 1110 (WI-7102): the two top-level issue-admission flags are materialized
    -- for the same reason as lane. issueAdmissibleWhereSql reads these columns through both
    -- the base/view aliases, so the shared fixture must keep the production generated shape.
    -- Text comparison intentionally admits only the exact value 'true', matching the old
    -- JSONB ->> predicates for both boolean true and a legacy string "true".
    claim_hold boolean GENERATED ALWAYS AS ((payload ->> '_claimHold') = 'true') STORED,
    needs_owner_action boolean GENERATED ALWAYS AS ((payload ->> 'needsOwnerAction') = 'true') STORED,
    -- migration 1308 (P-013, WI-10004929): issue severity materialized so the Work Items
    -- list/summary (sync-resolver/work-items-list-query.ts) reads wi.severity_projection
    -- for every in-scope row without detoasting payload. Same expression as production.
    severity_projection text GENERATED ALWAYS AS (
      CASE WHEN item_kind = ANY (ARRAY['bug'::text, 'change'::text, 'task'::text])
           THEN COALESCE(payload -> '_ei' ->> 'severity', 'minor')
           ELSE NULL
      END
    ) STORED,
    -- condition-singleton identity (migration 741 family): the stop-the-line floor
    -- (P-013/D-012, work-items-admission.ts stopTheLineExclusionSql) reads
    -- wi.condition_key on EVERY claim path — a fixture without this column fails the
    -- claim/preview queries outright with 'column "condition_key" does not exist',
    -- same class as the lane note above.
    condition_key text,
    -- migrations 551/1154: shared prose vector plus its human-readable mode
    -- and exact immutable space identity. Semantic work-item tests use the
    -- same physical columns as production instead of silently skipping the
    -- vector source when provenance is present.
    embedding vector(768),
    embedding_mode text,
    embedding_profile text,
    -- migration 1322 (P-010 / D-018): nature + audience. Production stamps them with a
    -- trigger from datatype_registry; this fixture has no registry, so rows default to
    -- agent work, which is what every built-in kind resolves to.
    nature text NOT NULL DEFAULT 'work',
    audience text DEFAULT 'agent',
    _search tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(notes, '')), 'C')
    ) STORED,
    PRIMARY KEY (harness_slug, feature_id)
  );
  DROP VIEW IF EXISTS harness_shared.harness_features_consolidated;
  CREATE VIEW harness_shared.harness_features_consolidated AS
    SELECT * FROM harness_shared.work_items WHERE item_kind NOT IN ('bug', 'change', 'task');
  DO $eidrop$ BEGIN
    -- Drop engineer_issues whether it is a leftover TABLE (mig 131) or a prior VIEW
    -- (idempotent re-application): DROP TABLE IF EXISTS errors on a view and vice-versa,
    -- so branch on relkind.
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
               WHERE n.nspname = 'harness_shared' AND c.relname = 'engineer_issues') THEN
      EXECUTE (SELECT CASE WHEN c.relkind = 'v' THEN 'DROP VIEW' ELSE 'DROP TABLE' END
               || ' harness_shared.engineer_issues CASCADE'
               FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
               WHERE n.nspname = 'harness_shared' AND c.relname = 'engineer_issues');
    END IF;
  END $eidrop$;
  CREATE VIEW harness_shared.engineer_issues AS
    SELECT
      workspace_id,
      feature_id AS issue_id,
      CASE WHEN harness_slug LIKE 'operator:%' OR harness_slug = '' THEN 'operator' ELSE 'harness:' || harness_slug END AS scope,
      title,
      COALESCE(summary, '') AS body,
      COALESCE(payload->'_ei'->>'severity', 'minor') AS severity,
      COALESCE(payload->'_ei'->>'source', 'engineer') AS source,
      status AS state,
      taken_by AS assignee,
      payload->'_ei'->>'found_during' AS found_during,
      payload->'_ei'->>'linked_feature_id' AS linked_feature_id,
      payload->'_ei'->>'created_by' AS created_by,
      to_timestamp(created_ts / 1000.0) AS created_at,
      to_timestamp(updated_ts / 1000.0) AS updated_at,
      author_pubkey, origin, _search,
      item_kind AS kind,
      -- migration 1096 (P-003 / WI-6688): the view must NOT subtract '_ei'.
      -- Subtracting it made payload->'_ei'->>'severity' resolve to NULL for
      -- every row while the severity COLUMN held the real value, so a
      -- critical-severity audit written against the base table's accessor
      -- returned a confident 0. Keep this fixture in lockstep with production.
      payload AS payload,
      payload->'_ei'->>'assigned_by' AS assigned_by,
      taken_at AS assigned_at,
      assignee_rank, rank_writer, rank_updated_at, fed_ts,
      COALESCE(payload->'_ei'->>'signal_origin', 'organic') AS signal_origin,
      fed_hlc,
      terminal_owner,
      terminal_completion_ref,
      -- WI-2990/WI-3006 (migration 509): the real item-scoped progress signal,
      -- mirroring the feature-family's last_progress_at.
      last_progress_at,
      harness_slug AS base_harness_slug,
      origin AS base_origin,
      -- EI-10421 (migration 588): expose feature_order so issue-family items'
      -- Queen-steered priority round-trips through work_items:get/list instead of
      -- being silently hardcoded null on read even after a successful write.
      feature_order,
      -- migration 646 (reexpose-terminal-reason-engineer-issues-view) / 688. Live
      -- orders this column BEFORE authority, and ordinal position is load-bearing
      -- (NOTE: no backticks anywhere in this comment on purpose — it lives inside a
      -- TS template literal, where a backtick closes the template and breaks parsing;
      -- see lint:no-sql-comment-backtick)
      -- here, not cosmetic: migration 721 re-declares this view with a literal
      -- CREATE OR REPLACE, and CREATE OR REPLACE VIEW may only APPEND columns — it
      -- cannot reorder or rename existing ones. With terminal_reason missing, 721
      -- fails against this fixture with the genuinely baffling
      -- 'cannot change name of view column "authority" to "terminal_reason"',
      -- which names neither the fixture nor the missing column as the cause.
      -- Found while adding the migration-726 guard (WI-7057); the same omission is
      -- why work-items-closed-ts.integration.test.ts could not apply 721 either.
      terminal_reason,
      -- agent-protocol-authority-semantics-2026-07-26 P-003 (migration 677). The
      -- feature-family view above is SELECT * and picks the column up for free; this
      -- one is an explicit list, so it has to be named here or every integration test
      -- reading authority through the issue family would see "column does not exist"
      -- while live works fine.
      authority,
      -- migration 698 (work-items-closed-ts): production dynamically ALTERs BOTH family
      -- views (engineer_issues + harness_features_consolidated) to expose this column via
      -- a pg_get_viewdef regex-replace, so no literal "CREATE VIEW ... closed_ts" line
      -- exists in 698's migration file to grep for — easy to miss when hand-maintaining
      -- this fixture. ISSUE_COLS (work-items.ts) selects it on every issue-family read, so
      -- omitting it here fails EVERY test that reads an issue through this view with
      -- 'column "closed_ts" does not exist' — the same class of fixture drift the
      -- feature-family closed_ts column comment above already documents, just missed on
      -- the issue-family view when 698 landed. Found via EI-19313515375179600 (WI-6822
      -- follow-up): every test in work-items-claim-issue-scope-reread.integration.test.ts
      -- was red for this reason, including ones unrelated to that item's own fix.
      closed_ts,
      -- migration 721 (WI-6934) appends "lane" here too (CREATE OR REPLACE VIEW only
      -- permits adding columns at the END, which is why 721 appends rather than inserts).
      -- Issue-family reads that go through this view need it for the same reason the base
      -- table does — see the lane column comment above.
      lane,
      -- WI-37711 / migration 790 appends "goal_id" after it, so it goes last here too.
      -- ⚠ THIS IS THE THIRD COPY (EI-10489): an engineer_issues column addition must land in
      -- the prod migration, the app-side ISSUE_COLS allowlist, AND this fixture — three
      -- independently-maintained lists with no compile-time or lint check tying them
      -- together. Migration 790 and ISSUE_COLS landed without this one, so EVERY integration
      -- test reaching listIssues died on a bare 'column "goal_id" does not exist' — an error
      -- that names the COLUMN and never the stale fixture, and test:affected cannot select
      -- this file because the migration diff never touches it. Found 2026-08-10 (WI-37774)
      -- when 11/11 of a BRAND-NEW test file failed for a reason unrelated to what it tested.
      goal_id,
      -- EI-20018021869343311 / migration 803: issue-family duplicate/child edge.
      parent_id,
      -- EI-20288042426947475 / migration 815: claim-spec columns. Keep this
      -- fixture projection in lockstep with the production view and ISSUE_COLS.
      tags,
      source_plan_slug,
      source_plan_item_ids,
      redundancy,
      expected_cost_cents,
      -- migrations 944 + 946 (plan work-queue-admission-and-bulk-dedup-2026-08-24, P-002):
      -- 944 put these three on the base table; 946 appends them to the production view AND
      -- to the INSTEAD OF trigger's INSERT. Both halves have to be mirrored here — see the
      -- THIRD COPY warning above — because createIssue now NAMES admission in its INSERT
      -- column list, so a fixture view lacking them fails every integration test that files
      -- an issue with 'column "admission" does not exist'. Note 946 patches the live view via
      -- pg_get_viewdef replace rather than a literal CREATE VIEW line, so (like migration 698)
      -- there is no "CREATE VIEW ... admission" text in the migration file to grep for.
      admission,
      admitted_at,
      admitted_by,
      -- migration 896: appended LAST here for the same CREATE OR REPLACE VIEW reason the
      -- lane/goal_id comments above record — 896 adds it to the production view by
      -- anchor-replacing the pg_get_viewdef tail, which appends. EI-21467654382027859
      -- federates it, so this projection needs the column visible on the view too.
      state_changed_at,
      -- EI-19320339017813143 / migration 1041: the release stamps the 'worked-then-abandoned'
      -- open-row audit bucket reads. Appended LAST for the same CREATE OR REPLACE VIEW reason
      -- every comment above records — 1041 anchor-replaces the pg_get_viewdef tail, which
      -- appends. READ SIDE ONLY: unlike 946, 1041 deliberately does NOT extend the INSTEAD OF
      -- trigger, because release stamps are lifecycle state the release path writes to
      -- harness_shared.work_items directly — so there is no DML half to mirror here.
      -- 94% of that bucket's population is issue-family, so a fixture missing these columns
      -- makes the audit look EMPTY rather than fail (see the THIRD COPY warning above).
      last_released_at,
      last_released_by,
      -- migration 1110 (WI-7102): generated admission booleans appended to the production
      -- view and read directly by issueAdmissibleWhereSql. Keep them last to mirror the
      -- append-only CREATE OR REPLACE VIEW migration contract.
      claim_hold,
      needs_owner_action,
      -- migration 1323 (P-010): nature and audience, appended last like 1110.
      nature,
      audience
    FROM harness_shared.work_items WHERE item_kind IN ('bug', 'change', 'task');
  CREATE OR REPLACE FUNCTION harness_shared.engineer_issues_view_dml() RETURNS trigger LANGUAGE plpgsql AS $ei_dml$
  DECLARE v_slug text; v_ei jsonb; v_payload jsonb; v_updated int;
  BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') AND EXISTS (
      SELECT 1
        FROM harness_shared.work_items cur
       WHERE cur.workspace_id = OLD.workspace_id
         AND cur.harness_slug = OLD.base_harness_slug
         AND cur.feature_id = OLD.issue_id
         AND cur.item_kind = OLD.kind
         AND cur.origin = 'remote'
    ) THEN
      RETURN NULL;
    END IF;
    IF TG_OP = 'DELETE' THEN
      DELETE FROM harness_shared.work_items WHERE workspace_id = OLD.workspace_id AND harness_slug = OLD.base_harness_slug AND feature_id = OLD.issue_id AND item_kind = OLD.kind;
      RETURN OLD;
    END IF;
    -- WI-5493: normalize NEW.payload to a real jsonb OBJECT before it is ever
    -- merged with the || operator below — a non-object payload (e.g. the
    -- postgres-js double-encoded string-scalar binding quirk) otherwise
    -- silently array-corrupts the merge, destroying every named key.
    v_payload := COALESCE(NEW.payload, '{}'::jsonb);
    IF jsonb_typeof(v_payload) IS DISTINCT FROM 'object' THEN
      BEGIN
        IF jsonb_typeof(v_payload) = 'string' THEN
          v_payload := (v_payload #>> '{}')::jsonb;
        END IF;
      EXCEPTION WHEN OTHERS THEN
        v_payload := '{}'::jsonb;
      END;
      IF jsonb_typeof(v_payload) IS DISTINCT FROM 'object' THEN
        v_payload := '{}'::jsonb;
      END IF;
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.scope IS NOT DISTINCT FROM OLD.scope THEN
      v_slug := OLD.base_harness_slug;
    ELSE
      v_slug := CASE WHEN COALESCE(NEW.scope,'operator') LIKE 'harness:%' THEN substr(NEW.scope,9) ELSE 'operator:' || COALESCE(NULLIF(NEW.workspace_id,''),'default') END;
    END IF;
    v_ei := jsonb_strip_nulls(jsonb_build_object('scope',NEW.scope,'severity',NEW.severity,'source',NEW.source,'found_during',NEW.found_during,'linked_feature_id',NEW.linked_feature_id,'created_by',NEW.created_by,'assigned_by',NEW.assigned_by,'signal_origin',NEW.signal_origin));
    -- EI-20092514168581881: refuse ungated terminal transitions. Lifecycle transitions belong to setIssueState /
    -- work_items:set_state, which applies the completion-integrity gate. Keep this
    -- hand-rolled fixture aligned with migration 797's live compatibility trigger,
    -- and with migration 799's self-diagnosing refusal (EI-20202062074776959): an
    -- application_name matching 'pcusp:%' reaching this branch is necessarily a STALE
    -- operator, because a current one writes harness_shared.work_items directly and
    -- never gets here — so it is told to redeploy, not to re-call the refused tools.
    IF TG_OP = 'UPDATE'
       AND NEW.state IN ('resolved', 'closed', 'done', 'dropped')
       AND COALESCE(OLD.state, '') NOT IN ('resolved', 'closed', 'done', 'dropped')
    THEN
      IF COALESCE(current_setting('application_name', true), '') LIKE 'pcusp:%' THEN
        RAISE EXCEPTION 'engineer_issues terminal transition refused for issue % — and RE-CALLING work_items:complete / work_items:set_state CANNOT FIX IT. This UPDATE arrived on operator connection "%", which still routes terminal state through the engineer_issues compatibility view; a CURRENT operator writes harness_shared.work_items directly and never reaches this trigger. So that process is running code older than issues-engineer.ts EI-20092514168581881, the REQUIRES-DEPLOYED half of migration 797. FIX: redeploy or restart THAT operator process, then retry the close once. Any completion record you already submitted is stored — only the state flip is outstanding.', NEW.issue_id, COALESCE(current_setting('application_name', true), '?')
          USING HINT = 'Dev box, force it now: PAPERCUSP_ALLOW_DEV_RESTART=1 npx tsx apps/operator/lib/release/deploy-cli.ts --execute — then re-run the close. Do NOT revert the guard and do NOT force-deploy on a fleet-wide premise: this refusal is PER-HOST (plan gui-chat-e2e-actions-2026-08-11, D-014).';
      ELSE
        RAISE EXCEPTION 'engineer_issues terminal transition refused — use setIssueState/work_items:set_state or work_items:complete so completion integrity is enforced (issue %) ', NEW.issue_id
          USING HINT = 'The issue compatibility view is a read/field-edit surface, not a lifecycle writer. If you ARE an operator process and reached this, your build predates issues-engineer.ts EI-20092514168581881 — redeploy that process rather than retrying the tools (EI-20202062074776959).';
      END IF;
    END IF;
    IF TG_OP = 'INSERT' THEN
      -- agent-protocol-authority-semantics-2026-07-26 P-004 (migration 679): authority
      -- must be enumerated HERE too. This view is NOT auto-updatable — it writes through
      -- this INSTEAD OF trigger, whose branches list their columns explicitly. 677 added
      -- the column and exposed it on the view but left this list alone, so an
      -- UPDATE ... SET authority = ... through the view was silently DROPPED: no error,
      -- no warning, no write. Anything added to work_items that the issue family must be
      -- able to write has to be added to all three places in this function.
      INSERT INTO harness_shared.work_items (workspace_id, harness_slug, feature_id, title, summary, status, taken_by, taken_at, item_kind, origin, author_pubkey, assignee_rank, rank_writer, rank_updated_at, fed_ts, fed_hlc, ts, created_ts, updated_ts, payload, terminal_owner, terminal_completion_ref, last_progress_at, authority, parent_id, admission, admitted_at, admitted_by)
      VALUES (COALESCE(NEW.workspace_id,'default'), v_slug, NEW.issue_id, NEW.title, COALESCE(NEW.body,''), COALESCE(NEW.state,'open'), NEW.assignee, NEW.assigned_at, COALESCE(NEW.kind,'bug'), COALESCE(NEW.origin,'local'), NEW.author_pubkey, NEW.assignee_rank, NEW.rank_writer, NEW.rank_updated_at, NEW.fed_ts, NEW.fed_hlc, (extract(epoch FROM COALESCE(NEW.updated_at,now()))*1000)::bigint, (extract(epoch FROM COALESCE(NEW.created_at,now()))*1000)::bigint, (extract(epoch FROM COALESCE(NEW.updated_at,now()))*1000)::bigint, v_payload || jsonb_build_object('_ei', v_ei), NEW.terminal_owner, NEW.terminal_completion_ref, NEW.last_progress_at, NEW.authority, NEW.parent_id, NEW.admission, NEW.admitted_at, NEW.admitted_by);
      RETURN NEW;
    ELSE
      -- Mig 499: release-cooldown provenance (mirrors the feature-family release stamp) —
      -- a release is exactly "this update clears an assignee that was previously set".
      UPDATE harness_shared.work_items SET harness_slug=v_slug, title=NEW.title, summary=COALESCE(NEW.body,''), status=NEW.state, taken_by=NEW.assignee, taken_at=NEW.assigned_at,
        last_released_by = CASE WHEN NEW.assignee IS NULL AND OLD.assignee IS NOT NULL THEN OLD.assignee ELSE last_released_by END,
        last_released_at = CASE WHEN NEW.assignee IS NULL AND OLD.assignee IS NOT NULL THEN now() ELSE last_released_at END,
        -- WI-2990/WI-3006 (migration 509): thread last_progress_at through the view's
        -- UPDATE path (parity with the app-side markIssueProgress direct base-table write).
        last_progress_at = NEW.last_progress_at,
        item_kind=COALESCE(NEW.kind,'bug'), origin=COALESCE(NEW.origin,'local'), author_pubkey=NEW.author_pubkey, assignee_rank=NEW.assignee_rank, rank_writer=NEW.rank_writer, rank_updated_at=NEW.rank_updated_at, fed_ts=NEW.fed_ts, fed_hlc=NEW.fed_hlc, updated_ts=(extract(epoch FROM COALESCE(NEW.updated_at,now()))*1000)::bigint, payload=COALESCE(payload, '{}'::jsonb) || (v_payload - '_ei') || jsonb_build_object('_ei', v_ei), terminal_owner=NEW.terminal_owner, terminal_completion_ref=NEW.terminal_completion_ref, authority=NEW.authority, parent_id=NEW.parent_id
      WHERE workspace_id=OLD.workspace_id AND harness_slug=OLD.base_harness_slug AND feature_id=OLD.issue_id AND item_kind=OLD.kind
        -- 655 (claim-race guard): re-verify ownership against the CURRENT taken_by
        -- (fresh, at lock-acquisition time), not the OLD pre-commit snapshot the
        -- outer view-query's WHERE clause used — closes the TOCTOU window between
        -- two concurrent claimIssue() calls on the same row. See 655's migration
        -- comment for the full mechanism.
        AND (
          NEW.assignee IS NULL
          OR taken_by IS NULL OR btrim(taken_by) = '' OR lower(btrim(taken_by)) = 'unassigned'
          OR taken_by = NEW.assignee
          OR taken_by = OLD.assignee
        );
      GET DIAGNOSTICS v_updated = ROW_COUNT;
      IF v_updated = 0 THEN
        RETURN NULL;
      END IF;
      RETURN NEW;
    END IF;
  END;
  $ei_dml$;
  DROP TRIGGER IF EXISTS engineer_issues_view_dml_trg ON harness_shared.engineer_issues;
  CREATE TRIGGER engineer_issues_view_dml_trg INSTEAD OF INSERT OR UPDATE OR DELETE ON harness_shared.engineer_issues FOR EACH ROW EXECUTE FUNCTION harness_shared.engineer_issues_view_dml();

  -- Minimal datatype_registry (migration 421). The work-item VISIBILITY clause
  -- (featureFamilyKindClause: listWorkItems/count/search) AND the PLACEMENT clause
  -- (frontierPlacementKindClause: claim floors / survey / wake-frontier) reference this table
  -- via a subquery, so EVERY work-items integration test must have it present — same D-014
  -- read-path-completeness rationale as work_item_deps / user_trust_list above. Just the 5
  -- columns those subqueries read; the full 421 (VECTOR(384) embedding + generated title_tsv)
  -- is not needed and would require the pgvector extension. Empty by default ⇒ the subquery
  -- matches nothing, so the clauses behave exactly as the built-in-kinds-only form did before.
  CREATE TABLE IF NOT EXISTS harness_shared.datatype_registry (
    id              text NOT NULL,
    workspace_id    text NOT NULL,
    work_item_kind  text,
    tier            text NOT NULL DEFAULT 'generic-kind',
    status          text NOT NULL DEFAULT 'active',
    review_status   text NOT NULL DEFAULT 'none',
    tags            text[] NOT NULL DEFAULT '{}',
    PRIMARY KEY (workspace_id, id)
  );
  -- WI-2118 reserved-plan-lane floor (reservedPlanLaneExclusionSql): the issue-claim path AND
  -- diagnoseClaimNextMiss reference these two tables to exclude items reserved by another active
  -- plan lane. Empty by default ⇒ the EXISTS subqueries match nothing, so a test that seeds
  -- neither is byte-identical to the pre-floor behavior (mirrors the datatype_registry precedent
  -- above).
  --
  -- ⚠ plan_item_claims MUST be the FULL migration-141 shape, not a column subset: several tests
  -- (e.g. plan-item-convert.integration) apply this fixture FIRST and readMigration('141-…') AFTER
  -- — a stunted stub here makes 141's CREATE TABLE IF NOT EXISTS silently no-op and its
  -- CREATE INDEX (workspace_id, owner) then fails with 'column "workspace_id" does not exist'
  -- (the exact D-014 fixture-subset trap this file exists to end; broke the green gate 2026-07-05).
  -- Same doctrine for harness_plans: carry the real multi-tenant key columns (with test-friendly
  -- DEFAULTs) so a richer real-DDL application in either order composes instead of colliding.
  -- ⚠ The OPERATIONAL columns are load-bearing, not optional padding: status is the
  -- LIFECYCLE axis (draft/ready/active/shipped/superseded) while op_status
  -- (started/paused/done) is what plans:start / plans:pause actually write, and the
  -- reserved-plan-lane claim floor (reservedPlanLaneExclusionSql) reads BOTH. Omitting
  -- op_status here is not a harmless subset — it makes every claim-floor test that sets up
  -- a genuinely RUNNING plan fail at INSERT with 'column "op_status" does not exist', which
  -- reads like a broken test rather than a stale fixture (EI-19409397800537963).
  -- ⚠ template_slug is load-bearing for the same reason (WI-38258): it is the column that
  -- distinguishes a per-run INSTANCE plan (minted by system:plan-run, non-NULL back-pointer to
  -- its template) from an ordinary plan, and the floor's lifecycle leg is qualified by it so a
  -- scheduled run's own items are not reserved for a driving agent that never exists. Omitting
  -- it makes every claim-floor query fail at 'column "template_slug" does not exist'.
  CREATE TABLE IF NOT EXISTS harness_shared.harness_plans (
    workspace_id text NOT NULL DEFAULT 'default',
    harness_slug text NOT NULL DEFAULT 'papercup',
    plan_slug text NOT NULL,
    status text,
    op_status text,
    op_started_at timestamptz,
    op_updated_at timestamptz,
    items jsonb,
    template_slug text,
    PRIMARY KEY (workspace_id, harness_slug, plan_slug)
  );
  -- Pre-existing fixture rows predate op_status; ALTER keeps an older fixture application
  -- (or a CREATE ... IF NOT EXISTS that no-ops against a stunted earlier shape) composable,
  -- exactly like the plan_item_claims doctrine above.
  ALTER TABLE harness_shared.harness_plans ADD COLUMN IF NOT EXISTS op_status text;
  ALTER TABLE harness_shared.harness_plans ADD COLUMN IF NOT EXISTS op_started_at timestamptz;
  ALTER TABLE harness_shared.harness_plans ADD COLUMN IF NOT EXISTS op_updated_at timestamptz;
  -- EI-13738: "items" is load-bearing for the SAME reason op_status is (see above), one floor
  -- later. Claim floor #13 (plan-item-blocked, migration 759) reads the PLAN dependency graph
  -- out of harness_plans.items[].blockedBy[], and it is a LANGUAGE sql function whose body is
  -- validated at CREATE time — so omitting this column does not merely skip coverage, it makes
  -- the migration itself fail to apply with 'column "items" does not exist', which reads like a
  -- broken migration rather than a stale fixture.
  ALTER TABLE harness_shared.harness_plans ADD COLUMN IF NOT EXISTS items jsonb;
  ALTER TABLE harness_shared.harness_plans ADD COLUMN IF NOT EXISTS template_slug text;
  -- Migration 675 normalizes the canonical plan content into these derived indexes. The
  -- reserved-plan-lane claim floor reads plan_items on every issue-family preview/claim path,
  -- so the shared fixture must carry the production relation even when a test does not seed a
  -- normalized row. Keep the full key/column shape so tests that apply migration 675 afterward
  -- compose with this DDL instead of silently accepting a stub.
  CREATE TABLE IF NOT EXISTS harness_shared.plan_items (
    workspace_id text NOT NULL DEFAULT 'default',
    harness_slug text NOT NULL DEFAULT 'papercup',
    plan_slug text NOT NULL,
    item_id text NOT NULL,
    seq integer NOT NULL,
    item_text text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'todo',
    importance text,
    phase text,
    owner_gate_marker text,
    blocked_by text[] NOT NULL DEFAULT '{}'::text[],
    decision_refs text[] NOT NULL DEFAULT '{}'::text[],
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, harness_slug, plan_slug, item_id)
  );
  -- Migration 675's index writer persists the owner-gate marker introduced by
  -- the claim-floor contract.  Keep older/stub fixture applications
  -- composable when the relation already exists without the column.
  ALTER TABLE harness_shared.plan_items
    ADD COLUMN IF NOT EXISTS owner_gate_marker text;
  CREATE TABLE IF NOT EXISTS harness_shared.plan_decisions (
    workspace_id text NOT NULL DEFAULT 'default',
    harness_slug text NOT NULL DEFAULT 'papercup',
    plan_slug text NOT NULL,
    decision_id text NOT NULL,
    seq integer NOT NULL,
    title text NOT NULL DEFAULT '',
    body text NOT NULL DEFAULT '',
    decision_date text,
    item_refs text[] NOT NULL DEFAULT '{}'::text[],
    affects text[] NOT NULL DEFAULT '{}'::text[],
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, harness_slug, plan_slug, decision_id)
  );
  CREATE INDEX IF NOT EXISTS plan_items_status_idx
    ON harness_shared.plan_items (workspace_id, harness_slug, status);
  CREATE INDEX IF NOT EXISTS plan_items_plan_seq_idx
    ON harness_shared.plan_items (workspace_id, harness_slug, plan_slug, seq);
  CREATE INDEX IF NOT EXISTS plan_items_blocked_by_gin
    ON harness_shared.plan_items USING gin (blocked_by);
  CREATE INDEX IF NOT EXISTS plan_decisions_plan_seq_idx
    ON harness_shared.plan_decisions (workspace_id, harness_slug, plan_slug, seq);
  CREATE INDEX IF NOT EXISTS plan_decisions_item_refs_gin
    ON harness_shared.plan_decisions USING gin (item_refs);
  CREATE INDEX IF NOT EXISTS plan_decisions_affects_gin
    ON harness_shared.plan_decisions USING gin (affects);
  -- The watchdog recovery-window floor is also unconditional in the shared claim SQL. Keep an
  -- empty, production-shaped relation in the common fixture so tests that do not seed watchdog
  -- evidence still exercise the same fail-open query path.
  CREATE TABLE IF NOT EXISTS harness_shared.watchdog_ticks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    tick_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'ran',
    known_open_keys text[]
  );
  -- Mirrors libs/papercusp/libs/db/sql/141-plan-item-claims.sql column-for-column (checks/COMMENT/
  -- GRANTs intentionally omitted — superset-only, no-enforcement fixture stance).
  CREATE TABLE IF NOT EXISTS harness_shared.plan_item_claims (
    workspace_id text NOT NULL DEFAULT 'default',
    harness_slug text NOT NULL DEFAULT 'papercup',
    plan_slug text NOT NULL,
    item_id text NOT NULL,
    claim_id uuid DEFAULT gen_random_uuid() NOT NULL,
    owner text NOT NULL,
    owner_label text,
    owner_name text,
    intent text DEFAULT '' NOT NULL,
    liveness_mode text DEFAULT 'availability' NOT NULL,
    ttl_sec integer DEFAULT 1200 NOT NULL,
    acquired_ts timestamptz DEFAULT clock_timestamp() NOT NULL,
    expires_ts timestamptz NOT NULL,
    last_activity_ts timestamptz DEFAULT clock_timestamp() NOT NULL,
    PRIMARY KEY (workspace_id, harness_slug, plan_slug, item_id)
  );
  -- Mirrors libs/papercusp/libs/db/sql/140-plan-item-assignments.sql (columns only — same
  -- superset-only fixture stance as plan_item_claims above). The plan-lane claim floor
  -- (reservedPlanLaneExclusionSql, work-items.ts) gained an UNCONDITIONAL
  -- plan_item_assignments + agent_name_sessions leg (EI-22040912157347872), so every
  -- claim/preview query in this fixture family 42P01s without these relations — the same
  -- lane/condition_key fixture-lag class the comments above record.
  CREATE TABLE IF NOT EXISTS harness_shared.plan_item_assignments (
    workspace_id text NOT NULL,
    harness_slug text NOT NULL,
    plan_slug text NOT NULL,
    item_id text NOT NULL,
    assignee_name text,
    assigned_by_user text,
    assigned_ts timestamptz,
    released_ts timestamptz,
    strategy text,
    note text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    author_pubkey text,
    origin text DEFAULT 'local' NOT NULL,
    fed_key text GENERATED ALWAYS AS ((plan_slug || ':'::text) || item_id) STORED,
    PRIMARY KEY (workspace_id, harness_slug, plan_slug, item_id)
  );
  -- Mirrors migration 140's agent_name_sessions (adoption binding read by the same floor leg).
  CREATE TABLE IF NOT EXISTS harness_shared.agent_name_sessions (
    workspace_id text NOT NULL,
    session_owner_id text NOT NULL,
    agent_name text NOT NULL,
    owner_user text NOT NULL,
    adopted_at timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (workspace_id, session_owner_id)
  );`;

/**
 * Minimal watchdog-tick fixture for the issue claim recovery-window floor.
 *
 * The claim path reads only these four columns when deciding whether an eligible
 * watchdog signal has six complete ran ticks of recovery evidence. Keep this
 * fixture intentionally narrow: the full production table is migration 202 plus
 * additive columns, while these integration tests do not exercise the collector
 * writer or its unrelated diagnostics.
 */
export const WATCHDOG_TICKS_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.watchdog_ticks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    tick_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'ran',
    known_open_keys text[]
  )`;

/**
 * Minimal `adv_sessions` DDL for claim-path fixtures. Every claim door (feature
 * `claimNextWorkItem`, issue `claimNextIssueWorkItem`, `setWorkItemState`) now asks
 * `readActiveOperationWorkerClaimBinding` (blueprint/operation-worker-binding.ts)
 * whether the claimant is an active blueprint operation worker. That read selects
 * from this table; a fixture that omits it turns the read into status 'unavailable',
 * and the door then fails CLOSED with "operation claim authority unavailable" before
 * the behaviour under test runs (WI-10003526, WI-10003684). With the table present
 * and no row for the claimant, the REAL read returns 'none', which is what an
 * ordinary test claimant is. `launch_spec` is included so a fixture that does seed an
 * operation-worker session reaches the second query instead of erroring on it.
 */
export const ADV_SESSIONS_CLAIM_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.adv_sessions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    coord_owner_id text,
    role text,
    launch_spec jsonb,
    started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    ended_at timestamptz,
    ended_by text
  );
  -- WI-10005130: the lapse/takeover reads (shutdownAcceptedOwnerIds,
  -- listRecordedLiveSessions) select these; ADD COLUMN IF NOT EXISTS so a fixture that
  -- hand-built a narrower adv_sessions first is filled in too.
  ALTER TABLE harness_shared.adv_sessions
    ADD COLUMN IF NOT EXISTS plan_slug text,
    ADD COLUMN IF NOT EXISTS shutdown_accepted_at timestamptz,
    -- listRecordedLiveSessions selects these too. Without them it logs
    -- 'column "agent" does not exist' (console.warn fails the file under
    -- vitest-fail-on-console). Types match the live table.
    ADD COLUMN IF NOT EXISTS agent text,
    ADD COLUMN IF NOT EXISTS feature text,
    ADD COLUMN IF NOT EXISTS mode text,
    ADD COLUMN IF NOT EXISTS terminal_bin text,
    ADD COLUMN IF NOT EXISTS pid integer,
    ADD COLUMN IF NOT EXISTS window_id text,
    ADD COLUMN IF NOT EXISTS omp_thread_id text,
    ADD COLUMN IF NOT EXISTS label text,
    ADD COLUMN IF NOT EXISTS cwd text,
    ADD COLUMN IF NOT EXISTS session_id text,
    ADD COLUMN IF NOT EXISTS exit_code integer,
    ADD COLUMN IF NOT EXISTS ended_signal text`;

/**
 * `fleet_membership_events` — the append-only fleet membership fact the claim path's
 * fleet-scope admission reads (WI-10005130). Columns from the live table; the projection
 * trigger and GRANTs are omitted (no fixture asserts the coord_presence projection here).
 */
export const FLEET_MEMBERSHIP_EVENTS_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.fleet_membership_events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    owner_id text NOT NULL,
    owner_label text,
    fleet_slug text,
    fleet_role text,
    event text NOT NULL DEFAULT 'join',
    at timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX IF NOT EXISTS fleet_membership_events_owner_idx
    ON harness_shared.fleet_membership_events (workspace_id, owner_id, id DESC)`;

/**
 * `user_trust_list` DDL — the owner's trusted github user ids (migration 276,
 * shared-hive-trust-admission). The work-items claim path's `autoPickableWhereSql`
 * (work-items-admission.ts, P-010) LEFT-JOINs this table to let un-screened remote
 * work whose VERIFIED author is trusted pass the admission gate. The engine reads it
 * on EVERY claim / claim_next / observe, so any claim-path integration test needs it
 * present — same D-014 read-path-completeness rationale as the consolidated table
 * above: add the engine's read dependencies HERE once, apply in the bootstrap block.
 *
 * Test-friendly DEFAULT on created_ts (prod requires it explicitly); RLS + GRANTs
 * from the migration are intentionally omitted — the test connects as the DB owner
 * (RLS bypassed) and provisions no app roles, matching this fixture's superset-only,
 * no-enforcement stance. Empty by default → the trust leg matches nothing, so the
 * gate behaves exactly as it does for an owner with no trusted authors.
 */
export const USER_TRUST_LIST_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.user_trust_list (
    workspace_id            text NOT NULL,
    trusted_github_user_id  bigint NOT NULL,
    note                    text,
    created_ts              bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (workspace_id, trusted_github_user_id)
  )`;

/** Minimal migration 1337 work_admissions relation for work_items:update tests.
 * The update handler checks source-owned fields before writing; these focused
 * fixtures only need the column-complete empty ledger read, not admission writes. */
export const WORK_ADMISSIONS_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.work_admissions (
    workspace_id    text        NOT NULL,
    id              uuid        NOT NULL,
    work_item_id    text        NOT NULL,
    harness_slug    text        NOT NULL,
    data_source_id  uuid,
    source_kind     text        NOT NULL,
    source_key      text        NOT NULL,
    source_ref      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    field_authority jsonb       NOT NULL DEFAULT '{}'::jsonb,
    admitted_via    text        NOT NULL,
    admitted_by     text        NOT NULL,
    rule_id         uuid,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, id),
    UNIQUE (workspace_id, source_kind, source_key)
  );
  CREATE INDEX IF NOT EXISTS work_admissions_work_item_idx
    ON harness_shared.work_admissions (workspace_id, work_item_id);
`;

/**
 * Minimal `work_item_deps` table (migration 367) for the claim path. claimNextWorkItem's
 * readiness AND-clause (work-item-deps-and-readiness-2026-06-22 P-005, the F1 fix)
 * UNCONDITIONALLY references harness_shared.work_item_deps, so EVERY integration test that
 * exercises the claim path must have this table — apply it in the test bootstrap alongside
 * HARNESS_FEATURES_CONSOLIDATED_DDL. Just the columns + the edge-uniqueness the inserts use;
 * the change-notify trigger/extra indexes (migration 367) are not what the readiness read needs.
 */
export const WORK_ITEM_DEPS_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.work_item_deps (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  text        NOT NULL DEFAULT 'default',
    blocked_kind  text        NOT NULL,
    blocked_ref   text        NOT NULL,
    blocker_kind  text        NOT NULL,
    blocker_ref   text        NOT NULL,
    dep_type      text        NOT NULL DEFAULT 'blocks',
    satisfaction  text        NOT NULL DEFAULT 'settled',
    created_by    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT work_item_deps_no_self
      CHECK (NOT (blocked_kind = blocker_kind AND blocked_ref = blocker_ref)),
    CONSTRAINT work_item_deps_satisfaction_check
      CHECK (satisfaction IN ('settled', 'success'))
  );
  CREATE UNIQUE INDEX IF NOT EXISTS work_item_deps_edge_uniq
    ON harness_shared.work_item_deps (workspace_id, blocked_kind, blocked_ref, blocker_kind, blocker_ref, dep_type);

  -- work-item-deps-and-readiness P-005 (migration 379): the maintained-readiness blocked-set sidecar
  -- + oracle fn + one-hop triggers. Folded in HERE (not per-test) so that with SCHEDULER_MAINTAINED_READY
  -- ON the claim's indexed anti-join (NOT EXISTS work_item_blocked) finds a MAINTAINED table in EVERY
  -- claim integration test (applied alongside + AFTER HARNESS_FEATURES_CONSOLIDATED_DDL, which creates
  -- work_items). Mirrors the frozen migration 379 — keep in sync if 379 ever changes.
  CREATE TABLE IF NOT EXISTS harness_shared.work_item_blocked (
      workspace_id text        NOT NULL DEFAULT 'default',
      harness_slug text        NOT NULL,
      feature_id   text        NOT NULL,
      updated_at   timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (workspace_id, harness_slug, feature_id)
  );
  -- Migration 719: the workspace is a REQUIRED third argument, and BOTH blocker legs
  -- resolve within the blocked item's own workspace. The 2-arg form is dropped first
  -- because a 3-arg overload alongside it makes every 2-arg call ambiguous.
  -- (EI-19313459163394127 — the issue leg used to hardcode 'default', where almost no
  -- issue lives, so every issue-family blocking edge silently did nothing.)
  DROP FUNCTION IF EXISTS harness_shared.work_item_is_blocked(text, text);
  CREATE OR REPLACE FUNCTION harness_shared.work_item_is_blocked(p_harness text, p_feature text, p_workspace text)
      RETURNS boolean LANGUAGE sql STABLE AS $WIB$
      SELECT EXISTS (
          SELECT 1 FROM harness_shared.work_item_deps d
           WHERE d.workspace_id = 'default' AND d.dep_type = 'blocks'
             AND d.blocked_ref = p_harness || '#' || p_feature
             AND ( EXISTS (SELECT 1 FROM harness_shared.work_items bf
                            WHERE bf.item_kind <> ALL (ARRAY['bug','change','task'])
                              AND bf.workspace_id = p_workspace
                              AND (bf.harness_slug || '#' || bf.feature_id) = d.blocker_ref
                              AND ((bf.authority IS NOT NULL AND bf.authority NOT IN ('committed','validated')
                                AND lower(COALESCE(bf.status, '')) NOT IN ('deprecated','dropped'))
                                OR bf.status NOT IN ('passed','deprecated','done','dropped')))
                   OR EXISTS (SELECT 1 FROM harness_shared.work_items bi
                            WHERE bi.item_kind = ANY (ARRAY['bug','change','task'])
                              AND bi.workspace_id = p_workspace AND bi.feature_id = d.blocker_ref
                              AND ((bi.authority IS NOT NULL AND bi.authority NOT IN ('committed','validated')
                                AND lower(COALESCE(bi.status, '')) NOT IN ('closed','dropped'))
                                OR bi.status NOT IN ('resolved','closed','done','dropped'))) )
      );
  $WIB$;
  CREATE OR REPLACE FUNCTION harness_shared.sync_work_item_blocked(p_ws text, p_harness text, p_feature text)
      RETURNS void LANGUAGE plpgsql AS $SWB$
  BEGIN
      IF harness_shared.work_item_is_blocked(p_harness, p_feature, p_ws) THEN
          INSERT INTO harness_shared.work_item_blocked (workspace_id, harness_slug, feature_id, updated_at)
          VALUES (p_ws, p_harness, p_feature, now())
          ON CONFLICT (workspace_id, harness_slug, feature_id) DO UPDATE SET updated_at = now();
      ELSE
          DELETE FROM harness_shared.work_item_blocked
           WHERE workspace_id = p_ws AND harness_slug = p_harness AND feature_id = p_feature;
      END IF;
  END;
  $SWB$;
  CREATE OR REPLACE FUNCTION harness_shared.wir_deps_sync() RETURNS trigger LANGUAGE plpgsql AS $WDS$
  DECLARE v_ref text := COALESCE(NEW.blocked_ref, OLD.blocked_ref); r record;
  BEGIN
      IF COALESCE(NEW.dep_type, OLD.dep_type) <> 'blocks' THEN RETURN COALESCE(NEW, OLD); END IF;
      FOR r IN SELECT f.workspace_id, f.harness_slug, f.feature_id FROM harness_shared.work_items f
                WHERE f.item_kind <> ALL (ARRAY['bug','change','task'])
                  AND (f.harness_slug || '#' || f.feature_id) = v_ref
      LOOP PERFORM harness_shared.sync_work_item_blocked(r.workspace_id, r.harness_slug, r.feature_id); END LOOP;
      RETURN COALESCE(NEW, OLD);
  EXCEPTION WHEN OTHERS THEN RETURN COALESCE(NEW, OLD); END;
  $WDS$;
  DROP TRIGGER IF EXISTS wir_deps_sync_trg ON harness_shared.work_item_deps;
  CREATE TRIGGER wir_deps_sync_trg AFTER INSERT OR UPDATE OR DELETE ON harness_shared.work_item_deps
      FOR EACH ROW EXECUTE FUNCTION harness_shared.wir_deps_sync();
  CREATE OR REPLACE FUNCTION harness_shared.wir_status_sync_dependents() RETURNS trigger LANGUAGE plpgsql AS $WSS$
  DECLARE r record;
  BEGIN
      FOR r IN SELECT f.workspace_id, f.harness_slug, f.feature_id
                 FROM harness_shared.work_item_deps d
                 JOIN harness_shared.work_items f
                   ON f.item_kind <> ALL (ARRAY['bug','change','task'])
                  AND (f.harness_slug || '#' || f.feature_id) = d.blocked_ref
                WHERE d.workspace_id = 'default' AND d.dep_type = 'blocks'
                  AND ( d.blocker_ref = NEW.harness_slug || '#' || NEW.feature_id
                        OR (NEW.item_kind = ANY (ARRAY['bug','change','task']) AND d.blocker_ref = NEW.feature_id) )
      LOOP PERFORM harness_shared.sync_work_item_blocked(r.workspace_id, r.harness_slug, r.feature_id); END LOOP;
      RETURN NEW;
  EXCEPTION WHEN OTHERS THEN RETURN NEW; END;
  $WSS$;
  DROP TRIGGER IF EXISTS wir_status_sync_dependents_trg ON harness_shared.work_items;
  CREATE TRIGGER wir_status_sync_dependents_trg AFTER UPDATE OF status, authority ON harness_shared.work_items
      -- Keep the fixture in parity with migration 640: setIssueState canonicalizes
      -- legacy resolved/closed requests to unified done/dropped before updating the
      -- base table, and those canonical terminal flips must refresh dependents too.
      FOR EACH ROW WHEN (
        ((OLD.status IN ('passed','deprecated','resolved','closed','done','dropped'))
          AND (OLD.status IN ('deprecated','closed','dropped')
            OR COALESCE(OLD.authority IN ('committed','validated'), true)))
        IS DISTINCT FROM
        ((NEW.status IN ('passed','deprecated','resolved','closed','done','dropped'))
          AND (NEW.status IN ('deprecated','closed','dropped')
            OR COALESCE(NEW.authority IN ('committed','validated'), true))))
      EXECUTE FUNCTION harness_shared.wir_status_sync_dependents();
  CREATE OR REPLACE FUNCTION harness_shared.wir_insert_sync_own() RETURNS trigger LANGUAGE plpgsql AS $WIS$
  BEGIN
      IF NEW.item_kind <> ALL (ARRAY['bug','change','task']) THEN
          PERFORM harness_shared.sync_work_item_blocked(NEW.workspace_id, NEW.harness_slug, NEW.feature_id);
      END IF;
      RETURN NEW;
  EXCEPTION WHEN OTHERS THEN RETURN NEW; END;
  $WIS$;
  DROP TRIGGER IF EXISTS wir_insert_sync_own_trg ON harness_shared.work_items;
  CREATE TRIGGER wir_insert_sync_own_trg AFTER INSERT ON harness_shared.work_items
      FOR EACH ROW EXECUTE FUNCTION harness_shared.wir_insert_sync_own();
  CREATE OR REPLACE FUNCTION harness_shared.wir_delete_cleanup() RETURNS trigger LANGUAGE plpgsql AS $WDC$
  BEGIN
      DELETE FROM harness_shared.work_item_blocked
       WHERE workspace_id = OLD.workspace_id AND harness_slug = OLD.harness_slug AND feature_id = OLD.feature_id;
      RETURN OLD;
  EXCEPTION WHEN OTHERS THEN RETURN OLD; END;
  $WDC$;
  DROP TRIGGER IF EXISTS wir_delete_cleanup_trg ON harness_shared.work_items;
  CREATE TRIGGER wir_delete_cleanup_trg AFTER DELETE ON harness_shared.work_items
      FOR EACH ROW EXECUTE FUNCTION harness_shared.wir_delete_cleanup();`;

/**
 * Minimal `engineer_issues` table for the claim path's readiness clause (P-005): its
 * issue-blocker EXISTS subquery reads harness_shared.engineer_issues(workspace_id, issue_id,
 * state). `CREATE TABLE IF NOT EXISTS`, so it composes harmlessly into a test that ALSO applies
 * the full migration 131 (the migration wins; this is a no-op there). Apply it only in claim-path
 * tests that DON'T already create engineer_issues, so the issue-blocker subquery has a table to read.
 */
export const ENGINEER_ISSUES_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.engineer_issues (
    workspace_id text NOT NULL DEFAULT 'default',
    issue_id     text NOT NULL,
    title        text NOT NULL DEFAULT '',
    state        text NOT NULL DEFAULT 'open',
    PRIMARY KEY (workspace_id, issue_id)
  )`;

/**
 * The `carry_notes` substrate (migration 472), trimmed to just the shape
 * `hasWorkItemCheckpointSql` (pot/survey.ts) reads via its `NOT EXISTS` check —
 * no RLS/grants (test-only, admin connection). EI-13695 added that checkpoint
 * exclusion to `fetchFrontierRows`/`countPlaceableFrontier`'s real SQL, but this
 * fixture was never updated for it, so every integration test reaching either
 * function failed with "relation harness_shared.carry_notes does not exist"
 * regardless of anything else under test (found live 2026-07-17 while verifying
 * an unrelated EI-13501 fix — a pre-existing gap, not caused by it).
 */
export const CARRY_NOTES_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.carry_notes (
    workspace_id   TEXT NOT NULL,
    scope          TEXT NOT NULL,
    note           TEXT,
    journal        JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_ts     BIGINT NOT NULL,
    deps           JSONB,
    -- migration 1118 (P-007/R-06 unchanged attestation). This fixture hand-rolls the
    -- table, so it does not inherit real migrations and falls silently one column
    -- behind every time one is added -- the exact stranding this block already had to
    -- be fixed for once. setCarryNoteWithPrior now writes both of these on every body
    -- write, so omitting them breaks every integration test that checkpoints.
    body_ts        BIGINT,
    attested_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (workspace_id, scope)
  )`;

/**
 * `substrate_outbox` federation CDC outbox (archive/102) — the bare table + drain index,
 * WITHOUT archive/102's per-table capture trigger attachments. Those attach to
 * harness_features_consolidated / harness_issues_consolidated, which are now compat VIEWS
 * after the P-010 unification, so 102's `CREATE TRIGGER ... ON <view>` would fail. Federation
 * tests apply THIS for the outbox surface, then the real work_items capture via
 * readMigration('375-work-items-cdc-capture.sql'); the projection-apply tests (echo-guarded,
 * remote-origin writes) need only this empty table for their beforeEach reset.
 */
export const SUBSTRATE_OUTBOX_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.substrate_outbox (
    id           BIGSERIAL PRIMARY KEY,
    workspace_id TEXT   NOT NULL,
    harness_slug TEXT   NOT NULL,
    table_name   TEXT   NOT NULL,
    op           TEXT   NOT NULL CHECK (op IN ('put', 'del')),
    key          TEXT   NOT NULL,
    row          JSONB,
    ts           BIGINT NOT NULL,
    drained_at   BIGINT,
    drained_log_key TEXT
  );
  CREATE INDEX IF NOT EXISTS substrate_outbox_drain_idx
    ON harness_shared.substrate_outbox (workspace_id, harness_slug, drained_at, id);`;

/**
 * The migration-103 workspace_id fill (fill_workspace_id_from_projects) + a BEFORE INSERT
 * trigger on work_items. Pre-unification this trigger lived on harness_features_consolidated
 * (fill_ws_features_trg); that table is now a compat VIEW, so the fill must run on the
 * work_items BASE — an INSERT through the auto-updatable hfc view fires the base's triggers.
 * Federation send-side tests apply this so a feature written WITHOUT workspace_id gets it
 * stamped from harness_shared.projects (by slug), matching the drain's workspace_id filter.
 * REQUIRES harness_shared.projects to exist (the function reads it at trigger time).
 */
export const FILL_WORKSPACE_ID_DDL = `
  -- The fill trigger only stamps when workspace_id is '' / NULL. The helper's work_items
  -- uses DEFAULT 'default' (so engine tests that OMIT the column get a value without this
  -- trigger); but the prod fill path keys off the '' default, so reset it here — otherwise
  -- an omitting INSERT gets 'default' and the fill (→ workspace from projects) never runs,
  -- leaving the outbox row keyed on 'default' and the drain's workspace filter missing it.
  ALTER TABLE harness_shared.work_items ALTER COLUMN workspace_id SET DEFAULT '';
  CREATE OR REPLACE FUNCTION harness_shared.fill_workspace_id_from_projects()
  RETURNS TRIGGER AS $fwip$
  BEGIN
    IF NEW.workspace_id IS NULL OR NEW.workspace_id = '' THEN
      SELECT workspace_id INTO NEW.workspace_id
        FROM harness_shared.projects WHERE slug = NEW.harness_slug LIMIT 1;
      IF NEW.workspace_id IS NULL OR NEW.workspace_id = '' THEN
        NEW.workspace_id := 'default';
      END IF;
    END IF;
    RETURN NEW;
  END;
  $fwip$ LANGUAGE plpgsql;
  DROP TRIGGER IF EXISTS fill_ws_work_items_trg ON harness_shared.work_items;
  CREATE TRIGGER fill_ws_work_items_trg
    BEFORE INSERT ON harness_shared.work_items
    FOR EACH ROW EXECUTE FUNCTION harness_shared.fill_workspace_id_from_projects();`;

/**
 * harness_issues_consolidated — the SEPARATE legacy issues-consolidated federated table
 * (distinct from engineer_issues; NOT part of the P-010 work_items unification). Some
 * federation round-trip tests federate it alongside features, so they need the table + the
 * generic substrate_outbox capture (archive/102) + the workspace_id fill on it. Apply AFTER
 * SUBSTRATE_OUTBOX_DDL + FILL_WORKSPACE_ID_DDL (which defines fill_workspace_id_from_projects)
 * + a harness_shared.projects row. The generic capture fn mirrors archive/102 verbatim.
 */
export const HARNESS_ISSUES_CONSOLIDATED_FED_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.harness_issues_consolidated (
    harness_slug      TEXT NOT NULL,
    issue_id          TEXT NOT NULL,
    workspace_id      TEXT NOT NULL DEFAULT '',
    title             TEXT NOT NULL,
    severity          TEXT NOT NULL,
    source            TEXT NOT NULL,
    status            TEXT NOT NULL,
    found_at          TIMESTAMPTZ NOT NULL,
    found_during      TEXT,
    repro             TEXT,
    evidence          TEXT,
    suggested_fix     TEXT,
    code_pointer      TEXT,
    linked_feature_id TEXT,
    attempts          INT NOT NULL DEFAULT 0,
    notes             JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_ts        BIGINT NOT NULL,
    updated_ts        BIGINT NOT NULL,
    author_pubkey     TEXT,
    origin            TEXT NOT NULL DEFAULT 'local',
    fed_ts            BIGINT,
    fed_hlc           TEXT,
    PRIMARY KEY (harness_slug, issue_id)
  );
  CREATE OR REPLACE FUNCTION harness_shared.capture_substrate_outbox() RETURNS trigger
    LANGUAGE plpgsql AS $cso$
    DECLARE v_op TEXT; v_rec RECORD; v_origin TEXT; v_key TEXT; v_row JSONB; v_ws TEXT; v_slug TEXT; v_keycol TEXT := TG_ARGV[0];
    BEGIN
      IF (TG_OP = 'DELETE') THEN v_op := 'del'; v_rec := OLD; ELSE v_op := 'put'; v_rec := NEW; END IF;
      v_row := to_jsonb(v_rec); v_origin := v_row ->> 'origin';
      IF COALESCE(v_origin, 'local') <> 'local' THEN RETURN v_rec; END IF;
      v_key := v_row ->> v_keycol; v_ws := COALESCE(v_row ->> 'workspace_id', ''); v_slug := v_row ->> 'harness_slug';
      INSERT INTO harness_shared.substrate_outbox (workspace_id, harness_slug, table_name, op, key, row, ts)
        VALUES (v_ws, v_slug, TG_TABLE_NAME, v_op, v_key, v_row, (extract(epoch from now()) * 1000)::bigint);
      PERFORM pg_notify('substrate_outbox', v_ws || '::' || v_slug);
      RETURN v_rec;
    END; $cso$;
  DROP TRIGGER IF EXISTS fill_ws_hic_trg ON harness_shared.harness_issues_consolidated;
  CREATE TRIGGER fill_ws_hic_trg BEFORE INSERT ON harness_shared.harness_issues_consolidated
    FOR EACH ROW EXECUTE FUNCTION harness_shared.fill_workspace_id_from_projects();
  DROP TRIGGER IF EXISTS capture_hic_insdel_trg ON harness_shared.harness_issues_consolidated;
  CREATE TRIGGER capture_hic_insdel_trg AFTER INSERT OR DELETE ON harness_shared.harness_issues_consolidated
    FOR EACH ROW EXECUTE FUNCTION harness_shared.capture_substrate_outbox('issue_id');
  DROP TRIGGER IF EXISTS capture_hic_upd_trg ON harness_shared.harness_issues_consolidated;
  CREATE TRIGGER capture_hic_upd_trg AFTER UPDATE ON harness_shared.harness_issues_consolidated
    FOR EACH ROW WHEN ((to_jsonb(OLD.*) - 'fed_ts') IS DISTINCT FROM (to_jsonb(NEW.*) - 'fed_ts'))
    EXECUTE FUNCTION harness_shared.capture_substrate_outbox('issue_id');`;

/**
 * The other two relations that store a work-item endpoint as '<harness>#<feature_id>':
 * `coord_links` (the AUTHORITATIVE store that work_item_deps mirrors) and `coord_threads`
 * (a work item's comment thread). Only the columns + UNIQUE indexes the endpoint-integrity
 * detector and migration 734's `repoint_qualified_refs` actually touch.
 *
 * The unique indexes are not decoration: re-pointing a ref can collide with a row already
 * at the target ref, and the two tables resolve that collision in OPPOSITE ways (an edge
 * duplicate is redundant and dropped; a thread owns posts and is preserved). Without the
 * indexes a test for that asymmetry cannot fail.
 */
export const COORD_REF_HOLDERS_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.coord_links (
    id bigserial PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    src_kind text NOT NULL, src_ref text NOT NULL,
    dst_kind text NOT NULL, dst_ref text NOT NULL,
    rel text NOT NULL,
    created_by text, created_at timestamptz NOT NULL DEFAULT now());
  CREATE UNIQUE INDEX IF NOT EXISTS coord_links_edge_uq ON harness_shared.coord_links
    (workspace_id, src_kind, src_ref, dst_kind, dst_ref, rel);
  CREATE TABLE IF NOT EXISTS harness_shared.coord_threads (
    workspace_id text NOT NULL DEFAULT 'default',
    thread_id text NOT NULL,
    parent_kind text NOT NULL, parent_ref text NOT NULL,
    title text, post_count int NOT NULL DEFAULT 0,
    harness_slug text, origin text NOT NULL DEFAULT 'local',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, thread_id));
  CREATE UNIQUE INDEX IF NOT EXISTS coord_threads_parent_uq ON harness_shared.coord_threads
    (workspace_id, parent_kind, parent_ref);`;

/**
 * The four event-await relations, taken from a live `pg_dump --schema-only` of the
 * fully-migrated schema (2026-10-02, WI-10005130) rather than replayed from the ~13
 * migrations that built them (163, 183, 533, 550, 569, 572, 599, 632, 710, 1214-1216,
 * 1274). A claim door emits awaited events (`emitAwaitedEvent`, lib/events/await), and
 * that fire path reads `event_awaits`, upserts the `event_key_fires` latch, enqueues
 * `event_wake_deliveries` and, for composed awaits, walks `event_await_nodes`. The same
 * fire then runs the identity reactions (lib/events/identity-reaction.ts), which read
 * `coord_entity_subscriptions` and write `event_reactions`. Without these tables the
 * fire logs "key-fire latch record failed ... relation ... does not exist", which
 * vitest-fail-on-console turns into a red test (measured on work-items-admission,
 * 2026-10-02: first event_awaits, then coord_entity_subscriptions).
 *
 * `predicate_watches` (541, 871, 1250) rides here too: settling a work-item retires its
 * lifecycle-bound watches in BOTH event_awaits and predicate_watches in one statement
 * (`retireLifecycleBoundWatches`, lib/events/await/store.ts), so resolving an issue
 * blocker errored "predicate_watches does not exist" (work-items-claim-readiness,
 * work-items-claim-issue-scope-reread, 2026-10-02).
 *
 * Columns are the full live set. CHECK constraints are omitted, as elsewhere in this
 * file. The three partial UNIQUE indexes on event_awaits are kept on purpose: they are
 * ON CONFLICT targets of the await writers, and without them those INSERTs error.
 */
export const EVENT_AWAITS_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.event_await_nodes (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    root_id bigint NOT NULL,
    parent_id bigint REFERENCES harness_shared.event_await_nodes(id) ON DELETE CASCADE,
    subscriber_id text NOT NULL,
    required_count integer NOT NULL,
    fired_count integer NOT NULL DEFAULT 0,
    fired_at timestamptz,
    spec jsonb,
    wake_handle jsonb,
    note text,
    expires_ts timestamptz,
    timeout_behavior text NOT NULL DEFAULT 'expire',
    cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS harness_shared.event_awaits (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    subscriber_id text NOT NULL,
    event_key text NOT NULL,
    policy text NOT NULL DEFAULT 'wake',
    note text,
    wake_handle jsonb,
    timeout_behavior text NOT NULL DEFAULT 'expire',
    expires_ts timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    fired_at timestamptz,
    fired_reason text,
    cancelled_at timestamptz,
    once boolean NOT NULL DEFAULT true,
    min_sleep_sec integer,
    urgency boolean NOT NULL DEFAULT false,
    payload_filter jsonb,
    scope_kind text,
    scope_ref text,
    node_id bigint,
    root_id bigint,
    member_fired_at timestamptz,
    member_payload jsonb,
    causal_generation bigint,
    expected_condition jsonb,
    superseded_at timestamptz,
    fired_by text,
    fired_payload jsonb,
    producer_health jsonb,
    timeout_verification jsonb,
    verification_claimed_at timestamptz,
    bound_to jsonb,
    cancel_reason text,
    logical_gate_key text,
    fired_delivery_intent_at timestamptz);
  CREATE UNIQUE INDEX IF NOT EXISTS event_awaits_announce_generation_unique
    ON harness_shared.event_awaits (workspace_id, event_key, causal_generation)
    WHERE policy = 'announce' AND causal_generation IS NOT NULL;
  CREATE UNIQUE INDEX IF NOT EXISTS event_awaits_exact_one_shot_one_per_subscriber_key
    ON harness_shared.event_awaits (workspace_id, subscriber_id, event_key)
    WHERE policy <> 'announce' AND once = true AND root_id IS NULL AND payload_filter IS NULL
      AND (note IS NULL OR note NOT LIKE '[fleet:bench] %')
      AND event_key NOT LIKE '%*%' AND event_key NOT LIKE '@%'
      AND fired_at IS NULL AND cancelled_at IS NULL AND superseded_at IS NULL;
  CREATE UNIQUE INDEX IF NOT EXISTS event_awaits_inbox_wake_one_per_agent
    ON harness_shared.event_awaits (workspace_id, subscriber_id, event_key)
    WHERE policy = 'wake' AND once = false AND cancelled_at IS NULL
      AND event_key LIKE 'coord:inbox-wake:%';
  CREATE TABLE IF NOT EXISTS harness_shared.event_key_fires (
    workspace_id text NOT NULL DEFAULT 'default',
    event_key text NOT NULL,
    first_fired_at timestamptz NOT NULL DEFAULT now(),
    last_fired_at timestamptz NOT NULL DEFAULT now(),
    last_fired_by text,
    last_payload jsonb,
    fire_count bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (workspace_id, event_key));
  CREATE TABLE IF NOT EXISTS harness_shared.event_wake_deliveries (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    await_id bigint NOT NULL,
    subscriber_id text NOT NULL,
    event_key text NOT NULL,
    payload jsonb,
    summary text,
    status text NOT NULL DEFAULT 'pending',
    channel text,
    attempts integer NOT NULL DEFAULT 0,
    last_error text,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    urgent boolean NOT NULL DEFAULT false,
    min_sleep_sec integer,
    coalesced_count integer NOT NULL DEFAULT 1,
    source text);
  CREATE TABLE IF NOT EXISTS harness_shared.coord_entity_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'default',
    subscriber_id text NOT NULL,
    target_kind text NOT NULL,
    target_ref text NOT NULL,
    delivery_mode text NOT NULL DEFAULT 'full',
    expires_ts timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    cancelled_at timestamptz,
    follow_blockers boolean NOT NULL DEFAULT false,
    derived_from_kind text,
    derived_from_ref text);
  CREATE UNIQUE INDEX IF NOT EXISTS coord_entity_subscriptions_active_uq
    ON harness_shared.coord_entity_subscriptions (workspace_id, subscriber_id, target_kind, target_ref)
    WHERE cancelled_at IS NULL;
  CREATE TABLE IF NOT EXISTS harness_shared.event_reactions (
    dedup_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    rule_id text NOT NULL,
    fire text NOT NULL,
    trigger_tool text,
    cause_root_run_id text,
    depth integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'fired',
    error_message text,
    fired_at timestamptz NOT NULL DEFAULT now(),
    contributor text);
  CREATE TABLE IF NOT EXISTS harness_shared.predicate_watches (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id text NOT NULL DEFAULT 'default',
    owner_id text NOT NULL,
    role text NOT NULL DEFAULT 'su',
    harness_slug text,
    event_key text NOT NULL,
    tool text NOT NULL,
    args jsonb NOT NULL DEFAULT '{}'::jsonb,
    path text NOT NULL,
    op text NOT NULL,
    value jsonb,
    interval_sec integer NOT NULL DEFAULT 60,
    once boolean NOT NULL DEFAULT true,
    last_eval boolean,
    last_value jsonb,
    last_polled_at timestamptz,
    last_error text,
    consecutive_errors integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    bound_to jsonb,
    evaluator_baselines jsonb NOT NULL DEFAULT '{}'::jsonb);`;

/**
 * The Scout idea ledger, read by the agent-review claim door (`readLedgerGrade` in
 * harness/improvements/agent-review.ts) when it claims a pending agent-review item.
 * Columns from the live table (pg_dump 2026-10-02); the RLS policy, the change-notify
 * trigger and the secondary indexes are omitted because no claim door depends on them.
 */
export const SCOUT_ROUTED_IDEAS_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.scout_routed_ideas (
    idea_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    harness_slug text NOT NULL,
    cycle_id text,
    lens text NOT NULL,
    rail text NOT NULL,
    routed_ref text NOT NULL,
    title text,
    addresses_pattern_refs jsonb,
    routed_at bigint NOT NULL,
    outcome text,
    outcome_checked_at bigint,
    human_grade smallint CHECK (human_grade >= 1 AND human_grade <= 5),
    human_feedback text,
    graded_by text,
    graded_at timestamptz,
    source_hive text,
    target_hive text,
    origin text NOT NULL DEFAULT 'scout',
    created_by text,
    model_spec text,
    model_config jsonb);
  CREATE INDEX IF NOT EXISTS scout_routed_ideas_routed_ref_idx
    ON harness_shared.scout_routed_ideas (routed_ref);`;

/**
 * Every relation a claim door reads or writes BEYOND the base work-item tables
 * (HARNESS_FEATURES_CONSOLIDATED_DDL or the test's own base schema), in apply order:
 * the trust-admission LEFT JOIN, the dependency-readiness clause, the operation-worker
 * claim binding (`adv_sessions`, fail-CLOSED when absent), the event fire, and the
 * Scout idea ledger the agent-review door grades against.
 *
 * WI-10005130: each of these was added to the claim path at a different time, and each
 * time every hand-built claim-path fixture that lacked the new table went red, without
 * anything in the gate radius noticing (integration files are outside it). Applying ONE
 * list means the next claim-path read dependency is added here once.
 * `claim-path-bootstrap-guard.test.ts` fails a fixture-built claim-path test that does
 * not call `applyClaimPathReadDeps`.
 */
/**
 * Read shape used by listFleetAssignments when an ordinary claimant has no
 * append-only fleet membership. Bare claim fixtures have no assignment rows;
 * the real reader must observe that empty inventory rather than a missing view.
 * IF NOT EXISTS preserves a fixture that installs the production view itself.
 */
export const FLEET_ASSIGNMENT_CLAIM_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.fleet_assignment (
    source text,
    workspace_id text NOT NULL,
    agent_id text,
    agent_name text,
    harness_slug text,
    plan_slug text,
    item_id text,
    work_item_id text,
    fleet_slug text,
    fleet_role text,
    claim_active boolean,
    holder_heartbeat_at timestamptz
  )`;

/** Current claim recall writer shape (migrations 240, 583, 703–771). */
export const MEMORY_RECALL_CLAIM_MIN_DDL = `
  CREATE TABLE IF NOT EXISTS harness_shared.memory_recall_stats (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    surface text NOT NULL,
    hit_count integer NOT NULL,
    top_score double precision,
    scores jsonb NOT NULL DEFAULT '[]'::jsonb,
    fragment_count integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    pools jsonb,
    workspace_id text,
    pot_slug text,
    score_scale text,
    query_chars integer,
    query_sha256 text,
    query_origin text,
    session_id text,
    legs jsonb,
    admission jsonb,
    client text,
    top_cosine_score double precision,
    cosine_scores jsonb
  );
  CREATE TABLE IF NOT EXISTS harness_shared.memory_recall_query_text (
    stats_id bigint PRIMARY KEY REFERENCES harness_shared.memory_recall_stats(id) ON DELETE CASCADE,
    query_text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`;

export const CLAIM_PATH_READ_DEPS_DDL: readonly string[] = [
  USER_TRUST_LIST_DDL,
  WORK_ITEM_DEPS_DDL,
  ADV_SESSIONS_CLAIM_MIN_DDL,
  FLEET_MEMBERSHIP_EVENTS_MIN_DDL,
  FLEET_ASSIGNMENT_CLAIM_MIN_DDL,
  MEMORY_RECALL_CLAIM_MIN_DDL,
  EVENT_AWAITS_MIN_DDL,
  SCOUT_ROUTED_IDEAS_MIN_DDL,
];

/**
 * Apply {@link CLAIM_PATH_READ_DEPS_DDL}. `exec` must run a multi-statement string:
 * postgres.js `(ddl) => sql.unsafe(ddl).simple()`, or node-pg `(ddl) => pool.query(ddl)`.
 * Every statement is IF NOT EXISTS, so calling it after a test's own schema is safe.
 */
export async function applyClaimPathReadDeps(
  exec: (ddl: string) => PromiseLike<unknown>,
): Promise<void> {
  for (const ddl of CLAIM_PATH_READ_DEPS_DDL) await exec(ddl);
}
