/**
 * authored-doc-projection — the pure half of "PG is canonical for authored doc prose".
 *
 * DIRECTION OF TRUTH (D-025, owner-directed 2026-08-10, applying the standing D-004 rule
 * of 2026-08-09). Canonical is ALWAYS PG; a filesystem projection exists IFF there is a
 * reader we do not control. For `content_mode='composed'` docs (CLAUDE.md / AGENTS.md)
 * that inversion already happened — `harness_doc_parts` is canonical and
 * `scripts/project-doc-parts.mjs` writes the files. This module is the SAME move for the
 * `content_mode='authored'` corpus, whose prose lived only in .mdx files while
 * `harness_docs.content` sat empty on all 952 authored rows (migration 787 documented
 * exactly that; migration 789 rewrites its comments to this contract).
 *
 * WHY A FILE STILL EXISTS, unlike plans. Plans are PG-only and have no file at all, which
 * is *why* agents never hand-edit them — there is nothing to hand-edit. Docs cannot reach
 * that end state: docs:search's lexical/BM25 leg reads the filesystem and the Starlight
 * site builds from it (D-022). So the file survives, stays temptingly editable, and
 * D-003's overwrite-as-enforcement substitutes for the impossibility plans get for free.
 *
 * WHY THIS IS A MODULE AND NOT PART OF THE SCRIPT. Three callers need the same answers —
 * the `docs:author` tool (writes a row, then projects one file), the CLI projector (the
 * whole corpus, both directions), and the tests. A second copy of the banner rules would
 * let two of them disagree about what the canonical text IS, at which point drift becomes
 * indistinguishable from a banner revision and the guards below start reporting nonsense.
 * The same argument `parseFrontmatterBlock` makes for itself, one level up.
 */

import { createHash } from 'node:crypto';
import { parseFrontmatterBlock } from '@papercusp/docs-engine';

export const sha256 = (s: string): string => createHash('sha256').update(s, 'utf8').digest('hex');

/**
 * The phrase that identifies a file as OUR OUTPUT rather than anyone's source.
 * Mirrors `PROJECTION_MARKER` in project-doc-parts.mjs — same role, different column.
 */
export const PROJECTION_MARKER = 'Projected from Postgres: harness_shared.harness_docs.content';

/**
 * The banner is emitted as YAML COMMENT LINES INSIDE the frontmatter block, and both
 * halves of that sentence are load-bearing:
 *
 *   • YAML comments, because the frontmatter parser drops them — so the warning reaches an
 *     agent reading the file in an editor while staying invisible to the rendered Starlight
 *     page and to every frontmatter consumer.
 *   • INSIDE the frontmatter, because frontmatter must be the first bytes of the file, and
 *     an HTML comment above it would both break that and be a parse error in MDX v2, which
 *     has no `<!-- -->` form at all.
 *
 * It is deliberately NOT part of `content`: the canonical text is what an author wrote, so
 * a change to this wording must not churn 672 content hashes or read as drift. That is
 * what `stripProjectionBanner` buys, and the round-trip identity it guarantees —
 * `strip(apply(c)) === c` — is the property the whole cutover rests on.
 */
export function bannerLines(docId: string): string[] {
  return [
    `# ⚠ GENERATED PROJECTION — DO NOT EDIT THIS FILE BY HAND.`,
    `# ${PROJECTION_MARKER} (doc_id=${docId}).`,
    `# Edit the doc with docs:author { overwrite: true } — a hand-edit here is REFUSED by`,
    `# the next projection (it cannot tell your edit from corruption), so it blocks the`,
    `# whole corpus instead of shipping. See agent-insights/authoring-docs-pg-canonical.`,
  ];
}

export interface FrontmatterSplit {
  present: boolean;
  bom: string;
  /** Byte offset (past any BOM) where the YAML block begins — just past the opening `---` line. */
  offset: number;
  eol: string;
  yaml: string;
}

/**
 * Split a doc into its frontmatter block and the rest.
 *
 * Tolerates a UTF-8 BOM and CRLF, because both appear in real corpora and a parser that
 * silently reported "no frontmatter" for a BOM-prefixed file would skip the banner on
 * exactly the files most likely to have been touched by another tool.
 */
export function splitFrontmatter(text: string): FrontmatterSplit {
  const bom = text.startsWith('﻿') ? '﻿' : '';
  const rest = bom ? text.slice(1) : text;
  const m = /^---[ \t]*(\r?\n)([\s\S]*?)\r?\n---[ \t]*(\r?\n|$)/.exec(rest);
  if (!m) return { present: false, bom, offset: 0, eol: '\n', yaml: '' };
  return { present: true, bom, offset: m[0].indexOf(m[1]) + m[1].length, eol: m[1], yaml: m[2] };
}

/**
 * Add the banner, producing the bytes that go on disk.
 *
 * ⚠ THIS SPLICES; IT DOES NOT REASSEMBLE. An earlier version rebuilt the file from its
 * parsed pieces and thereby normalised CRLF to LF — silently rewriting the line endings of
 * every doc it touched, which the round-trip test caught as a byte-inequality before it
 * reached the corpus. Inserting into the original string leaves every other byte provably
 * untouched, which is the only way the identity can hold for inputs we do not control.
 */
export function applyProjectionBanner(content: string, docId: string): string {
  const fm = splitFrontmatter(content);
  // No frontmatter: there is no invisible place to put a YAML comment, and inventing a
  // frontmatter block would change how the page renders. Emit the file unchanged and let
  // the caller report it — a missing warning is a far smaller harm than a doc this code
  // silently restructured.
  if (!fm.present) return content;
  const rest = fm.bom ? content.slice(1) : content;
  const banner = bannerLines(docId).join(fm.eol) + fm.eol;
  return `${fm.bom}${rest.slice(0, fm.offset)}${banner}${rest.slice(fm.offset)}`;
}

/**
 * Remove OUR banner, returning the canonical content.
 *
 * Only a LEADING run of comment lines is considered, and only when that run actually
 * carries `PROJECTION_MARKER`. A doc whose author wrote their own `# note` at the top of
 * the frontmatter therefore keeps it — the alternative (strip every leading comment) would
 * quietly delete authored text on ingest, which is the one thing an ingest must never do.
 */
export function stripProjectionBanner(text: string): { content: string; stripped: boolean } {
  const fm = splitFrontmatter(text);
  if (!fm.present) return { content: text, stripped: false };
  const rest = fm.bom ? text.slice(1) : text;
  // The leading run of comment lines at the top of the YAML block. `---` is not a comment,
  // so this can never run past the closing delimiter.
  const run = /^(?:[ \t]*#[^\n]*\r?\n)+/.exec(rest.slice(fm.offset));
  if (!run || !run[0].includes(PROJECTION_MARKER)) return { content: text, stripped: false };
  return {
    content: `${fm.bom}${rest.slice(0, fm.offset)}${rest.slice(fm.offset + run[0].length)}`,
    stripped: true,
  };
}

/**
 * The derived frontmatter index stored on `harness_docs.frontmatter`.
 *
 * `dates: 'string'` is not a detail: this value is PERSISTED, and js-yaml's default schema
 * would resolve `discovered: 2026-08-10` to a Date that JSON.stringify then widens into
 * "2026-08-10T00:00:00.000Z" — a timezone-bearing instant the doc never stated, reading
 * back as the previous day west of UTC. The index must answer questions about the FILE.
 *
 * Returns null for a doc with no frontmatter, or frontmatter that does not parse: the prose
 * is still canonical in both cases and only the INDEX is unavailable, so a parse failure
 * must never fail the write.
 */
export function deriveFrontmatterIndex(content: string): Record<string, unknown> | null {
  const parsed = parseFrontmatterBlock(content, { dates: 'string' });
  return parsed.present && parsed.ok && parsed.data ? parsed.data : null;
}

export type ProjectionVerdict =
  | {
      ok: true;
      reason: 'absent' | 'already-current' | 'matches-canonical' | 'matches-prior-projection';
      live?: string;
    }
  | { ok: false; reason: 'drifted'; live: string };

/**
 * PG → file. May we overwrite what is on disk?
 *
 * Same shape and same reasoning as `overwriteVerdict` in project-doc-parts.mjs: the
 * projector reads PG, never the file, so on its own it cannot notice that somebody edited
 * the .mdx after the row was written — those edits would simply be erased. The file is safe
 * to overwrite only when its bytes are something we already know about: nothing
 * (`absent`), the bytes we are about to write (`already-current`), the canonical text modulo
 * our own banner (`matches-canonical`, which also covers the state right after an ingest,
 * before any banner exists), or an older projection whose banner and mtime prove it predates
 * the current PG row (`matches-prior-projection`).
 *
 * Anything else means somebody changed the prose, and `drifted` REFUSES. That is a
 * deliberate softening of the D-003 slogan "a hand-edit is overwritten by the next
 * projection": overwriting silently is the behaviour that LOSES work, and refusing still
 * delivers the enforcement — the edit does not become canonical, and the run goes red until
 * a human moves it into PG — without destroying the text first.
 */
export function projectionVerdict(args: {
  onDisk: string | null;
  contentHash: string | null;
  nextText: string | null;
  /** Filesystem mtime, required to recognize a stale bannered projection safely. */
  fileMtimeMs?: number | null;
  /** Canonical row timestamp observed in the same snapshot as `contentHash`. */
  canonicalUpdatedAt?: string | null;
}): ProjectionVerdict {
  const { onDisk, contentHash, nextText, fileMtimeMs, canonicalUpdatedAt } = args;
  if (onDisk === null) return { ok: true, reason: 'absent' };
  const live = sha256(onDisk);
  if (nextText !== null && live === sha256(nextText)) return { ok: true, reason: 'already-current', live };
  const stripped = stripProjectionBanner(onDisk);
  const bare = stripped.content;
  if (contentHash && sha256(bare) === contentHash) return { ok: true, reason: 'matches-canonical', live };

  // A legacy projection can carry the correct provenance banner while its prose reflects an
  // older PG row. Once PG changes, the content hash no longer matches and the old guard called
  // this a hand edit. The banner alone is not enough — an edited file can retain it — so accept
  // this recovery path only when the file's mtime is no newer than the canonical row update.
  const canonicalUpdatedAtMs = canonicalUpdatedAt ? Date.parse(canonicalUpdatedAt) : Number.NaN;
  if (
    stripped.stripped &&
    fileMtimeMs != null &&
    Number.isFinite(fileMtimeMs) &&
    Number.isFinite(canonicalUpdatedAtMs) &&
    fileMtimeMs <= canonicalUpdatedAtMs
  ) {
    return { ok: true, reason: 'matches-prior-projection', live };
  }

  return { ok: false, reason: 'drifted', live };
}

export type IngestVerdict = {
  verdict: 'create' | 'bootstrap' | 'current' | 'drifted';
  content: string;
};

/**
 * file → PG. May we write the row from the file?
 *
 * ⚠ THE TWO DIRECTIONS ARE NOT SYMMETRIC, AND THAT ASYMMETRY IS THE WHOLE DESIGN.
 * `bootstrap` is the one-time move that made PG canonical, and it is safe precisely
 * BECAUSE the row is empty — there is no canonical text to overwrite. Once content exists,
 * an unguarded ingest is the failure mode this plan exists to remove: it would promote
 * whatever a hand-edit put in the file to canonical, silently, which is the exact inversion
 * of the direction of truth. Hence `drifted`, which the CLI refuses without --reconcile.
 */
export function ingestVerdict(args: { fileText: string; row: { content?: string | null } | null }): IngestVerdict {
  const content = stripProjectionBanner(args.fileText).content;
  if (!args.row) return { verdict: 'create', content };
  if (!args.row.content) return { verdict: 'bootstrap', content };
  if (args.row.content === content) return { verdict: 'current', content };
  return { verdict: 'drifted', content };
}
