/**
 * Store IDENTITY — the generation-3 connection guard.
 *
 * ## The lineage this closes
 *
 * `long-lived-admin-pool.ts` states the first two generations precisely:
 *
 * > every earlier guard asked *"what SHOULD we connect to?"*, and none asked
 * > *"what is the live pool actually bound to?"*
 *
 *   1. **Resolution** — "what *should* we connect to?" → `embedded-pg-discovery`
 *      (env → discovery file → native fallback), plus its pid and port liveness gates.
 *   2. **Binding** — "what is the live pool actually *bound* to?" → {@link endStalePool}
 *      and the self-rebinding `getLongLivedAdminPool` (EI-19285027465993737).
 *   3. **Identity — this module.** "Is the store at that address *the same store we have
 *      been talking to*?"
 *
 * Generations 1 and 2 both reason about the **address**. That is why they could not see
 * the 2026-08-02 22:40Z outage, and it is worth being exact about how thoroughly they
 * could not, because the near-miss fix was to make them stricter:
 *
 * MCP traffic reached a *different* embedded Postgres. That impostor was **alive** (its
 * postmaster had started seconds earlier), **listening** (reads succeeded against it), and
 * **freshly migrated** — 433 tables. So, measured against the exact input that caused a
 * fleet-wide outage:
 *
 * | guard | question it asks | verdict on the impostor |
 * |---|---|---|
 * | `isPidAlive()` | is the writer's process alive? | **PASS** |
 * | `isDiscoveredPortServed()` | is that port in TCP_LISTEN? | **PASS** |
 * | `validateDiscoveryTargetOnce()` (WI-5244) | does `harness_shared.schema_migrations` exist? | **PASS** |
 *
 * All three were deployed and passing. Every one of them asks a variant of *"is this a
 * plausible papercusp database?"*, and the impostor was a perfectly plausible papercusp
 * database. It was simply not **ours**. Reads therefore succeeded and returned `not_found`
 * for records that existed — a confident wrong answer, indistinguishable from data loss.
 *
 * A stricter liveness or shape check is not a weaker version of this guard; it is a
 * different question, and no amount of it reaches the failure.
 *
 * ## Why `system_identifier` is the right fingerprint
 *
 * `pg_control_system().system_identifier` is generated by **initdb** from the creation
 * timestamp plus randomness, stored in pg_control, and is stable for the entire life of a
 * cluster across restarts, crashes and failovers. Two independently-initdb'd clusters
 * cannot share one. That is exactly the discrimination required: an impostor embedded PG is
 * a *new cluster*, so it necessarily carries a different identifier — while an ordinary
 * restart, port change, or reconnect of our own store keeps the same one and stays silent.
 *
 * `current_database()` is carried alongside it because one cluster can host several
 * databases: the identifier alone would accept a connection that landed on the wrong
 * database of the right cluster.
 *
 * ## Indeterminate must never reject
 *
 * This mirrors the rule already load-bearing in the generic resolver, where
 * `listeningPorts()` returns `null` on a platform without `/proc` and the caller declines
 * to have an opinion: **a check that cannot run must never be able to reject a healthy
 * configuration.** So a failed probe, a missing column, an unreadable row — anything short
 * of two determinate identities that differ — yields {@link StoreIdentityVerdict} `kind:
 * 'indeterminate'` and changes nothing. Only a positive, unambiguous disagreement between
 * two successfully-read identities is ever treated as a violation.
 *
 * ## Why a violation LATCHES
 *
 * Once the store has demonstrably changed underneath us, later answers are suspect until
 * something deliberately resolves it. A self-clearing check would go quiet the moment the
 * impostor died and the real store came back — discarding the only evidence that anything
 * happened, which is the precise failure mode ("it recovered, so there is nothing to see")
 * this whole plan exists to eliminate. The latch is the durable record; {@link
 * clearStoreIdentityViolation} is the deliberate act that releases it.
 *
 * Pure and dependency-free on purpose: everything here is a value transform or module
 * state, with no `postgres` import and no I/O, so the whole state machine is unit-testable
 * without a database. The caller supplies rows; this decides what they mean.
 */

/** A store's identity: which cluster, and which database within it. */
export interface StoreIdentity {
  /** `pg_control_system().system_identifier` — unique per initdb'd cluster. */
  systemIdentifier: string;
  /** `current_database()` — one cluster can host several. */
  database: string;
}

/** An identity plus where it was observed, so a mismatch can name both endpoints. */
export interface ObservedStoreIdentity extends StoreIdentity {
  /** The URL the pool was built with, already redacted for logging. */
  url: string;
  /** Epoch ms of the observation. */
  observedAt: number;
}

export type StoreIdentityVerdict =
  /** First determinate sighting in this process — now pinned. */
  | { kind: 'pinned'; identity: ObservedStoreIdentity }
  /** Agrees with the pin. The overwhelmingly common case. */
  | { kind: 'match'; identity: ObservedStoreIdentity }
  /** Two determinate identities that DISAGREE. The one actionable outcome. */
  | { kind: 'mismatch'; pinned: ObservedStoreIdentity; observed: ObservedStoreIdentity }
  /** Could not tell. Never rejects, never pins, never latches. */
  | { kind: 'indeterminate'; reason: string };

/**
 * The probe. One round-trip, no catalog scan, safe on any role that can connect —
 * `pg_control_system()` is executable by PUBLIC and reads pg_control, not user data.
 */
export const STORE_IDENTITY_SQL =
  'SELECT (SELECT system_identifier::text FROM pg_control_system()) AS system_identifier, ' +
  'current_database() AS database';

/**
 * Strip credentials from a connection URL so an identity log line can name the endpoint
 * without leaking a password. Falls back to a coarse label rather than echoing an
 * unparseable string that might itself contain the secret.
 */
export function redactUrl(url: string): string {
  try {
    const u = new URL(url);
    const port = u.port ? `:${u.port}` : '';
    return `${u.protocol}//${u.hostname}${port}${u.pathname}`;
  } catch {
    return '<unparseable-url>';
  }
}

/**
 * Read an identity out of a probe result. Tolerant by construction: any shape that does
 * not yield two non-empty strings is `null` (→ indeterminate), never a partial identity.
 * A half-read identity compared against a pin would produce a false mismatch, which is the
 * one outcome this module must never manufacture.
 */
export function parseStoreIdentity(rows: unknown): StoreIdentity | null {
  const row = Array.isArray(rows) ? rows[0] : undefined;
  if (!row || typeof row !== 'object') return null;
  const r = row as Record<string, unknown>;
  const systemIdentifier = typeof r.system_identifier === 'string' ? r.system_identifier.trim() : '';
  const database = typeof r.database === 'string' ? r.database.trim() : '';
  if (!systemIdentifier || !database) return null;
  return { systemIdentifier, database };
}

/** Two identities are the same store iff BOTH halves agree. */
export function sameStore(a: StoreIdentity, b: StoreIdentity): boolean {
  return a.systemIdentifier === b.systemIdentifier && a.database === b.database;
}

let _pinned: ObservedStoreIdentity | null = null;
let _violation: { pinned: ObservedStoreIdentity; observed: ObservedStoreIdentity } | null = null;

/**
 * Pin the first determinate identity seen in this process, and verify every later one
 * against it.
 *
 * @param identity the parsed probe result, or `null` when the probe could not be read.
 * @param url      the URL the observing pool was built with (redacted internally).
 */
export function pinOrVerifyStoreIdentity(
  identity: StoreIdentity | null,
  url: string,
  now: number = Date.now(),
): StoreIdentityVerdict {
  if (!identity) {
    return { kind: 'indeterminate', reason: 'probe returned no readable identity' };
  }
  const observed: ObservedStoreIdentity = { ...identity, url: redactUrl(url), observedAt: now };
  if (!_pinned) {
    _pinned = observed;
    return { kind: 'pinned', identity: observed };
  }
  if (sameStore(_pinned, observed)) return { kind: 'match', identity: observed };

  // Latch on the FIRST disagreement: the earliest divergence is the diagnostically useful
  // one. A later probe overwriting it would leave only the most recent flap, losing the
  // transition that actually explains the incident.
  if (!_violation) _violation = { pinned: _pinned, observed };
  return { kind: 'mismatch', pinned: _pinned, observed };
}

/** The identity pinned for this process, if one has been established. */
export function pinnedStoreIdentity(): ObservedStoreIdentity | null {
  return _pinned;
}

/**
 * The latched violation, or `null`. Non-null means: at some point this process talked to a
 * different store than the one it pinned, so any `not_found` observed since is untrustworthy.
 */
export function storeIdentityViolation(): {
  pinned: ObservedStoreIdentity;
  observed: ObservedStoreIdentity;
} | null {
  return _violation;
}

/** Deliberately release the latch (an operator has resolved the divergence). */
export function clearStoreIdentityViolation(): void {
  _violation = null;
}

/**
 * The operator-facing explanation of a mismatch.
 *
 * Written to be actionable at 3am by whoever finds it in a log: it says what is wrong, what
 * it means for the answers already given, and what NOT to conclude — because the entire
 * cost of this failure mode last time was that its symptoms read as data loss.
 */
export function describeStoreIdentityMismatch(
  pinned: ObservedStoreIdentity,
  observed: ObservedStoreIdentity,
): string {
  return (
    `[store-identity] 🚨 WRONG STORE — refusing to treat this as the same database.\n` +
    `  pinned:   system_identifier=${pinned.systemIdentifier} database=${pinned.database} via ${pinned.url}\n` +
    `  observed: system_identifier=${observed.systemIdentifier} database=${observed.database} via ${observed.url}\n` +
    `  A differing system_identifier means a DIFFERENT POSTGRES CLUSTER (it is assigned by initdb\n` +
    `  and never changes for the life of a cluster) — this process is now talking to a store that\n` +
    `  is not the one it started with.\n` +
    `  ⚠ Any 'not found' / empty result returned since this point is NOT evidence of data loss.\n` +
    `  It is a correct answer from the wrong database. Do not delete, re-create or "restore"\n` +
    `  anything on the strength of it.\n` +
    `  Most likely cause: ~/.papercusp/embedded-pg.json was rewritten by another local install or\n` +
    `  an ephemeral operator instance, redirecting discovery to its own embedded Postgres.\n` +
    `  Note the liveness gates (pid alive, port listening) and the WI-5244 schema check CANNOT\n` +
    `  catch this: an impostor is alive, listening and freshly migrated. See plan\n` +
    `  outage-must-not-be-silent-2026-08-02 D-001.`
  );
}

/** Test-only — clears pin and latch so a test can drive the state machine from scratch. */
export function _resetStoreIdentityForTests(): void {
  _pinned = null;
  _violation = null;
}
