// GENERATED by `npm run gen:declarations` from scripts/lib/agent-intent-comment-patterns.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/agent-intent-comment-patterns.mjs and regenerate.
/** True when `file` is outside the source set this rule polices. */
export function isSkippedPath(file: any): boolean;
/**
 * Find comments that attribute a pending action to a named agent session id.
 *
 * @param {string} text file contents (or, at edit time, just the incoming edit)
 * @returns {{line:number,id:string,text:string}[]} one row per finding
 */
export function findAgentIntentComments(text: string): {
    line: number;
    id: string;
    text: string;
}[];
/**
 * agent-intent-comment-patterns.mjs — the detector half of
 * `lint:no-agent-intent-comments` (EI-19324979765038953).
 *
 * WHY THIS EXISTS
 * A dead sync-resolver entry (`operatorTurns.byConversation`) held the release gate
 * red for hours — 3 consecutive reds, `main` frozen for the whole fleet — behind this
 * comment:
 *
 *     // su-37bf2 is DELETING this entry under P-025 ... so that deletion,
 *     // not a declaration, is what satisfies the shrink-only ratchet here.
 *
 * That was true as an INTENT when written. It never happened: the named session
 * released the file without the delete landing and stopped responding. But the comment
 * kept asserting the present tense, so every later reader concluded the item was owned
 * and in flight. A second agent read the entry, UPDATED the comment's work-item
 * reference, and still did not delete it — because the comment said someone else had
 * it. A 2-line deletion three agents independently agreed was correct sat undone while
 * the gate stayed red.
 *
 * THE ASYMMETRY THAT MAKES THIS WORTH A GATE
 * Such a comment is strictly WORSE THAN SILENCE. Silence would have made the next
 * reader investigate; the comment actively redirected them away. A claim naming an
 * agent + a pending action has a shelf life measured in minutes on this fleet, but a
 * comment has no expiry and no liveness signal — it is the in-code analogue of the
 * checkpoint-staleness problem `checkpointStale` already solves for work-items, on a
 * surface with no such detector.
 *
 * THE RULE. A source comment may freely CITE an agent session id — 688 comment lines
 * across 390 files do, and almost all are sound history ("filed by su-x", "su-x parked
 * 2026-07-26 on a sha release:trace confirmed was stale"). What it may not do is
 * attribute a PENDING or IN-FLIGHT action to one. Record that on a work-item, which
 * has an assignee, a state, and a staleness signal.
 *
 * WHAT SEPARATES THE TWO — measured against the real corpus, not guessed:
 *
 *   • SUBJECT vs OBJECT is the cleanest discriminator. A live claim puts the id in
 *     SUBJECT position ("su-0e44e will switch the claim…", "su-1226c owns the impl").
 *     Sound history puts it after `by` ("[Registry entry added BY su-16e4c to green
 *     the capture-coverage…]") — past-tense attribution whose trailing infinitive is
 *     the PURPOSE of a completed action, not a pending one. A naive proximity matcher
 *     fires on that line; this one must not, and `no-agent-intent-comments.test.ts`
 *     pins it as a negative control.
 *
 *   • An explicit AS-OF FRAME defuses the claim, because it tells the reader the
 *     staleness is theirs to judge: "(P-201, su-164d8's lane, MID-FIX AT THE TIME THIS
 *     WAS WRITTEN) is a stable…". So does a date. Both are the shape the fix hint
 *     teaches, so both must lint clean or the rule punishes its own remedy.
 *
 * This module is the PATTERN half; scripts/check-no-agent-intent-comments.mjs is the
 * tree-walking half (enumerate, read, report) — same split as
 * scripts/lib/identity-leak-patterns.mjs, and for the same reason: an edit-time
 * advisory and a blocking gate must never disagree about what the rule is.
 *
 * NOTE: this file necessarily SPELLS the forbidden shapes in its own prose and
 * fixtures, so check-no-agent-intent-comments.mjs skips it (and the test) by path.
 */
/**
 * A papercusp agent session id: `su-` + a hex stem. Real ids run from a 5-hex short
 * form (`su-37bf2`) to a full uuid (`su-12b70e95-84ce-4ea0-b546-8a692cdc949c`).
 */
export const AGENT_ID: RegExp;
/**
 * Cheap whole-file pre-filter. A file with no `su-` bigram at all cannot hold this
 * class, so the line scan is skipped entirely.
 */
export const FAST_REJECT: RegExp;
/**
 * Not shipped / not source / regenerated, plus the two files that must describe the
 * forbidden shape to define and test it. Mirrors the sibling identity rules so every
 * guard agrees on what "source" means.
 */
export const SKIP: RegExp[];
/**
 * The one fix text, so the gate and any edit-time advisory teach the same thing.
 */
export const FIX_HINT: string;
