// GENERATED by `npm run gen:declarations` from scripts/lib/governed-test-process.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/governed-test-process.mjs and regenerate.
/** Load the canonical TypeScript seam lazily, preserving direct Node CLI startup. */
export function loadGovernedExecutionModule(): Promise<any>;
/** Test-only cache reset; no production caller needs to unload the loader. */
export function resetGovernedTestProcessLoaderForTests(): void;
/** Resolve a concrete workspace without silently inventing a tenant. */
export function resolveGovernedWorkspaceId(value: any, env?: NodeJS.ProcessEnv): Promise<string>;
/**
 * Stable, bounded idempotency identity for one resident test process.
 * @param {string} [scope]
 * @param {string} [identity]
 */
export function governedProcessIdempotencyKey(scope?: string, identity?: string): string;
/** Build a process reservation; measured peak values replace it at settlement. */
export function buildGovernedProcessDemand(options?: {}): {
    cpuWeight: any;
    memoryBytes: number;
    diskBytes: number;
    fileDescriptors: number;
};
/** Fail-soft aggregate resource snapshot for one child process tree. */
export function readGovernedProcessResourceSnapshot(pid: any): {
    cpuMicros: number | null;
    rssBytes: number | null;
    fileDescriptors: number | null;
};
/**
 * Sample peak process residency while a child is alive.  The reader and clock
 * are injectable so the accounting contract is testable without procfs.
 */
export function createGovernedProcessDemandSampler(planned: any, { readSnapshot, intervalMs, now }?: {
    readSnapshot?: typeof readGovernedProcessResourceSnapshot | undefined;
    intervalMs?: number | undefined;
    now?: (() => number) | undefined;
}): {
    attach(nextPid: any): void;
    sample: () => void;
    stop(extra?: {}): any;
};
/** Classify whether a child produced a trustworthy test verdict. */
export function classifyGovernedTestProcessOutcome(outcome?: {}): {
    kind: string;
    reason: string;
    actualDemand?: undefined;
} | {
    kind: string;
    actualDemand: any;
    reason?: undefined;
};
/** Add a typed lineage context to a child environment. */
export function withGovernedAdmissionContext(env: any, context: any): any;
/**
 * Is this admission rejection one the database itself told us to retry?
 *
 * Detected by PROPERTY, never `instanceof`: this repo's module graph can legitimately
 * produce two copies of a class (tsx's CJS preflight beside the ESM loader, a symlinked
 * `node_modules/@papercusp/*`, a bundled copy beside source), and an `instanceof` check
 * silently answers false across that split — failing closed in the direction that looks
 * like "not retryable", which is indistinguishable from the bug being unfixed.
 *
 * The `cause` chain is walked to a bounded depth because the governor may wrap the
 * originating PG error rather than rethrowing it; the depth bound keeps a cyclic or
 * pathologically deep chain from turning this predicate into a hang.
 */
export function isRetryableAdmissionFailure(error: any, maxDepth?: number): boolean;
/**
 * Run a child behind one durable process receipt.  A valid inherited context
 * means the caller already owns the resident process receipt, so no second
 * admission is created; the same typed context is simply forwarded.
 *
 * The callback receives `(context, childEnv, { inherited })` and must resolve
 * only after the child lifetime has ended.  That keeps the lease alive through
 * the actual process, rather than releasing it immediately after `spawn()`.
 *
 * A retryable ADMISSION failure (see `isRetryableAdmissionFailure`) is retried with
 * bounded exponential backoff.  ⛔ THE CONSTRAINT THAT MAKES THIS SAFE, and the reason
 * it is not simply `catch { retry }`: only a failure from BEFORE the child started may
 * be retried.  `started` flips the instant the callback is entered, which happens only
 * after admission has succeeded — so a rejection carrying `started === true` arrived at
 * or after child launch, and retrying it would RE-RUN TESTS.  That case rethrows
 * immediately regardless of how retryable the error looks.
 */
export function runGovernedTestProcess(options: any, run: any): Promise<any>;
export const GOVERNED_TEST_PROCESS_DEFAULT_MEMORY_BYTES: number;
export const GOVERNED_TEST_PROCESS_DEFAULT_DISK_BYTES: number;
export const GOVERNED_TEST_PROCESS_DEFAULT_FILE_DESCRIPTORS: 16;
export const GOVERNED_TEST_PROCESS_SAMPLE_INTERVAL_MS: 250;
/** Emitted on every retry so fleet-wide DB contention stays VISIBLE. */
export const GOVERNED_ADMISSION_RETRY_MARKER: "GOVERNED_ADMISSION_RETRY";
