// GENERATED by `npm run gen:declarations` from scripts/lib/identity-leak-patterns.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/identity-leak-patterns.mjs and regenerate.
/** True when `file` is outside the shipped-source set these rules police. */
export function isSkippedPath(file: any): boolean;
/**
 * Find named owner-provenance tags in `text`.
 *
 * @param {string} text file contents (or, at edit time, just the incoming edit)
 * @returns {{line:number,name:string,form:'bracket'|'paren',text:string}[]} one row per leak
 */
export function findOwnerNameLeaks(text: string): {
    line: number;
    name: string;
    form: "bracket" | "paren";
    text: string;
}[];
/** How the leak was written, for the fix hint. */
export function renderLeak(f: any): string;
/**
 * Find hardcoded home paths in `text`.
 *
 * @param {string} text file contents (or, at edit time, just the incoming edit)
 * @returns {{line:number,user:string,text:string}[]} one row per leak
 */
export function findBoxIdentityPaths(text: string): {
    line: number;
    user: string;
    text: string;
}[];
/**
 * Resolve the three useful views from one read of git config. `box` mirrors the machine/git
 * values after the release audit drops automation identities; `owner` contains only explicit
 * owner assertions; `all` applies those assertions as per-class overrides, exactly as the audit
 * does. Keeping the views together lets the broad repo lint retain its established box scope,
 * while the sidecar-copy lint applies asserted owner values only where the source bypasses the
 * source-archive scrub.
 *
 * @param {(cmd: string, args: string[]) => string} [readCmd] injection seam for tests
 * @param {NodeJS.ProcessEnv} [env] runtime identity env; injectable for tests
 * @returns {{box:Record<string,string>,owner:Record<string,string>,all:Record<string,string>}}
 */
export function resolveIdentityLiteralScopes(readCmd?: (cmd: string, args: string[]) => string, env?: NodeJS.ProcessEnv): {
    box: Record<string, string>;
    owner: Record<string, string>;
    all: Record<string, string>;
};
/**
 * Resolve one identity scope. Existing callers default to `box`; release-gate consumers that
 * need Python-audit parity request `all`, and narrowly scoped callers can request `owner`.
 *
 * @param {(cmd: string, args: string[]) => string} [readCmd] injection seam for tests
 * @param {{scope?:'box'|'owner'|'all',env?:NodeJS.ProcessEnv}} [opts] requested identity scope
 * @returns {Record<string,string>}
 */
export function resolveIdentityLiterals(readCmd?: (cmd: string, args: string[]) => string, opts?: {
    scope?: "box" | "owner" | "all";
    env?: NodeJS.ProcessEnv;
}): Record<string, string>;
/** The match rule for one literal — word-anchored and case-sensitive when low-entropy. */
export function literalPattern(lit: any): RegExp;
/**
 * Find bare box-identity literals in `text`.
 *
 * @param {string} text file contents (or, at edit time, just the incoming edit)
 * @param {[string,string][]} entries `Object.entries(resolveIdentityLiterals())` — or synthetic
 *   ones in a test. Empty ⇒ no findings (the bare/CI-box no-op).
 * @param {{vendor?: boolean}} [opts] `vendor` ⇒ the path is under node_modules, so low-entropy
 *   literals are not hunted (is_vendor() scoping).
 * @returns {{line:number,key:string,text:string}[]} one row per leak
 */
export function findIdentityLiterals(text: string, entries: [string, string][], opts?: {
    vendor?: boolean;
}): {
    line: number;
    key: string;
    text: string;
}[];
/** True when `file` is outside the shipped-source set the CLASS-3 rule polices. */
export function isSkippedPathForIdentityLiterals(file: any): boolean;
/** True when `file` is copied verbatim into the sidecar outside the source-archive scrub. */
export function isSidecarCopiedIdentityPath(file: any): boolean;
/**
 * Strip every identity-leak class this module detects, returning source-safe text.
 *
 * Order is deliberate: class 1 first (so a name inside a provenance tag is removed as a TAG,
 * yielding `[owner <date>]`, not turned into `[owner:owner <date>]` by the literal pass), then
 * class 3 (this box's exact literals — the most specific), then class 2 (the shape-based
 * catch-all, which also covers OTHER boxes' home paths that class 3 cannot know about).
 *
 * @param {string} text the prose to scrub
 * @param {[string,string][]} [entries] `Object.entries(resolveIdentityLiterals())`; omitted =
 *   resolved once and cached. Pass explicitly to scrub against SYNTHETIC literals in a test —
 *   this module is tracked source, so a fixture may not spell a real box identity.
 * @returns {string} text with no class-1/2/3 leak remaining
 */
export function redactIdentityLeaks(text: string, entries?: [string, string][]): string;
/**
 * Names that identify NOBODY: the stand-ins a test fixture or doc example uses on purpose,
 * precisely because they name no real person. A fixture asserting that the release scrubber
 * strips `[owner:Jane …]` must be able to say `[owner:Jane …]`.
 *
 * This is a list of PLACEHOLDERS, not an allowlist of people. A real contributor's name does
 * not go here — strip it from the tag instead. Adding your name here is the bug this gate
 * exists to catch.
 */
export const PLACEHOLDER_NAMES: Set<string>;
/**
 * Not shipped / not source / regenerated. Mirrors check-no-box-identity.mjs so every rule
 * agrees on what "shipped" means. Exported so the edit-time hook skips the same paths the
 * gate skips — otherwise the hook nags about a `[owner:<name>]` tag on a CARRY surface,
 * where the named form is CORRECT, and agents learn to ignore it.
 */
export const SKIP: RegExp[];
/**
 * Cheap whole-file pre-filter: skip the overwhelming majority of files without running the
 * real matchers. Deliberately NOT a bare /owner/i — `ownerId` appears in thousands of files
 * in this tree, so that would reject almost nothing and cost more than it saves.
 */
export const FAST_REJECT: RegExp;
/** The one fix text, so the gate and the edit-time advisory teach the same thing. */
export const FIX_HINT: string;
/** Home dirs that are NOT a person: shared installs, CI runners, containers. */
export const GENERIC_USERS: Set<string>;
export function isRedactedUser(user: any): boolean;
/** Cheap whole-text pre-filter, same as the per-file one the gate script applied: text with no
 *  `/home/`-shaped bigram anywhere cannot hold this class, so skip the line scan entirely. */
export const BOX_IDENTITY_FAST_REJECT: RegExp;
/** The one fix text for class 2, shared by the gate lint and the edit-time advisory. */
export const BOX_IDENTITY_FIX_HINT: string;
/** Accounts/hosts that identify NOBODY — mirrors identity_literals()'s own
 *  exclusions (`user not in (root, runner, build, ubuntu)`, `host not startswith
 *  (runner, ci-, localhost)`) plus class 2's GENERIC_USERS, so a CI runner or
 *  shared box never self-flags. */
export const GENERIC_ACCOUNTS: Set<string>;
export function isGenericHost(h: any): boolean;
export function needsWordBoundary(lit: any): boolean;
export function isVendorPath(p: any): any;
/** The one fix text for class 3, shared by the gate lint and the edit-time advisory. */
export const IDENTITY_LITERAL_FIX_HINT: string;
/**
 * Class 3 polices a WIDER path set than its two siblings, so it needs its own skip predicate.
 * Ported verbatim from check-no-identity-literals.mjs's SKIP: `scratchpad/` and `scratch/` are
 * excluded because — unlike classes 1 and 2 — this rule hunts BARE literals with no structural
 * anchor (no `[owner:` tag, no `/home/` shape), which widens its surface to catch things like a
 * scratch investigation artifact that RECORDS a past leak as data (e.g. a lexicon-audit dump),
 * which is not itself a leak. Neither dir is in stage-source-tree.sh's ship allowlist, so
 * excluding them costs nothing real. The rule's own script is excluded because it necessarily
 * describes the class in prose.
 */
export const IDENTITY_LITERAL_EXTRA_SKIP: RegExp[];
/**
 * What each resolved identity literal is replaced BY.
 *
 * Mirrors REDACTION_BY_KEY in papercusp-desktop/bin/audit-release-bundle.py — the release
 * scrubber's own vocabulary — so a file scrubbed at GENERATION time and the same file scrubbed
 * at TAR time come out reading the same way. Every value here is also accepted by the matchers
 * above (see the GENERIC_USERS entries for `builduser` / `buildhost`), which is the property
 * that makes a redacted file lint clean.
 */
export const IDENTITY_REDACTIONS: {
    'build-user-name': string;
    'build-hostname': string;
    'build-git-email': string;
    'build-git-name': string;
};
/** Fallback for a literal with no explicit mapping — mirrors the audit's own default. */
export const IDENTITY_REDACTION_FALLBACK: "redacted";
/** The stand-in for a home-directory owner, e.g. `/home/jdoe/x` -> `/home/builduser/x`. */
export const REDACTED_HOME_USER: "builduser";
