// GENERATED by `npm run gen:declarations` from scripts/lib/pure-lane-proof-capture.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/pure-lane-proof-capture.mjs and regenerate.
/** @param {Record<string, string | undefined>} [env] */
export function pureProofCaptureEnabled(env?: Record<string, string | undefined>): boolean;
/** @param {Record<string, string | undefined>} [env] */
export function pureProofCaptureBudgetMs(env?: Record<string, string | undefined>): number;
/** @param {Record<string, string | undefined>} [env] */
export function pureProofCaptureSliceSize(env?: Record<string, string | undefined>): number;
/**
 * Which pure-lane files to capture, in order (D-005 §1 "Population" and "Order"). PURE.
 *
 * Excluded: files with a fail/error row at the sha (the co-residency rail: capture never mints a
 * proof over a failure), and files already holding a fresh proof AT the sha. Then, by path within
 * each tier:
 *   (i)   ranPassed — passed in this sha's suite (the radius the next candidate most likely shares);
 *   (ii)  unproven  — no usable proof (none, expired, or from another runner identity);
 *   (iii) refresh   — a usable proof at an older sha, oldest first, refreshed before it expires.
 *
 * @param {object} o
 * @param {string[]} o.laneFiles repo-relative pure-lane files
 * @param {Set<string>} o.failedAtSha repo-relative files with a fail/error row at the sha
 * @param {Set<string>} o.passedInSuite repo-relative files with a clean source=ci pass at the sha
 * @param {Map<string, { recordedSha: string, recordedAtMs: number, runnerIdentity?: string | null }>} o.proofs
 * @param {string} o.sha
 * @param {number} o.nowMs
 * @param {number} o.maxAgeMs
 * @param {string | null} [o.runnerIdentity] the runner capture will record under; a proof from
 *   another identity cannot be reused (D-004 rule 1), so it counts as no proof
 */
export function orderCaptureCandidates({ laneFiles, failedAtSha, passedInSuite, proofs, sha, nowMs, maxAgeMs, runnerIdentity, }: {
    laneFiles: string[];
    failedAtSha: Set<string>;
    passedInSuite: Set<string>;
    proofs: Map<string, {
        recordedSha: string;
        recordedAtMs: number;
        runnerIdentity?: string | null;
    }>;
    sha: string;
    nowMs: number;
    maxAgeMs: number;
    runnerIdentity?: string | null | undefined;
}): {
    order: string[];
    tiers: {
        ranPassed: number;
        unproven: number;
        refresh: number;
    };
    excluded: {
        failed: number;
        proven: number;
    };
};
/**
 * Whether to start the next slice (D-005 §1 "Before each slice"). PURE.
 *
 * @param {object} o
 * @param {number} o.nowMs
 * @param {number} o.startedAtMs when the phase began
 * @param {number} o.budgetMs
 * @param {number} o.estimateMs the slice's expected wall time
 * @param {number | null} o.nextFireAtMs the next scheduled gate fire; null = unknown (budget only)
 * @param {number} [o.marginMs]
 * @returns {{ go: boolean, reason: "budget" | "next-fire" | null }}
 */
export function decideNextSlice({ nowMs, startedAtMs, budgetMs, estimateMs, nextFireAtMs, marginMs, }: {
    nowMs: number;
    startedAtMs: number;
    budgetMs: number;
    estimateMs: number;
    nextFireAtMs: number | null;
    marginMs?: number | undefined;
}): {
    go: boolean;
    reason: "budget" | "next-fire" | null;
};
/** The vitest argv for one slice: an explicit file list, and an empty match is an ERROR. */
export function buildCaptureVitestArgs(wsRelFiles: any): any[];
/**
 * The env one capture slice runs with. Starts from the gate's suite env (GREEN_CHECKPOINT=1, the
 * worker budget), then: the isolated default config (PC_TEST_LANE unset); no reuse skip list (every
 * named file must run); recording armed for the workspace; test_runs rows as source=local under the
 * phase's own run group, stamped with the judged sha. PURE.
 */
export function buildCaptureEnv(env: any, { resultFile, runGroupId, sha }: {
    resultFile: any;
    runGroupId: any;
    sha: any;
}): any;
/** The repo-relative pure-lane files of `wsAbsDir`, whatever form the include list uses. */
export function repoRelativeLaneFiles(root: any, wsAbsDir: any, include: any): any;
/**
 * Read the proofs THIS capture slice actually persisted, with its source=local test row.
 * The proof table is mutable: retain these names now, before another run replaces them.
 * No cap or aggregate may stand in for the named population.
 * @param {{ client: { query: Function }, sha: string, runGroupId: string, files: string[], sinceMs: number }} o
 * @returns {Promise<Array<{ file: string, testRunId: string, recordedAtMs: number,
 *   runnerIdentity: string, runContext: string, runGroupId: string, source: string }> >}
 */
export function loadCapturedProofRows({ client, sha, runGroupId, files, sinceMs }: {
    client: {
        query: Function;
    };
    sha: string;
    runGroupId: string;
    files: string[];
    sinceMs: number;
}): Promise<Array<{
    file: string;
    testRunId: string;
    recordedAtMs: number;
    runnerIdentity: string;
    runContext: string;
    runGroupId: string;
    source: string;
}>>;
/**
 * Run the capture phase once, in the clean checkpoint checkout `root`, at its HEAD.
 *
 * @param {object} o
 * @param {string} o.root the checkpoint checkout
 * @param {Record<string, string | undefined>} o.env the gate's suite env (buildGreenCheckpointEnv)
 * @param {string} o.runGroupId test_runs group for this phase's rows
 * @param {string | null} [o.logFile] where vitest output goes (appended per slice)
 * @param {number | null} [o.sinceMs] epoch ms the gate run started; lets a notRun skip name the
 *   sha the suite actually judged when the checkout has since moved off it
 * @param {Partial<typeof defaultDeps>} [o.deps]
 * @returns {Promise<{ state: string, reason: string | null, sha: string | null, slices: number,
 *   files: number, rows: number, retired: number, failed: number, isolatedFail: number,
 *   remaining: number, stoppedBy: string | null, evidence: { version: 1, runGroupId: string,
 *   startedAtMs: number, completedAtMs: number, clean: boolean | null,
 *   proofs: Awaited<ReturnType<typeof loadCapturedProofRows>> | null }, lines: string[] }>}
 */
export function runPureLaneProofCapture({ root, env, runGroupId, logFile, sinceMs, deps, }: {
    root: string;
    env: Record<string, string | undefined>;
    runGroupId: string;
    logFile?: string | null | undefined;
    sinceMs?: number | null | undefined;
    deps?: Partial<{
        git: typeof defaultGit;
        laneInclude: (wsAbsDir: any) => string[];
        runnerIdentity: typeof defaultRunnerIdentity;
        connect: (env: any) => Promise<import("pg").Client>;
        loadProofs: typeof loadReuseProofs;
        loadShaOutcomes: typeof defaultLoadShaOutcomes;
        loadLatestLaneSha: typeof defaultLoadLatestLaneSha;
        loadSliceFailures: typeof defaultLoadSliceFailures;
        loadCapturedProofRows: typeof loadCapturedProofRows;
        readResults: (file: any) => import("./executed-source-map.mjs").ExecutedMapResultRead;
        runSlice: typeof defaultRunSlice;
        /** @returns {Promise<number | null>} epoch ms of the next scheduled gate fire, null = unknown */
        readNextFireAtMs: () => Promise<number | null>;
        now: () => number;
        makeTempDir: () => string;
        removeTempDir: (dir: any) => void;
        log: (line: any) => void;
    }> | undefined;
}): Promise<{
    state: string;
    reason: string | null;
    sha: string | null;
    slices: number;
    files: number;
    rows: number;
    retired: number;
    failed: number;
    isolatedFail: number;
    remaining: number;
    stoppedBy: string | null;
    evidence: {
        version: 1;
        runGroupId: string;
        startedAtMs: number;
        completedAtMs: number;
        clean: boolean | null;
        proofs: Awaited<ReturnType<typeof loadCapturedProofRows>> | null;
    };
    lines: string[];
}>;
export const PURE_PROOF_CAPTURE_ENV: "PC_PURE_PROOF_CAPTURE";
export const PURE_PROOF_CAPTURE_BUDGET_ENV: "PC_PURE_PROOF_CAPTURE_BUDGET_MS";
export const PURE_PROOF_CAPTURE_SLICE_ENV: "PC_PURE_PROOF_CAPTURE_SLICE";
export const PURE_PROOF_CAPTURE_BUDGET_MS_DEFAULT: number;
export const PURE_PROOF_CAPTURE_SLICE_DEFAULT: 250;
/** Stop before a slice that would end within this margin of the next scheduled gate fire. */
export const PURE_PROOF_CAPTURE_NEXT_FIRE_MARGIN_MS: number;
/** D-005 input (b): ~0.22 s/file isolated at the gate's worker budget, rounded up. */
export const PURE_PROOF_CAPTURE_EST_MS_PER_FILE: 250;
/** A slice running this many times its estimate (and at least the floor) is killed. */
export const PURE_PROOF_CAPTURE_SLICE_TIMEOUT_FACTOR: 4;
export const PURE_PROOF_CAPTURE_SLICE_TIMEOUT_MIN_MS: number;
/** Proofs are only consumed from the gate's own run context (D-004 rule 1). */
export const PURE_PROOF_CAPTURE_RUN_CONTEXT: "green-checkpoint";
/** The only workspace with a pure lane (packages/operator-core `test:lane-pure`). */
export const PURE_PROOF_CAPTURE_WORKSPACE: Readonly<{
    dir: "packages/operator-core";
    name: "@papercusp/operator-core";
}>;
/** Prefix of every line this phase logs (grep target for the gate log). */
export const PURE_PROOF_CAPTURE_LINE: "PURE_PROOF_CAPTURE";
declare function defaultGit(root: any, args: any): string | null;
import { defaultRunnerIdentity } from "./targeted-task-reuse.mjs";
import { loadReuseProofs } from "./executed-source-map.mjs";
/**
 * Per-file outcomes at the sha over the lane files. Bounded to 7 days so the
 * (file_path, finished_at) index range stays small (measured 3.4s unbounded over 3,731 files).
 */
declare function defaultLoadShaOutcomes({ client, sha, files }: {
    client: any;
    sha: any;
    files: any;
}): Promise<{
    failed: Set<any>;
    passedInSuite: Set<any>;
    ranInSuite: number;
}>;
/**
 * The newest commit the gate suite recorded a clean source=ci row at, for any lane file, since
 * `sinceMs` (this gate process's start). Used only to explain a notRun skip: a repair-queue run can
 * judge one head and then move the checkout to a newly admitted head before capture runs, so HEAD
 * no longer names the sha the suite judged (measured 2026-10-01: judged b8eb76cc, HEAD 3f0e22e9).
 */
declare function defaultLoadLatestLaneSha({ client, files, sinceMs }: {
    client: any;
    files: any;
    sinceMs: any;
}): Promise<any>;
declare function defaultLoadSliceFailures({ client, runGroupId, files }: {
    client: any;
    runGroupId: any;
    files: any;
}): Promise<any>;
/**
 * Run one slice through the SAME governed launcher each `test:lane-pure` shard uses
 * (runVitestProcess → runGovernedTestProcess): inside the gate run it forwards the run's inherited
 * process receipt, so capture adds no second admission. The spawn seam adds what that launcher
 * leaves to npm: the workspace cwd, the root vitest binary, output to the capture log, and a kill
 * past `timeoutMs`. Never rejects.
 */
declare function defaultRunSlice({ bin, args, cwd, env, timeoutMs, logFile }: {
    bin: any;
    args: any;
    cwd: any;
    env: any;
    timeoutMs: any;
    logFile: any;
}): Promise<{
    code: number;
    signal: null;
    timedOut: boolean;
    spawnError: null;
} | {
    code: null;
    signal: null;
    timedOut: boolean;
    spawnError: unknown;
}>;
export {};
