// GENERATED by `npm run gen:declarations` from scripts/lib/quarantine.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/quarantine.mjs and regenerate.
/**
 * Parse quarantine.txt content into the set of BARE (fully-quarantined)
 * workspace names. Per-file `workspace::glob` lines are deliberately excluded.
 * @param {string} text
 * @returns {Set<string>}
 */
export function parseQuarantineWorkspaces(text: string): Set<string>;
