// GENERATED by `npm run gen:declarations` from scripts/lib/related-tests.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/related-tests.mjs and regenerate.
/**
 * Resolve the widening threshold from the environment.
 *
 * @param {Record<string, string | undefined>} [env]
 * @returns {{ threshold: number, source: 'default' | 'env', invalid?: string }}
 */
export function resolveRelatedWidenThreshold(env?: Record<string, string | undefined>): {
    threshold: number;
    source: "default" | "env";
    invalid?: string;
};
/**
 * Persist a workspace-relative selection as a filter-list file.
 *
 * @param {string}   dir    directory to write into (created if missing)
 * @param {string[]} files  workspace-relative test paths
 * @returns {{ path: string, digest: string, count: number }}
 */
export function writeRelatedFilterList(dir: string, files: string[]): {
    path: string;
    digest: string;
    count: number;
};
export function isTestFile(file: any): boolean;
/**
 * Which files in this workspace belong to PLAYWRIGHT rather than Vitest.
 *
 * `TEST_RE` above deliberately spans `.test.*` AND `.spec.*`, because both name real tests
 * somewhere in this repo. But they are not interchangeable RUNNERS: the Vitest unit layer
 * includes only `**\/*.test.ts(x)` (libs/test-config/src/vitest-config.ts), while
 * apps/operator/playwright.config.ts claims `testDir: './e2e'` + `testMatch: /.*\.spec\.ts$/`.
 * A Playwright spec handed to a Vitest lane therefore matches NOTHING, and the test router
 * refuses the whole partial-match run rather than false-greening it
 * (`TEST_FILE_ROUTE_ERROR requested=342 matched=340`, scripts/test-files.mjs). The task then
 * exits 1 with ZERO attributable test files — invisible to the `test_runs` ledger (no fail
 * rows) and to the gate's isolation re-run (no failing file to isolate), which is what made
 * EI-21440128879545486 red-pin green-checkpoint and freeze `main` for the whole fleet.
 *
 * The boundary is DERIVED from Playwright's own config, not a hardcoded `e2e/` glob, so
 * moving `testDir` moves this with it. The extension alone is NOT a safe discriminator:
 * search-core and the three papergrid packages legitimately use `src/**\/*.spec.ts` as their
 * VITEST include, and excluding those would silently shrink their runs — the exact false-green
 * this refusal exists to prevent.
 *
 * A config that is absent or unparseable owns NOTHING. That direction is deliberate: the
 * failure then stays LOUD (a red gate naming the unmatched file) instead of silently
 * withholding a test that should have run.
 *
 * @param {string} rootDir workspace root to look for a Playwright config in
 * @param {{ readFile?: (p: string) => string }} [seam] injected in tests
 * @returns {(absFile: string) => boolean} true when Playwright — not Vitest — owns the file
 */
export function playwrightOwnedTest(rootDir: string, { readFile }?: {
    readFile?: (p: string) => string;
}): (absFile: string) => boolean;
/**
 * Whether Vitest's default UNIT config universally excludes this test path.
 *
 * Keep this contract byte-for-byte aligned with `LAYERED_TEST_FILE` and the unit-layer
 * exclusion globs in `libs/test-config/src/vitest-config.ts`. A related selection is handed
 * to the unit `test`/lane scripts as positional filters; allowing an integration or browser
 * test through makes the unit config reject the entire invocation before any test runs.
 *
 * This deliberately does NOT classify every `.spec.*` file. Some workspaces own Vitest specs
 * through a custom config, while the integration/browser suffixes are excluded by the shared
 * unit config everywhere.
 *
 * @param {string} file test path, absolute or relative
 * @returns {boolean} true when the unit Vitest layer excludes the file
 */
export function unitExcludedVitestTest(file: string): boolean;
/**
 * A specifier is INTRA-REPO if it points at a path we ought to be able to resolve
 * ourselves — relative, or one of the repo's path aliases. A BARE specifier
 * (`node:fs`, `vitest`, `@papercusp/operator-core`) is deliberately out of graph:
 * cross-package effects are already covered by workspace-level selection, and the
 * caller's empty-selection rail turns "changed file is in another package" into a
 * full-suite run.
 */
export function classifySpecifier(spec: any): "relative" | "alias" | "bare";
/**
 * Walk the transitive static module graph from a small set of entry files.
 *
 * This is the entry-oriented sibling of `buildIndex`: it reuses the same specifier parser and
 * resolver, but reads only modules the entries can actually reach. Passing-task provenance uses
 * it for the affected-test runner itself; indexing every file under `scripts/` would make an
 * unrelated maintenance script an input to every workspace test, while indexing the whole repo
 * would cost more than the cache can save.
 *
 * Runtime file paths named as `resolve(__dirname, './x')` / `new URL('./x', import.meta.url)` are
 * edges too. Vitest config loads setup/reporting modules by path rather than import; ignoring that
 * shape would produce a complete-looking but false-small proof. Every uncertainty fails closed.
 * An unreadable entry, unresolved relative/alias import or runtime path, edge escaping `rootDir`,
 * or empty graph returns `ok:false`; callers must run the task instead of reusing a proof. Bare
 * package imports are represented by the package-manager lockfiles in the caller's manifest and
 * therefore do not create an on-disk edge here.
 *
 * @param {object} [o]
 * @param {string} o.rootDir absolute repository root
 * @param {string[]} o.entryFiles absolute entry files to walk
 * @param {RelatedFs} [o.fs] filesystem seam (injected in tests)
 * @returns {{ ok: boolean, files: string[], unresolved: string[] }}
 */
export function staticImportClosure({ rootDir, entryFiles, fs, }?: {
    rootDir: string;
    entryFiles: string[];
    fs?: RelatedFs | undefined;
}): {
    ok: boolean;
    files: string[];
    unresolved: string[];
};
/**
 * The injectable filesystem seam. Declared as a typedef because `gen:declarations`
 * emits from JSDoc: an UNDOCUMENTED destructured option is inferred as a CLOSED
 * literal type (or, with no default to infer from, dropped from the emitted type
 * altogether), and every caller passing it then fails TS2353 "does not exist in
 * type". That is not hypothetical — it is exactly how this block came to be
 * written: the first emit declared `selectRelatedTests` as accepting only the
 * three params its JSDoc happened to list, and lint:tsc reported 10 errors in
 * related-tests-selection.test.ts for the ones it omitted. Keep every option
 * documented here, or the declaration silently narrows again.
 *
 * @typedef {object} RelatedFs
 * @property {(dir: string) => string[]}      list   recursively enumerate source files under `dir`
 * @property {(p: string) => string | null}   read   file contents, or null when unreadable
 * @property {(p: string) => boolean}         exists does this path resolve on disk
 */
/**
 * @typedef {object} RelatedIndex
 * @property {string[]}                files      every source file found under the root
 * @property {Map<string, Set<string>>} deps      file -> the intra-repo files it imports directly
 * @property {Set<string>}             unresolved files carrying an import we could NOT resolve
 */
/**
 * Build the forward dependency graph for `rootDir`.
 *
 * Returns `{ files, deps, unresolved }` where `unresolved` is the set of files
 * carrying at least one INTRA-REPO specifier we could not resolve. Those files are
 * treated as depending on everything (see `selectRelatedTests`) — an unresolved
 * edge is a hole in the graph, and the safe reading of a hole is "this might depend
 * on the thing you changed".
 *
 * @param {object}                  [o]
 * @param {string}                  o.rootDir   absolute dir to index (a workspace's source root)
 * @param {Record<string, string>}  [o.aliases] tsconfig `paths` prefix -> absolute dir
 * @param {RelatedFs}               [o.fs]      filesystem seam (injected in tests)
 * @returns {RelatedIndex}
 */
export function buildIndex({ rootDir, aliases, fs }?: {
    rootDir: string;
    aliases?: Record<string, string> | undefined;
    fs?: RelatedFs | undefined;
}): RelatedIndex;
/**
 * Exact transitive forward closure, including cyclic import graphs.
 *
 * A plain DFS cannot safely memoize while it is breaking a cycle: the first root
 * through a strongly-connected component sees a stack-truncated closure and
 * poisons every later lookup with that partial set. Test selection then depends
 * on file enumeration order and can silently miss a test. Collapse SCCs first;
 * their condensation graph is acyclic, so memoization is exact.
 */
export function transitiveDeps(index: any): (file: any) => Set<any>;
/**
 * Select the test files that a change to `changedPaths` could affect.
 *
 * `mode` is `'related'` only when we are confident the subset is sound; every other
 * outcome is `'full'`, meaning the caller should run the whole suite. `reason`
 * always says which rail fired, so a collapse to "0 tests" can never be silent.
 *
 * @param {object}                 [o]
 * @param {string}                 o.rootDir        absolute dir to index (a workspace's source root)
 * @param {string[]}               o.changedPaths   absolute paths that changed
 * @param {Record<string, string>} [o.aliases]      tsconfig `paths` prefix -> absolute dir
 * @param {number}                 [o.threshold]    share of the suite at/above which the selection is
 *                                                  widened to the whole suite (default: the
 *                                                  `AFFECTED_RELATED_THRESHOLD` env, else
 *                                                  RELATED_WIDEN_THRESHOLD_DEFAULT)
 * @param {RelatedFs}              [o.fs]           filesystem seam (injected in tests)
 * @param {RelatedIndex | null}    [o.index]        prebuilt index, to avoid re-walking the tree
 * @param {ExecutedMap | null}     [o.executedMap]  P-002: per-test-file executed-source map (see
 *                                                  pruneWithExecutedMap); absent ⇒ no pruning
 * @param {string | null}          [o.judgedSha]    P-002: the sha this selection is judged at
 * @param {ChangedBetween | null}  [o.changedBetween] P-002: (recordedSha, judgedSha) ⇒ absolute
 *                                                  paths that changed between them, or null when
 *                                                  the pair cannot be diffed (⇒ treated as stale)
 * @returns {{ mode: 'related' | 'full', selected: string[], total: number, reason: string, threshold: number, executedMap: ExecutedMapSummary }}
 */
export function selectRelatedTests({ rootDir, changedPaths, aliases, threshold, fs, index, executedMap, judgedSha, changedBetween, }?: {
    rootDir: string;
    changedPaths: string[];
    aliases?: Record<string, string> | undefined;
    threshold?: number | undefined;
    fs?: RelatedFs | undefined;
    index?: RelatedIndex | null | undefined;
    executedMap?: ExecutedMap | null | undefined;
    judgedSha?: string | null | undefined;
    changedBetween?: ChangedBetween | null | undefined;
}): {
    mode: "related" | "full";
    selected: string[];
    total: number;
    reason: string;
    threshold: number;
    executedMap: ExecutedMapSummary;
};
/**
 * Apply the P-002 pruning rule to a static selection. Pure: every input is a value or a seam.
 *
 * @param {object}                        o
 * @param {Set<string>}                   o.selected       statically selected tests (absolute)
 * @param {Set<string>}                   o.changedSet     in-scope changed paths (absolute)
 * @param {(file: string) => Set<string>} o.reach          transitive static closure, excluding the file
 * @param {Set<string>}                   o.unresolved     files with an unresolved intra-repo import
 * @param {ExecutedMap | null | undefined} o.executedMap
 * @param {string | null | undefined}     o.judgedSha
 * @param {ChangedBetween | null | undefined} o.changedBetween
 * @returns {{ selected: Set<string>, summary: ExecutedMapSummary }}
 */
export function pruneWithExecutedMap({ selected, changedSet, reach, unresolved, executedMap, judgedSha, changedBetween, }: {
    selected: Set<string>;
    changedSet: Set<string>;
    reach: (file: string) => Set<string>;
    unresolved: Set<string>;
    executedMap: ExecutedMap | null | undefined;
    judgedSha: string | null | undefined;
    changedBetween: ChangedBetween | null | undefined;
}): {
    selected: Set<string>;
    summary: ExecutedMapSummary;
};
export const RELATED_WIDEN_THRESHOLD_DEFAULT: 0.95;
export const RELATED_WIDEN_THRESHOLD_ENV: "AFFECTED_RELATED_THRESHOLD";
export const RELATED_FILTER_LIST_ENV: "PC_TEST_FILTER_LIST";
/**
 * The injectable filesystem seam. Declared as a typedef because `gen:declarations`
 * emits from JSDoc: an UNDOCUMENTED destructured option is inferred as a CLOSED
 * literal type (or, with no default to infer from, dropped from the emitted type
 * altogether), and every caller passing it then fails TS2353 "does not exist in
 * type". That is not hypothetical — it is exactly how this block came to be
 * written: the first emit declared `selectRelatedTests` as accepting only the
 * three params its JSDoc happened to list, and lint:tsc reported 10 errors in
 * related-tests-selection.test.ts for the ones it omitted. Keep every option
 * documented here, or the declaration silently narrows again.
 */
export type RelatedFs = {
    /**
     * recursively enumerate source files under `dir`
     */
    list: (dir: string) => string[];
    /**
     * file contents, or null when unreadable
     */
    read: (p: string) => string | null;
    /**
     * does this path resolve on disk
     */
    exists: (p: string) => boolean;
};
export type RelatedIndex = {
    /**
     * every source file found under the root
     */
    files: string[];
    /**
     * file -> the intra-repo files it imports directly
     */
    deps: Map<string, Set<string>>;
    /**
     * files carrying an import we could NOT resolve
     */
    unresolved: Set<string>;
};
/**
 * `executed` holds ABSOLUTE module paths (the same shape as `changedPaths`).
 */
export type ExecutedEntry = {
    recordedSha: string;
    executed: Set<string> | string[];
};
/**
 * keyed by ABSOLUTE test-file path
 */
export type ExecutedMap = Map<string, ExecutedEntry>;
/**
 * absolute paths changed between the two shas; `null` when the pair cannot be diffed.
 */
export type ChangedBetween = (recordedSha: string, judgedSha: string) => Iterable<string> | null;
export type ExecutedMapSummary = {
    applied: boolean;
    reason: string | null;
    entries: number;
    pruned: number;
    prunable: number;
    wouldEmpty: boolean;
    kept: {
        changedTest: number;
        unresolved: number;
        noEntry: number;
        untrusted: number;
        unknownDrift: number;
        stale: number;
        intersects: number;
    };
};
