// GENERATED by `npm run gen:declarations` from scripts/lib/strip-comments-and-strings.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/strip-comments-and-strings.mjs and regenerate.
/**
 * Strip comments AND the CONTENTS of string/template literals, in ONE pass.
 *
 * THE ONE canonical implementation for every lint guard in `scripts/` that text-matches a
 * call-shaped token. Import it; do not copy it. Copy-pasted `stripComments` IS the root
 * cause this module exists to remove (EI-19991116787260658) — at the time of lifting,
 * 16 guard scripts carried their own private copy and 5 were measurably defective.
 *
 * WHY THIS EXISTS (EI-19989853369726696): guards used to run a comments-only `stripComments`,
 * which leaves string literals intact — so a call-shaped token appearing in PROSE inside a
 * string parsed as a real call site. That is not hypothetical and it was not cheap:
 * `apps/operator/lib/release/green-checkpoint.ts` contains the error text of a DIFFERENT
 * guard —
 *
 *     '... a new recurring timer bypassed managedSetInterval (P-008) ...'
 *
 * The detector regex was /\bmanagedSetInterval\s*\(/, and `\s*\(` happily matches the space
 * before `(P-008)`. The scan extracted `P-008` as that "call's" argument text, found no
 * `classification:`, and reported a phantom offender — red-pinning the fleet gate on a file
 * that does not even IMPORT managedSetInterval, while agents triaged a call site that did
 * not exist.
 *
 * That failure mode is STRUCTURAL for this class of tool, not bad luck: a guard's error
 * message quotes the very token the guard detects, so guards are exactly the code most
 * likely to contain their own detection tokens inside strings. A guard whose own failure
 * text is quoted elsewhere will keep minting phantoms, so the fix belongs in the scanner —
 * never in a reword of the quoting file.
 *
 * ONE pass rather than strip-comments-then-strip-strings, because the two are mutually
 * escaping: `//` inside a string does not start a comment ("http://x" must survive as a
 * string, not silently truncate the rest of the line), and a quote inside a comment does
 * not start a string (`// don't` would otherwise open an unterminated literal and eat the
 * rest of the file). Chaining two independent regex passes gets both of those wrong.
 *
 * `${...}` template expressions are preserved AS CODE — a real call can legitimately live
 * inside one, and dropping them would trade a false POSITIVE for a false NEGATIVE, which is
 * the worse direction for a guard.
 *
 * The delimiters are kept (contents emptied) so nothing new is concatenated across a
 * removal. Argument-level detection is unaffected: a check looking for a `classification:`
 * KEY is reading code, never the string VALUE — `{ classification: 'must-sample' }` still
 * reads as `{ classification: '' }` and still matches.
 *
 * ⚠ NOT FOR EVERY GUARD. Some guards detect tokens that legitimately live INSIDE string or
 * template literals — `check-no-raw-install-slug-filter` matches `harness_slug = ${installSlug}`
 * inside SQL template literals BY DESIGN, and `check-migration-forward-compat`
 * has the same SQL-in-string shape. For those guards, stripping
 * strings would trade this false positive for a false NEGATIVE. Use this module when the token
 * you detect is CODE (a call or identifier); keep reading raw text when the token is legitimately
 * string-resident.
 *
 * ⚠ REGEX LITERAL BODIES ARE BLANKED TOO (delimiters kept). A guard's own detection regex is
 * the single most likely place for its token to appear — `/\bsetInterval\s*\(/` sits in the
 * source of the very guard that bans `setInterval(` — so a regex body is data, exactly like a
 * string, for every consumer of this function.
 *
 * ⚠ JSX TEXT IS LEFT AS CODE. `<p>see https://x/y</p>` is neither a comment nor a literal;
 * treating the `//` there as a comment (which the pre-AST lexer did) erases the rest of the
 * line. Leaving it fails toward a false POSITIVE, which is the safe direction for a guard.
 *
 * WHY A REAL PARSER (EI-20064929206355679, measured 2026-08-10). This was a hand-rolled lexer
 * until then, and it carried TWO defects that no amount of care in the regexes downstream
 * could have compensated for:
 *
 *   1. NO REGEX-LITERAL HANDLING. The quote in an ordinary `/['"]/` opened a phantom string
 *      that ran to the end of the line, DELETING whatever followed it — including a real
 *      call site — and then consumed the newline, gluing the next line onto it. Telling a
 *      regex from division genuinely needs parsing; the old header said so and accepted it.
 *   2. BLOCK COMMENTS WERE DELETED, NEWLINES AND ALL, so every line after one SHIFTED UP.
 *      Any caller counting lines in the stripped text reported the wrong line, and an
 *      `^`-anchored /m regex could match across a boundary that does not exist in the source.
 *
 * Both are now structurally impossible: TypeScript's own parser supplies the literal, regex
 * and comment ranges, and every removal is BLANKED WITH SPACES rather than deleted, so the
 * output is the same LENGTH as the input, character for character. Offsets and line numbers
 * in the stripped text are therefore exact — `text.indexOf(x)` and `slice(0, i).split('\n')`
 * mean in the stripped text precisely what they mean in the source.
 *
 * @param {string} text
 * @param {string} [fileName]  the real path, used ONLY to pick a ScriptKind (.ts vs .tsx
 *        change how `<T>x` parses). Omit it and the kind is inferred by parsing both ways and
 *        keeping whichever the parser preferred — correct, but twice the work, so pass it.
 * @returns {string}
 */
export function stripCommentsAndStrings(text: string, fileName?: string): string;
/**
 * Comments ONLY — string literals are left intact.
 *
 * ⚠ USE THIS ONLY when your downstream analysis has to READ STRING VALUES. Reach for
 * `stripCommentsAndStrings` by default; this one leaves you exposed to the phantom-offender
 * class documented above, and that exposure is a deliberate trade, not an oversight.
 *
 * THE CASE THAT FORCED THIS TO EXIST (EI-19991116787260658, measured 2026-08-09): a single guard can
 * need BOTH strippers at DIFFERENT call sites. `check-no-module-scope-flag-subscribe` detects the
 * CODE token `onFlagChange(` (wants strings stripped) but then hands the matched call's text to
 * `checkUnpopulatedDeclaration`, which reads the string VALUE out of
 * `kind: 'seeded-from-flag-default'` via /kind\s*:\s*['"]([a-z-]+)['"]/. Strip the strings there
 * and the value becomes `kind: ''`, the regex stops matching, and EVERY call site reports
 * "no `unpopulated.kind` declared" — a guard that fails loudly on correct code.
 *
 * So the A/B split is PER CALL SITE, not per guard. Ask what the regex downstream of the strip
 * actually reads: a KEY or a call token (code) -> stripCommentsAndStrings; a VALUE inside quotes
 * -> this function.
 *
 * ⚠ THIS IS QUOTE-AWARE AND LINE-PRESERVING, and both properties are load-bearing (WI-37605).
 * It was a two-regex pass until 2026-08-10 — `.replace(/\/\/[^\n]*\/g, '')` — which had exactly
 * the two defects the module header warns about, in the FALSE-NEGATIVE direction:
 *
 *   1. A `//` INSIDE A STRING started a "comment". `console.warn("see https://x/d", tag)` lost
 *      everything after `https:`, so a real violation later on that line was silently erased.
 *      A guard that reports clean on an offending line is the worst failure this class has.
 *   2. Block comments were DELETED rather than blanked, so `a/*c*\/b` became `ab` (tokens
 *      concatenated across the removal — the very thing stripCommentsAndStrings keeps its
 *      delimiters to prevent) and every line after a multi-line comment SHIFTED UP, making
 *      reported line numbers wrong for any caller that counts them.
 *
 * Comments are replaced with spaces (newlines preserved) rather than removed, so offsets and
 * line numbers stay true. String CONTENTS are still fully preserved — this function remains
 * string-blind BY DESIGN, which is what `guard-string-literal-blindness` uses it to control for.
 *
 * ⚠ IT WAS ALSO REGEX-BLIND until 2026-08-10 (EI-20064929206355679), and that defect ran in
 * the FALSE-POSITIVE direction — the one this module exists to eliminate. The quote in a
 * regex literal (`/'/`, `/['"]/`) opened a phantom string that never closed, so from that
 * point to the end of the file NO comment was blanked and every detection token quoted in a
 * doc comment read as a live call site. Measured, not hypothetical: it put a phantom
 * `role: 'cup'` — text from a doc comment in `check-ungated-mug-kettle.mjs` — into the
 * mug/kettle surface census. Comment ranges now come from TypeScript's parser, which knows a
 * regex from a division.
 *
 * @param {string} text
 * @param {string} [fileName]  the real path, used ONLY to pick a ScriptKind. See
 *        `stripCommentsAndStrings` — omitting it costs a second parse.
 * @returns {string}
 */
export function stripCommentsOnly(text: string, fileName?: string): string;
/**
 * SQL comments blanked; string and dollar-quoted literals left INTACT.
 * The SQL counterpart of `stripCommentsOnly` — use it when the value you match on lives inside
 * a literal (a `DEFAULT 'default'`, a quoted identifier).
 * @param {string} text
 * @returns {string}
 */
export function stripSqlComments(text: string): string;
/**
 * SQL comments AND literal contents blanked — the SQL counterpart of
 * `stripCommentsAndStrings`, and the default choice unless you must read literal values.
 *
 * `dollarBodies` PICKS WHAT A `$tag$…$tag$` BODY IS, and there is no universally right answer —
 * which is exactly why it is a parameter rather than a fixed behaviour:
 *
 *   'literal' (DEFAULT) — the body is an opaque string literal; blank it entire. Correct when a
 *       hit inside a body would be a FALSE POSITIVE because the body is not top-level SQL:
 *       `findRawTxControl` (a `COMMIT` inside a PL/pgSQL body is not top-level transaction
 *       control) and `findUnguardedConstraintRename` (a rename inside a `DO` block is that
 *       lint's own documented FIX SHAPE, so flagging it would flag the fix).
 *
 *   'code' — the body is PL/pgSQL CODE; recurse into it, so comments and strings INSIDE the body
 *       are still blanked but its statements stay live. Correct when a hit inside a body is REAL
 *       and sealing it would be a FALSE NEGATIVE on a safety lint: `findUniqueIndexShapeSwap`
 *       (a DROP + re-ADD of a unique constraint inside a `DO` block really executes, and really
 *       breaks every `ON CONFLICT` written against the old shape).
 *
 * ⚠ "A hit inside a body is real, so use 'code'" is NOT sufficient — check whether the consumer
 * also EXEMPTS itself on something it finds. `findUnguardedReslug` detects a real in-body offence
 * AND disarms on a guard token found anywhere in the file, so 'code' widens its exemption faster
 * than its detection and makes it strictly blinder (measured: 2 offences found, 0 reported). It
 * stays on 'literal' for that reason. For any detect-then-exempt check, ask what the wider view
 * does to the EXEMPT branch, not just to the detect branch.
 *
 * Both readings are legitimate — PostgreSQL says a dollar-quoted body IS a string literal, while
 * every one of these consumers cares about whether the DDL inside it RUNS. Choosing per call site
 * is the whole point; a single shared answer silently mints false positives for one half of the
 * callers or false negatives for the other. Getting this wrong is not hypothetical: masking every
 * body was measured to drop migration 377's in-`DO` unique-constraint swap from
 * `findUniqueIndexShapeSwap` (6 firing files -> 5) with every test still green (WI-37800).
 *
 * @param {string} text
 * @param {{ dollarBodies?: 'literal'|'code' }} [opts]
 * @returns {string}
 */
export function stripSqlCommentsAndStrings(text: string, { dollarBodies }?: {
    dollarBodies?: "literal" | "code";
}): string;
/**
 * Was the character at `index` LIVE CODE, or was it blanked out as string/comment content?
 *
 * THE CASE THIS EXISTS FOR — a pattern that SPANS code and string content, where NEITHER
 * stripper works and read-on-raw does not apply either. `check-no-retired-imports` matches
 * /(?:\bfrom\b|\bimport\b)\s*['"`][^'"`]*_retired\//: masking strings deletes the specifier it
 * needs, and masking only comments leaves a template literal quoting an import standing as a
 * phantom. `check-no-wire-compression` is the same shape one level worse — its rules disagree
 * with EACH OTHER: `createGzip(` is pure code (wants strings masked) while
 * `'content-encoding': 'gzip'` lives ENTIRELY inside string literals (masking deletes it).
 *
 * The resolution is to stop choosing a mask and use the mask as an ORACLE instead: exec the
 * pattern on the RAW text, then ask whether its ANCHOR — the first character of the match, which
 * for these patterns is always the code-shaped part (`from`, `import`, `new`, or the literal's
 * own opening quote) — is real program text. Blanked ⇒ the whole match was string or comment
 * content ⇒ phantom, skip it. Live ⇒ a real hit, and its specifier being a string is EXPECTED.
 *
 * Exact by construction: blanking only ever REPLACES a character with a space, so
 * `raw[i] !== masked[i]` holds if and only if that character was blanked. String DELIMITERS are
 * kept, so a quote reads as live code (it is program text) while its contents do not — which is
 * precisely why a rule anchored on the opening quote still fires on real code but not on the
 * same text nested inside a template literal, where the inner quote is itself blanked.
 *
 * @param {string} raw     the original source
 * @param {string} masked  the SAME source through stripCommentsAndStrings (length-preserving)
 * @param {number} index   an offset into either — they address identically
 * @returns {boolean}
 */
export function isLiveCodeAt(raw: string, masked: string, index: number): boolean;
/**
 * The first match of `re` in `raw` whose anchor is LIVE CODE, or null.
 *
 * ⚠ IT MUST SCAN PAST PHANTOMS, NOT STOP AT THE LEFTMOST MATCH — that is the whole reason this
 * is a helper instead of one `re.exec` plus an `isLiveCodeAt` check at each call site. A single
 * exec returns the LEFTMOST match; if that one happens to sit inside a string while a REAL
 * occurrence follows it on the same line, testing only the leftmost rejects the line and the
 * real hit is silently lost. That is a false NEGATIVE created by a fix aimed at false positives
 * — the same trap already measured once here, where a real `vi.mock` call after a comment
 * quoting the same shape was double-counted (check-full-replacement-mocks, 2 → 1).
 *
 * ⚠ IT TESTS THE FIRST NON-WHITESPACE CHARACTER, NOT `m.index`. Blanking replaces a character
 * WITH A SPACE, so a blanked character and a real space are indistinguishable — and a pattern
 * that opens with `^\s*` (every line-anchored rule here) puts exactly that ambiguous character
 * at `m.index`. Testing it directly would report a match inside a template literal as live code
 * and let the phantom straight through, which is the precise defect this module exists to stop.
 *
 * `re` is cloned with the `g` flag when it lacks one, so a caller's shared module-scope regex is
 * never mutated and never carries `lastIndex` state between calls.
 *
 * @param {string} raw
 * @param {string} masked  `raw` through stripCommentsAndStrings (length-preserving)
 * @param {RegExp} re
 * @returns {RegExpExecArray | null}
 */
export function firstLiveMatch(raw: string, masked: string, re: RegExp): RegExpExecArray | null;
/**
 * The shared RECURRENCE GUARD for the phantom-offender class.
 *
 * Feed a guard's own exported detector a source in which its detection token appears ONLY
 * inside a string literal. A correct detector reports nothing. A detector still running a
 * comments-only strip reports a phantom — the exact defect that red-pinned the fleet gate.
 *
 * This lives beside the stripper on purpose: the fix (import the stripper) and the proof
 * (run this) travel together, so a NEW guard cannot ship with the defect merely by not
 * knowing the history. Call it from the guard's own test suite.
 *
 * @param {(src: string) => unknown} detector  the guard's exported detector
 * @param {string} tokenInProse  a line containing the guard's token as PROSE, e.g.
 *        `a bare setInterval (P-008) is banned`
 * @returns {{ ok: boolean, flagged: boolean, detail: string }}
 */
export function probeStringLiteralBlindness(detector: (src: string) => unknown, tokenInProse: string): {
    ok: boolean;
    flagged: boolean;
    detail: string;
};
/**
 * Strip a trailing `#` comment from ONE SHELL line, respecting quotes.
 *
 * The shell arm of this module. `#` opens a comment only at the START OF A WORD, so it is
 * comment-initiating at position 0 or after whitespace or one of `;`, `&`, `|`, `(` — and is
 * ordinary data anywhere else. That distinction is the whole point: `grep -q '#define'` must
 * not be truncated into a different pipeline, and neither must a `#` in `sed 's/#//'`.
 *
 * ⚠ THIS RETURNS A TRUNCATED LINE, unlike every other export here, which BLANKS its ranges to
 * keep offsets and line numbers true. That is deliberate and is why it is a separate function
 * rather than a `ScriptKind` on the others: its callers split the surviving text into pipeline
 * stages and never map a match back to a column, so truncation is the honest shape for them.
 * If you ever need shell offsets preserved, add a blanking variant — do not "fix" this one.
 *
 * WHY IT LIVES HERE. Until 2026-09-02 the shell arm was a private copy inside
 * `check-assert-integrity.mjs`, and the BASELINE in `guard-string-literal-blindness` listed it
 * under "Entries that are NOT JS/TS and so cannot use the shared module". That reason expired
 * the moment a SECOND copy appeared (`check-pipefail-sigpipe.mjs`, landed the same day with a
 * NARROWER `/\s/` predecessor class that missed `;`, `&`, `|` and `(`) — which is the exact
 * copy-paste-then-drift the module exists to prevent, and is how "SQL cannot use the shared
 * module" had already died on 2026-08-10. Both callers now delegate here, and the shared
 * implementation keeps the WIDER, correct class.
 *
 * @param {string} line  a single shell line
 * @returns {string}     the line up to its first live `#`, or the line unchanged
 */
export function stripShellTrailingComment(line: string): string;
