#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/lib/tsc-baseline-gate.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lib/tsc-baseline-gate.mjs and regenerate.
/**
 * Parse tsc output into { file, code } entries (file null when unattributable).
 *
 * @param {string} tscOutput
 * @returns {TscErrorEntry[]}
 */
export function parseTscErrors(tscOutput: string): TscErrorEntry[];
/**
 * Collapse a compiler path into the repo-relative spelling used by the baseline.
 * A linked worktree can report the same source as both `packages/foo.ts` and
 * `../../../packages/foo.ts`; this helper is pure so the path rule is unit-testable.
 *
 * @param {string | null} file
 * @param {{root:string, canonicalRoot?:string}} roots
 * @returns {string | null}
 */
export function normalizeDiagnosticPath(file: string | null, { root, canonicalRoot }: {
    root: string;
    canonicalRoot?: string;
}): string | null;
/**
 * @param {TscErrorEntry[]} errors
 * @param {{root:string, canonicalRoot:string}} roots
 * @returns {TscErrorEntry[]}
 */
export function normalizeTscErrorPaths(errors: TscErrorEntry[], roots: {
    root: string;
    canonicalRoot: string;
}): TscErrorEntry[];
/**
 * Parse only TS7016/TS2307 diagnostics whose message names a module specifier.
 *
 * @param {string} tscOutput
 * @returns {MissingModuleDiagnostic[]}
 */
export function parseMissingModuleDiagnostics(tscOutput: string): MissingModuleDiagnostic[];
/**
 * Match a module subpath (`@scope/pkg/subpath`) to its declared package name.
 * Relative and absolute specifiers are deliberately not candidates.
 *
 * @param {string} moduleSpecifier
 * @returns {string | null}
 */
export function packageNameFromModuleSpecifier(moduleSpecifier: string): string | null;
/**
 * Decide whether the tsc output plus a dependency-doctor snapshot proves the mid-install shape.
 * The returned diagnostics are the subset that actually match a missing direct dependency, so
 * an unrelated TS2307 elsewhere cannot manufacture the warning.
 *
 * @param {{tscOutput:string, missing?:{dep:string,workspace?:string}[], minimum?:number}} input
 * @returns {{diagnostics:MissingModuleDiagnostic[], dependencies:string[]} | null}
 */
export function detectUnextractedDependencyDiagnostics({ tscOutput, missing, minimum }: {
    tscOutput: string;
    missing?: {
        dep: string;
        workspace?: string;
    }[];
    minimum?: number;
}): {
    diagnostics: MissingModuleDiagnostic[];
    dependencies: string[];
} | null;
/**
 * Format the shared marker used by test-file routing, enriched with the tsc/doctor evidence.
 * This is reporting only: callers must retain tsc's original non-zero exit status.
 *
 * @param {{label:string, diagnostics:MissingModuleDiagnostic[], dependencies:string[]}} input
 * @returns {string[]}
 */
export function formatMidInstallWarning({ label, diagnostics, dependencies }: {
    label: string;
    diagnostics: MissingModuleDiagnostic[];
    dependencies: string[];
}): string[];
/**
 * Files carrying parser/scanner diagnostics. This is the syntax projection only;
 * the gate's hard-fail policy intentionally remains broader (see hardFailFiles).
 *
 * @param {TscErrorEntry[]} errors
 * @returns {string[]}
 */
export function syntaxBrokenFiles(errors: TscErrorEntry[]): string[];
/**
 * Aggregate parsed errors into a { file: count } map. Unattributable errors bucket under '(unattributed)'.
 *
 * @param {TscErrorEntry[]} errors
 * @returns {Record<string, number>}
 */
export function countByFile(errors: TscErrorEntry[]): Record<string, number>;
/**
 * @param {Record<string, number>} map
 * @returns {number}
 */
export function sumValues(map: Record<string, number>): number;
/**
 * The set of repo-relative paths the caller has changed (staged, unstaged, or untracked), for
 * `--mine` scoping. Fail-SOFT: a git failure (packaged install, detached state) returns an empty
 * set, which under `--mine` means "attribute nothing to me" — never a crash, never a false pass on
 * a real CI gate (CI runs bare, without `--mine`).
 *
 * @param {string} [root] - Repo root to run git in.
 * @returns {Set<string>}
 */
export function gitChangedFiles(root?: string): Set<string>;
/**
 * Resolve the local source files reachable from a set of diagnostics. A full-tree tsc run is
 * not an atomic snapshot on the shared checkout: a peer can edit an imported module while tsc is
 * reading its importer, then leave only the importer in the diagnostic. Walking direct local
 * imports keeps the concurrency check scoped to the error site rather than declaring every
 * unrelated edit in the tree inconclusive.
 *
 * @param {{root:string, files:string[]|Set<string>}} input
 * @returns {Set<string>} repo-relative paths (including the seed files)
 */
export function relatedSourceFiles({ root, files }: {
    root: string;
    files: string[] | Set<string>;
}): Set<string>;
/**
 * Find dependency-cone files whose mtime is newer than a typecheck's start. Such a file may have
 * been half-written while tsc read the tree, so a regression that names the cone is INCONCLUSIVE
 * until the caller re-runs against a settled snapshot.
 *
 * @param {{root:string, files:string[]|Set<string>, runStartMs:number, dirtyFiles?:Set<string>|null}} input
 * @returns {string[]} repo-relative paths, sorted and de-duplicated
 */
export function filesModifiedDuringRun({ root, files, runStartMs, dirtyFiles }: {
    root: string;
    files: string[] | Set<string>;
    runStartMs: number;
    dirtyFiles?: Set<string> | null;
}): string[];
/**
 * EI-18731016038876755 — parse an EXPLICIT `--files=a.ts,b.ts` or `--files a.ts,b.ts` CLI flag
 * naming exactly the files the caller changed THIS session, as an alternative to `--mine`'s implicit
 * git-status-derived scoping. Large callers may use `--files-from=/path/to/json`, where the
 * response file contains a JSON array of paths; keeping the list out of argv avoids Linux's
 * exec E2BIG limit without changing the scoped-verdict semantics.
 *
 * WHY: `gitChangedFiles` (above) attributes "mine" from working-tree dirt (`git status`), which
 * on this concurrently-edited shared checkout includes every PEER's uncommitted edits too — not
 * just the caller's own. Observed live: `--mine` reported a regression in a file the calling
 * agent had never opened, because a peer had it mid-edit at that exact moment; re-running the
 * gate a minute later (once the peer's edit settled) gave the opposite verdict on the identical
 * command against the identical tree. `git status` cannot distinguish WHICH agent dirtied a
 * file on a shared checkout — there is no session-scoped signal to read there.
 *
 * `--files=` sidesteps the ambiguity entirely: the caller states which files are theirs
 * (e.g. from their own edit history / Edit-tool log this turn), and that explicit set is used
 * VERBATIM instead of the git-status guess — no heuristic, no false attribution. Passing
 * `--files=` also implies `--mine`-style scoping (a caller naming exact files obviously wants
 * the check scoped to them), so `--mine` need not be passed alongside it.
 *
 * Returns `null` when the flag is absent (falls through to the existing `--mine`/bare behavior
 * unchanged) — never an empty Set for "flag absent", so callers can tell "not scoped" apart from
 * "scoped to zero files" (a malformed `--files=` with no content, which is now the caller's own
 * bug to fix, not a silent no-op).
 *
 * @param {string[]} argv
 * @returns {Set<string> | null} null when the flag is absent; an EMPTY set means "scoped to zero files".
 */
export function parseExplicitFiles(argv: string[]): Set<string> | null;
/**
 * EI-18756182128903253 — the cause-aware widening (fix option 1 of the filed bug): `--mine` /
 * `--files` scope attribution to the literal set of files the caller changed, which is
 * structurally BLIND to the single most common gate-redding change shape — adding a REQUIRED
 * field to a shared exported interface. By definition, the new type errors that causes land in
 * OTHER files (the fixtures/constructors that build that type and were never updated), not in
 * the file the caller edited. So the caller's own `--mine` reads clean, and the break first
 * surfaces hours later at green-checkpoint, redding the gate for the whole fleet.
 *
 * The fix: when a changed file exports a type/interface/class/enum, treat every OTHER file that
 * textually references that name as ALSO attributed to the caller if it regresses — not just the
 * changed file itself. This is a coarse, name-based proxy (it does not diff which specific
 * declaration line changed, and cannot tell a real reference from an unrelated identifier of the
 * same name) — deliberately so: for a lint GATE, the dangerous failure direction is a false
 * negative (silently missing the real cause), not a false positive (a name collision needlessly
 * widening attribution by one entry). Widening is always safe; missing is what cost the fleet a
 * gate cycle four times in 24 hours.
 *
 * Exported top-level type/interface/class/enum names declared in the given files' CURRENT
 * on-disk content.
 *
 * @param {string} root
 * @param {Iterable<string>} files
 * @returns {Set<string>}
 */
export function exportedTypeNames(root: string, files: Iterable<string>): Set<string>;
/**
 * Which of `candidateFiles` reference any of `typeNames` as a standalone identifier — the other
 * half of `exportedTypeNames` above (EI-18756182128903253): cross-reference a changed file's
 * exported type names against every OTHER file, so a fixture that never added the new required
 * field gets attributed to the change that added it, instead of reported as unrelated peer drift.
 *
 * @param {string} root
 * @param {Iterable<string>} candidateFiles
 * @param {Set<string>} typeNames
 * @returns {Set<string>}
 */
export function filesReferencingTypeNames(root: string, candidateFiles: Iterable<string>, typeNames: Set<string>): Set<string>;
/**
 * Find candidate files whose assignability diagnostic names a changed exported type.
 *
 * Source-text attribution misses inferred callback/object-literal errors: the dependent source
 * can omit the expected type while tsc names it in the diagnostic message. Keep this parser
 * narrow to the missing-property/assignability diagnostics emitted by required-field strands.
 *
 * @param {string} tscOutput
 * @param {Iterable<string>} candidateFiles
 * @param {Set<string>} typeNames
 * @param {{root?: string, canonicalRoot?: string}} [roots]
 * @returns {Set<string>}
 */
export function diagnosticFilesReferencingTypeNames(tscOutput: string, candidateFiles: Iterable<string>, typeNames: Set<string>, { root, canonicalRoot }?: {
    root?: string;
    canonicalRoot?: string;
}): Set<string>;
/**
 * Resolve the EFFECTIVE per-file baseline, inheriting cross-package files from their OWNING
 * package's baseline (EI-18649014117371738).
 *
 * ## Why this exists
 *
 * `decidePerFile` treats a file ABSENT from the baseline as an implicit 0 — correct for a file this
 * gate OWNS (a fresh file that arrives with errors IS a named regression). It is WRONG for a file in
 * ANOTHER package that has its own baseline gate: this gate's baseline was captured at some other
 * moment, under a DIFFERENT tsconfig, so "absent" there means "this gate never recorded it", NOT
 * "it was clean". Absent ⇒ 0 turns that gap into a phantom regression.
 *
 * That is not hypothetical: operator-core's baseline records e.g.
 * `packages/operator-core/lib/agent-tools/memory/search.ts: 1` (a KNOWN, TOLERATED error), while
 * apps/operator-vite's baseline — seeded four days later — never listed it. So `lint:tsc` PASSED and
 * `lint:tsc:operator-vite` FAILED on the SAME source file, and 12 operator-core files read as
 * regressions to an agent who had opened none of them. Two gates over one tree giving opposite
 * verdicts makes neither number trustworthy — exactly the false-signal problem the per-file gate was
 * built to kill (EI-847), reintroduced at the cross-package seam.
 *
 * ## The rule
 *
 * For a file this gate MEASURED but did not record, that lives under a `prefix` owned by a package
 * with its own baseline, inherit that package's recorded count instead of defaulting to 0.
 *
 *   - Own baseline ALWAYS wins when present — an explicit entry is this gate's own measured truth
 *     under its own tsconfig, and ratchet-only-down must never be loosened by a foreign number.
 *   - Inheritance is scoped to files actually in `currentByFile`, so a foreign baseline can never
 *     inject files this gate does not measure (that would fabricate phantom "improvements" and
 *     inflate the reported total).
 *   - Absent from BOTH is still an implicit 0 — a genuinely NEW error in a foreign file still gates.
 *
 * @param {{
 *   baselineByFile: Record<string, number>,
 *   currentByFile: Record<string, number>,
 *   foreignBaselines?: {prefix:string, files:Record<string,number>, label?:string}[],
 * }} args
 * @returns {{ effective: Record<string, number>, inherited: {file:string,baseline:number,from:string}[] }}
 */
export function effectiveBaselineByFile({ baselineByFile, currentByFile, foreignBaselines }: {
    baselineByFile: Record<string, number>;
    currentByFile: Record<string, number>;
    foreignBaselines?: {
        prefix: string;
        files: Record<string, number>;
        label?: string;
    }[];
}): {
    effective: Record<string, number>;
    inherited: {
        file: string;
        baseline: number;
        from: string;
    }[];
};
/**
 * EI-19444246913245434 — lower ONLY the named files in an existing baseline map.
 *
 * A SCOPED `--update` must never write a whole-project map: on this shared checkout every other
 * file's current count may include a peer's uncommitted edit, and baking that in creates a false
 * red the moment they revert. (That racy write is why the bug report ruled out bare `--update` as
 * a workaround — so the scoped ratchet had no working form at all.)
 *
 * Merges against the gate's OWN on-disk baseline, never the EFFECTIVE map `decidePerFile` judges
 * with: the effective map folds in entries INHERITED from foreign package baselines
 * (effectiveBaselineByFile), and persisting those would durably copy another package's rows into
 * this one. Pure + total so the "the VALUE changed" property is unit-testable without running tsc.
 *
 * @param {{ baselineFiles: Record<string, number>, ratchetFiles: PerFileGateEntry[] }} input
 * @returns {Record<string, number>}
 */
export function mergeRatchetIntoBaseline({ baselineFiles, ratchetFiles }: {
    baselineFiles: Record<string, number>;
    ratchetFiles: PerFileGateEntry[];
}): Record<string, number>;
/**
 * Pure per-file gate decision — the ONE place the policy lives, so it is unit-testable (EI-104).
 * A file is a REGRESSION when its current error count exceeds its baseline (a file absent from the
 * baseline has an implicit baseline of 0, so any new error in a fresh file is a named regression).
 * Regressions always win over improvements, preserving ratchet-only-down.
 *
 * @param {{
 *   currentByFile: Record<string, number>,
 *   baselineByFile: Record<string, number>,
 *   brokenFiles: string[],
 *   updateFlag?: boolean,
 *   changedFiles?: Set<string> | null,
 *   typeReferencedFiles?: Set<string> | null,
 *   dirtyFiles?: Set<string> | null,
 *   attributionDeclared?: boolean,
 * }} args
 * @returns {PerFileGateResult}
 */
export function decidePerFile({ currentByFile, baselineByFile, brokenFiles, updateFlag, changedFiles, typeReferencedFiles, dirtyFiles, attributionDeclared, }: {
    currentByFile: Record<string, number>;
    baselineByFile: Record<string, number>;
    brokenFiles: string[];
    updateFlag?: boolean;
    changedFiles?: Set<string> | null;
    typeReferencedFiles?: Set<string> | null;
    dirtyFiles?: Set<string> | null;
    attributionDeclared?: boolean;
}): PerFileGateResult;
/**
 * Is this file's own commit age old enough that its NEW diagnostic cannot be its own doing?
 *
 * Exported and shared so the ROW wording and the caller's `unchangedCount` (which drives the
 * footer) can never disagree about which rows are unchanged — a divergence that would print the
 * per-file explanation with the wrong count, or omit it while rows are marked UNCHANGED.
 *
 * `null` (unknown) is deliberately NOT unchanged: `lastCommitTimes` fails soft to `null`, and a
 * path inside a submodule also reads `null` from the superproject, so treating unknown as
 * "unchanged" would manufacture an exoneration out of an absence of evidence.
 *
 * @param {number | null} [commitAgeSec]
 * @returns {boolean}
 */
export function isUnchangedForAttribution(commitAgeSec?: number | null): boolean;
/**
 * Describe a clean diagnostic site without inventing its causal provenance.
 *
 * A clean file is genuinely committed, but its NEW diagnostic may still be caused by another
 * uncommitted file in its import/type graph. `tsc` reports the error site, not the edit that made
 * the site invalid, so asserting "standing red" while any other path is dirty can send a caller
 * straight into a live peer's lane. Preserve the strong warning only when the working tree gives
 * us no uncommitted alternative cause.
 *
 * THREE readings, strongest evidence first (EI-19340874432965755):
 *   1. `commitAgeSec` says THIS FILE has not moved in longer than the landing-race window — then
 *      the cause is provably not this file's own content. Most actionable, and about the file
 *      itself rather than the tree, so it wins.
 *   2. `dirtyPathCount > 0` — some other path could be the cause, but we cannot say which.
 *   3. Neither — nothing else is in flight, so the strong standing-red warning is earned.
 *
 * WHY IT MATTERS, measured: the flat "COMMITTED: a standing red that WILL red the fleet" wording
 * produced THREE work-items from three agents on 2026-08-02 and TWO were not reproducible against
 * the file named (WI-6928, EI-19332542096444388). In WI-6928 the file was unchanged since 01:21
 * with no commits since the report, so its content never varied — a peer's edit elsewhere induced
 * the error and fixing that file cleared it. Reading 1 is exactly that case, named.
 *
 * @param {PerFileGateEntry} r
 * @param {{dirtyPathCount?: number, commitAgeSec?: number | null}} [opts] `commitAgeSec` is the
 *   file's age in seconds since its last commit, or `null` when unknown. It MUST be annotated
 *   `number | null` rather than left to inference: a bare `= null` default makes TS infer the
 *   parameter as `null | undefined`, so every real (numeric) caller fails to typecheck — this
 *   file is `.mjs`, so its types come from these JSDoc tags and nothing else.
 * @returns {string}
 */
export function formatStandingRedRow(r: PerFileGateEntry, { dirtyPathCount, commitAgeSec }?: {
    dirtyPathCount?: number;
    commitAgeSec?: number | null;
}): string;
/**
 * The headline for an ATTRIBUTED failure, worded per how the changed-set was derived.
 *
 * This is a pure function purely so the wording is TESTABLE, because the wording is where
 * the bug was. `--files` means the caller NAMED the files, so "you changed" is a fact.
 * `--mine` infers them from `git status` — and this repo has ONE working tree shared by the
 * whole fleet, with every agent's edits unstaged until the next git-sync tick, so that set is
 * "dirty right now": yours AND every peer's. Claiming "YOU changed" over it is false, and it
 * is expensively false in BOTH directions — you chase a peer's error believing it is yours,
 * or your own genuine regression arrives amid peer noise under the same label and you dismiss
 * the lot as fleet drift. Filed four separate times before the wording was fixed
 * (EI-18731016038876755, which added `--files`, plus three later duplicates).
 *
 * WHY THE COUNT SPLITS (EI-23783377300333258). "YOU NAMED" is a claim about the caller's
 * ARGUMENTS, and under `--files` the reported set is deliberately WIDER than the argument:
 * cause-aware widening (EI-18756182128903253) also gates a file reached from a type one of the
 * named files exports — the "I added a required field, the fixture that constructs it broke, and
 * the fixture is not in my diff" shape. Measured: TWO paths named, NINE reported, all nine
 * labelled `file(s) YOU NAMED`. The result was correct and the widening is the whole point; only
 * the label lied. It lies expensively, because the natural reading of a false claim about your
 * arguments is "I passed the wrong --files", which sends the reader off to re-type the flag at
 * exactly the moment the gate is handing them a real finding — and re-scoping can NEVER clear a
 * type-reached file. `typeAttributed` is already carried separately for precisely this purpose
 * ("so callers/reporting can say WHY a file outside the diff still gates"), so the honest wording
 * costs one count. It defaults to 0, which reproduces the earlier wording verbatim.
 *
 * @param {{count: number, explicit: boolean, typeAttributedCount?: number}} opts
 * @returns {string}
 */
export function formatAttributionHeadline({ count, explicit, typeAttributedCount }: {
    count: number;
    explicit: boolean;
    typeAttributedCount?: number;
}): string;
/**
 * The explanation printed under a `fail-new-file` verdict, worded per how the changed-set was
 * DERIVED. The verdict itself never moves (EI-18766822535373909): a file the baseline has never
 * seen has no known-good state to drift from, so NO scoping can exonerate it. Only the remedy
 * differs.
 *
 * WHY IT BRANCHES (EI-18802204276510164). The single closing line used to read "re-run with
 * --files=<paths>" unconditionally — including for a caller who had just passed `--files`, in a
 * run that echoes `[--files]` in its own header two lines above. Prescribing the action already
 * taken reads as "I invoked it wrong", so the reader goes to this script hunting their own
 * mistake instead of to the actual next step, and it lands on precisely the agents doing the
 * right thing: scoping their check exactly, at the moment they are deciding whether their change
 * is safe to leave in the shared tree.
 *
 * @param {{explicit: boolean, liveEditCount?: number, standingCount?: number}} opts `explicit` —
 *   the changed-set came from `--files` (named by the caller) rather than `--mine` (inferred from
 *   `git status`). `liveEditCount`/`standingCount` split the new files into a peer's uncommitted
 *   live edits vs committed standing reds (EI-19278299775574199); omitting BOTH yields the full
 *   standing text, so a caller that does not supply the split is never quietly exonerated.
 * @returns {string[]} console lines, already indented.
 */
export function formatNewFileGuidance({ explicit, liveEditCount, standingCount }: {
    explicit: boolean;
    liveEditCount?: number;
    standingCount?: number;
}): string[];
/**
 * The closing lines of the SCOPED (`--files`) new-file report, for the COMMITTED population.
 *
 * WI-7153. This block used to end "…the committed one(s) above need an owner", which reads as an
 * instruction to FILE a work-item — and directly contradicts `recordStandingReds()`, called a few
 * lines later on this same population. That mechanism exists precisely BECAUSE filing on first
 * sight is wrong: these reds are dominated by self-healing (measured 2026-08-02: 4 of 5 gone in
 * 15min, unaided), so `tsc-red-sweep` deliberately waits DWELL_SEC before judging one ownerless.
 *
 * With the recording silent and the prose asking for an owner, every reader correctly concluded
 * "nobody has this, so I should file it". Two agents filed the SAME 9 paths 75 seconds apart on
 * 2026-08-02 (WI-7149 / WI-7150), at 1.9–7.1 minutes of observed life — 6–24x under the dwell —
 * which is exactly the backlog-noise outcome the hot-path/sweeper split was designed to avoid.
 *
 * The dwell is read from DWELL_SEC rather than written out, so this text cannot drift from the
 * policy it describes.
 */
export function formatStandingRedFooter({ dwellSec, unchangedCount }?: {
    dwellSec?: number | undefined;
    unchangedCount?: number | undefined;
}): string[];
/**
 * Split `newFiles` into a peer's LIVE EDITS and STANDING reds — the two populations the
 * `fail-new-file` report used to conflate (EI-19278299775574199).
 *
 * The asymmetry that makes this safe. EI-18766822535373909 established that the verdict can never
 * move, because `changedFiles` cannot prove a file is not yours: git-sync commits this tree every
 * few minutes, so your own new file stops being dirty and drops out of the changed set. That
 * argument is about a file being CLEAN — and it is exactly right. It says nothing about a file that
 * is DIRTY *right now*, which is the opposite evidence: under `--files` the caller enumerated their
 * own files, so a dirty file they did not name has a live editor who is not them.
 *
 * `dirty === undefined` (dirty set unreadable, or `--mine`, where a dirty file is already
 * `attributed` and can never reach here) is deliberately treated as STANDING. Unknown must never
 * buy an exoneration — that would be the fail-open shape this gate's whole design avoids.
 *
 * @param {PerFileGateEntry[]} newFiles
 * @returns {{liveEdits: PerFileGateEntry[], standing: PerFileGateEntry[]}}
 */
export function partitionNewFilesByLiveEdit(newFiles: PerFileGateEntry[]): {
    liveEdits: PerFileGateEntry[];
    standing: PerFileGateEntry[];
};
/**
 * EI-23768041578113385 — the live-edit split, generic over ANY `PerFileGateEntry[]` carrying
 * `dirty`. `partitionNewFilesByLiveEdit` (above) is the new-file caller and delegates here; the
 * `typeAttributed` reporter is the second. Kept as ONE primitive so the two can never disagree
 * about the rule that actually matters: `dirty !== true` — which INCLUDES `undefined`, i.e. an
 * unreadable git state — routes to `standing`. Absence of evidence is never an exoneration.
 *
 * @param {PerFileGateEntry[]} entries
 * @returns {{liveEdits: PerFileGateEntry[], standing: PerFileGateEntry[]}}
 */
export function partitionEntriesByLiveEdit(entries: PerFileGateEntry[]): {
    liveEdits: PerFileGateEntry[];
    standing: PerFileGateEntry[];
};
/**
 * Split files with unattributed TS1xxx hard-fail diagnostics (outside the caller's `--mine`/`--files` set — see
 * `decidePerFile`'s `unattributedBrokenFiles`) into a peer's LIVE EDIT (uncommitted right now)
 * vs a COMMITTED standing red — the hard-fail analog of `partitionNewFilesByLiveEdit` above
 * (EI-19321397364088260).
 *
 * Before this split, every unattributed broken file was reported with one blanket "a peer is
 * likely mid-edit" line — true for a genuinely dirty file, but false reassurance for a file that
 * is actually COMMITTED and will red the fleet at the next bare run: a reader could dismiss a
 * real standing defect as transient noise. Both the bug that added the underlying scoping
 * (EI-19321179234197157) and the near-duplicate that re-found the gap (EI-19321397364088260)
 * asked for exactly this split.
 *
 * `dirtyFiles === null` covers two cases, and both correctly route every entry to `standing`:
 * under `--mine`, `changedFiles` IS the dirty set, so anything reaching this function (outside
 * `changedFiles`) is by construction already committed; an unreadable git state (see
 * `gitChangedFiles`'s fail-soft) must never manufacture an exoneration either — "unknown is
 * never an exoneration", the same rule `partitionNewFilesByLiveEdit` applies.
 *
 * @param {string[]} unattributedBrokenFiles
 * @param {Set<string> | null} dirtyFiles
 * @returns {{liveEdits: string[], standing: string[]}}
 */
export function partitionBrokenFilesByLiveEdit(unattributedBrokenFiles: string[], dirtyFiles: Set<string> | null): {
    liveEdits: string[];
    standing: string[];
};
/**
 * The COMPILER LINES behind a new file's `+N` — the WHAT the count alone withholds (WI-6767).
 *
 * The gate holds the full tsc output and, until now, reported only `file: 0 → 1 (+1)`. Recovering
 * the message from that costs a fresh full-project compile, which on this box is ~100s under
 * contention and is exactly what the two agents who hit this could not afford: the WI-6764 filer
 * recorded that a full `tsc -p packages/operator-core` blew their shell budget TWICE, so they filed
 * a major bug without ever seeing the error; the next agent then spent ~20 minutes re-deriving it.
 * The line was sitting in a string the gate already had.
 *
 * It matters far beyond convenience, because the message is frequently the whole diagnosis. The
 * WI-6764 error read `TS2322: Type '"memory-recall-scale"' is not assignable to type
 * 'WatchdogSource'` — naming a type in a DIFFERENT file, which is the signature of a multi-file
 * change still landing (see `formatLandingRaceCaveat`). A bare `+1` cannot suggest that; the
 * message says it outright.
 *
 * Deliberately a separate projection rather than a widening of `parseTscErrors`: that function's
 * `{file, code}` shape is asserted with strict equality by `lint-tsc.test.ts` and its narrowness is
 * a documented decision (`packages/operator-core/lib/tsc-diagnostics.ts` explains why the gate
 * counts rather than carries messages). This is display-only and feeds nothing that decides a
 * verdict.
 *
 * @param {string} tscOutput - Raw compiler output.
 * @param {Iterable<string>} files - Repo-relative paths to quote lines for.
 * @param {{maxPerFile?: number, root?: string, canonicalRoot?: string}} [opts] - `maxPerFile` bounds the quote so a file with 40 errors
 *   cannot bury the guidance underneath it (the report stays readable; the count already told you
 *   the true total).
 * @returns {Map<string, string[]>} file → its diagnostic lines, in compiler order, capped.
 */
export function diagnosticLinesForFiles(tscOutput: string, files: Iterable<string>, { maxPerFile, root, canonicalRoot }?: {
    maxPerFile?: number;
    root?: string;
    canonicalRoot?: string;
}): Map<string, string[]>;
/**
 * The effective per-file quote cap: `defaultCap`, or uncapped under `--all-errors`.
 *
 * ## Why a flag rather than a bigger default (EI-19343733961745670)
 *
 * The caps exist so one pathological file cannot bury the guidance printed beneath it, and for the
 * ordinary 1–3 error case they never bind. But when they DO bind the reader is back in the hole
 * this whole feature was built to fill: the footer says `+30 more not shown`, and the only way to
 * read those 30 is the second full ~150s compile that queues behind pc-heavy. Capping by default
 * and letting the reader lift it keeps the common report readable without ever making the
 * expensive recompute the only route to a diagnostic the gate already has in hand.
 *
 * Applied at EVERY quoting site rather than only the regressed one. A flag honoured on some report
 * branches and silently ignored on others is worse than no flag: `--all-errors` that returns a
 * capped block reads as "that is all of them", and nothing in the output contradicts it.
 *
 * @param {string[] | undefined} argv - The gate's raw argv.
 * @param {number} defaultCap - The cap that applies without the flag.
 * @returns {number} `defaultCap`, or `Infinity` when `--all-errors` is present.
 */
export function diagnosticCapFromArgv(argv: string[] | undefined, defaultCap: number): number;
/**
 * The quoted-diagnostic block under ONE regressed file already present in the baseline.
 *
 * ## Why this is not simply `diagnosticLinesForFiles` again (EI-19454211066351073)
 *
 * The new-file branch (WI-6767) can quote lines and stop, because a file the baseline has never
 * seen has a baseline of 0 — every error in it is new, so any line quoted is a line you caused.
 *
 * A file at `2 → 4` is different in kind, and the difference is a trap. The baseline stores a
 * COUNT, not the errors themselves, so NOTHING in the gate knows WHICH 2 of the current 4 are new.
 * Diagnostics arrive in compiler (line) order, so quoting the first N can legitimately show only
 * pre-existing errors and never the regression at all. A reader handed three plausible errors,
 * none of which is theirs, does not discover the omission — they fix a pre-existing one and read
 * the still-red gate as flaky. That failure is worse than the silence this function replaces,
 * because it is confidently wrong rather than merely unhelpful (the same "a count delta is not
 * presence" class the containment recipe in CLAUDE.md warns about).
 *
 * So the block states its own limits: it never claims a quoted line is new, it names how many
 * pre-date the change, and it says plainly that the split is not mechanically determinable. Where
 * the baseline IS 0 the answer is unambiguous and it says THAT instead, because that is the common
 * case and the reader should not have to weigh a caveat that does not apply.
 *
 * Pure (no I/O) so the wording is unit-testable — the wording is the whole feature, mirroring
 * `formatAttributionHeadline` / `formatNewFileGuidance`.
 *
 * @param {{file: string, baseline: number, current: number, delta: number, dirty?: boolean}} row - The gate entry.
 * @param {string[]} lines - Already-capped diagnostic lines for this file (compiler order).
 * @returns {string[]} Indented lines to print beneath the row; empty when nothing was quoted.
 */
export function formatRegressedFileDiagnostics(row: {
    file: string;
    baseline: number;
    current: number;
    delta: number;
    dirty?: boolean;
}, lines: string[]): string[];
/**
 * Last commit time (epoch seconds) per path. Fail-SOFT per file: anything unreadable maps to
 * `null`, which `partitionStandingByCommitRecency` treats as NOT recent — i.e. the loud, standing
 * reading. An unreadable git state must never manufacture a "probably fine, ignore it" caveat.
 *
 * Uses `execFileSync` (argv, no shell) so a path with a space or a shell metacharacter is passed
 * verbatim instead of being re-split or interpreted.
 *
 * @param {string} root - Repo root to run git in.
 * @param {Iterable<string>} files
 * @returns {Map<string, number | null>}
 */
export function lastCommitTimes(root: string, files: Iterable<string>): Map<string, number | null>;
/**
 * Split committed new files into ones committed so recently they may be a LANDING RACE, and ones
 * settled long enough that the red is really standing (WI-6767).
 *
 * `null`/missing/future timestamps fall to `settled` — the same "unknown is never an exoneration"
 * rule `partitionNewFilesByLiveEdit` applies, and for the same reason: this caveat tells a reader
 * it is safe to wait rather than act, so it must be earned by positive evidence, never by an
 * absence of evidence.
 *
 * @param {PerFileGateEntry[]} standing - The COMMITTED subset (never a peer's live buffer).
 * @param {Map<string, number | null>} commitTimes
 * @param {number} nowSec - Current time, epoch seconds (injected so this stays pure/testable).
 * @param {number} [windowSec]
 * @returns {{recent: PerFileGateEntry[], settled: PerFileGateEntry[]}}
 */
export function partitionStandingByCommitRecency(standing: PerFileGateEntry[], commitTimes: Map<string, number | null>, nowSec: number, windowSec?: number): {
    recent: PerFileGateEntry[];
    settled: PerFileGateEntry[];
};
/**
 * The LANDING-RACE caveat — the third population the committed/uncommitted split cannot express.
 *
 * EI-19278299775574199 taught this report to separate a peer's UNCOMMITTED live edit ("don't touch
 * it") from a COMMITTED standing red ("fix it now"). That split is right and stays. But it assumes
 * `committed` means `settled`, and on this repo it does not: git-sync commits the WHOLE shared tree
 * on a schedule, so ONE logical multi-file change routinely lands across TWO ticks. Between them
 * the committed tree holds a half-landed change that typechecks as a genuine error belonging to
 * nobody.
 *
 * Measured, not hypothesised (WI-6764): commit 133317acd0 @20:25:57 landed a file emitting
 * `source: 'memory-recall-scale'`; the union that accepts that value arrived in watchdog.ts at
 * 82a0d03bef @20:33:46. For 7m49s the tree carried exactly one real type error. An agent ran this
 * gate inside that window, checked `git status` (clean), correctly concluded "committed ⇒ standing
 * red" — and filed a major bug for something that had healed itself ~1 minute earlier. Their
 * reasoning was sound; the report simply had no way to say "wait a moment first".
 *
 * Note what this does NOT do: it never moves the verdict, never suppresses a row, and never
 * downgrades the exit code. A landing race and a standing red are indistinguishable at this
 * instant, so the honest report is "still failing — and here is the one cheap check that tells you
 * which".
 *
 * @param {{recentCount: number, windowMin?: number}} opts
 * @returns {string[]} console lines, already indented; empty when nothing is recent.
 */
export function formatLandingRaceCaveat({ recentCount, windowMin }: {
    recentCount: number;
    windowMin?: number;
}): string[];
/**
 * Resolve the repository's pinned TypeScript CLI by package identity, never through the
 * ambient `node_modules/.bin/tsc` slot (EI-21107417900847684).
 *
 * The toolchain contract deliberately installs TWO compilers: `@typescript/native` owns the
 * TypeScript 7 CLI, while `typescript` names the TypeScript 6 compiler API required by TypeDoc,
 * typescript-eslint, and declaration generation. During a concurrent install the shared `.bin`
 * slot briefly resolved to the unrelated placeholder `tsc` package, so `npx tsc` exited 1 with
 * zero diagnostics and red-pinned the release gate. Resolve the native package's declared bin
 * from the root manifest instead; this is the CLI counterpart of gen-declarations.ts resolving
 * its compiler-API input by package identity.
 *
 * @param {string} root repository root
 * @returns {string} absolute path to the pinned native tsc entrypoint
 */
export function resolvePinnedTscBin(root: string): string;
/**
 * Replace only the canonical `npx tsc …` prefix with the pinned native compiler. Arbitrary
 * injected commands (the focused tests use `cat <fixture>`) remain byte-for-byte unchanged.
 *
 * @param {string} root repository root
 * @param {string} tscCommand configured command
 * @returns {string}
 */
export function resolvePinnedTscCommand(root: string, tscCommand: string): string;
/**
 * The child env for a tsc spawn: `process.env` plus `extra`, with
 * `--max-old-space-size` appended to NODE_OPTIONS.
 *
 * An existing LARGER `--max-old-space-size` is left alone — an operator who
 * pinned more must win — and a second copy is never appended (that would
 * silently take the LAST occurrence rather than erroring).
 *
 * ⚠ A SMALLER existing value is RAISED, not deferred to. This is a correction
 * (WI-37450, measured 2026-08-09): the previous rule deferred to ANY existing
 * pin, reasoning that "a constrained CI box that pinned a smaller one must win".
 * That is wrong for THIS workload and it froze the fleet gate for ~10h across 11
 * consecutive reds. The chain:
 *
 *   buildGreenCheckpointEnv (green-checkpoint.ts:3145) unconditionally sets
 *   NODE_OPTIONS = sanitizeForkNodeOptions(...), which always pins
 *   `--max-old-space-size=GREEN_CHECKPOINT_FORK_HEAP_MB` (4096) so eight
 *   concurrent TEST forks cannot each inherit the bg-host's 128 GiB heap. That
 *   env is then handed to runPostSuiteLegs, which spawns `npm run lint:tsc`
 *   with it — so the tsc child inherited a cap meant for a FORK POOL, this
 *   function deferred to it, and TSC_HEAP_MB never applied. Measured red:
 *   `Mark-Compact (reduce) 4081.5 (4104.6) -> 4060.6 (4078.6) MB`, i.e. a ~4 GB
 *   ceiling on a compile that needs 8 GB.
 *
 * Deferring BELOW what the compile provably needs is never a graceful
 * degradation — it converts "this box might be tight" into "this gate is
 * structurally unpassable", which is strictly worse and silent. The 4096 pin is
 * correct for its own purpose (a per-FORK cap) and simply is not a statement
 * about a single whole-program tsc process.
 *
 * @param {Record<string, string>} [extra]
 * @returns {Record<string, string | undefined>}
 */
export function tscChildEnv(extra?: Record<string, string>): Record<string, string | undefined>;
/**
 * EI-19341572300046923 — the repo-relative directory prefix a `tsc -p <dir>/tsconfig.json`
 * invocation actually COMPILES.
 *
 * Every per-project CLI here is a thin wrapper whose `tscCommand` is a per-project constant
 * (`lint-tsc.mjs` → `packages/operator-core/`, `lint-tsc-operator-vite.mjs` →
 * `apps/operator-vite/`, …). `--files=` is a GATE-scoping flag that never reaches tsc, so
 * naming a file OUTSIDE that project does not widen the compile — it just scopes the verdict
 * to files this run never looked at. Deriving the prefix from the command itself (rather than
 * a hand-maintained roster) means a new per-project CLI inherits the guard below for free;
 * a roster would reproduce the very "gate exists, gates nothing" defect WI-6841 documents.
 *
 * @param {string} tscCommand
 * @returns {string | null} prefix with a trailing slash, `''` for a whole-repo project, or
 *   `null` when no `-p` operand is parseable (callers must then FAIL OPEN — an unparseable
 *   command is not evidence that a file is uncovered).
 */
export function projectPrefixFromTscCommand(tscCommand: string): string | null;
/**
 * Canonicalize an explicit `--files=` set to repository-relative paths while accepting paths
 * relative to the workspace that launched the gate.
 *
 * The operator-core gate is exposed both from the repository root and as the package's own npm
 * script. npm runs a workspace script with that workspace as `cwd`, so `--files=lib/foo.ts`
 * means `packages/operator-core/lib/foo.ts` in the latter form. Existing callers also pass
 * repository-relative paths, including from a workspace cwd. Prefer a direct repository spelling
 * whenever it is already covered (or names an existing repository path), then resolve the entry
 * from `cwd` only when that candidate lands under a covered gate prefix. An unresolved direct
 * path is preserved when neither interpretation is covered, so the caller still receives the
 * normal out-of-scope diagnostic instead of a guessed green verdict.
 *
 * @param {{files: Iterable<string>, root: string, coveredPrefixes: Iterable<string>, cwd?: string, pathExists?: (path: string) => boolean}} opts
 * @returns {Set<string>}
 */
export function normalizeExplicitFilesForProject({ files, root, coveredPrefixes, cwd, pathExists, }: {
    files: Iterable<string>;
    root: string;
    coveredPrefixes: Iterable<string>;
    cwd?: string;
    pathExists?: (path: string) => boolean;
}): Set<string>;
/**
 * Split the caller's `--files=` set into the files this invocation can actually judge and the
 * ones it cannot.
 *
 * A `''` prefix (whole-repo project) covers everything.
 *
 * @param {{files: Iterable<string>, coveredPrefixes: Iterable<string>}} opts
 * @returns {{covered: string[], uncovered: string[]}}
 */
export function partitionFilesByCoverage({ files, coveredPrefixes }: {
    files: Iterable<string>;
    coveredPrefixes: Iterable<string>;
}): {
    covered: string[];
    uncovered: string[];
};
/**
 * Which typecheck gate DOES cover `file`? Discovery, not a hardcoded map: walk up to the
 * nearest `package.json` and read its `typecheck` script.
 *
 * The four per-project gates in this repo are reachable this way because each workspace's own
 * `typecheck` script points at the right one (e.g. apps/operator-vite's is
 * `node ../../scripts/lint-tsc-operator-vite.mjs`, the baseline-gated form — not a raw `tsc`).
 * So a workspace that earns a gate later is routed to automatically.
 *
 * @param {string} root Absolute repo root.
 * @param {string} file Repo-relative path.
 * @returns {{workspaceDir: string, packageName: string, standalone: boolean, command: string | null} | null}
 *   `command: null` = the owning workspace declares NO typecheck script (a real coverage gap,
 *   worth saying out loud); `null` = no owning package.json found at all. `standalone: true` =
 *   no root `workspaces` pattern names the package, so it is run with `npm --prefix`.
 */
export function suggestTypecheckGate(root: string, file: string): {
    workspaceDir: string;
    packageName: string;
    standalone: boolean;
    command: string | null;
} | null;
/**
 * WI-10003822 — the `npm` argv that runs `typecheck` inside ONE owning package.
 *
 * A STANDALONE package (a package.json that no root `workspaces` pattern names, e.g.
 * `tools/perf-test/wdio` or `papercusp-desktop`) is not an npm workspace, so
 * `npm run --workspace <dir> typecheck` answers "No workspaces found" and exits 1 having
 * checked nothing. `npm --prefix <dir> run typecheck` runs the same script there. Measured
 * 2026-09-29 on tools/perf-test/wdio: the --workspace form exits 1, the --prefix form runs
 * `tsc --noEmit` and exits 0. affected-tests' formatWorkspaceCommand makes the same split
 * (EI-22152426246970496).
 *
 * Misclassifying a real workspace as standalone is the safe direction: `--prefix` still runs
 * that package's script. Only the reverse ever fails.
 *
 * @param {string} workspaceDir Repo-relative package directory.
 * @param {boolean} standalone True when no root `workspaces` pattern covers it.
 * @returns {string[]} argv for `npm`, executed without a shell.
 */
export function workspaceTypecheckArgs(workspaceDir: string, standalone: boolean): string[];
/**
 * EI-19461218392796337 — the repo-relative prefixes ONE sibling gate module actually compiles.
 *
 * Read from the module's REAL exports, never re-derived from its source text: a static mirror of
 * a value the module already exports is exactly the drift-prone shape these gates keep getting
 * bitten by, and the whole defect this closes is a conclusion drawn from a partial view.
 *
 * Two declaration forms, in priority order:
 *  - `GATE_COVERAGE` — an explicit prefix list (or a thunk returning one), for FAN-OUT gates
 *    whose coverage is a discovered set rather than a single `-p` project.
 *  - `TSC_COMMAND` — the per-project constant the four single-project CLIs already export.
 *
 * ⚠ A `GATE_COVERAGE` THUNK MAY THROW, and that must degrade rather than crash. The fan-out gates
 * compute their coverage by WALKING THE FILESYSTEM (EI-19462776655300160), so a broken tree, a
 * permission error or an unreadable package.json raises here — on the uncovered-files ERROR path,
 * i.e. exactly when the gate is already reporting something and least able to afford an
 * unhandled throw. A throw is caught and reported as `null`, so the gate lands in `unresolved`
 * with its reason and the banner says "none FOUND": the same honest degradation as a module that
 * declares nothing. Never let it read as "this gate covers nothing", which would be a confident
 * claim derived from a failure to look.
 *
 * @param {Record<string, unknown>} mod An imported gate module.
 * @param {{onCoverageError?: (err: unknown) => void}} [opts] Notified when a `GATE_COVERAGE` thunk
 *   THREW, so the caller can say so instead of reporting the generic "exports neither" reason —
 *   which would be false here (it does export one; it failed). Both are `null`, but only one of
 *   them is the module's fault, and a reason that misattributes the cause sends the reader to the
 *   wrong file.
 * @returns {string[] | null} Prefixes (trailing slash, `''` = whole repo), or `null` when this
 *   module declares nothing parseable — which callers MUST treat as "unknown", never "covers
 *   nothing" (see `discoverSiblingTypecheckGates`).
 */
export function coveragePrefixesFromGateModule(mod: Record<string, unknown>, { onCoverageError }?: {
    onCoverageError?: (err: unknown) => void;
}): string[] | null;
/**
 * EI-19461218392796337 — every `lint:tsc*` gate declared in the root package.json, with the
 * prefixes each one really covers.
 *
 * ## Why this exists
 *
 * The uncovered-files banner used to conclude, from two things it could see (the file is outside
 * MY project; its workspace declares no `typecheck` script), a universal it could not:
 * "NO typecheck gate covers these — nothing local will ever catch a type error here." The
 * per-project SIBLING gates are a third case it never consulted, and being covered by a sibling
 * while declaring no workspace script is the NORMAL arrangement in this repo — so the sentence
 * was wrong in the common case, not a rare one.
 *
 * Measured cost of that one sentence (2026-08-03): it talked an agent out of
 * `npm run lint:tsc:operator` — which covers the file exactly — into hand-grepping a raw
 * 579-error `tsc` run, where they classified 5 type errors they had just introduced into
 * `green-checkpoint.test.ts` as a pre-existing file-wide pattern and shipped them. The file it
 * declared uncoverable implements the fleet's release gate.
 *
 * ## The discipline this function has to keep
 *
 * A wider view is still a partial view. Every gate that cannot be resolved is returned in
 * `unresolved` WITH a reason, so the banner can say "none found" instead of "none exists" — a
 * fix that replaced one confident universal with a slightly better-informed confident universal
 * would be the same defect wearing a bigger hat. Symmetrically, coverage is only ever claimed
 * from a gate's own declared prefixes, so this never routes a caller to a gate that would not in
 * fact check their file.
 *
 * Discovery, not a roster: a new `lint:tsc:*` script is picked up the moment it lands.
 *
 * @param {string} root Absolute repo root.
 * @param {{exclude?: string[]}} [opts] npm-script names to skip (e.g. the gate doing the asking).
 * @returns {Promise<{gates: {npmScript: string, prefixes: string[]}[], unresolved: {npmScript: string, reason: string}[], rosterReadable: boolean}>}
 *   `rosterReadable: false` means the root package.json itself could not be read — the roster is
 *   entirely unknown, so NO absence claim of any strength is available.
 */
export function discoverSiblingTypecheckGates(root: string, { exclude }?: {
    exclude?: string[];
}): Promise<{
    gates: {
        npmScript: string;
        prefixes: string[];
    }[];
    unresolved: {
        npmScript: string;
        reason: string;
    }[];
    rosterReadable: boolean;
}>;
/**
 * The MOST SPECIFIC sibling gate covering `file`, or `null`.
 *
 * Longest matching prefix wins, so a file under `libs/papercusp/packages/orchestrator/` routes to
 * `lint:tsc:orchestrator` rather than the broader `lint:tsc:papercusp-libs` fan-out that also
 * contains it — the narrower gate is the faster, more attributable answer.
 *
 * @param {{npmScript: string, prefixes: string[]}[]} gates
 * @param {string} file Repo-relative path.
 * @returns {{npmScript: string, prefix: string} | null}
 */
export function gateCoveringFile(gates: {
    npmScript: string;
    prefixes: string[];
}[], file: string): {
    npmScript: string;
    prefix: string;
} | null;
/**
 * Build the verified commands that can judge an out-of-project file set.
 *
 * A workspace `typecheck` script is the owning workspace's whole-project gate, while a
 * discovered sibling `lint:tsc*` gate is an exact-file gate. The distinction matters: appending
 * `--files` to an arbitrary workspace script is not safe, but a sibling lint gate explicitly
 * accepts that selector. Files with neither route stay in `unknown`; callers MUST NOT execute a
 * partial route set and then claim the original request was covered.
 *
 * @param {{files: Iterable<string>, suggestions: Map<string, ReturnType<typeof suggestTypecheckGate>>, siblingGates?: {npmScript: string, prefixes: string[]}[]}} opts
 * @returns {{routes: {key: string, workspaceDir?: string, standalone?: boolean, npmScript?: string, files: string[], scoped: boolean, command: string, args: string[]}[], unknown: string[]}}
 */
export function collectAutoTypecheckRoutes({ files, suggestions, siblingGates }: {
    files: Iterable<string>;
    suggestions: Map<string, ReturnType<typeof suggestTypecheckGate>>;
    siblingGates?: {
        npmScript: string;
        prefixes: string[];
    }[];
}): {
    routes: {
        key: string;
        workspaceDir?: string;
        standalone?: boolean;
        npmScript?: string;
        files: string[];
        scoped: boolean;
        command: string;
        args: string[];
    }[];
    unknown: string[];
};
/**
 * Execute an already-validated set of owning gates and return the first non-zero status.
 *
 * The environment marker prevents a malformed workspace script from recursively routing back
 * into this gate forever. A routed child owns the actual verdict; this caller only aggregates its
 * exit status. `execFile` is injectable for unit tests and never receives a shell command string.
 *
 * @param {{root: string, routes: {args: string[]}[], execFile?: Function}} opts
 * @returns {number}
 */
export function runAutoTypecheckRoutes({ root, routes, execFile }: {
    root: string;
    routes: {
        args: string[];
    }[];
    execFile?: Function;
}): number;
/**
 * The banner for `--files=` entries this run cannot judge.
 *
 * Written to be impossible to mistake for a pass: the failure this closes is that a scoped run
 * naming only out-of-project files printed a clean verdict having typechecked NONE of them —
 * indistinguishable from a real green, which is the same silent-zero shape `build:typecheck`
 * already refuses (it will not report a clean run that checked zero files).
 *
 * @param {{label: string, uncovered: string[], suggestions: Map<string, ReturnType<typeof suggestTypecheckGate>>, fatal: boolean, autoRoute?: boolean, siblingGates?: {npmScript: string, prefixes: string[]}[], unresolvedGates?: {npmScript: string, reason: string}[], rosterReadable?: boolean}} opts
 * @returns {string[]} console lines.
 */
export function formatUncoveredFilesBanner({ label, uncovered, suggestions, fatal, autoRoute, siblingGates, unresolvedGates, rosterReadable, }: {
    label: string;
    uncovered: string[];
    suggestions: Map<string, ReturnType<typeof suggestTypecheckGate>>;
    fatal: boolean;
    autoRoute?: boolean;
    siblingGates?: {
        npmScript: string;
        prefixes: string[];
    }[];
    unresolvedGates?: {
        npmScript: string;
        reason: string;
    }[];
    rosterReadable?: boolean;
}): string[];
/**
 * The `.d.mts` companions of the `.mjs` modules declared in `tsconfig.declarations.json`
 * (WI-6394's naming convention: `foo.mjs` -> `foo.d.mts`, same directory) — the hidden
 * dependency `coalesceWatermarkFor` folds in below (EI-19483243844876537).
 *
 * Deliberately duplicated rather than imported from `scripts/gen-declarations.ts`: that
 * module calls `generate()`/`check()` UNCONDITIONALLY at module load — no entrypoint guard —
 * so importing it here would regenerate declarations as a side effect of every gate call,
 * including read-only ones on a shared, concurrently-edited checkout. `generated-
 * declarations.test.ts` already duplicates `BANNER_MARKER` for the identical reason; this
 * follows the same precedent rather than introducing a new one.
 *
 * By default, read/parse errors return an empty array for the supplementary freshness
 * signal. Publishing callers use strict mode so unreadable enrollment fails the preflight.
 *
 * @param {string} root
 * @param {{ strict?: boolean }} [options] - Publishing callers must reject unreadable enrollment.
 * @returns {string[]} repo-relative `.d.mts` paths
 */
export function declarationFilesFromConfig(root: string, { strict }?: {
    strict?: boolean;
}): string[];
/**
 * The freshness watermark this run may safely replay a COALESCED compile from
 * (epoch seconds), or `null` to opt out of sharing entirely.
 *
 * ## Why a watermark makes sharing safe where a tree token could not
 *
 * A full compile that STARTED at S read every file as of S. So its diagnostics are a
 * true answer about file F iff F has not changed since S. The dominant caller here is
 * an agent that edited F and immediately asked "did I break it?" — for that caller the
 * only thing that can invalidate a shared result is a change to *its own* files, never
 * a peer's edit somewhere else in the tree.
 *
 * pc-heavy's tree-state token asks the whole-tree question instead, which is sound but
 * far stricter, and on this repo strictly worse than useless: the token moves ~every 18s
 * against a ~170s compile, so two callers seconds apart never share a key and every one
 * of them pays a full compile (measured 2026-08-02; 3-5 byte-identical operator-core
 * compiles observed running at once, three separate times that day). Passing the
 * watermark lets pc-heavy drop the token and answer the narrower question exactly.
 *
 * ## The two opt-outs, and why each is a correctness requirement
 *
 * - **Unscoped run** (no `--files`): a bare `npm run lint:tsc` (CI, green-checkpoint)
 *   renders a verdict over EVERY file, so its watermark would have to be "no file in the
 *   project has changed since S" — which is the tree-token question again, and would be
 *   wrong to approximate with anything narrower. Return null: run fresh, share nothing.
 * - **`--update`**: the ratchet WRITES `.tsc-baseline.json`, lowering a file's recorded
 *   count. Ratcheting off a replayed compile would persist a number nobody re-measured
 *   from this tree state, and a too-low baseline is the failure mode the whole gate
 *   exists to prevent (EI-487 / WI-4488: an under-report that ratchets in reads as clean
 *   for days). A run that WRITES the baseline measures it itself.
 *
 * ## KNOWN NARROWING — name every file you edited, not just the one you are asking about
 *
 * The watermark is computed from the files you NAMED, so the guarantee it buys is exactly
 * "the shared compile postdates edits to the files this run renders a verdict on". If you
 * edit G and then ask only about F, a replay may come from a compile that predates the G
 * edit — and since F imports G, F's reported count could be pre-G. The tree token used to
 * cover that incidentally (any edit anywhere busted the key), so this is a real narrowing
 * and not merely a restatement.
 *
 * It is accepted rather than closed for the GENERAL case, because every way of closing it
 * re-widens the watermark to "any uncommitted edit in the tree", which on a checkout ~16
 * agents are saving into is `now` on every call — i.e. exactly the churn that made
 * coalescing impossible in the first place (~1 change/18s vs a ~170s compile). The
 * mitigation is the instruction the gate already gives everywhere: pass `--files=` listing
 * what you actually changed. That is also what makes the VERDICT trustworthy here, so the
 * two align.
 *
 * ONE instance of "G edited, F asked about" IS closed, narrowly, because it doesn't share
 * the churn problem above: generated `.d.mts` declarations (EI-19483243844876537). They are
 * a small, fixed, enumerable set (`tsconfig.declarations.json`'s `files`, currently ~11) that
 * only moves on an explicit `npm run gen:declarations` run — not on every peer's save — so
 * folding them in doesn't reintroduce the per-18s churn the general fix was rejected for. See
 * `declarationFilesFromConfig` below.
 *
 * @param {{ root: string, files: Set<string> | null, updateFlag: boolean }} args
 * @returns {number | null} epoch seconds, or null to disable coalescing for this run
 */
export function coalesceWatermarkFor({ root, files, updateFlag }: {
    root: string;
    files: Set<string> | null;
    updateFlag: boolean;
}): number | null;
/**
 * Build the argv handed to pc-heavy for one compiler pass.
 *
 * `--files` scopes the GATE verdict, not TypeScript itself, so it is deliberately
 * absent from {@link executableTscCommand}. Put the stable `lint:tsc` sentinel after
 * `sh -c`'s command string for EVERY compile — `sh` consumes it as `$0`, while
 * pc-heavy uses it to recognize the finite-cgroup typecheck shape even though the
 * real compiler command is inside one shell-string argument. A scoped invocation
 * also carries the stable `--files` marker as `$1`, which lets release-gate
 * materialization route only those calls through the focused lane. Neither sentinel
 * includes the caller's real comma-separated file list, preserving coalescing.
 */
export function pcHeavyCompileArgv(executableTscCommand: any, scoped: any): string[];
/**
 * Which scope the caller asked this gate to judge — reported on the completion marker so a
 * reader can tell a whole-project verdict from one scoped to a handful of files. `--update`
 * leads because it MUTATES the baseline rather than judging against it.
 *
 * EI-19444246913245434 — `--update` used to be reported ALONE, swallowing any scope flag beside
 * it, so `--files=X --update` announced a whole-project `scope=update` for a run that judged (and,
 * before the same fix, wrote) only X. The label was the more visible of the two disagreeing
 * facts, which is what made the silent no-op read as a successful ratchet. A composite label
 * cannot drift from the run's actual scope because both halves are read from the same argv.
 *
 * @param {string[]} argv
 * @returns {'update'|'update:files'|'update:mine'|'files'|'mine'|'all'}
 */
export function lintTscScopeFromArgv(argv: string[]): "update" | "update:files" | "update:mine" | "files" | "mine" | "all";
/**
 * The terminal completion marker (EI-19395061642732083). Pure so it is unit-testable —
 * the `process.on('exit')` hook that prints it is not.
 *
 * `status` is derived from the exit code the gate actually exited with, never from a
 * separately-tracked verdict variable that could drift out of sync with it.
 *
 * `nothingTypechecked` is the ONE deliberate exception, and it is a REFINEMENT of the
 * failure, never the verdict itself (EI-20072775668558359). The exit code alone genuinely
 * cannot separate the two ways this gate exits 1:
 *
 *   - a real REGRESSION — files were compiled and some sit above baseline;
 *   - NOTHING WAS TYPECHECKED — every `--files=` path lies outside this project, so the
 *     gate compiled none of them and has no verdict to give.
 *
 * Reporting the second as `status=regressed` is a false alarm in the machine-readable
 * field, which is the one a caller greps. It fails in both directions: read literally it
 * sends someone hunting a type error that does not exist, and once learned as "regressed
 * here can mean nothing ran" it corrodes the token that must stay trustworthy when a
 * regression IS real. Most edits in this repo are NOT in operator-core, so a `--files=` run
 * naming out-of-scope paths is a common shape, not an exotic one.
 *
 * The drift the original note warns about is still excluded: `nothingTypechecked` cannot
 * make a FAILING run look clean (a truthy value is only consulted when `code !== 0`, and
 * `code === 0` still reports `clean` unconditionally), and it is set at the same site that
 * computes `fatal` and calls `process.exit(1)` — so the flag and the exit cannot disagree
 * without that one branch being wrong about itself. Pinned by
 * packages/operator-core/lib/lint-tsc.test.ts.
 *
 * ## EI-20712456514085524 — PARTIAL coverage is the third outcome, and it exited 0 as `clean`
 *
 * `nothingTypechecked` above covers the ALL-uncovered case. The mixed case — some named files
 * inside the project, some outside — took the other branch: the banner warns on stderr, the
 * covered verdict is genuinely true, so the gate exits 0 and the marker read `status=clean`.
 * That is the same false-coverage failure the all-uncovered branch exists to prevent, arriving
 * through the door left open beside it. `--files=a,b,c,d` naming two operator-core files and two
 * `packages/agent-mcp` ones printed `exit=0 status=clean`, and an agent who names four files and
 * reads `clean` concludes four files compiled. Two never did.
 *
 * The exit CODE is deliberately unchanged (0): the covered files really were judged, and making
 * the mixed case fatal would red the common, legitimate "check my edit across two packages" run.
 * What changes is the machine-readable token, because that is what is actually misread:
 * `status=partial filesUnchecked=N`. `partial` is chosen over `clean-partial` so that the
 * established consumer idiom — a substring `grep 'status=clean'` — CANNOT match a run that left
 * files unchecked. A run with full coverage still reports exactly `status=clean`, so this is
 * additive for every caller that was already honest.
 *
 * ## EI-21467670625776948 — a PREFLIGHT abort is the fourth exit-1 shape, and it read `regressed`
 *
 * The `gen:declarations` preflight compiles the WHOLE declarations project, so ANY agent's
 * in-flight file anywhere in the repo can abort it — for a caller whose own files are clean and
 * were never measured. The exit hook then printed `status=regressed`: a verdict about the
 * caller's work, emitted when the truthful statement is "nothing of yours was judged". Same
 * repair as `nothingTypechecked`/`partial`: refine the machine token (`preflight-failed`),
 * keep the exit code. Scoped to exit 1 exactly like `nothingTypechecked` — an abnormal code
 * stays `error(N)` — and `preflightFailed` wins over `nothingTypechecked` because it is the
 * more specific claim about WHY nothing was typechecked (in practice they are mutually
 * exclusive: the coverage branch exits before the preflight runs).
 *
 * ## EI-22405627533381152 — `filesRoutedAway` names the fifth shape, and it is NOT a status
 *
 * A MIXED `--files` set now delegates its out-of-project files to the owning gate and keeps
 * compiling its own (see `runTscBaselineGate`'s coverage branch). That run's verdict is still
 * this gate's own — `clean` or `regressed` — so `status` must NOT change; what would otherwise
 * be lost is that part of the answer came from a delegate. `filesRoutedAway=N` is therefore an
 * additive FIELD beside `filesUnchecked`, never a status value: a caller grepping
 * `status=clean` still matches a fully-covered run, which is the property EI-20712456514085524
 * established and this must not break. `routed`/`routed-failed` remain reserved for the case
 * where this gate had NO verdict of its own and handed the whole request over.
 *
 * @param {{ label: string, scope: string, code: number, nothingTypechecked?: boolean, preflightFailed?: boolean, concurrentEditInconclusive?: boolean, filesUnchecked?: number, filesRoutedAway?: number, routed?: boolean, runStartIso?: string | null, headSha?: string | null }} input
 * @returns {string}
 */
export function formatLintTscResultMarker({ label, scope, code, nothingTypechecked, preflightFailed, concurrentEditInconclusive, filesUnchecked, filesRoutedAway, routed, runStartIso, headSha, }: {
    label: string;
    scope: string;
    code: number;
    nothingTypechecked?: boolean;
    preflightFailed?: boolean;
    concurrentEditInconclusive?: boolean;
    filesUnchecked?: number;
    filesRoutedAway?: number;
    routed?: boolean;
    runStartIso?: string | null;
    headSha?: string | null;
}): string;
/**
 * The pre-run stamp (EI-19323399466378077): what this run is about to judge, printed BEFORE the
 * compile so a killed/hung run still leaves it on disk. Mirrors scripts/test-files.mjs's
 * `TEST_FILE_PROVENANCE` banner (same item, same fix shape, two files) — the resolved file set
 * lives here (a caller `| tail -N`ing the terminal line does not need it repeated there), while
 * the run-start time + HEAD are ALSO appended to the terminal `LINT_TSC_RESULT` line above.
 *
 * @param {{ label: string, runStartIso: string, headSha: string|null, scope: string, files: string[]|null }} input
 * @returns {string}
 */
export function formatLintTscRunStamp({ label, runStartIso, headSha, scope, files }: {
    label: string;
    runStartIso: string;
    headSha: string | null;
    scope: string;
    files: string[] | null;
}): string;
/**
 * Persist the same run stamp to disk (EI-19421388108187854).
 *
 * The stamp above is printed to STDOUT, which means it exists only in whatever
 * terminal scrollback the run happened to land in. Nothing downstream can ask
 * "is the standing tsc verdict still current?", because the answer — when the
 * last run started and which files it covered — was never recorded anywhere a
 * later process can read.
 *
 * That gap is what makes the typecheck→test→fix-the-test loop bank a stale
 * verdict: the last edit in that loop is almost always a TEST file, edited
 * AFTER the typecheck ran, and the green suite that follows carries zero type
 * information (vitest transforms via esbuild and never typechecks). The agent
 * ends holding a fresh green signal that is silent on types beside a stale
 * clean one that is not, and reads the pair as agreement.
 *
 * Written at run START (like the stamp), so a killed or hung run still leaves a
 * marker — a verdict that never finished is exactly the kind that must not be
 * quoted as clean. Best-effort by construction: a marker is an advisory input
 * to a nudge, so failing to write one must never fail the typecheck itself.
 *
 * @param {{ root: string, label: string, runStartIso: string, headSha: string|null, scope: string, files: string[]|null, sessionId?: string|null }} input
 * @returns {boolean} true iff the marker was written
 */
export function writeLintTscRunMarker({ root, label, runStartIso, headSha, scope, files, sessionId, }: {
    root: string;
    label: string;
    runStartIso: string;
    headSha: string | null;
    scope: string;
    files: string[] | null;
    sessionId?: string | null;
}): boolean;
/** Short HEAD sha at call time, or null when git cannot answer (never a fabricated value). */
export function gitHeadShaForLintTsc(root: any): string | null;
/**
 * Run the full CLI gate for one project and `process.exit(...)` with its verdict — the shared
 * `main()` every per-project CLI (lint-tsc.mjs, lint-tsc-operator-vite.mjs, …) delegates to.
 *
 * @param {RunTscBaselineGateOptions} options
 */
export function runTscBaselineGate({ root, tscCommand, preTscCommand, baselineFile, label, argv, countField, foreignBaselines, }: RunTscBaselineGateOptions): Promise<void>;
/**
 * A module-resolution diagnostic that may be explained by a package being half-written during
 * a concurrent npm install. This is intentionally narrower than every TS2307/TS7016: one
 * missing module can be a real code defect, while a burst that names a directly-declared package
 * absent from node_modules is the distinctive shared-tree failure this guard can substantiate.
 *
 * @typedef {object} MissingModuleDiagnostic
 * @property {string | null} file
 * @property {'TS7016' | 'TS2307'} code
 * @property {string} module
 */
/**
 * Two matching diagnostics are the minimum signal. A single TS7016 is common for an intentionally
 * untyped package; two or more diagnostics for a package that the dependency doctor cannot find on
 * disk is the measured concurrent-install shape (EI-19366483607548056).
 */
export const MID_INSTALL_DIAGNOSTIC_MIN: 2;
/**
 * Per-file quote cap for a REGRESSED file, deliberately larger than the new-file cap of 3.
 *
 * A new file's every error is new, so three lines are a fair sample of one homogeneous set. A
 * regressed file's lines are a MIXTURE of pre-existing and new, and the reader has to find the new
 * ones among them — so cutting at 3 is far likelier to hide the very line the report exists to
 * surface. Ten bounds a pathological file without routinely truncating the ordinary 1–3 error case.
 */
export const REGRESSION_DIAGNOSTIC_MAX_PER_FILE: 10;
/** Opt out of the per-file quote caps for THIS run. */
export const ALL_ERRORS_FLAG: "--all-errors";
/**
 * How recently a file must have been committed for its red to be treated as possibly still landing.
 *
 * 20 minutes, sized from the mechanism rather than taste: git-sync commits this tree on a schedule
 * of a few minutes, and the observed WI-6764 split was 7m49s between the two halves of one logical
 * change. 20min covers that with margin while staying far below the hours a genuine standing red
 * survives. It only ever adds a caveat — never removes one — so erring long is the safe direction.
 */
export const LANDING_RACE_WINDOW_SEC: number;
/**
 * V8 old-space ceiling (MB) for the `tsc` CHILD, applied by `tscChildEnv` below.
 *
 * WHY THIS EXISTS (WI-37503, measured 2026-08-09): every gate here shells out to
 * `npx tsc … --incremental false`, which builds the WHOLE program in memory —
 * 9013 files for operator-core. With no `--max-old-space-size` the child got
 * node's DEFAULT old-space (~4GB) and OOM'd mid-compile:
 *   FATAL ERROR: Ineffective mark-compacts near heap limit … heap out of memory
 *   Mark-Compact (reduce) 4086.9 (4109.7) -> 4068.3 (4086.9) MB
 * sitting exactly on the ceiling. This is a SIZE limit, not host pressure — the
 * box had ~80GB free at the time — so it recurs and worsens as the tree grows.
 *
 * It is applied HERE, at the one place every gate actually spawns, rather than
 * baked into each `TSC_COMMAND` string: there are four of those constants
 * (operator-core / operator / operator-vite / orchestrator) and a fifth would be
 * added without the number, which is precisely the drift this module's shared
 * policy half already exists to prevent.
 *
 * ⚠ It is NOT free: concurrent agents each run their own compile (WI-7191
 * measured 5 at once), so this is a per-process CEILING, not a reservation —
 * raise it deliberately. pc-heavy's coalescing window is what keeps the
 * concurrent count low enough for this to be safe.
 *
 * @type {number}
 */
export const TSC_HEAP_MB: number;
/** Where the standing-verdict marker lives, relative to the repo root. */
export const LINT_TSC_RUN_MARKER_REL: ".papercusp/scratch/lint-tsc-last-run.json";
/**
 * One diagnostic parsed out of tsc's output.
 */
export type TscErrorEntry = {
    /**
     * - null when the diagnostic carries no file (unattributable).
     */
    file: string | null;
    /**
     * - The `TSnnnn` code.
     */
    code: string;
};
/**
 * One file's standing against its baseline.
 */
export type PerFileGateEntry = {
    file: string;
    baseline: number;
    current: number;
    /**
     * - `current - baseline`; positive is a regression.
     */
    delta: number;
    /**
     * - Set when the dirty set could be read: the file is uncommitted in
     * the shared working tree, i.e. a peer is very likely mid-edit (EI-19278299775574199). On a
     * regression this is populated only for an unscoped/bare run, where a dirty row is otherwise
     * reported as an unhedged failure. `undefined` means UNKNOWN, never "clean" — see
     * `partitionNewFilesByLiveEdit`.
     */
    dirty?: boolean | undefined;
};
/**
 * A baseline owned by ANOTHER package, whose recorded counts this gate inherits for
 * files under `prefix` rather than assuming an implicit 0 (EI-18649014117371738).
 */
export type ForeignBaselineSource = {
    /**
     * - Repo-relative path prefix of the files the other package owns.
     */
    prefix: string;
    /**
     * - That package's own per-file baseline map.
     */
    files: Record<string, number>;
    label?: string | undefined;
};
/**
 * The verdict vocabulary. `fail-new-file` is split out of `peerDrift` so `--mine` can
 * never greenwash a brand-new file: absence from the git-status changed set does not
 * prove a new file isn't yours, because git-sync auto-commits this shared tree every few
 * minutes (EI-18766822535373909).
 */
export type PerFileGateVerdict = "fail-syntax" | "fail-regressed" | "fail-attributed" | "fail-new-file" | "ok-peer-drift" | "ok-ratchet" | "ok-below" | "ok";
/**
 * A cross-package baseline named by PATH, for `runTscBaselineGate`'s options. Distinct
 * from `ForeignBaselineSource`, which carries the already-LOADED `files` map — this is
 * what a CLI passes in before the gate reads it off disk.
 */
export type ForeignBaselineRef = {
    /**
     * - Repo-relative path prefix the owning package covers.
     */
    prefix: string;
    /**
     * - Absolute path to that package's `.tsc-baseline.json`.
     */
    baselineFile: string;
    label?: string | undefined;
};
/**
 * Options for the shared CLI entry point.
 *
 * ⚠ Written as a `@typedef` with `@property` tags, NOT as an inline `@param {{ … }}`
 * object type. TypeScript's JSDoc TYPE parser does not accept `//` comments inside a type
 * expression: this options bag was previously documented inline with a `//` gloss per
 * field, and everything from the first comment-only continuation line onward — including
 * `foreignBaselines` — was silently dropped from the emitted type while still reading as
 * fully documented. `@property` descriptions are prose by design, so the annotation and
 * the explanation can coexist without one eating the other.
 */
export type RunTscBaselineGateOptions = {
    /**
     * - cwd the tscCommand runs from (repo root).
     */
    root: string;
    /**
     * - e.g. 'npx tsc -p apps/foo/tsconfig.json --noEmit --incremental false'.
     */
    tscCommand: string;
    /**
     * - Optional generated-input preflight. The standard
     * declaration generator publishes only explicitly selected modules on a scoped run.
     */
    preTscCommand?: string | null | undefined;
    /**
     * - Absolute path to this project's `.tsc-baseline.json`.
     */
    baselineFile: string;
    /**
     * - Human label for console output, e.g. 'operator-core'.
     */
    label: string;
    /**
     * - `process.argv.slice(2)`.
     */
    argv: string[];
    /**
     * - Baseline JSON field the derived total is written to on
     * `--update` (default 'errorCount'; operator-core keeps its legacy 'operatorCoreErrorCount'
     * name for back-compat with existing tooling).
     */
    countField?: string | undefined;
    /**
     * - Cross-package files this gate
     * MEASURES but does not OWN: a file under `prefix` that is absent from this gate's
     * baseline inherits the owning package's recorded count instead of an implicit 0. See
     * `effectiveBaselineByFile` (EI-18649014117371738).
     */
    foreignBaselines?: ForeignBaselineRef[] | undefined;
};
/**
 * The full decision for one run.
 */
export type PerFileGateResult = {
    verdict: PerFileGateVerdict;
    regressions: PerFileGateEntry[];
    improvements: PerFileGateEntry[];
    attributed?: PerFileGateEntry[] | undefined;
    /**
     * - Subset of `attributed` NOT in the caller's
     * changed-file set, attributed instead because the file or its compiler diagnostic references
     * an exported type/interface one of the changed files also exports (EI-18756182128903253's
     * cause-aware widening).
     */
    typeAttributed?: PerFileGateEntry[] | undefined;
    peerDrift?: PerFileGateEntry[] | undefined;
    /**
     * - Regressions in files ABSENT from the baseline.
     */
    newFiles?: PerFileGateEntry[] | undefined;
    total: number;
    baselineTotal: number;
    /**
     * - FULL replacement map, written only by
     * a BARE `--update` (no `--mine`/`--files`). Never set on a scoped run — see `ratchetFiles`.
     */
    newBaselineByFile?: Record<string, number> | undefined;
    /**
     * - EI-19444246913245434. The caller's OWN improved
     * files on a SCOPED `--update`, to be lowered individually via `mergeRatchetIntoBaseline`.
     * Deliberately a payload rather than a verdict: a ratchet is an EFFECT, and modelling it as a
     * mutually-exclusive verdict is what let `ok-peer-drift` silently swallow it. Carried on any
     * non-failing verdict, so restoring the write costs the existing reporting nothing.
     */
    ratchetFiles?: PerFileGateEntry[] | undefined;
    brokenFiles?: string[] | undefined;
    /**
     * - Files with TS1xxx hard-fail diagnostics OUTSIDE the caller's
     * `changedFiles` set (EI-19321179234197157). Never gates the verdict — reported so the caller
     * knows tsc's counts for other files may be under/over-reported while these stay broken — but a
     * TS1xxx diagnostic in a file the caller did not name must not fail a `--mine`/`--files`-scoped run,
     * mirroring how an unattributed TYPE-error regression is `peerDrift`, not a gate failure.
     */
    unattributedBrokenFiles?: string[] | undefined;
};
/**
 * A module-resolution diagnostic that may be explained by a package being half-written during
 * a concurrent npm install. This is intentionally narrower than every TS2307/TS7016: one
 * missing module can be a real code defect, while a burst that names a directly-declared package
 * absent from node_modules is the distinctive shared-tree failure this guard can substantiate.
 */
export type MissingModuleDiagnostic = {
    file: string | null;
    code: "TS7016" | "TS2307";
    module: string;
};
