#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-vacuous-negative-assertions.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-vacuous-negative-assertions.mjs and regenerate.
/**
 * DRIFTED gates: a prose literal that exists nowhere emittable, while a long fragment of
 * it IS in the source — the guard is pinned to that string's OLD wording.
 * ORPHANED reports only: nothing resembling the literal survives, or the literal is not
 * prose (a value pin, a shape guard, fixture-composed output).
 *
 * @typedef {'DRIFTED' | 'ORPHANED'} VacuousVerdict
 */
/**
 * A negative assertion with a static literal argument, as extracted from a test file.
 *
 * @typedef {object} NegativeAssertion
 * @property {number} line - 1-indexed line of the assertion in the test file.
 * @property {string} kind - Rendered matcher form, e.g. `not.toMatch(/…/)`.
 * @property {string} lit - The static string the assertion pins.
 * @property {string} span - The matched assertion text, used to exclude self-references.
 */
/**
 * One judged assertion that did not survive the gate.
 *
 * @typedef {object} VacuousFinding
 * @property {string} file
 * @property {number} line
 * @property {string} kind
 * @property {string} lit
 * @property {VacuousVerdict} verdict
 * @property {string | null} fragment - The reworded fragment the source still carries, or null when nothing is close.
 */
/**
 * Answers "does the non-test corpus contain this string". Injected so the unit tests can
 * drive a synthetic corpus.
 *
 * @typedef {(needle: string) => boolean} IncludesFn
 */
/**
 * The GATE is narrowed to PROSE — multi-word wording with no embedded values. That is
 * where this class actually bites (banners, prompt text, advice strings: copy that gets
 * reworded often, and carries negative guards precisely because a bad phrasing already
 * caused an incident once), and it is the shape that CANNOT be produced by interpolating
 * a value, so its absence is decisive.
 *
 * The non-prose population is dominated by legitimate guards this must not fail:
 * value pins (`SKIP_FROMREPO="${SKIP_FROMREPO:-0}"` — the default must not be 0), shape
 * guards (`kill "$PORT_LOCK_KEEPER_PID"` — stop.sh must not force-kill the keeper), and
 * fixture-composed output (`(subpath "/p")`). Every one of those was a live finding on
 * the first sweep of this repo, and every one is a *good* assertion. They stay visible
 * under --report; they do not gate.
 *
 * @param {string} lit
 * @returns {boolean}
 */
export function proseShaped(lit: string): boolean;
/**
 * "Looks like it names emitted output" — deliberately narrowed to the banner-marker
 * case ONLY, not the ticket's full "prose-shaped OR banner marker" predicate. A first
 * pass with the OR'd prose branch (≥3 words, mostly letters, no digit) returned 245
 * findings across 74 files on this repo's real prompt corpus — dominated by CLI-usage
 * examples (`harness-features list <your-slug>`, a curl/jq invocation) that are
 * legitimately prose-shaped by that measure but are USAGE TEMPLATES, not quoted
 * emitted output, and blueprint prompts are full of them by design. A report nobody
 * can act on trains the same "ignore the alarm" reflex CLAUDE.md's own load-average /
 * false-alarm sections warn about. The banner-marker signal alone is what the
 * motivating instance actually was (`⚠ quiet-cut EXCLUDED`), every genuinely-emitted
 * banner in this codebase carries one (the `⚠`/`✓`/`✗`/`✅` convention is used
 * pervasively per CLAUDE.md's own pipeline-state examples), and a marked backtick span
 * is a shell command/URL/path essentially never. Widening back to prose-without-marker
 * is a real option later, but needs its own noise-reduction pass (reject shell-shaped
 * spans: `/`, `<`, `$`, `|`, leading CLI verbs) — scoped out of this ticket's landing.
 *
 * @param {string} lit
 * @returns {boolean}
 */
export function looksLikeEmittedOutput(lit: string): boolean;
/**
 * @typedef {object} DocLiteral
 * @property {number} line
 * @property {string} lit
 */
/**
 * Single-backtick inline-code spans in a markdown file, fenced ``` code blocks blanked
 * out first (their backticks are not inline-code delimiters, and their contents are
 * verbatim command/output examples this lint is not scoped to judge).
 *
 * @param {string} text
 * @returns {DocLiteral[]}
 */
export function extractDocLiterals(text: string): DocLiteral[];
/**
 * Judge one prompt file's backticked literals against the code corpus. Mirrors
 * `judgeFile`'s DRIFTED/ORPHANED split: DRIFTED when a long fragment of the literal IS
 * in the corpus (the guarded string was reworded, not removed — the live incident's
 * shape); ORPHANED when nothing resembling it survives.
 *
 * @param {{ file: string; text: string; includes: IncludesFn }} args
 * @returns {{ considered: number; findings: VacuousFinding[] }}
 */
export function judgeDocFile({ file, text, includes }: {
    file: string;
    text: string;
    includes: IncludesFn;
}): {
    considered: number;
    findings: VacuousFinding[];
};
/**
 * The plain string a regex source encodes, or null when it uses real regex power
 * (`\d`, `\s`, a character class, alternation, a quantifier). Only a pattern that is
 * a plain literal can be judged by "does this string exist anywhere".
 *
 * @param {string} src - The regex source (no delimiters, no flags).
 * @returns {string | null}
 */
export function regexSourceToLiteral(src: string): string | null;
/**
 * Negative assertions with a static literal argument, in source order.
 *
 * @param {string} text - Full source of one test file.
 * @returns {NegativeAssertion[]}
 */
export function extractNegativeLiterals(text: string): NegativeAssertion[];
/**
 * A maximal contiguous fragment of `lit` present in `corpus`, long enough to prove the
 * guarded string still exists in a reworded form — plus what it leaves uncovered.
 *
 * Windows of exactly the threshold length are probed and the first hit is then GROWN
 * outward. Growing matters: the residue (what the source does NOT have) is the whole
 * discriminator below, and an un-grown threshold-length window reports residue the
 * source actually contains.
 *
 * `residue` is a fixed PAIR — [before the fragment, after it]. The implementation builds
 * it as an array literal, which infers as `string[]`; the tuple only survives because it
 * is written here.
 *
 * @param {string} lit
 * @param {IncludesFn} includes
 * @returns {{ fragment: string; residue: [string, string] } | null}
 */
export function driftFragment(lit: string, includes: IncludesFn): {
    fragment: string;
    residue: [string, string];
} | null;
/**
 * Build a one-pass substring matcher for a finite set of probes.
 *
 * `String.prototype.includes` is excellent for an isolated lookup, but this guard
 * performs thousands of lookups against one ~200 MB corpus. Calling it once per
 * assertion turns an absent literal into another full-corpus scan. The matcher below
 * uses an Aho–Corasick trie: it scans the corpus once, records which trie states were
 * reached, then propagates those hits through failure links so every requested literal
 * gets the same exact substring semantics as `corpus.includes(literal)`.
 *
 * The returned function keeps a native `includes` fallback for probes discovered while
 * growing a drift fragment. Main preloads every fixed-size window, so the fallback is
 * limited to the few matched fragments that need maximal growth; the public helper also
 * remains useful for callers with an intentionally open-ended query set.
 *
 * @param {string} corpus
 * @param {Iterable<string>} queries
 * @returns {IncludesFn}
 */
export function createCorpusIncludes(corpus: string, queries: Iterable<string>): IncludesFn;
/**
 * Judge one test file's negative assertions. `includes` answers "does the non-test
 * corpus contain this string" — injected so the unit tests can drive a synthetic corpus.
 *
 * @param {{ file: string; text: string; includes: IncludesFn }} args
 * @returns {{ considered: number; findings: VacuousFinding[] }}
 */
export function judgeFile({ file, text, includes }: {
    file: string;
    text: string;
    includes: IncludesFn;
}): {
    considered: number;
    findings: VacuousFinding[];
};
/**
 * A prompt (a `blueprints/**\/prompts/*.md` agent brief) told every release-fixer agent
 * to grep a reply for `⚠ quiet-cut EXCLUDED` — a banner `checkpoint-run.ts` had already
 * stopped emitting. Front-end 1 above only ever scans TEST files for assertions and
 * PROSE files as (excluded) corpus; nothing ever scans a prompt/doc's OWN quoted text
 * against what the code can actually emit. This is that second front-end, over the
 * SAME corpus (`corpusFiles` in main(), passed in as `includes`) and the SAME
 * DRIFTED/ORPHANED verdict + suppression pragma as front-end 1 — not a new system.
 *
 * DELIBERATELY SCOPED to blueprint prompts only (`DOC_PROMPT_RE` below), not the whole
 * doc corpus (agent-insights/CLAUDE.md/READMEs): those narrate INCIDENTS on purpose,
 * routinely quoting a banner/recipe that is no longer correct as the point of the
 * example ("this file used to prescribe exactly that... has been removed" is a real
 * CLAUDE.md sentence). Scanning that corpus would flag the teaching device itself.
 * A blueprint prompt has no such genre — every line is a live instruction to an agent
 * about to act on it — so absence there is a straight defect, never a narrative device.
 * Widening scope (agent-insights docs, with the pragma covering the deliberate-history
 * case) is a natural follow-up once this is proven quiet here.
 *
 * REPORT-ONLY BY DESIGN (never flips the exit code) — see main()'s doc section. A
 * substring/fragment heuristic over free-form prose is inherently noisier than the
 * structural regex front-end 1 parses out of test source, and a new GATING check with
 * unproven false-positive behavior is exactly the class of mistake CLAUDE.md's own
 * "Adding a tool" prompt-weight-budget story warns about (a scoped quick-check the repo
 * SHOULD have caught it with — this is that quick-check for prompt drift, not yet a gate).
 */
export const DOC_PROMPT_RE: RegExp;
/**
 * DRIFTED gates: a prose literal that exists nowhere emittable, while a long fragment of
 * it IS in the source — the guard is pinned to that string's OLD wording.
 * ORPHANED reports only: nothing resembling the literal survives, or the literal is not
 * prose (a value pin, a shape guard, fixture-composed output).
 */
export type VacuousVerdict = "DRIFTED" | "ORPHANED";
/**
 * A negative assertion with a static literal argument, as extracted from a test file.
 */
export type NegativeAssertion = {
    /**
     * - 1-indexed line of the assertion in the test file.
     */
    line: number;
    /**
     * - Rendered matcher form, e.g. `not.toMatch(/…/)`.
     */
    kind: string;
    /**
     * - The static string the assertion pins.
     */
    lit: string;
    /**
     * - The matched assertion text, used to exclude self-references.
     */
    span: string;
};
/**
 * One judged assertion that did not survive the gate.
 */
export type VacuousFinding = {
    file: string;
    line: number;
    kind: string;
    lit: string;
    verdict: VacuousVerdict;
    /**
     * - The reworded fragment the source still carries, or null when nothing is close.
     */
    fragment: string | null;
};
/**
 * Answers "does the non-test corpus contain this string". Injected so the unit tests can
 * drive a synthetic corpus.
 */
export type IncludesFn = (needle: string) => boolean;
export type DocLiteral = {
    line: number;
    lit: string;
};
