#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-js-syntax.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-js-syntax.mjs and regenerate.
/**
 * The pure detector: resolves to `null` when the file parses, else a
 * `{ line, reason }` describing node's own parse error.
 *
 * Reads the exit CODE, never the output text. `node --check f 2>&1 | head -3`
 * reports HEAD's status (0) and reads exactly like a pass — the mistake made
 * while first measuring this class.
 */
export function findJsSyntaxError(absPath: any): Promise<any>;
/**
 * Resolves to `null` when the module has no undeclared-write, else
 * `{ line, name }` naming the binding that will throw on load.
 *
 * Returns `null` for a file that does not PARSE: that is the `--check` leg's
 * class, and double-reporting one break as two would misstate the offender count.
 *
 * @param {string} absPath
 * @param {string | null} [source] Pass the module's source text directly to skip
 *   the disk read (callers that already hold it, e.g. tests). Defaults to
 *   reading `absPath` — bare `= null` alone left the generated declaration
 *   inferring `source` as `null`-only, rejecting every real string caller.
 */
export function findJsLoadError(absPath: string, source?: string | null): Promise<{
    line: any;
    name: any;
} | null>;
export function isJsSyntaxScanned(f: any): any;
/**
 * The load leg builds a full AST + scope graph; `node --check` only parses and
 * retains nothing. That difference is not academic here: the tree contains a
 * 44.7 MB vendored bundle (papercusp-desktop/src-tauri/env-sidecars/staging/serve.mjs),
 * and scope-analysing it — 32 files wide, via availableParallelism() — exhausted the
 * default 4 GB heap and killed the guard with a V8 OOM.
 *
 * 1 MB is chosen against the measured distribution, not guessed: the largest
 * hand-edited `.mjs` in the tree is apps/operator/scripts/psu-launcher.mjs at 0.54 MB,
 * and only 3 files exceed 0.5 MB. Everything this leg exists to protect stays in
 * scope; what falls out is vendored bundles, which are not hand-edited and cannot
 * acquire a glued-keyword typo from an interrupted refactor.
 *
 * Files over the cap are still fully covered by the `node --check` leg, and are
 * REPORTED as skipped rather than folded silently into the ✓ — an unmeasured file
 * quietly counted as clean is the exact defect this whole check was added to fix.
 */
export const LOAD_CHECK_MAX_BYTES: 1000000;
