#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-migration-forward-compat.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-migration-forward-compat.mjs and regenerate.
export function violationsFor(sqlText: any): {
    id: string;
    re: RegExp;
    why: string;
}[];
/**
 * True when `file` is a migration this guard ENFORCES on — i.e. `NNN-*.sql`
 * with NNN >= ENFORCE_FROM. Exported so the nudge applies the same cutoff and
 * never nags about a historical migration that can no longer be edited.
 */
export function isEnforcedMigrationFile(file: any): boolean;
/**
 * True when a filename is an armed migration or a parked migration artifact.
 * The main lint uses this instead of `endsWith('.sql')` so a DRAFT can reach the
 * dependency check while destructive-DDL enforcement remains limited to armed SQL.
 *
 * @param {string} file
 * @returns {boolean}
 */
export function isMigrationArtifactFile(file: string): boolean;
/** True when `file` is an enforced migration that has not been armed yet. */
export function isDraftMigrationFile(file: any): boolean;
/** The sidecar filename for a migration, keyed on its EFFECTIVE `.sql` name. */
export function sidecarNameFor(effectiveFile: any): string;
/** The effective `.sql` name for a migration artifact (strips any parked suffix). */
export function effectiveMigrationName(file: any): any;
/** sha256 of a migration's bytes — the same value schema_migrations records. */
export function migrationSha256(text: any): string;
/**
 * Resolve whether `sha` is a commit in this repo that is an ANCESTOR of HEAD.
 * Returns true / false / null, where **null means "could not determine"** and the
 * caller must fail closed on it. Never throws.
 *
 * @param {{ exec?: (file: string, args: string[], options?: Record<string, unknown>) => unknown, cwd?: string }} [options]
 * @returns {(sha: string) => boolean | null}
 */
export function makeAncestorResolver({ exec, cwd }?: {
    exec?: (file: string, args: string[], options?: Record<string, unknown>) => unknown;
    cwd?: string;
}): (sha: string) => boolean | null;
/**
 * Decide whether a sidecar acknowledges its migration. PURE — every input is
 * passed in, so the whole refusal matrix is testable without touching the tree.
 *
 * Returns { present, honored, refusals }. `present:false` means no sidecar exists
 * (not a refusal); `honored:false` with refusals means one exists and was REJECTED.
 *
 * @param {{
 *   artifactFile?: string,
 *   effectiveFile?: string,
 *   sidecarText?: string | null,
 *   migrationSha?: string | null,
 *   isAncestorOfHead?: (sha: string) => boolean | null,
 *   now?: Date,
 * }} [input]
 * @returns {{ present: boolean, honored: boolean, refusals: string[] }}
 */
export function evaluateForwardCompatSidecar({ artifactFile, effectiveFile, sidecarText, migrationSha, isAncestorOfHead, now, }?: {
    artifactFile?: string;
    effectiveFile?: string;
    sidecarText?: string | null;
    migrationSha?: string | null;
    isAncestorOfHead?: (sha: string) => boolean | null;
    now?: Date;
}): {
    present: boolean;
    honored: boolean;
    refusals: string[];
};
/**
 * Read + evaluate the sidecar for one migration artifact on disk.
 *
 * @param {string} directory
 * @param {string} artifactFile
 * @param {{
 *   migrationText?: string,
 *   isAncestorOfHead?: (sha: string) => boolean | null,
 *   now?: Date,
 *   readFile?: (path: string, encoding: string) => string,
 * }} [options]
 * @returns {{ present: boolean, honored: boolean, refusals: string[], sidecarFile: string }}
 */
export function readForwardCompatSidecar(directory: string, artifactFile: string, { migrationText, isAncestorOfHead, now, readFile }?: {
    migrationText?: string;
    isAncestorOfHead?: (sha: string) => boolean | null;
    now?: Date;
    readFile?: (path: string, encoding: string) => string;
}): {
    present: boolean;
    honored: boolean;
    refusals: string[];
    sidecarFile: string;
};
/**
 * Extract column identifiers introduced by an ALTER TABLE ADD COLUMN statement.
 * Comments are masked first, while SQL string bodies remain visible so a real
 * EXECUTE statement inside a DO block is still checked. This intentionally covers
 * the narrow, mechanically decidable class behind EI-20208711931756460.
 */
export function addedColumnsFor(sqlText: any): string[];
/**
 * Extract what the ALTER TABLE statements target, split into the tables we RESOLVED and
 * the targets we could NOT resolve.
 *
 * The split is the safety property. `tables` is only sound as an EXCLUSION filter when it
 * is COMPLETE, and a dynamic target means it is not — so callers must consult `unresolved`
 * rather than assuming a non-empty list describes every altered table.
 */
export function alterTargetsFor(sqlText: any): {
    tables: any[];
    unresolved: any[];
};
export function alteredTablesFor(sqlText: any): any[];
/**
 * Read a path found by a directory scan after re-stat'ing it.
 *
 * A parked migration is an in-flight authoring artifact: reservation and rename
 * can remove it after readdirSync returned its name. Re-stat narrows the normal
 * race window, while the read catch closes the final stat/read window. Callers
 * choose whether ENOENT is tolerable; other errors always remain fatal.
 *
 * @param {string} filePath
 * @param {{ allowMissing?: boolean, readFile?: Function, stat?: Function }} options
 * @returns {string|null}
 */
export function readScannedFile(filePath: string, { allowMissing, readFile, stat }?: {
    allowMissing?: boolean;
    readFile?: Function;
    stat?: Function;
}): string | null;
/**
 * Read the names returned by a directory scan, tolerating only explicitly
 * allowed files that disappear while the scan is in flight.
 *
 * @param {string} directory
 * @param {string[]} files
 * @param {{ allowMissing?: boolean|((file: string) => boolean), readFile?: Function, stat?: Function }} options
 * @returns {Array<{file: string, text: string}>}
 */
export function readScannedFiles(directory: string, files: string[], { allowMissing, readFile, stat }?: {
    allowMissing?: boolean | ((file: string) => boolean);
    readFile?: Function;
    stat?: Function;
}): Array<{
    file: string;
    text: string;
}>;
/**
 * Find source files that already reference columns introduced by a parked
 * migration. `sourceFiles` is injectable so unit tests can prove the detector on
 * small fixtures without writing into the shared checkout.
 *
 * `unresolvedTargets` is non-empty when an ALTER TABLE target could not be parsed (a dynamic
 * `%I`/`%s`). The table filter is SKIPPED in that case — see the reasoning at the call site —
 * so the caller can explain why its result set is column-name-only and broad.
 *
 * @param {string} sqlText
 * @param {Array<{file: string, text: string}>} sourceFiles
 * @returns {{ columns: string[], references: Array<{column: string, file: string, line: number}>, unresolvedTargets: string[] }}
 */
export function findDraftColumnReferences(sqlText: string, sourceFiles?: Array<{
    file: string;
    text: string;
}>): {
    columns: string[];
    references: Array<{
        column: string;
        file: string;
        line: number;
    }>;
    unresolvedTargets: string[];
};
/**
 * Repo-relative form of the scanned directory, EXPORTED so the repo-wide invariant
 * guard that routes this lint (MIGRATION_SQL_DIR in scripts/affected-tests.mjs) can be
 * asserted against the directory this lint actually reads, rather than a hand-copied
 * duplicate of it. Mirrors SCHEMA_FILE_REL in check-partial-index-alignment.mjs, and
 * exists for the same reason: if the two silently disagree the guard stops firing and
 * the run stays green while no longer checking anything. (WI-9573)
 */
export const SQL_DIR_REL: "libs/papercusp/libs/db/sql";
/**
 * A migration is authored in a parked filename before it is armed. The runner
 * intentionally ignores these suffixes, but the authoring-time dependency guard
 * must not: this is the exact window in which code can start naming a column that
 * the shared database does not have yet.
 */
export const PARKED_SUFFIXES: string[];
/**
 * Production source roots searched for references to columns added by parked
 * migrations. Keep this explicit: scanning generated output, docs, or dependency
 * trees would turn a cheap authoring guard into a noisy repository grep.
 *
 * Exported so the affected-tests router can mirror the exact domain and attach the
 * guard when either the parked migration OR a source consumer changes.
 */
export const SOURCE_ROOTS: string[];
/**
 * Migrations are immutable once applied, so historical files can never be fixed.
 * Enforce from the first migration authored after this guard landed.
 */
export const ENFORCE_FROM: 693;
/**
 * The acknowledgment token, EXPORTED for the same reason SQL_DIR_REL is: the
 * authoring-time PostToolUse nudge
 * (apps/operator/scripts/hooks/cc/posttooluse-migration-forward-compat-nudge.mjs)
 * must apply THIS marker, not a hand-copied duplicate. A second copy that
 * silently disagreed would let the nudge stay quiet on a file the gate then
 * reds on — reintroducing the exact discover-it-hours-later cost the nudge
 * exists to remove.
 *
 * NOTE for anyone tempted to seed a placeholder ack into new migrations: this
 * matches ANY non-whitespace after the colon, so `-- FORWARD-COMPAT: TODO` and
 * `-- FORWARD-COMPAT: <why>` both SATISFY it. A seeded placeholder would
 * therefore rubber-stamp every migration and silence the guard permanently.
 * scripts/next-migration.mjs deliberately emits prose that does NOT match;
 * `forward-compat-authoring-nudge.test.ts` pins that.
 */
export const ACK_MARKER: RegExp;
/**
 * ---------------------------------------------------------------------------
 * Typed, candidate-bound acknowledgement sidecar for an APPLIED migration.
 * Ruling: stable-candidate-related-gate-2026-08-23#D-092. Root cause:
 * EI-21539300249506308.
 * ---------------------------------------------------------------------------
 * WHY THIS EXISTS. Before this, a migration that crossed into immutability
 * carrying destructive DDL had NO satisfiable route through this lint:
 *
 *   - add `-- FORWARD-COMPAT:` inline  -> migration-immutability-guard (WI-38352)
 *     refuses any write to a file already recorded in schema_migrations;
 *   - rename to `.sql.PENDING-CODE-DEPLOY` -> the scan below maps parked names
 *     back to their effective `.sql` name, so parking changes nothing (measured:
 *     the rename was executed, the guard stayed rc=1, and it was reverted);
 *   - raise ENFORCE_FROM past it -> that constant is a one-time historical
 *     watermark, not a rolling cutoff; moving it silently un-enforces every
 *     migration in between.
 *
 * Two guards, each individually correct, were jointly unsatisfiable, and this
 * lint is gate-blocking: the intersection was a permanent red that froze every
 * agent's deploys. ENFORCE_FROM already handles migrations that were immutable
 * BEFORE the guard landed; nothing handled one that becomes immutable AFTER it,
 * which is every future occurrence.
 *
 * THE SHAPE OF THE FIX. The acknowledgement moves OUT of the immutable file into
 * a sidecar that sits beside it. That is the whole trick: the sidecar is mutable,
 * so every refusal it can produce is ACTIONABLE — which is what makes it safe to
 * fail closed here, where failing closed on the migration itself produced the
 * un-actionable deadlock above.
 *
 * It is deliberately far stricter than the inline `-- FORWARD-COMPAT:` marker it
 * sits beside (that marker accepts any non-whitespace, `TODO` included). Every
 * field is typed and machine-checkable, and ANY defect refuses the whole sidecar
 * rather than honouring a partially-valid one.
 *
 *   {
 *     "kind": "migration-forward-compat-ack",
 *     "version": 1,
 *     "migration": "975-remove-owned-trigger-legacy-arbiter.sql",
 *     "appliedSha256": "<sha256 of that file's exact bytes>",
 *     "requiresDeployedCommit": "<40-hex commit containing the compatible writer>",
 *     "requiresDeployedNote": "what that commit changed, in one line",
 *     "rationale": "why the deployed release tolerates this DDL",
 *     "workItem": "EI-21539300249506308",
 *     "reviewBy": "YYYY-MM-DD",
 *     "postDeploy": "remove-sidecar" | "renew-review"
 *   }
 *
 * The two bindings that carry the weight:
 *   - appliedSha256 pins the acknowledgement to EXACT BYTES. schema_migrations
 *     stores sha256 of the applied file, and immutability means the file on disk
 *     still IS those bytes — so recomputing the hash here verifies the ledger
 *     binding offline, with no database dependency in a lint that runs inside the
 *     gate. Edit the migration and the sidecar stops applying to it.
 *   - requiresDeployedCommit pins it to a CANDIDATE. The sidecar is honoured only
 *     in a tree that actually contains the compatible writer, so it cannot travel
 *     backwards to a checkout where the DDL really would break the live release.
 *
 * On "unapplied/editable": a sidecar is refused outright for a `.DRAFT` or
 * `.PENDING-CODE-DEPLOY` artifact. Those are editable by construction, so their
 * author must use the inline marker. Armed-and-immutable is the only case this
 * exists for, and the immutability guard is what enforces the other half.
 */
export const SIDECAR_SUFFIX: ".forward-compat.json";
export const SIDECAR_KIND: "migration-forward-compat-ack";
export const SIDECAR_VERSION: 1;
/** Exact permitted key set. An unknown key refuses the sidecar (no free-form fields). */
export const SIDECAR_KEYS: readonly string[];
