#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-lockfile-census.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-lockfile-census.mjs and regenerate.
/**
 * Count the entries in an npm lockfile that describe SHIPPED code, and the entries that
 * describe build tooling. `dev: true` is npm's own resolved verdict, written by the
 * installer that walked the manifest — not a guess from a dependency name.
 *
 * WHY THIS EXISTS — A COUNT WHOSE UNITS WERE WRONG SENT THE CENSUS TO THE WRONG FILE
 *
 * The first version of this file counted `packages` ENTRIES and called the total "deps",
 * then baselined `papercusp-desktop/package-lock.json` at "12 deps ... it is SHIPPED —
 * this is the highest-priority row here." Measured 2026-09-05, every one of those 12
 * entries is `dev: true` (`@tauri-apps/cli` plus its 11 platform binaries, 11 of which
 * are also `optional`), so the shipped-dependency count of that lockfile is ZERO. The
 * row was real, its number was real, and the conclusion drawn from it — gate this next —
 * was work that would have bought nothing.
 *
 * So the bucket is DERIVED from this measurement rather than curated: an npm lockfile
 * that resolves no runtime dependency ships nothing, and the lockfile itself says so.
 * A dependency promoted out of `devDependencies` moves that file back into the
 * classification set on the next run, with no list for anyone to remember to update.
 */
export function npmDepCounts(lockJson: any): {
    shipped: number;
    devOnly: number;
    total: number;
    rootName: any;
};
/** `[[package]]` blocks in a Cargo.lock. Cargo has no dev/runtime split at this layer. */
export function cargoDepCounts(lockText: any): {
    shipped: any;
    devOnly: number;
    total: any;
};
/**
 * Measure every census row. The IO half of the derivation above; `classifyCensus` stays
 * pure and takes the result. A row that cannot be measured is recorded as `null` rather
 * than as zero, because "we could not read it" and "it ships nothing" must not collapse
 * into the same bucket — that collapse is the whole defect this measurement repairs.
 */
export function measureLockfiles(root: any, lockfiles: any): Map<any, any>;
/**
 * Walk the tree for lockfiles. Returns repo-relative POSIX paths, sorted.
 *
 * Symlinked directories are NOT followed. That is deliberate and is the opposite of the
 * `find -L` advice for cross-checkout searches: here a symlink out of the repo would
 * import a SIBLING hive's lockfiles into this repo's census, which is a false positive,
 * not a missed row. The population is bounded by the repo, so a positive control on the
 * result (see censusOrThrow) is what protects against an under-read.
 */
export function walkLockfiles(root: any, { pruned, names }?: {
    pruned?: Set<string> | undefined;
    names?: Map<string, string> | undefined;
}): string[];
/**
 * The census plus its own falsifier. A walk that returns nothing has either been pointed
 * at the wrong root or had its prune set widened until it excludes the whole tree; both
 * produce an EMPTY offender list, which is indistinguishable from a fully-classified one.
 * The repo's own root package-lock.json is the positive control: it is the one lockfile
 * whose presence is structurally guaranteed.
 *
 * @param {string} root
 * @param {{ pruned?: Set<string>, names?: Map<string,string> }} [options] forwarded to walkLockfiles
 */
export function censusOrThrow(root: string, options?: {
    pruned?: Set<string>;
    names?: Map<string, string>;
}): string[];
/**
 * Directories whose npm dependencies are hoisted into the root lockfile.
 *
 * Read back from the root lockfile's `packages` map rather than asserted: every root
 * workspace member appears there as its own directory key. Throws on an unreadable or
 * shapeless root lockfile, because a silent {} makes every nested lock look UNSUBSUMED —
 * turning a parse failure into a page of fabricated blind spots.
 */
export function rootWorkspaceDirs(rootLockJson: any): Set<any>;
/**
 * Classify every census row into exactly one bucket. Pure: all IO is the caller's.
 *
 * @param {object} input
 * @param {string[]} input.lockfiles          repo-relative census rows
 * @param {Set<string>} input.workspaceDirs   directories hoisted into the root lockfile
 * @param {Map<string,{shipped:number,devOnly:number,total:number,rootName?:string|null}|null>} [input.measurements]
 *   per-path output of measureLockfiles. A null VALUE means UNMEASURABLE, never zero — the
 *   distinction the build-only classifier turns on. `rootName` is npm-only; cargoDepCounts
 *   has no root package node to name.
 * @param {Map<string,string>} [input.covered]
 * @param {Map<string,string>} [input.notShipped]
 * @param {Map<string,{deps:number,reason:string}>} [input.uncovered]
 */
export function classifyCensus({ lockfiles, workspaceDirs, measurements, covered, notShipped, uncovered, }: {
    lockfiles: string[];
    workspaceDirs: Set<string>;
    measurements?: Map<string, {
        shipped: number;
        devOnly: number;
        total: number;
        rootName?: string | null;
    } | null> | undefined;
    covered?: Map<string, string> | undefined;
    notShipped?: Map<string, string> | undefined;
    uncovered?: Map<string, {
        deps: number;
        reason: string;
    }> | undefined;
}): {
    rows: ({
        path: string;
        ecosystem: string;
        bucket: string;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note: string | undefined;
        deps?: undefined;
    } | {
        path: string;
        ecosystem: string;
        bucket: string;
        deps: number;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note: string;
    } | {
        path: string;
        ecosystem: string;
        bucket: string;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note?: undefined;
        deps?: undefined;
    })[];
    offenders: ({
        path: string;
        ecosystem: string;
        bucket: string;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note: string | undefined;
        deps?: undefined;
    } | {
        path: string;
        ecosystem: string;
        bucket: string;
        deps: number;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note: string;
    } | {
        path: string;
        ecosystem: string;
        bucket: string;
        measured: {
            shipped: number;
            devOnly: number;
            total: number;
            rootName?: string | null;
        } | null;
        note?: undefined;
        deps?: undefined;
    })[];
    stale: {
        path: any;
        source: string | Map<string, string> | Map<string, {
            deps: number;
            reason: string;
        }>;
    }[];
    byBucket: {};
    total: number;
};
/** Lockfiles the SBOM should inventory: everything that ships and is not vestigial. */
export function sbomSubjects(rows: any): any;
/**
 * Emit a CycloneDX inventory of the shipped lockfiles via syft.
 *
 * syft is a dev-box tool, not a pipeline dependency, so its ABSENCE must refuse loudly:
 * an SBOM step that silently skips when the binary is missing produces no file and a
 * green exit, which is the same "measured nothing" reading this whole guard is built to
 * prevent. The gate legs above never touch syft, so the gate stays runnable without it.
 */
export function emitSbom(subjects: any, outPath: any, { root, syft, measurements }?: {
    root?: string | undefined;
    syft?: string | undefined;
    measurements?: Map<any, any> | undefined;
}): {
    subject: any;
    components: any;
    catalogued: any;
}[];
/**
 * Dependency components in a CycloneDX document, excluding the two components that are
 * present whether or not the cataloger read anything: the synthetic `type: 'file'` node
 * syft emits for the scanned path, and the subject lockfile's own root package.
 *
 * This distinction is the entire reason the previous `components === 0` check could not
 * fire. Measured 2026-09-05 against `papercusp-desktop/package-lock.json`, syft
 * catalogued exactly those two components and no dependency at all — a 2, not a 0, so
 * the guard passed and reported an inventory containing none of the file's packages.
 * A threshold placed below the value that "catalogued nothing" actually produces is not
 * a weak guard; it is an unfalsifiable one.
 *
 * @param {any} bom
 * @param {string} subject
 * @param {string} [root]
 * @param {string|null} [rootPackageName] the subject lockfile's own root package name, from
 *   `measureLockfiles`. Typed explicitly because the `= null` default alone generates the
 *   parameter as `null`, which makes every real call site a type error.
 */
export function countCataloguedDependencies(bom: any, subject: string, root?: string, rootPackageName?: string | null): any;
/**
 * The POSITIVE control on the inventory: two independent readings of the same lockfile
 * must agree. `measured.shipped` is this file's own parse of the lockfile; `catalogued`
 * is what syft's cataloger produced from it. A cataloger that silently declined the file
 * makes the second number collapse while the first stays intact, which is the only way
 * to tell "this artifact genuinely has few dependencies" from "nothing read it".
 *
 * syft excludes npm `dev` dependencies, which is why the comparison is against
 * `measured.shipped` and not the entry total. Calibrated 2026-09-05 across every shipped
 * subject: docs-viewer 509 shipped / 509 catalogued, Cargo 615 / 615, root 2469 / 2481
 * (the +12 are workspace package nodes, which the root lockfile does not count as
 * dependencies). Catalogued runs at or just above shipped, never below, so a SHORTFALL —
 * and only a shortfall — is signal. The comparison is deliberately one-sided: an excess
 * is a naming difference between two catalogers, while a deficit can only mean one of
 * them declined to read something.
 */
export function assertSbomCoverage(subject: any, catalogued: any, measured: any): void;
/**
 * `--sbom` takes a PATH OPERAND, and a missing one must REFUSE rather than resolve to
 * `undefined` and skip the emit block.
 *
 * MEASURED 2026-09-05, and the reason this function exists as its own export: the npm
 * script `lint:lockfile-census:sbom` was `check-lockfile-census.mjs --strict --sbom` with
 * nothing after the flag. `argv[sbomIdx + 1]` was `undefined`, the `if (sbomOut)` block
 * never ran, and the script printed the plain census and EXITED 0 — no syft invocation,
 * no assertSbomCoverage positive control, no file, and no line saying any of that was
 * skipped. A script whose entire name is `:sbom` was a silent duplicate of the one
 * without the suffix.
 *
 * That is this guard's own thesis in its cheapest possible form. Every instrument aimed
 * at the SCRIPT reported green because the script WAS green: `emitSbom` works,
 * `assertSbomCoverage` is a real positive control, the unit tests pass. The defect was one
 * absent word in a package.json string, and nothing that tested a FUNCTION could see it.
 * Hence both halves of the repair: refuse here, and pin the INVOCATION in the guard test.
 *
 * A flag-shaped operand (`--sbom --strict`) is refused for the same reason — silently
 * writing an SBOM to a file named `--strict` is not a better outcome than refusing.
 */
export function parseSbomOut(argv: any): any;
export const ROOT: string;
/** Lockfile basenames that pin a resolved dependency graph, by ecosystem. */
export const LOCKFILE_ECOSYSTEMS: Map<string, string>;
/** Directories that never contain a lockfile we ship or audit. */
export const PRUNED_DIRS: Set<string>;
/**
 * Lockfiles an advisory gate ACTUALLY scans, and the gate that scans each. Keep this
 * keyed by the gate's own exported scope wherever the gate exports one, so widening the
 * gate widens the census automatically instead of requiring two edits.
 */
export const COVERED_LOCKFILES: Map<string, string>;
/**
 * Lockfiles that do NOT describe a shipped artifact. Each states WHY — the judgment the
 * derivation cannot make. A path here that no longer exists is reported as stale so the
 * list shrinks with the tree instead of accumulating.
 */
export const NOT_SHIPPED_LOCKFILES: Map<string, string>;
/**
 * Lockfiles that DO describe shipped or potentially-shipped code and are NOT covered by
 * any advisory gate. This is acknowledged debt, and it is SHRINK-ONLY: an entry leaves
 * when a gate starts scanning the lockfile, and a NEW uncovered lockfile is a hard
 * failure rather than a quiet append. `deps` is the measured graph size at the time of
 * baselining, so the cost of the gap is legible without re-measuring.
 */
/** @type {Map<string, { deps: number; reason: string }>} */
export const UNCOVERED_BASELINE: Map<string, {
    deps: number;
    reason: string;
}>;
