#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-prompt-projections.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-prompt-projections.mjs and regenerate.
/**
 * Compare the canonical prompt with every committed generated projection.
 *
 * The read function is injectable so tests can prove the detector is
 * falsifiable without mutating this shared checkout. The returned summaries
 * intentionally expose hashes and byte counts, never prompt contents.
 */
export function comparePromptProjections({ root, sourcePath, projectionPaths, read, }?: {
    root?: string | undefined;
    sourcePath?: string | undefined;
    projectionPaths?: readonly string[] | undefined;
    read?: typeof readFileSync | undefined;
}): {
    ok: boolean;
    source: {
        path: any;
        exists: boolean;
        bytes: number | null;
        sha256: string | null;
        errorCode: string | null;
    };
    projections: {
        path: any;
        exists: boolean;
        bytes: number | null;
        sha256: string | null;
        errorCode: string | null;
    }[];
    mismatches: {
        path: any;
        reason: string;
    }[];
};
/** Compare every maintained source/projection group used by the CLI guard. */
export function compareAllPromptProjections({ root, groups, read, }?: {
    root?: string | undefined;
    groups?: readonly (Readonly<{
        sourcePath: "libs/papercusp/packages/harness/blueprints/base/prompts/su.md";
        projectionPaths: readonly string[];
    }> | Readonly<{
        sourcePath: "apps/operator/prompts/pot-instances/papercup-pot.su.md";
        projectionPaths: readonly string[];
    }>)[] | undefined;
    read?: typeof readFileSync | undefined;
}): {
    ok: boolean;
    groups: {
        ok: boolean;
        source: {
            path: any;
            exists: boolean;
            bytes: number | null;
            sha256: string | null;
            errorCode: string | null;
        };
        projections: {
            path: any;
            exists: boolean;
            bytes: number | null;
            sha256: string | null;
            errorCode: string | null;
        }[];
        mismatches: {
            path: any;
            reason: string;
        }[];
    }[];
    mismatches: {
        path: any;
        reason: string;
        sourcePath: any;
    }[];
};
/**
 * Refresh stale tracked projections with an atomic same-directory rename.
 *
 * Read every source before writing anything so one missing source cannot leave
 * a partially refreshed projection set. Already-current targets are untouched.
 */
export function writePromptProjections({ root, groups, read, write, rename, unlink, mkdir, }?: {
    root?: string | undefined;
    groups?: readonly (Readonly<{
        sourcePath: "libs/papercusp/packages/harness/blueprints/base/prompts/su.md";
        projectionPaths: readonly string[];
    }> | Readonly<{
        sourcePath: "apps/operator/prompts/pot-instances/papercup-pot.su.md";
        projectionPaths: readonly string[];
    }>)[] | undefined;
    read?: typeof readFileSync | undefined;
    write?: typeof writeFileSync | undefined;
    rename?: typeof renameSync | undefined;
    unlink?: typeof unlinkSync | undefined;
    mkdir?: typeof mkdirSync | undefined;
}): string[];
/** The single authored base persona that owns the generated bytes. */
export const CANONICAL_PROMPT_PATH: "libs/papercusp/packages/harness/blueprints/base/prompts/su.md";
/**
 * Committed generated projections that must match the canonical source.
 *
 * The desktop primary sidecar under src-tauri/sidecar is intentionally not
 * required here: it is ignored build output and is absent in clean checkpoint
 * trees. The same now holds for apps/operator/dist-sidecar/ — it was untracked
 * and gitignored on 2026-09-02 (WI-2141120), so its su.md projection exists
 * only in a tree that has run the bundle build and is absent in the
 * green-checkpoint checkout; requiring it there reads as 'missing-projection'
 * on every candidate. The desktop staging projection is tracked and is the
 * durable artifact.
 */
export const GENERATED_PROMPT_PATHS: readonly string[];
/** Papercusp's authored pot-specific SU override and its tracked desktop copy. */
export const INSTANCE_PROMPT_SOURCE_PATH: "apps/operator/prompts/pot-instances/papercup-pot.su.md";
export const INSTANCE_PROMPT_PROJECTION_PATHS: readonly string[];
/** Every authored source whose tracked desktop projection must stay byte-identical. */
export const PROMPT_PROJECTION_GROUPS: readonly (Readonly<{
    sourcePath: "libs/papercusp/packages/harness/blueprints/base/prompts/su.md";
    projectionPaths: readonly string[];
}> | Readonly<{
    sourcePath: "apps/operator/prompts/pot-instances/papercup-pot.su.md";
    projectionPaths: readonly string[];
}>)[];
export const PROMPT_PROJECTIONS_MARKER: "__PROMPT_PROJECTIONS__";
import { readFileSync } from 'node:fs';
import { writeFileSync } from 'node:fs';
import { renameSync } from 'node:fs';
import { unlinkSync } from 'node:fs';
import { mkdirSync } from 'node:fs';
