#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/check-declared-consumed.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/check-declared-consumed.mjs and regenerate.
/**
 * A minified/bundled artifact is not a consumer — vacuous pass (5).
 *
 * This one was found the hard way, and it is the most dangerous of the set
 * because it produces confident, plausible-looking numbers. The first green run
 * of this sweep reported `CellSpec.ordered` as CONSUMED with 46 readers. All 46
 * were `.ordered` inside `storybook-static/**` webpack bundles — minified
 * third-party code where two-letter property names collide with anything. The
 * field is in fact read by nothing, which is the defect the gate exists to find,
 * and a build artifact checked into the tree had hidden it perfectly.
 *
 * Detection is by line SHAPE rather than by path, because the next bundle will
 * live somewhere this list does not name: source is written in lines, generated
 * code is not.
 *
 * ⚠ The test is DOMINANCE, not presence — "has one long line" is NOT "is
 * minified", and conflating the two red-pinned the fleet gate for hours
 * (EI-19409948281572150). The original form returned true on the FIRST line over
 * 2000 chars, which silently dropped six hand-written source files whose only sin
 * was one long prose string: `cell-registrations.ts` (2657-char `why:`, 6.9% of
 * the file), `libs/flags/src/types.ts` (1.1%), `converse-prompt.ts` (10.9%) and
 * `work_items/get.ts` (13.9%). Dropping `cell-registrations.ts` removed the ONLY
 * writer of `CellSpec.unknownHoist` and `CellSpec.materiality`, so the sweep
 * reported both as 0-writer "read-only" and failed the build on fields that are
 * in fact written seven and one times respectively.
 *
 * That is the worst failure mode this file has, because a skipped file is
 * indistinguishable from an absent one: the sweep under-scans SILENTLY and every
 * row's verdict quietly loses confidence, not just the rows that go red.
 *
 * Measured separation is wide for MINIFIED output: real minified bundles
 * (`_astro/*.js`, `pagefind-*.js`, and the base64 asset blobs
 * `release-bg.ts` / `release-video.ts`) carry 93–100% of their bytes in
 * over-long lines; genuine source with a long literal carries 1.1–13.9%.
 *
 * ⚠⚠ BUT SHAPE ALONE IS NOT SUFFICIENT, and believing it was is what made the
 * first attempt at this fix WORSE than the bug. A bundle that is BUNDLED BUT NOT
 * MINIFIED defeats every line-shape test: `apps/operator/dist-host/hono-host.mjs`
 * is 62.9 MB over 1,219,924 lines with only 14.4% of its bytes in long lines —
 * shaped exactly like source. Admitting it contributed 412 writes and 1,802 reads
 * of `summary` by itself, flipping every column row to a confident "consumed".
 * That is the ORIGINAL storybook defect at 40x the scale: it does not merely
 * report a wrong number, it GREENS the gate by manufacturing consumers for
 * fields nothing reads.
 *
 * Nor can size stand in for it: the largest file both rules already scan is a
 * genuine 394 KB source script (`apps/operator/scripts/psu-launcher.mjs`), while
 * generated files occur at every size down to 4 KB. The populations overlap on
 * every intrinsic axis measured.
 *
 * So detection is now TWO tests, and the path one is load-bearing rather than a
 * convenience: build output is EXCLUDED BY LOCATION, and the long-line dominance
 * test remains as the shape backstop that still catches a bundle checked in
 * somewhere this list does not name — which is the case the original comment was
 * right to worry about.
 */
export function looksGenerated(src: any): boolean;
export function isBuildOutput(rel: any): any;
/** A test file proves a field is reachable, never that anything ships using it. */
export function isTestFile(rel: any): boolean;
/**
 * Every repo-relative path whose edit can change this sweep's verdict statically:
 * the two registries' declaration sites, plus this file (adding a row is the most
 * common such edit and must select the guard that judges it).
 *
 * EI-21082046676950143 — exported so `scripts/affected-tests.mjs` DERIVES which
 * edits select `lint:declared-consumed` instead of restating the paths. A copy
 * there would drift in the SILENT direction: a field declared under a new
 * `declaredIn`, or a column added by a new migration, would quietly stop
 * selecting this guard — the same orphaned-guard failure the guard exists to
 * catch, one layer up.
 */
export function declaringPaths(): string[];
/**
 * Blank every comment, preserving byte offsets and line numbers so reported
 * line:col still points at real source. Closes vacuous pass (2).
 *
 * String and template literals are LEFT INTACT: SQL lives in template literals,
 * so blanking them would blank the very column references this gate counts.
 */
export function stripComments(src: any): string;
/**
 * Blank the CONTENTS of single/double-quoted strings, keeping the quotes and the
 * length. Template literals survive untouched — they carry the SQL.
 *
 * Used only for the TS-field pass: a rejection message reading "`materiality`
 * must name a `path`" is prose that happens to live in a string, and counting it
 * is vacuous pass (2) wearing a different hat.
 */
export function blankQuotedStrings(src: any): any;
/**
 * Line ranges (1-based, inclusive) covered by an `interface X { … }` or
 * `type X = { … }` body. A property inside one is a DECLARATION; the same text
 * outside one is an object-literal WRITE. Closes vacuous pass (1).
 *
 * Brace depth is counted on comment-stripped source, so a `{` in a docblock
 * cannot desynchronise the range.
 */
export function interfaceRanges(src: any): {
    start: number;
    end: number;
}[];
/**
 * Normalise one file ONCE for every target.
 *
 * Not merely an optimisation: stripping and brace-scanning per (file × target)
 * is what made the first version of this sweep exceed two minutes on this tree.
 * Interface ranges are derived from the STRING-BLANKED text on purpose — a brace
 * inside a string literal (`'{ positions, stages[] }'` appears verbatim in
 * `cell-registrations.ts`) would otherwise desynchronise the depth count and
 * silently move every subsequent range.
 */
export function prepareSource(source: any): {
    stripped: string;
    blanked: any;
    ranges: {
        start: number;
        end: number;
    }[];
    lineStarts: number[];
};
/**
 * Classify every occurrence of a TS property `name` in one file's source.
 * Returns `{ declarations, writes, reads }` of 1-based line numbers.
 *
 * The rules, in the order they are tried:
 *   · `name:` / `name?:` at the start of a line INSIDE an interface body  → declaration
 *   · `name:` at the start of a line outside one (object-literal property) → write
 *   · `.name =` with a single `=`                                          → write
 *   · `.name` anywhere else                                                → read
 *   · `const { … name … } =`                                               → read
 */
export function classifyTsField(source: any, name: any): {
    declarations: any[];
    writes: number[];
    reads: number[];
};
/**
 * Classify occurrences of a SQL `column` by the nearest preceding SQL clause
 * keyword — the cheapest thing that is actually *about* SQL rather than about
 * text. `SET col =` and an `INSERT INTO t (…col…)` column list are writes;
 * everything else naming the column (a `WHERE` predicate, a select list, a
 * `RETURNING`, a `.col` on a result row) is a read.
 *
 * Occurrences inside an interface body are skipped: `superseded_at: string | null`
 * in a row type mirrors the column, it does not touch it — vacuous pass (1)
 * again, in its SQL costume.
 */
export function classifySqlColumn(source: any, column: any): {
    writes: any[];
    reads: any[];
};
/**
 * Judge one target. Pure, so every distinction this gate exists to make is
 * unit-testable against literal source strings with no filesystem.
 *
 * ⚠ `not-declared` is neither pass nor fail-for-the-usual-reason — see the
 * header. It means the ROW is stale, not that the field lost its consumers.
 */
export function judgeConsumption({ declarations, writes, reads }: {
    declarations: any;
    writes: any;
    reads: any;
}): "consumed" | "write-only" | "read-only" | "inert" | "not-declared";
/**
 * Roll judged rows up into an exit decision.
 *
 * A row carrying `knownUnbuilt` is REPORTED but does not fail the build: the gap
 * is already filed and owned, and re-failing for a known-open bug is how a gate
 * becomes noise the fleet routes around (WI-6464 nearly died that way). Deleting
 * the row to green the gate is the one response that is never acceptable — the
 * field stops being watched at exactly the moment it is known to be broken.
 */
export function rollupSweep(rows: any): {
    consumed: any;
    knownUnbuilt: any;
    stale: any;
    failures: any;
};
export function walkSource(dir: any, rel?: string): any;
/**
 * Parse every exported string-literal union in one COMMENT-STRIPPED source.
 * Unions of a single variant are skipped: there is no branch to be phantom.
 */
export function enumVariantDeclarations(stripped: any): {
    name: any;
    variants: any[];
    declText: any;
}[];
/** Count non-overlapping occurrences of `needle` in `hay`. */
export function countOccurrences(hay: any, needle: any): number;
/**
 * Decide which declared variants nothing can produce.
 *
 * `decls` is [{ file, name, variants, declText }]; `strippedByFile` is a Map of
 * comment-stripped sources; `quoted` is a Map of quoted-literal counts over the
 * same sources (the cheap stage-1 shortlist).
 */
export function judgeEnumVariants({ decls, strippedByFile, quoted }: {
    decls: any;
    strippedByFile: any;
    quoted: any;
}): {
    variantCount: number;
    shortlisted: number;
    rescued: number;
    mirrors: {
        id: string;
        file: any;
    }[];
    phantoms: {
        id: string;
        file: any;
    }[];
};
/** Directories a live consumer cannot live in. `_retired` is vacuous-pass (4). */
export const SKIP_DIRS: Set<string>;
/**
 * Every OPTIONAL field on `CellSpec`, plus a deliberately retained row for
 * `assessment`. Optional fields are the original risk surface: a required field
 * cannot be silently unwritten, because omitting it fails to compile. A required
 * field can still be silently UNREAD, though. `assessment` became required after
 * this census shipped, and remains here because dropping its consumer would hand
 * callers an un-interpreted value while the registration still typechecks.
 */
export const DECLARED_FIELDS: {
    id: string;
    name: string;
    declaredIn: string;
    producer: string;
    consumer: string;
    why: string;
}[];
/**
 * Every column added by the three migrations this plane shipped.
 *
 * `table` is not decoration — it is the scan filter. A file that never names the
 * table cannot be reading or writing its columns in SQL, and without that scope
 * a column called `summary` or `metrics` matches half the tree and the sweep
 * reports a confident pass built entirely from unrelated identifiers.
 */
export const DECLARED_COLUMNS: {
    id: string;
    table: string;
    name: string;
    migration: string;
    why: string;
}[];
/**
 * Where a declared COLUMN's declaration lives: the migration that adds it. The
 * sweep reads it below to tell `inert` (declared, nobody uses it) apart from
 * `not-declared` (the row describes a column that no longer exists).
 */
export const DB_MIGRATION_DIR: "libs/papercusp/libs/db/sql";
/** This module, repo-relative — a registry row edited here is a policed edit too. */
export const REGISTRY_SOURCE_PATH: string;
export const CONSUMPTION_VERDICTS: string[];
/** Enums whose variants mirror an external API's vocabulary (false-finding 2). */
export const PROVIDER_MIRROR_RE: RegExp;
/** Only unions declared under this prefix are swept (the agent-facing core). */
export const ENUM_SWEEP_PREFIX: "packages/operator-core/lib";
/**
 * SHRINK-ONLY BASELINE. Every variant here is declared and unreachable TODAY.
 * The gate fails on a NEW one, and equally on a row that is no longer phantom —
 * so the list can only shrink, and a fix must retire its row rather than leave a
 * ratchet that quietly watches nothing (the `stale` rule the field axis uses).
 *
 * Re-seed it from a measuring run (`--list-phantom-variants`), never by hand.
 */
export const PHANTOM_VARIANT_BASELINE: Set<string>;
