-- One-time cleanup: drop everything except papercup-org + its 6 departments + sheets.
-- Idempotent enough to re-run; the first run does the work, subsequent runs see
-- empty deltas and exit clean.
--
-- Schema drops happen one-per-statement (no surrounding transaction) because
-- DROP SCHEMA CASCADE acquires AccessExclusiveLocks on every table in the
-- schema; bundling 85 schemas × ~12 tables in one tx busts max_locks_per_tx.

\set ON_ERROR_STOP on

-- ── 1. Single-tx: shared-table cleanup + registry rewrite ────────────────
BEGIN;

CREATE TEMP TABLE _keep(slug TEXT PRIMARY KEY);
INSERT INTO _keep VALUES
  ('sheets'),
  ('papercup-org'),
  ('papercup-org-business'),
  ('papercup-org-rd'),
  ('papercup-org-technology'),
  ('papercup-org-management'),
  ('papercup-org-marketing'),
  ('papercup-org-coordination');

DELETE FROM harness_shared.harness_features_consolidated WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.plugin_enables                WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.user_actions                  WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_proposals_shared      WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_status                WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_lanes                 WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_summaries             WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_pending_issues        WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_phases                WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_tests                 WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.harness_escalations           WHERE harness_slug NOT IN (SELECT slug FROM _keep);
DELETE FROM harness_shared.pending_reviews               WHERE harness_slug NOT IN (SELECT slug FROM _keep);

UPDATE harness_shared.harness_registry
   SET payload = jsonb_build_object(
         'projects',
         (SELECT COALESCE(jsonb_agg(p), '[]'::jsonb)
            FROM jsonb_array_elements(payload->'projects') AS p
           WHERE p->>'slug' IN (SELECT slug FROM _keep))
       ),
       updated_at = (extract(epoch from now()) * 1000)::bigint
 WHERE workspace_id = 'default';

COMMIT;

-- ── 2. Drop the harness_features_all view first so the schemas it
-- references can be dropped next. We'll rebuild it at the end.
DROP VIEW IF EXISTS harness_shared.harness_features_all;

-- ── 3. One DROP per schema, each its own implicit transaction.
-- Generate the DDL inline; psql executes each line as its own statement.
SELECT format('DROP SCHEMA IF EXISTS %I CASCADE;', schema_name) AS cmd
  FROM information_schema.schemata
 WHERE schema_name LIKE 'harness_%'
   AND schema_name <> 'harness_shared'
   AND replace(substring(schema_name FROM 9), '_', '-') NOT IN
       ('sheets','papercup-org','papercup-org-business','papercup-org-rd',
        'papercup-org-technology','papercup-org-management',
        'papercup-org-marketing','papercup-org-coordination')
\gexec

-- ── 4. Rebuild the cross-harness UNION view from the final 8 schemas.
CREATE VIEW harness_shared.harness_features_all AS
  SELECT * FROM harness_papercup_org.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_business.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_rd.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_technology.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_management.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_marketing.harness_features
  UNION ALL SELECT * FROM harness_papercup_org_coordination.harness_features
  UNION ALL SELECT * FROM harness_sheets.harness_features;
COMMENT ON VIEW harness_shared.harness_features_all IS
  'Auto-generated UNION ALL of every harness_*.harness_features. Read-only. Regenerated by scripts/regenerate-harness-features-view.sh.';
GRANT SELECT ON harness_shared.harness_features_all TO harness_app;

-- ── 5. Confirmation.
SELECT 'registry projects' AS what, jsonb_array_length(payload->'projects')::int AS n
  FROM harness_shared.harness_registry WHERE workspace_id='default'
UNION ALL SELECT 'per-harness schemas',
  count(*)::int FROM information_schema.schemata
 WHERE schema_name LIKE 'harness_%' AND schema_name <> 'harness_shared';
