#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/lint-tsc-operator-vite.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/lint-tsc-operator-vite.mjs and regenerate.
/** @type {string} */
export const TSC_COMMAND: string;
/**
 * A baseline owned by another package that this gate reads rather than maintains.
 *
 * @typedef {object} ForeignBaseline
 * @property {string} prefix - Repo-relative path prefix the owning package covers.
 * @property {string} baselineFile - Absolute path to that package's `.tsc-baseline.json`.
 * @property {string} [label] - Display name for the owning package, if it differs from `prefix`.
 */
/**
 * Cross-package files this gate MEASURES but does not OWN (EI-18649014117371738).
 *
 * The SPA's type graph pulls packages/operator-core in transitively, so ~27 of this baseline's
 * entries live there — deliberately covered, not ignored. But the two baselines were captured days
 * apart under DIFFERENT tsconfigs, so an operator-core file could be recorded (and tolerated) in
 * operator-core's baseline yet be ABSENT from this one, where absent⇒0 turned it into a phantom
 * regression: `lint:tsc` passed and `lint:tsc:operator-vite` failed on the SAME untouched file.
 * Pointing at the OWNING package's baseline makes the two gates agree by construction rather than
 * by two hand-maintained files happening to stay in sync.
 *
 * @type {ForeignBaseline[]}
 */
export const FOREIGN_BASELINES: ForeignBaseline[];
/**
 * A baseline owned by another package that this gate reads rather than maintains.
 */
export type ForeignBaseline = {
    /**
     * - Repo-relative path prefix the owning package covers.
     */
    prefix: string;
    /**
     * - Absolute path to that package's `.tsc-baseline.json`.
     */
    baselineFile: string;
    /**
     * - Display name for the owning package, if it differs from `prefix`.
     */
    label?: string | undefined;
};
