#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/next-migration.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/next-migration.mjs and regenerate.
/**
 * Build the shell-safe command for the shared linted CLI arm executor.
 *
 * @param {string} draftPath Repository-relative or absolute .sql.DRAFT path.
 * @returns {string}
 */
export function armCommandFor(draftPath: string): string;
/**
 * Lint a DRAFT with the same per-file pre-apply gate used by boot and db:migrate,
 * then atomically publish a separate, no-clobber .sql copy.
 *
 * @param {object} args
 * @param {string} args.draftPath Repository-relative or absolute .sql.DRAFT path.
 * @param {string} [args.sqlDir] SQL directory (default: canonical migrations; tests may use a temp dir).
 * @returns {Promise<{ok: boolean, draft_path: string, arm_path: string, draft_removed: boolean, warning?: string}>}
 */
export function armMigration({ draftPath, sqlDir }: {
    draftPath: string;
    sqlDir?: string | undefined;
}): Promise<{
    ok: boolean;
    draft_path: string;
    arm_path: string;
    draft_removed: boolean;
    warning?: string;
}>;
/**
 * Pure — builds the JSON payload printed on success. Exported and unit tested
 * without a DB so the DRAFT write-target, eventual armed SQL path, and linted
 * no-clobber arm command cannot silently diverge.
 *
 * @param {object} args
 * @param {number} args.next          The reserved migration number.
 * @param {string} args.filename      The eventual armed `<NNN>-<slug>.sql` filename.
 * @param {string} args.reservedBy    Who/what reserved it (for the printed `reserved_by`).
 * @param {boolean} args.dryRun       True when nothing was actually reserved.
 * @param {string} [args.canonicalDir] Override for the sql dir (tests only).
 * @param {string|null} [args.redundancyWarning] WI-38353: a non-blocking "a
 *   near-identical migration already exists" notice, surfaced on the SUCCESS
 *   path so a probable duplicate is visible even when it is not refused.
 */
export function buildAllocationResult({ next, filename, reservedBy, dryRun, canonicalDir, redundancyWarning, }: {
    next: number;
    filename: string;
    reservedBy: string;
    dryRun: boolean;
    canonicalDir?: string | undefined;
    redundancyWarning?: string | null | undefined;
}): {
    forward_compat: string;
    note: string;
    redundancy_warning?: string | undefined;
    ok: boolean;
    number: number;
    reserved: boolean;
    filename: string;
    path: string;
    arm_path: string;
    arm_command: string;
    reserved_by: string;
};
export { ALLOC_ADVISORY_KEY };
import { ALLOC_ADVISORY_KEY } from './lib/migration-allocation.mjs';
