#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/npm-install-safe.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/npm-install-safe.mjs and regenerate.
/**
 * Keep an explicit --cache override attached to the cache repair. Without it,
 * `npm run install:safe -- --cache <dir> ...` would verify the user's default
 * cache and then reify from a different cache, leaving the corrupt one
 * untouched. Environment/config-file cache selection is inherited by npm.
 */
export function cacheVerifyArgs(npmArgs?: any[]): any[];
/**
 * npm's repeatable workspace selectors (`--workspace X`, `--workspace=X`, `-w X`,
 * `-w=X`) in argv order. An empty list means an unscoped, whole-project command.
 */
export function workspaceSelectorsForNpmArgs(npmArgs?: any[]): any[];
/**
 * Resolve npm's repeatable workspace selectors to the canonical repo-relative
 * directories consumed by the dependency-integrity scanners. npm accepts both
 * package names and paths, while those scanners intentionally accept paths only.
 * No selector means a full install and therefore a full-tree verification.
 */
export function verificationScopeForNpmArgs({ repoRoot, npmArgs, deps, }?: {
    repoRoot?: string | undefined;
    npmArgs?: never[] | undefined;
    deps?: {} | undefined;
}): {
    workspaceDirs: undefined;
    repairWorkspaceArgs: never[];
} | {
    workspaceDirs: any[];
    repairWorkspaceArgs: string[];
};
/**
 * Verify and repair npm's content-addressed cache before reification. npm's
 * cache verifier removes index entries whose content blobs disappeared, so a
 * stale cacache reference cannot make the install fail with an opaque ENOENT.
 * The caller runs this while holding the same repo-keyed install mutex as the
 * subsequent npm command.
 */
export function verifyNpmCache({ repoRoot, npmArgs, runNpm, env, }?: {
    repoRoot?: string | undefined;
    npmArgs?: never[] | undefined;
    runNpm?: typeof spawnSync | undefined;
    env?: NodeJS.ProcessEnv | undefined;
}): number;
/**
 * Run `verify` (npm cache verify) while holding PACKAGE_CACHE_MUTEX_NAME EXCLUSIVELY.
 *
 * `npm cache verify` WRITES the user-level cache that every checkout shares: after its
 * garbage collection, cacache's `cleanTmp` step runs `rm -rf <cache>/tmp`, deleting every
 * download another npm process has staged there and not yet renamed into content-v2.
 * Until WI-10004430 it ran under the shared READ lease, beside other checkouts' reifies
 * (the repo-keyed install mutex cannot serialize different roots), so a verify in one
 * checkout could fail an install in another with
 * `ENOENT rename <cache>/tmp/… -> content-v2/…` — a workspace-host release cut, 2026-09-30.
 *
 * Verify is a repair step, not a precondition. The fs-mutex is writer-preferring, so
 * while this verifier waits, every other checkout's install queues behind it; past
 * `waitMs` it gives up and skips verify (loudly) rather than fail this install or stall
 * the others. Returns verify's exit status, or 0 when it was skipped.
 */
export function verifyNpmCacheExclusive({ verify, env, waitMs, acquire, log, }?: {
    env?: NodeJS.ProcessEnv | undefined;
    waitMs?: number | undefined;
    acquire?: typeof withFsMutex | undefined;
    log?: {
        (...data: any[]): void;
        (message?: any, ...optionalParams: any[]): void;
    } | undefined;
}): Promise<any>;
/**
 * Convert detector findings into the only paths install:safe may remove before
 * its bounded repair. Both the workspace and package segments are untrusted
 * manifest-derived strings, so validate the repo boundary and the narrower
 * <workspace>/node_modules boundary before returning a target.
 *
 * @param {{ repoRoot?: string, findings?: Array<{ workspace?: unknown, package?: unknown }> }} [options]
 * @returns {string[]}
 */
export function packageLocalRepairTargets({ repoRoot, findings, }?: {
    repoRoot?: string;
    findings?: Array<{
        workspace?: unknown;
        package?: unknown;
    }>;
}): string[];
/**
 * Remove a detector-confirmed stale package-local entry from package-lock.json
 * before npm reifies it again. The on-disk target alone is insufficient: npm
 * treats an orphaned lock entry as install intent even when the workspace's
 * current declaration is satisfied by a hoisted package.
 *
 * Only delete an exact entry whose locked version still matches the invalid
 * installed version the detector observed. A newer/different lock entry may be
 * a concurrent repair and must not be removed. The write is atomic so an
 * interrupted repair cannot leave the shared lockfile half-written.
 *
 * @param {{
 *   repoRoot?: string,
 *   findings?: Array<{ workspace?: unknown, package?: unknown, installed?: unknown, declared?: unknown }>,
 *   deps?: { readLock?: () => any, writeLock?: (lock: any) => void },
 * }} [options]
 * @returns {string[]} the package-lock.json `packages` keys that were removed.
 */
export function removePackageLocalRepairLockEntries({ repoRoot, findings, deps, }?: {
    repoRoot?: string;
    findings?: Array<{
        workspace?: unknown;
        package?: unknown;
        installed?: unknown;
        declared?: unknown;
    }>;
    deps?: {
        readLock?: () => any;
        writeLock?: (lock: any) => void;
    };
}): string[];
/**
 * Compare two parsed lockfiles. Returns the `packages` keys whose ONLY
 * difference is npm's dependency-type flags (`[]` = semantically identical), or
 * `null` when ANYTHING else differs: a version, resolved URL or integrity, a
 * dependency edge, an added or removed package, or any top-level field.
 */
export function lockfileDepFlagOnlyChanges(before: any, after: any): string[] | null;
/** The root package-lock.json text, or `undefined` when there is none. */
export function readLockfileText(repoRoot?: string, deps?: {}): any;
/**
 * WI-10003114: undo a workspace-scoped command's lockfile rewrite when it changed
 * nothing but npm's dependency-type flags.
 *
 * `npm install --workspace=A --workspace=B` recomputes dev/optional/devOptional
 * for the WHOLE lockfile, but it does so without seeing the whole workspace graph.
 * An unscoped install writes one set of flags and a scoped install writes another,
 * so the committed lockfile flips between them depending on which ran last.
 * Measured 2026-09-29: an unscoped shared-tree install flipped 196 entries
 * dev -> devOptional. The desktop sidecar build's scoped installs then flipped
 * them back inside the exact-SHA live-certification checkout. Every certification
 * of green main 93f1c720 went RED `certification-source-dirty-at-build-end`
 * (dirty file: package-lock.json only) even though every functional leg passed.
 *
 * Restoring those bytes cannot change what is installed: the rewrite touched no
 * version, URL, integrity or dependency edge (a formatting-only rewrite is
 * restored for the same reason). A substantive rewrite (a new dependency, a
 * version bump, a removed package) is left exactly as npm wrote it. Unscoped
 * installs are never touched: they are the writer that sees the whole graph.
 */
export function restoreScopedFlagOnlyLockfileRewrite({ repoRoot, beforeText, deps, }?: {
    repoRoot?: string | undefined;
    deps?: {} | undefined;
}): {
    restored: boolean;
    reason: string;
    entries: string[];
};
/**
 * Verify (post-install, still holding the lock) that dependency directories and
 * critical runtime contents actually landed on disk; repair once if not.
 *
 * @param {{
 *   repoRoot?: string,
 *   npmArgs?: string[],
 *   runNpm?: (args: string[]) => number,
 *   probeSpecifiers?: unknown,
 *   env?: NodeJS.ProcessEnv,
 *   deps?: Record<string, any>,
 * }} [options] `probeSpecifiers` and `deps` are forwarded unchanged to the detectors in
 *   scripts/check-declared-deps-extracted.mjs, which define their shapes.
 * @returns {Promise<0|1>} 0 = healthy (possibly after repair), 1 = still broken.
 */
export function verifyDepsExtracted({ repoRoot, npmArgs, runNpm, probeSpecifiers, env, deps, }?: {
    repoRoot?: string;
    npmArgs?: string[];
    runNpm?: (args: string[]) => number;
    probeSpecifiers?: unknown;
    env?: NodeJS.ProcessEnv;
    deps?: Record<string, any>;
}): Promise<0 | 1>;
export function repoLockName(repoRoot?: string): string;
/**
 * Hold a shared host-wide cache lease while a package manager may read/write
 * its global cache. Independent safe installs remain concurrent (reader +
 * reader); the scheduled package-cache janitor takes the matching writer lease
 * before native cleanup. This is deliberately separate from the repo-scoped
 * install writer, because staging/release/checkpoint have different realpaths
 * while sharing the same user-level caches.
 */
export function withPackageCacheReadLease(fn: any, opts?: {}): Promise<any>;
/**
 * npm treats config flags before a command as global flags. Preserve the
 * long-documented `npm run install:safe -- --legacy-peer-deps` form by making
 * the implicit install explicit before spawning npm.
 */
export function normalizeNpmArgs(argv: any): any;
/**
 * Build the environment for npm children without changing the parent process.
 * The offline override is deliberately opt-in: ordinary installs retain an
 * explicit caller setting (including `ONNXRUNTIME_NODE_INSTALL=skip`).
 */
export function npmChildEnv({ env, offlineSafe, }?: {
    env?: NodeJS.ProcessEnv | undefined;
    offlineSafe?: boolean | undefined;
}): {
    ONNXRUNTIME_NODE_INSTALL?: string | undefined;
};
/**
 * Publish the verified install as an immutable dependency generation under a
 * shared reader marker for the repo-keyed install mutex. The generation builder
 * carries its own before/after fingerprint guard and a short atomic-publish
 * lock; this reader boundary keeps a concurrent safe install from reifying
 * node_modules during the potentially long copy while still allowing other
 * dependency readers to proceed together.
 */
export function publishDependencyGeneration({ repoRoot, runPublisher, env, }?: {
    repoRoot?: string | undefined;
    runPublisher?: typeof spawnSync | undefined;
    env?: NodeJS.ProcessEnv | undefined;
}): Promise<any>;
/**
 * Parse the wrapper-only target selector without stealing npm's own flags.
 * `--repo-root` is recognized only as the first wrapper argument and an
 * optional `--` cleanly separates it from the npm argv.
 */
export function parseCliArgs(argv?: string[], { cwd }?: {
    cwd?: string | undefined;
}): {
    help: boolean;
} | {
    offlineSafe?: boolean | undefined;
    repoRoot: string;
    commandArgs: string[];
    help?: undefined;
} | {
    offlineSafe?: boolean | undefined;
    repoRoot: string;
    npmArgs: any;
    help?: undefined;
};
/**
 * Run a dependency reader under the SAME repo-keyed mutex as install:safe.
 * The marker environment prevents a wrapped script from recursively wrapping
 * itself while keeping the contract explicit and testable at the child seam.
 *
 * @param {{
 *   repoRoot?: string,
 *   commandArgs?: string[],
 *   runCommand?: (command: string, args: string[], options: { cwd: string, stdio: 'inherit', env: NodeJS.ProcessEnv }) => { status: number | null },
 *   env?: NodeJS.ProcessEnv,
 * }} [options]
 */
/**
 * WI-10006385: pair a lock's "waiting" notices with ONE closing line that says how long
 * the wait actually lasted and under what budget. Without it a build log shows
 * "waiting … (0s so far)" and then nothing, so nobody can tell a 1 s wait from a 50 min
 * one, or whether PAPERCUSP_UNATTENDED_LOCK_WAIT_SEC raised the budget. Prints nothing
 * for an uncontested lock: the closing line only follows a printed notice.
 *
 * @param {{ lock: 'writer' | 'reader', describe: (owner: string, elapsedMs: number) => string, log: (line: string) => void, budgetMs: number }} opts
 * @returns {{ onWaiting: (info: { owner: string, elapsedMs: number }) => void, onAcquired: (info: { waitedMs: number }) => void }}
 */
export function installLockWaitReporter({ lock, describe, log, budgetMs }: {
    lock: "writer" | "reader";
    describe: (owner: string, elapsedMs: number) => string;
    log: (line: string) => void;
    budgetMs: number;
}): {
    onWaiting: (info: {
        owner: string;
        elapsedMs: number;
    }) => void;
    onAcquired: (info: {
        waitedMs: number;
    }) => void;
};
/**
 * @param {{
 *   repoRoot?: string,
 *   commandArgs?: string[],
 *   runCommand?: (command: string, args: string[], options: {
 *     cwd: string, stdio: 'inherit', env: NodeJS.ProcessEnv,
 *   }) => { status?: number | null, error?: Error },
 *   env?: NodeJS.ProcessEnv,
 * }} [options]
 */
export function runCommandUnderInstallMutex({ repoRoot, commandArgs, runCommand, env, }?: {
    repoRoot?: string;
    commandArgs?: string[];
    runCommand?: (command: string, args: string[], options: {
        cwd: string;
        stdio: "inherit";
        env: NodeJS.ProcessEnv;
    }) => {
        status?: number | null;
        error?: Error;
    };
    env?: NodeJS.ProcessEnv;
}): Promise<number>;
export function main(argv?: string[]): Promise<any>;
export { installMutexIsHeld } from "./lib/install-lock-name.mjs";
/** Default wait for EXCLUSIVE use of the shared package cache before verify is skipped. */
export const NPM_CACHE_VERIFY_WAIT_MS_DEFAULT: 30000;
/** Printed for `--help` / `-h`; never takes the install mutex. */
export const USAGE: "Usage: npm run install:safe [-- <npm args>]   (defaults to plain `npm install`)\n       node scripts/npm-install-safe.mjs [--repo-root <path>] [--offline-safe] [--] [<npm args>]\n       node scripts/npm-install-safe.mjs [--repo-root <path>] --exec-under-lock [--] <command> [args...]\n\nSerializes npm installs in a shared checkout behind a repo-keyed mutex, then verifies every\ndeclared dependency landed on disk. Arguments that start with \"-\" get an implicit `install`\nprepended, so `-- --legacy-peer-deps` means `npm install --legacy-peer-deps`.\n--help / -h is recognised only as the first argument; use `install --help` for npm's own help.\n";
import { spawnSync } from "node:child_process";
import { withFsMutex } from "./lib/fs-mutex.mjs";
