#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/okf-backfill-packs.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/okf-backfill-packs.mjs and regenerate.
/** Decide the addition for one pack DOC. Returns { lines, skipped }. */
export function planDocAddition(text: any): {
    lines: never[];
    skipped: string;
    kind?: undefined;
} | {
    lines: string[];
    kind: any;
    skipped?: undefined;
};
/**
 * Decide the addition for one manifest.yaml. A manifest has NO `---` fences, so
 * the field is appended as a plain trailing line rather than inserted into a
 * frontmatter block.
 */
export function planManifestAddition(text: any): {
    next: null;
    skipped: string;
} | {
    next: string;
    skipped?: undefined;
};
