#!/usr/bin/env bash
# Regenerate harness_shared.harness_features_all — a cross-harness view
# that UNIONs every harness_*.harness_features table.
#
# Run this after creating a new harness schema (or on every deploy as a
# safety net). The view is read-only.
#
# Required env: PGPASSWORD or use a .pgpass file
#   PGPASSWORD=harness_admin_pwd ./regenerate-harness-features-view.sh
#
# Why a view rather than a regular table: harnesses are schema-per-tenant,
# so a UNION ALL view is the natural cross-tenant aggregator. Read-only is
# fine — writes must still go through the per-harness API endpoints.

set -euo pipefail

DB="${DB:-papercusp}"
HOST="${PGHOST:-127.0.0.1}"
USER="${PGUSER:-harness_admin}"

slugs=$(psql -h "$HOST" -U "$USER" -d "$DB" -tAc "
  SELECT t.table_schema
  FROM information_schema.tables t
  WHERE t.table_schema ~ '^harness_'
    AND t.table_schema <> 'harness_shared'
    AND t.table_name = 'harness_features'
  ORDER BY t.table_schema;
")

if [ -z "$slugs" ]; then
  echo "no per-harness harness_features tables found — nothing to do" >&2
  exit 0
fi

# Build UNION ALL across every schema's harness_features.
# Each branch selects every column to keep schema additions auto-picked-up.
unions=""
first=1
while read -r schema; do
  [ -z "$schema" ] && continue
  if [ $first -eq 1 ]; then
    unions+="  SELECT * FROM ${schema}.harness_features"
    first=0
  else
    unions+=$'\n  UNION ALL\n  SELECT * FROM '"${schema}"'.harness_features'
  fi
done <<< "$slugs"

sql="
DROP VIEW IF EXISTS harness_shared.harness_features_all;
CREATE VIEW harness_shared.harness_features_all AS
${unions};
COMMENT ON VIEW harness_shared.harness_features_all IS
  'Auto-generated UNION ALL of every harness_*.harness_features. Read-only. Regenerated by scripts/regenerate-harness-features-view.sh.';

GRANT SELECT ON harness_shared.harness_features_all TO harness_app;
GRANT SELECT ON harness_shared.harness_features_all TO harness_zero;
"

echo "$sql" | psql -h "$HOST" -U "$USER" -d "$DB" -v ON_ERROR_STOP=1

count=$(psql -h "$HOST" -U "$USER" -d "$DB" -tAc "SELECT COUNT(*) FROM harness_shared.harness_features_all;")
echo "harness_shared.harness_features_all → $count rows across $(echo "$slugs" | grep -c .) harnesses"
