#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/templates-mirror-sync.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/templates-mirror-sync.mjs and regenerate.
/**
 * Parse a canonical GitHub HTTPS or SSH remote into its repository identity.
 *
 * Git accepts both `https://github.com/Owner/repo.git` and the scp-shaped
 * `git@github.com:Owner/repo.git` form. Comparing the parsed owner/repo keeps
 * the push guard fail-closed for every other host or repository without
 * rejecting equivalent transport forms.
 *
 * @param {string} remote
 * @returns {{ owner: string, repo: string } | null}
 */
export function parseGithubRemote(remote: string): {
    owner: string;
    repo: string;
} | null;
/**
 * Compare the parsed GitHub identity, rather than the spelling of its remote.
 * GitHub repository names are case-insensitive, while the parser remains
 * deliberately strict about host and URL shape.
 *
 * @param {string} remote
 * @returns {boolean}
 */
export function isMirrorRemote(remote: string): boolean;
/**
 * Recursively list files under dir as dir-relative paths (posix slashes).
 *
 * @param {string} dir
 * @param {{ exclude?: (rel: string) => boolean }} [opts]
 * @returns {Promise<string[]>}
 */
export function walk(dir: string, { exclude }?: {
    exclude?: (rel: string) => boolean;
}): Promise<string[]>;
/**
 * Build the expected manifest: mirror-relative path -> canonical source abs path.
 * Exported so a test can drive it against a synthetic tree without touching the
 * shared checkout.
 *
 * Throws (with `exitCode: 2`) when a vendored package's source is missing —
 * an empty canonical source would otherwise flag every vendored mirror file
 * extraneous, and `--push` would delete them.
 *
 * @param {string} [root]
 * @param {string[]} [vendored]
 * @returns {Promise<{ expected: Map<string, string>, templateIds: string[], rubricIds: string[] }>}
 */
export function buildExpected(root?: string, vendored?: string[]): Promise<{
    expected: Map<string, string>;
    templateIds: string[];
    rubricIds: string[];
}>;
/**
 * Enumerate the mirror's ACTUAL state over the SYNCED surface only.
 *
 * @param {string} mirror
 * @param {string[]} [vendored]
 * @returns {Promise<Set<string>>}
 */
export function buildActual(mirror: string, vendored?: string[]): Promise<Set<string>>;
/**
 * Diff expected vs actual. Byte-compares every file present on both sides.
 *
 * @param {Map<string, string>} expected
 * @param {Set<string>} actual
 * @param {string} mirror
 * @returns {Promise<{ missing: string[], changed: string[], extraneous: string[] }>}
 */
export function computeDrift(expected: Map<string, string>, actual: Set<string>, mirror: string): Promise<{
    missing: string[];
    changed: string[];
    extraneous: string[];
}>;
export const VENDORED: string[];
export function driftTotal(drift: {
    missing: string[];
    changed: string[];
    extraneous: string[];
}): number;
