#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/verify-identities-r7.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/verify-identities-r7.mjs and regenerate.
/**
 * Whether an activation event row applies a stack containing `layerRef`, after `afterId`.
 *
 * @param {{ id: number|string, phase: string, stack_refs: unknown }} row
 * @param {string} layerRef
 * @param {number} afterId
 * @returns {boolean}
 */
export function appliesLayer(row: {
    id: number | string;
    phase: string;
    stack_refs: unknown;
}, layerRef: string, afterId: number): boolean;
/**
 * The page URL a switch starts from. It deliberately carries NO `identityTab`, so the page opens
 * on its default `library` tab: that is the only tab that renders the `.pc-identities__identity`
 * rows and the `Inspect identity <id>` buttons the switch clicks. Review then moves to the agent
 * tab itself. Pinning the tab param to the agent tab here made the library assertion
 * unsatisfiable, and it failed as a DOM timeout that read like a slow page.
 *
 * @param {string} owner
 * @param {string} identityId
 * @param {number} nonce
 * @returns {string}
 */
export function identitiesUrl(owner: string, identityId: string, nonce: number): string;
/** Return the action available on the currently loaded identity catalog page. */
export function catalogProbeExpression(identityId: any): string;
/**
 * Classify a failed VERIFY_TAURI_SETTLE run. The settle contract exits 1 when the page is still
 * busy at its timeout and 3 when readiness is unknown; both are recorded, not fatal. Anything else
 * (a spawn failure, a killed child, a missing script) is a real error and is rethrown.
 *
 * @param {{ status?: number|null } | null | undefined} error
 * @returns {"busy"|"unknown"|null}
 */
export function settleOutcome(error: {
    status?: number | null;
} | null | undefined): "busy" | "unknown" | null;
export function main(): Promise<void>;
