#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from scripts/workspace-test.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// scripts/workspace-test.mjs and regenerate.
export function isVitestTestFileArg(arg: any): boolean;
/**
 * Build the child invocation without running it, keeping the routing decision
 * independently testable. The package script supplies --passWithNoTests as a
 * fixed argument; the router does not need that flag after it has verified the
 * requested file set, so it is removed from routed invocations.
 *
 * @param {string[]} [argv] launcher arguments (defaults to this process's argv)
 * @param {string} [repoRoot] repository root the loader and router resolve against
 */
export function workspaceTestInvocation(argv?: string[], repoRoot?: string): {
    command: string;
    args: string[];
    cwd: string;
    routed: boolean;
};
export function main(argv?: string[]): number;
