/**
 * scout-plan-draft.ts — Scout P-008/P-007 broad rail: the system-side
 * `plans:new` DRAFT creator the `system:scout-cycle` action supplies to
 * cb4b9's buildScoutCycleDeps (its `createPlanDraft` / PlanDraftCreator seam).
 *
 * The broad-scope rail routes a Scout proposal to a `plans:new` DRAFT plan that
 * the Queen/owner reviews (D-002/D-010 — Scout proposes, the Queen greenlights by
 * promoting the draft; it is NOT auto-active). The `plans:new` *tool* needs an
 * operator ctx for its write-lock/revision/event, but the lock core
 * ({@link withPlanLock}) ignores its ctx param (the PG advisory lock needs no
 * identity) — so a routine system action can create the draft directly through it.
 * No bearer/principal needed: the write lands in `harness_shared.harness_plans`
 * via the org PG. Idempotent: a slug collision returns the existing slug
 * (created:false) rather than throwing, so a replayed routine step is safe.
 */

import { withPlanLock as realWithPlanLock } from '../agent-tools/plans/with-plan-lock';
import { stampPlanGoalProvenance as realStampPlanGoalProvenance } from '../modes/goal-context';
import { recordPlanRevision, type PlanSessionRef } from '../agent-tools/plans/revisions';
import type { AgentIdentity } from '../agent-tools/coordination/identity';
import { SCOUT_DRAFT_LOOP_NOTE } from './feedback-loop-prompt';

/** Append the `-YYYY-MM-DD` filename suffix (plan convention) when absent. */
export function ensureDatedSlug(slug: string, today: string): string {
  return /-\d{4}-\d{2}-\d{2}$/.test(slug) ? slug : `${slug}-${today}`;
}

/** The canonical draft-plan body — same shape `plans:new` writes (frontmatter + Now + sections). */
export function buildScoutPlanTemplate(args: {
  slug: string;
  title: string;
  date: string;
  rationale?: string;
}): string {
  const why = args.rationale?.trim()
    ? args.rationale.trim()
    : '(Blender-generated broad-scope proposal — see the Now block.)';
  return `---
title: ${args.title}
slug: ${args.slug}
status: draft
origin: scout
created: ${args.date}
updated: ${args.date}
specTriad: required
---

# ${args.title}

## Now

**State:** Draft — autonomously generated by the Blender loop (hive-creative-ideation, D-002/D-010). Awaiting steward/owner triage; not active until greenlit.

**Next:** ${SCOUT_DRAFT_LOOP_NOTE}

## Background

${why}

## Requirements

TBD

## Design

TBD

## Phase 1 — TODO

- **P-001** \`todo\` ${args.title} — first concrete slice of the proposal's mechanism (reviewer: refine/split during review — a ratified plan's open items auto-promote to work_items on start, WI-1574)

## Decisions

(Use plans:add-decision to append.)
`;
}

export interface CreateScoutPlanDraftInput {
  /** Topic slug stem (kebab-case); a date suffix is appended if absent. */
  slug: string;
  title: string;
  rationale?: string;
  harnessSlug?: string;
  workspaceId?: string;
  /** Identity attributed to the initial revision. Route callers pass their resolved su identity. */
  revisionIdentity?: AgentIdentity;
  /** Resolved conversation provenance for that initial revision. */
  revisionSession?: PlanSessionRef;
  /** ISO date (YYYY-MM-DD); defaults to today. */
  date?: string;
  /**
   * Override the draft body, built from the RESOLVED (dated) slug + date so the
   * body's frontmatter slug always matches the row's slug. Default:
   * {@link buildScoutPlanTemplate} (the broad-rail draft). The Scout `rubric` rail
   * (rubric-rail.ts, P-009) passes a `template: rubric` body builder — reusing this
   * function's idempotent withPlanLock create path rather than forking it.
   */
  buildBody?: (args: { slug: string; date: string }) => string;
}

export interface ScoutPlanDraftDeps {
  withPlanLock: typeof realWithPlanLock;
  recordPlanRevision?: typeof recordPlanRevision;
  stampPlanGoalProvenance?: typeof realStampPlanGoalProvenance;
}

const defaultDeps: ScoutPlanDraftDeps = {
  withPlanLock: realWithPlanLock,
  recordPlanRevision,
  stampPlanGoalProvenance: realStampPlanGoalProvenance,
};

/**
 * Create a DRAFT plan from the Scout loop (system-side). Returns the (dated) slug
 * and whether it was newly created (false = a plan with that slug already existed).
 * Throws only on lock contention (a concurrent writer on the same slug) — the
 * routine step then replays safely (idempotent on retry).
 */
export async function createScoutPlanDraft(
  input: CreateScoutPlanDraftInput,
  deps: ScoutPlanDraftDeps = defaultDeps,
): Promise<{ slug: string; created: boolean }> {
  const date = (input.date ?? new Date().toISOString()).slice(0, 10);
  const slug = ensureDatedSlug(input.slug, date);
  const body = input.buildBody
    ? input.buildBody({ slug, date })
    : buildScoutPlanTemplate({ slug, title: input.title, date, rationale: input.rationale });

  const result = await deps.withPlanLock<{ created: boolean }>(
    null,
    {
      slug,
      intent: `scout:plans-new ${slug}`,
      ...(input.harnessSlug ? { harnessSlug: input.harnessSlug } : {}),
      ...(input.workspaceId ? { workspaceId: input.workspaceId } : {}),
      // The initial revision is part of the same canonical writer contract as plans:new.
      // Keep the hook best-effort, matching every other plan revision capture path.
      afterWrite: async (writtenBody, scope) => {
        const identity = input.revisionIdentity ?? {
          ownerId: 'scout:route-idea',
          ownerLabel: 'scout · route-idea',
          source: 'static-client',
          workspaceId: scope.workspaceId,
          userId: null,
        };
        await (deps.recordPlanRevision ?? recordPlanRevision)({
          planSlug: slug,
          harnessSlug: scope.harnessSlug,
          workspaceId: scope.workspaceId,
          content: writtenBody,
          rationale: input.rationale ?? null,
          identity,
          sessionId: input.revisionSession?.sessionId ?? null,
          sessionKind: input.revisionSession?.sessionKind ?? null,
        });

        // Goal attribution, at the SAME point plans:new stamps it (migration 791,
        // goal-mode-design-intent-hardening-2026-08-16 P-003). This rail is a THIRD
        // plan-creation path beside plans:new and plans:launch, and it reached neither
        // stamp — so every draft routed through `blender:route-idea` landed with
        // `harness_plans.goal_id` NULL and was invisible on the goal page and
        // uncountable in goal-scoped stewardship instruments (WI-2142649: 4 of 4
        // routed origins over 48h). A goal steward whose posture is *route, never
        // implement* does most of its placement through exactly this rail, so the work
        // it routes was the work least attributable back to the goal that produced it.
        //
        // Fires only on a real create: withPlanLock calls afterWrite only when
        // `writtenBody !== null`, and the mutator below returns `newBody: null` on the
        // idempotent already-exists path — so a replayed routine step cannot stamp a
        // plan it did not author.
        //
        // `scope` is the RESOLVED pair withPlanLock actually wrote the row with
        // (resolvePlanScope collapses a member harness to its pot home). Using
        // `input.harnessSlug` here would miss pot-scoped plans SILENTLY — a zero-row
        // UPDATE — the exact trap new.ts and launch.goal-stamp.test.ts both document.
        //
        // `ownerId` is the caller's resolved identity, never the `scout:route-idea`
        // static fallback above: the helper derives the goal from the OWNER's context,
        // so a system `scout-cycle` step (no revisionIdentity) correctly stamps
        // nothing rather than attributing a routine's draft to some agent's goal.
        //
        // Best-effort BY DESIGN, and swallowed here rather than merely un-awaited: a
        // plan that was successfully created must not be failed retroactively because
        // its provenance stamp could not be written, and afterWrite rejecting WOULD
        // fail it (with-plan-lock.ts awaits this hook). The helper itself writes
        // `WHERE goal_id IS NULL`, so first attribution still wins.
        try {
          await (deps.stampPlanGoalProvenance ?? realStampPlanGoalProvenance)({
            workspaceId: scope.workspaceId,
            harnessSlug: scope.harnessSlug,
            planSlug: slug,
            ownerId: input.revisionIdentity?.ownerId,
          });
        } catch {
          // provenance is metadata — never fail a created plan on it
        }
      },
    },
    async (current) => {
      if (current !== null) return { newBody: null, value: { created: false } }; // exists — idempotent
      return { newBody: body, value: { created: true } };
    },
  );

  if (result.kind === 'busy') {
    throw new Error(`createScoutPlanDraft: plan ${slug} is being written by another caller`);
  }
  return { slug, created: result.value.created };
}
