export type {
  DesignEcosystemAdapter,
  AdapterCapability,
  RegistryEntry,
  RegistrySurface,
  PreviewSurface,
  PreviewSpec,
  TokensSurface,
  MockInputSurface,
  CodeEmitSurface,
  ExportTargetSurface,
  SourcePointer,
  FileEmit,
  ImageAsset,
  DtcgToken,
  DtcgDoc,
  CodeEmitTarget,
} from './contract';
export {
  installAdapter,
  uninstallAdapter,
  listAdapters,
  adaptersForEcosystem,
  pickAdapter,
  clearAdapterPick,
  getAdapter,
  getAdapterFor,
  getAdapterWithCapability,
  supportsIrVersion,
  unionUiGlobs,
  AdapterConflictError,
  IrVersionMismatchError,
  _resetAdapterRegistryForTests,
} from './registry';
export {
  checkAdapterConformant,
  assertAdapterConformant,
  AdapterConformanceError,
  type ConformanceFailure,
  type ConformanceOptions,
} from './conformance';
