/**
 * `ClaudeFileMemoryBackend` — the Claude Code topic-file bridge
 * (generalize-memory-backend-swappable-2026-06-05 D-005, built by
 * claude-memory-projection-integration-2026-06-05 P-004).
 *
 * Reads/writes the owner's de facto memory store — the native Claude Code
 * file memory (`~/.claude/projects/<slug>/memory/*.md`, one topic file per
 * fact) — through the neutral `MemoryBackend` seam, so the `memory:*`
 * tools and the memory surfaces can render/edit it like any other store.
 *
 * Contract with the user-env memory system (fix-claude-code-memory):
 *   - **`MEMORY.md` is NEVER written or read for data.** It is an
 *     auto-generated projection of the topic files, regenerated by the
 *     SessionStart hook (`memory-compact.mjs`); this backend only touches
 *     topic files, and the next regen picks them up.
 *   - **`forget` archives, never deletes** — files move to `archive/`
 *     (recoverable), matching the index projector's own eviction
 *     convention. `archive/` and `skills/` are never read as entries.
 *   - Serialized files parse under the hook's frontmatter rules
 *     (see ./topic-file), so a projected fact lands in the regenerated
 *     index unchanged.
 *
 * Scope model: the store is a single pool per Claude project, so scope is
 * persisted per-entry in frontmatter (`metadata.scope`). Hand-curated
 * files predate the backend and carry no scope — they report
 * `unscopedScope` (default `'local'`) and, with the visibility-first
 * default `matchUnscopedToAnyScope: true`, surface under ANY queried pool
 * (the whole point of the bridge is making the existing store visible).
 *
 * Search is plain lexical scoring (name > description > body token hits) —
 * deliberately no embeddings: this is a file bridge, not a vector store.
 */

import fs from 'node:fs';
import path from 'node:path';

import {
  MemoryUnavailableError,
  scopesOf,
  type ListOptions,
  type MemoryAvailability,
  type MemoryBackend,
  type MemoryEntry,
  type RememberOptions,
  type SearchOptions,
  type UpdatePatch,
} from './backend';
import {
  deriveDescription,
  parseTopicFile,
  serializeTopicFile,
  slugify,
  typeForKind,
  type ClaudeMemoryType,
  type TopicFile,
} from './topic-file';

export const CLAUDE_FILE_BACKEND_NAME = 'claude-file';
export const MEMORY_DIR_MISSING_REASON = 'memory_dir_missing';

// Generated index files — projections of the topic files, never data entries.
// MEMORY.md is the always-loaded index; MEMORY-overflow.md is the on-demand
// overflow index (memory-compact tiering). Both must be skipped when reading
// entries, or the index text leaks in as a bogus "memory".
const INDEX_FILES = new Set(['MEMORY.md', 'MEMORY-overflow.md']);
const ARCHIVE_DIR = 'archive';
const DEFAULT_SEARCH_LIMIT = 10;

export interface ClaudeFileBackendOptions {
  /** The Claude project memory directory (`…/.claude/projects/<slug>/memory`). */
  memoryDir: string;
  /**
   * Scope reported for topic files that carry no stored scope (the owner's
   * hand-curated store). Default `'local'`.
   */
  unscopedScope?: string;
  /**
   * Match unscoped files against ANY queried scope (default true —
   * visibility-first: the legacy store surfaces in every pool). Set false
   * to confine unscoped files to `unscopedScope` queries only.
   */
  matchUnscopedToAnyScope?: boolean;
  /** Create the memory dir on first write instead of reporting unavailable. */
  createIfMissing?: boolean;
  /** Override the neutral-kind → Claude-type mapping (see typeForKind). */
  kindToType?: (kind: string | undefined) => ClaudeMemoryType;
}

interface LoadedEntry {
  file: string; // basename incl. .md
  tf: TopicFile;
  mtimeMs: number;
}

export class ClaudeFileMemoryBackend implements MemoryBackend {
  readonly name: string = CLAUDE_FILE_BACKEND_NAME;

  /** A pure token match with no embedder anywhere — `search` and
   *  `searchLexical` are the SAME call, so both are the lexical scale. */
  readonly scoreScale = 'lexical' as const;
  readonly lexicalScoreScale = 'lexical' as const;

  private readonly dir: string;
  private readonly unscopedScope: string;
  private readonly matchUnscopedToAnyScope: boolean;
  private readonly createIfMissing: boolean;
  private readonly kindToType: (kind: string | undefined) => ClaudeMemoryType;

  constructor(opts: ClaudeFileBackendOptions) {
    this.dir = path.resolve(opts.memoryDir);
    this.unscopedScope = opts.unscopedScope ?? 'local';
    this.matchUnscopedToAnyScope = opts.matchUnscopedToAnyScope ?? true;
    this.createIfMissing = opts.createIfMissing ?? false;
    this.kindToType = opts.kindToType ?? typeForKind;
  }

  async available(): Promise<MemoryAvailability> {
    if (fs.existsSync(this.dir) || this.createIfMissing) return { ok: true };
    return { ok: false, reason: MEMORY_DIR_MISSING_REASON };
  }

  async remember(text: string, opts: RememberOptions): Promise<{ ids: string[] }> {
    this.ensureDir();
    const meta = { ...(opts.metadata ?? {}) };
    const description =
      typeof meta.description === 'string' && meta.description.trim()
        ? deriveDescription(meta.description)
        : deriveDescription(text);
    delete meta.description;

    const type = this.kindToType(opts.kind);
    const id = this.uniqueId(`${type}_${slugify(description)}`);
    const tf: TopicFile = {
      name: id,
      description,
      type,
      scope: opts.scope,
      kind: opts.kind,
      extra: Object.keys(meta).length ? meta : undefined,
      body: text,
    };
    fs.writeFileSync(this.fileFor(id), serializeTopicFile(tf), 'utf8');
    return { ids: [id] };
  }

  async search(query: string, opts: SearchOptions): Promise<MemoryEntry[]> {
    const entries = this.collect();
    const tokens = tokenize(query);
    if (tokens.length === 0) return [];
    const limit = opts.limit ?? DEFAULT_SEARCH_LIMIT;

    const merged = new Map<string, MemoryEntry>();
    for (const scope of scopesOf(opts.scope)) {
      const pool = entries
        .filter((e) => this.inScope(e, scope))
        .map((e) => ({ e, score: scoreEntry(tokens, e) }))
        .filter((s) => s.score > 0)
        .sort((a, b) => b.score - a.score || b.e.mtimeMs - a.e.mtimeMs)
        .slice(0, limit);
      for (const { e, score } of pool) {
        const id = idOf(e);
        if (!merged.has(id)) merged.set(id, this.toEntry(e, scope, score));
      }
    }
    return [...merged.values()].sort((a, b) => (b.score ?? 0) - (a.score ?? 0));
  }

  /** search() is already a pure token match with no embedder — the lexical
   *  capability (WI-4214) is the same call. */
  searchLexical(query: string, opts: SearchOptions): Promise<MemoryEntry[]> {
    return this.search(query, opts);
  }

  async list(opts: ListOptions): Promise<MemoryEntry[]> {
    const entries = this.collect();
    const merged = new Map<string, MemoryEntry>();
    for (const scope of scopesOf(opts.scope)) {
      for (const e of entries) {
        if (!this.inScope(e, scope)) continue;
        if (opts.kind && (e.tf.kind ?? e.tf.type) !== opts.kind) continue;
        const id = idOf(e);
        if (!merged.has(id)) merged.set(id, this.toEntry(e, scope));
      }
    }
    return [...merged.values()].sort((a, b) => Number(b.metadata?.mtimeMs ?? 0) - Number(a.metadata?.mtimeMs ?? 0));
  }

  async get(id: string): Promise<MemoryEntry | null> {
    if (!isSafeId(id)) return null;
    const file = this.fileFor(id);
    if (!fs.existsSync(file)) return null;
    const loaded = this.load(path.basename(file));
    return loaded ? this.toEntry(loaded, loaded.tf.scope ?? this.unscopedScope) : null;
  }

  /** Archive (never delete) — matches the index projector's eviction convention. */
  async forget(id: string): Promise<void> {
    if (!isSafeId(id)) return; // a hostile/garbage id is simply "already gone"
    const src = this.fileFor(id);
    if (!fs.existsSync(src)) return;
    const archiveDir = path.join(this.dir, ARCHIVE_DIR);
    fs.mkdirSync(archiveDir, { recursive: true });
    let dest = path.join(archiveDir, `${id}.md`);
    if (fs.existsSync(dest)) dest = path.join(archiveDir, `${id}.${Date.now().toString(36)}.md`);
    fs.renameSync(src, dest);
  }

  async update(id: string, patch: UpdatePatch): Promise<void> {
    if (!isSafeId(id)) throw new MemoryUnavailableError(MEMORY_DIR_MISSING_REASON);
    const file = this.fileFor(id);
    if (!fs.existsSync(file)) throw new Error(`memory entry not found: ${id}`);
    const tf = parseTopicFile(fs.readFileSync(file, 'utf8'));
    if (!tf.name) tf.name = id;

    if (typeof patch.text === 'string') tf.body = patch.text;
    if (patch.metadata) {
      const meta = { ...patch.metadata };
      if (typeof meta.description === 'string') {
        tf.description = deriveDescription(meta.description);
        delete meta.description;
      }
      if (typeof meta.kind === 'string') {
        tf.kind = meta.kind;
        delete meta.kind;
      }
      if (typeof meta.scope === 'string') {
        tf.scope = meta.scope;
        delete meta.scope;
      }
      if (Object.keys(meta).length) tf.extra = { ...(tf.extra ?? {}), ...meta };
    }
    fs.writeFileSync(file, serializeTopicFile(tf), 'utf8');
  }

  // ---- internals -----------------------------------------------------------

  private ensureDir(): void {
    if (fs.existsSync(this.dir)) return;
    if (!this.createIfMissing) throw new MemoryUnavailableError(MEMORY_DIR_MISSING_REASON);
    fs.mkdirSync(this.dir, { recursive: true });
  }

  private fileFor(id: string): string {
    return path.join(this.dir, `${id}.md`);
  }

  private uniqueId(base: string): string {
    if (!fs.existsSync(this.fileFor(base))) return base;
    for (let i = 2; ; i++) {
      const candidate = `${base}_${i}`;
      if (!fs.existsSync(this.fileFor(candidate))) return candidate;
    }
  }

  /** Top-level topic files only — never the generated index, archive/ or skills/. */
  private collect(): LoadedEntry[] {
    if (!fs.existsSync(this.dir)) return [];
    const out: LoadedEntry[] = [];
    for (const d of fs.readdirSync(this.dir, { withFileTypes: true })) {
      if (!d.isFile() || !d.name.endsWith('.md') || INDEX_FILES.has(d.name)) continue;
      const loaded = this.load(d.name);
      if (loaded) out.push(loaded);
    }
    return out;
  }

  private load(basename: string): LoadedEntry | null {
    const full = path.join(this.dir, basename);
    try {
      const text = fs.readFileSync(full, 'utf8');
      const stat = fs.statSync(full);
      return { file: basename, tf: parseTopicFile(text), mtimeMs: stat.mtimeMs };
    } catch {
      return null;
    }
  }

  private inScope(e: LoadedEntry, scope: string): boolean {
    if (e.tf.scope) return e.tf.scope === scope;
    return this.matchUnscopedToAnyScope || scope === this.unscopedScope;
  }

  private toEntry(e: LoadedEntry, queriedScope: string, score?: number): MemoryEntry {
    return {
      id: idOf(e),
      text: e.tf.body.trim() || e.tf.description,
      kind: e.tf.kind ?? e.tf.type,
      scope: e.tf.scope ?? (this.matchUnscopedToAnyScope ? queriedScope : this.unscopedScope),
      ...(score !== undefined ? { score } : {}),
      metadata: {
        type: e.tf.type,
        description: e.tf.description,
        file: e.file,
        mtimeMs: e.mtimeMs,
        ...(e.tf.extra ?? {}),
      },
    };
  }
}

function idOf(e: LoadedEntry): string {
  return e.file.replace(/\.md$/, '');
}

/** Ids are filenames — reject anything that could escape the memory dir. */
function isSafeId(id: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(id) && !id.includes('..');
}

function tokenize(q: string): string[] {
  return [...new Set(q.toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length >= 2))];
}

/** Lexical relevance: name hits > description hits > body hits, normalized 0..1. */
function scoreEntry(tokens: string[], e: LoadedEntry): number {
  const name = `${e.file} ${e.tf.name}`.toLowerCase();
  const desc = e.tf.description.toLowerCase();
  const body = e.tf.body.toLowerCase();
  let s = 0;
  for (const t of tokens) {
    if (name.includes(t)) s += 3;
    else if (desc.includes(t)) s += 2;
    else if (body.includes(t)) s += 1;
  }
  return s / (tokens.length * 3);
}
