#!/usr/bin/env node
// GENERATED by `npm run gen:declarations` from apps/operator/scripts/hooks/cc/regenerate-declaration-before-lock-release.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// apps/operator/scripts/hooks/cc/regenerate-declaration-before-lock-release.mjs and regenerate.
/**
 * Which artifacts this edit stranded, without running anything.
 *
 * Exported as the pure seam the tests assert on: proving the SELECTION rule needs
 * no npm, no generator and no writes. Returns `{ id, selected }` and never throws
 * — an entry that cannot decide is simply absent.
 */
export function selectDerivedArtifacts(repoRoot: any, paths: any): {
    id: string;
    selected: any;
}[];
/**
 * Regenerate every artifact this edit stranded. Returns the number of enrolled
 * inputs that selected across all entries (0 = nothing to do).
 *
 * Generators run INDEPENDENTLY: one failing generator must not stop the others,
 * because they emit unrelated artifacts. Every failure is still surfaced — the
 * aggregated throw is what the callers turn into a recorded release error.
 */
export function regenerateForPaths(repoRoot: any, paths: any): number;
export function regenerateForHookPayload(payload: any): number;
