-- Migration 048 — Design phase fields on features + design artifacts table.
-- Step 1 of the design-phase plan
-- (apps/operator/content/internal-docs/design/design-phase-plan.mdx). Adds the
-- minimum schema needed to gate features on design completion. UI, agent,
-- and adapter wiring follow in later steps.
--
-- Idempotent. Re-runs are no-ops.

\set ON_ERROR_STOP on
BEGIN;

-- 1. Lifecycle fields on the canonical features table.
ALTER TABLE harness_shared.harness_features_consolidated
  ADD COLUMN IF NOT EXISTS needs_design          BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS design_status         TEXT,        -- 'pending' | 'accepted' | 'ignored' | NULL
  ADD COLUMN IF NOT EXISTS design_spec_id        TEXT,        -- → harness_design_artifacts.id
  ADD COLUMN IF NOT EXISTS discarded_design_work BOOLEAN NOT NULL DEFAULT FALSE;

-- Sanity: design_status must be one of the known values when set.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'hfc_design_status_chk'
  ) THEN
    ALTER TABLE harness_shared.harness_features_consolidated
      ADD CONSTRAINT hfc_design_status_chk
      CHECK (design_status IS NULL OR design_status IN ('pending', 'accepted', 'ignored'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS hfc_needs_design_idx
  ON harness_shared.harness_features_consolidated(harness_slug, needs_design)
  WHERE needs_design = TRUE;

CREATE INDEX IF NOT EXISTS hfc_design_status_idx
  ON harness_shared.harness_features_consolidated(harness_slug, design_status)
  WHERE design_status IS NOT NULL;

-- 2. Artifacts: per-feature design outputs (specs, sketches, screenshots,
-- annotations, rejected candidates, etc.). 1:N with features.
CREATE TABLE IF NOT EXISTS harness_shared.harness_design_artifacts (
  id            TEXT NOT NULL,                   -- ULID, generated by writer
  harness_slug  TEXT NOT NULL,
  feature_id    TEXT NOT NULL,
  kind          TEXT NOT NULL,                   -- 'spec' | 'sketch' | 'screenshot' | 'annotation' | 'rejected_candidate'
  payload       JSONB NOT NULL,                  -- shape depends on kind
  metadata      JSONB,                           -- cost_usd, tokens_in/out, model_id, elapsed_ms, etc.
  created_ts    BIGINT NOT NULL,
  PRIMARY KEY (harness_slug, id),
  CONSTRAINT hda_kind_chk CHECK (
    kind IN ('spec', 'sketch', 'screenshot', 'annotation', 'rejected_candidate')
  )
);

CREATE INDEX IF NOT EXISTS hda_feature_idx
  ON harness_shared.harness_design_artifacts(harness_slug, feature_id);
CREATE INDEX IF NOT EXISTS hda_kind_idx
  ON harness_shared.harness_design_artifacts(harness_slug, feature_id, kind);
CREATE INDEX IF NOT EXISTS hda_created_idx
  ON harness_shared.harness_design_artifacts(harness_slug, created_ts DESC);

GRANT SELECT, INSERT, UPDATE, DELETE
  ON harness_shared.harness_design_artifacts
  TO harness_app, harness_admin;

-- 3. Update the per-harness → consolidated sync trigger so legacy writers
-- (linear-sync, jira-sync, the libs/papercusp/apps/web hono route — anything
-- still INSERT-ing into per-harness harness_features tables) propagate the
-- new fields. NULL defaults are fine because new columns are nullable or
-- have safe default values.
CREATE OR REPLACE FUNCTION harness_shared.sync_features_consolidated()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'DELETE') THEN
    DELETE FROM harness_shared.harness_features_consolidated
      WHERE harness_slug = OLD.harness_slug AND feature_id = OLD.feature_id;
    RETURN OLD;
  END IF;
  INSERT INTO harness_shared.harness_features_consolidated (
    harness_slug, feature_id, title, summary, status, attempts, claims, notes,
    metadata, kind, project_id, expected_cost_cents, tags, needs_human_review,
    ts, created_ts, updated_ts, parent_id, goal_id, taken_by, taken_at, expires_at,
    deprecation_reason
  ) VALUES (
    NEW.harness_slug, NEW.feature_id, NEW.title, NEW.summary, NEW.status,
    NEW.attempts, NEW.claims, NEW.notes, NEW.metadata, NEW.kind, NEW.project_id,
    NEW.expected_cost_cents, NEW.tags, NEW.needs_human_review, NEW.ts,
    NEW.created_ts, NEW.updated_ts, NEW.parent_id, NEW.goal_id,
    NEW.taken_by, NEW.taken_at, NEW.expires_at,
    NEW.deprecation_reason
  )
  ON CONFLICT (harness_slug, feature_id) DO UPDATE SET
    title               = EXCLUDED.title,
    summary             = EXCLUDED.summary,
    status              = EXCLUDED.status,
    attempts            = EXCLUDED.attempts,
    claims              = EXCLUDED.claims,
    notes               = EXCLUDED.notes,
    metadata            = EXCLUDED.metadata,
    kind                = EXCLUDED.kind,
    project_id          = EXCLUDED.project_id,
    expected_cost_cents = EXCLUDED.expected_cost_cents,
    tags                = EXCLUDED.tags,
    needs_human_review  = EXCLUDED.needs_human_review,
    ts                  = EXCLUDED.ts,
    created_ts          = EXCLUDED.created_ts,
    updated_ts          = EXCLUDED.updated_ts,
    parent_id           = EXCLUDED.parent_id,
    goal_id             = EXCLUDED.goal_id,
    taken_by            = EXCLUDED.taken_by,
    taken_at            = EXCLUDED.taken_at,
    expires_at          = EXCLUDED.expires_at,
    deprecation_reason  = EXCLUDED.deprecation_reason;
    -- design_* columns are NOT mirrored from per-harness tables; they are
    -- written directly to consolidated (canonical store).
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMIT;
