[package]
name = "papercusp-heap-retainers"
version = "0.1.0"
edition = "2021"
publish = false
license = "UNLICENSED"

[dependencies]
v8-heap-parser = { git = "https://github.com/microsoft/vscode-v8-heap-tools", rev = "05edd8131a77790ab0e7bce2eedf5770d6bb83ae" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
