-- Durable request identity for blueprint operation admission. The canonical
-- work item or plan run remains the outcome and history store. A receipt is
-- retained across transport reconnects and does not inherit the one-hour MCP
-- result-replay or two-hour governor queue retention windows.
CREATE TABLE IF NOT EXISTS harness_shared.blueprint_operation_invocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id text NOT NULL,
  harness_slug text NOT NULL,
  caller_id text NOT NULL,
  operation_id text NOT NULL,
  request_key text NOT NULL,
  request_fingerprint text NOT NULL CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  specification_revision text NOT NULL CHECK (specification_revision ~ '^[0-9a-f]{64}$'),
  target_kind text NOT NULL CHECK (target_kind IN ('work-item', 'plan')),
  target_ref text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, harness_slug, caller_id, operation_id, request_key)
);

COMMENT ON TABLE harness_shared.blueprint_operation_invocations IS
  'Durable request identity for blueprint operation admission; canonical work_items and plan_runs retain outcome authority.';

ALTER TABLE harness_shared.blueprint_operation_invocations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS blueprint_operation_invocations_workspace_isolation
  ON harness_shared.blueprint_operation_invocations;
CREATE POLICY blueprint_operation_invocations_workspace_isolation
  ON harness_shared.blueprint_operation_invocations
  USING (workspace_id = current_setting('app.workspace_id', true))
  WITH CHECK (workspace_id = current_setting('app.workspace_id', true));

GRANT SELECT, INSERT, UPDATE ON harness_shared.blueprint_operation_invocations TO harness_app;
GRANT SELECT ON harness_shared.blueprint_operation_invocations TO harness_zero;
GRANT USAGE, SELECT ON SEQUENCE harness_shared.blueprint_operation_invocations_id_seq TO harness_app;

-- The crash-recovery path scans by request key through the unified canonical
-- work_items base table (migration 374). One index covers both item families.
CREATE INDEX IF NOT EXISTS blueprint_invocation_item_recovery_idx
  ON harness_shared.work_items
    (workspace_id, harness_slug,
     ((payload->'blueprintOperation'->>'operationId')),
     ((payload->'blueprintOperation'->>'callerId')),
     ((payload->'blueprintOperation'->>'requestKey')))
  WHERE payload ? 'blueprintOperation';

-- A run instance is a snapshot of an already admitted template, not a new
-- author plan. Migration 1111's original trigger stamped every non-rubric
-- INSERT as a new BAR subject, so promotion of a legacy template's instance
-- immediately failed against an empty post-epoch cohort. Keep ordinary new
-- plans strict; exempt only the canonical template@run-<digits> instance shape.
CREATE OR REPLACE FUNCTION harness_shared.stamp_acceptance_bar_epoch()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.template IS DISTINCT FROM 'rubric'
     AND NOT (NEW.template_slug IS NOT NULL AND NEW.plan_slug ~ '.+@run-[0-9]+$')
     AND NEW.acceptance_bar_epoch IS NULL THEN
    NEW.acceptance_bar_epoch := 1;
    NEW.acceptance_bar_cohort := 'post-epoch';
  END IF;
  RETURN NEW;
END;
$fn$;
