-- 252-deferral-pricing-model.sql
--
-- self-learning-frontier-2026-06-12 (P-042 / FB-14): deferral interest — the
-- LEARNED successor of consume-edges B-08's static blocking-impact score
-- (frontier D-006). The refit loop (system:deferral-interest-refit) backfills
-- realized deferral costs from history (human-lane items → downstream blockage
-- accrued while each sat deferred, counted over timestamped coord_links edges +
-- same-signature re-captures) and fits an inspectable multiplicative-rate
-- pricing model; the latest version prices NEW deferrals at creation as a
-- named feature for the one queue ranker (P-040 / FB-12, D-005).
--
-- One row per trained model VERSION (append-only — a trained model is history;
-- re-fitting writes a new row, the read side takes the latest per workspace):
--
--   model:        the serialized DeferralPricingModel (version, global rate,
--                 per-bucket shrunken coefficients with sample sizes — every
--                 coefficient is named + inspectable, D-005).
--   sample_items: deferral items in the training set (the honest-v0 weakness
--                 signal — coefficients are weak until weeks of outcomes accrue).
--   sample_weeks: total deferral-exposure weeks the rates were pooled over.
--
-- Volume: one row per refit (nightly cadence when armed) — tens per month.
-- No RLS (mirrors 245-negative-space-demand): the refit loop and the feature
-- read scope by workspace_id explicitly.

CREATE TABLE IF NOT EXISTS harness_shared.deferral_pricing_model (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    trained_at   timestamptz NOT NULL DEFAULT now(),
    model        jsonb NOT NULL,
    sample_items integer NOT NULL,
    sample_weeks numeric NOT NULL,
    created_by   text,
    CONSTRAINT deferral_pricing_model_workspace_nonempty CHECK (workspace_id <> ''),
    CONSTRAINT deferral_pricing_model_items_nonneg CHECK (sample_items >= 0),
    CONSTRAINT deferral_pricing_model_weeks_nonneg CHECK (sample_weeks >= 0)
);

CREATE INDEX IF NOT EXISTS deferral_pricing_model_latest_idx
  ON harness_shared.deferral_pricing_model USING btree (workspace_id, trained_at DESC);

GRANT SELECT, INSERT ON harness_shared.deferral_pricing_model TO harness_app;
GRANT USAGE, SELECT ON SEQUENCE harness_shared.deferral_pricing_model_id_seq TO harness_app;
-- Append-only at the GRANT level (the 246 lesson: the baseline's ALTER DEFAULT
-- PRIVILEGES hands harness_app ALL on every new table at CREATE time — revoke
-- the widening explicitly; a trained model version is history).
REVOKE UPDATE, DELETE, TRUNCATE ON harness_shared.deferral_pricing_model FROM harness_app;
DO $z$ BEGIN
  GRANT SELECT ON harness_shared.deferral_pricing_model TO harness_zero;
  REVOKE UPDATE, DELETE, TRUNCATE ON harness_shared.deferral_pricing_model FROM harness_zero;
EXCEPTION WHEN undefined_object THEN NULL;
END $z$;
