-- 367-work-item-deps.sql
--
-- work-item-deps-and-readiness-2026-06-22 — P-002 (the dedicated dependency table).
--
-- WHY: blocking currently rides coord_links rel='blocks' — a polymorphic, opaque-text-ref, NO-FK,
-- mixed hot table (also backs tagged/relates/duplicates/fixes). Scheduling dependencies are now a
-- first-class concern; they get a dedicated, single-purpose, well-indexed table. This is the new
-- source of truth that the blockersOf() seam (P-001) will read from (P-003 flips the seam's backend
-- + migrates the existing coord_links blocks edges here, then mig-366's bespoke coord_links trigger
-- is dropped). FK + cascade-on-delete arrive when work-items unify (P-009 — opaque refs until then,
-- like coord_links, because work-items still span two base tables).
--
-- ACYCLICITY is enforced at the WRITER (P-008, reusing detectDependencyCycle) — a CHECK can't see
-- the transitive graph. The no-self-block CHECK here is the trivial 1-cycle guard.
--
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE). New table + indexes; no rewrite of existing data.

CREATE TABLE IF NOT EXISTS harness_shared.work_item_deps (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  text        NOT NULL DEFAULT 'default',
    blocked_kind  text        NOT NULL,           -- the item whose readiness depends on the blocker
    blocked_ref   text        NOT NULL,
    blocker_kind  text        NOT NULL,           -- the item that must be terminal before blocked is ready
    blocker_ref   text        NOT NULL,
    dep_type      text        NOT NULL DEFAULT 'blocks',  -- 'blocks' today; room for 'soft' / 'or-group:<g>'
    created_by    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT work_item_deps_endpoints_nonempty
      CHECK (blocked_kind <> '' AND blocked_ref <> '' AND blocker_kind <> '' AND blocker_ref <> ''),
    CONSTRAINT work_item_deps_workspace_nonempty CHECK (workspace_id <> ''),
    CONSTRAINT work_item_deps_no_self
      CHECK (NOT (blocked_kind = blocker_kind AND blocked_ref = blocker_ref))
);

COMMENT ON TABLE harness_shared.work_item_deps IS
  'First-class work-item dependency edges (work-item-deps-and-readiness-2026-06-22 P-002). dep_type=blocks: blocked_ref is ready only when blocker_ref is terminal. Replaces coord_links rel=blocks for work-item blocking (issue->plan_item edges stay on coord_links). FK to the unified work_items base table lands with P-009. Read via the blockersOf() seam (work-item-blocking.ts), never directly.';

-- One edge per (workspace, blocked, blocker, dep_type) — idempotent dual-writes / no duplicate edges.
CREATE UNIQUE INDEX IF NOT EXISTS work_item_deps_edge_uniq
  ON harness_shared.work_item_deps (workspace_id, blocked_kind, blocked_ref, blocker_kind, blocker_ref, dep_type);

-- Forward "what blocks me" (readiness of a blocked item).
CREATE INDEX IF NOT EXISTS work_item_deps_blocked_idx
  ON harness_shared.work_item_deps (workspace_id, blocked_kind, blocked_ref);

-- Reverse "what I block" (readiness re-propagation when a blocker reaches terminal — the one-hop scope).
CREATE INDEX IF NOT EXISTS work_item_deps_blocker_idx
  ON harness_shared.work_item_deps (workspace_id, blocker_kind, blocker_ref);

-- Scoped change-notify trigger: emits the affected refs + the CORRECT app.workspace_id GUC (the
-- generic emit_change_notify reads the wrong papercusp.workspace_id — fixed globally in P-006). A
-- dedicated trigger (not the generic one) because readiness invalidation needs the semantic
-- blocked/blocker refs, not the dep row's PK.
CREATE OR REPLACE FUNCTION harness_shared.emit_work_item_dep_change_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  ws_id   text;
  payload jsonb;
BEGIN
  ws_id := current_setting('app.workspace_id', true);
  payload := jsonb_build_object(
    'name', 'harness_shared.work_item_deps.changed',
    'args', jsonb_build_object(
      'workspace_id', ws_id,
      'op',           TG_OP,
      'dep_type',     COALESCE(NEW.dep_type,     OLD.dep_type),
      'blocked_kind', COALESCE(NEW.blocked_kind, OLD.blocked_kind),
      'blocked_ref',  COALESCE(NEW.blocked_ref,  OLD.blocked_ref),
      'blocker_kind', COALESCE(NEW.blocker_kind, OLD.blocker_kind),
      'blocker_ref',  COALESCE(NEW.blocker_ref,  OLD.blocker_ref)
    )
  );
  PERFORM pg_notify('sync_invalidate', payload::text);
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER emit_work_item_dep_change_notify_trg
    AFTER INSERT OR UPDATE OR DELETE ON harness_shared.work_item_deps
    FOR EACH ROW EXECUTE FUNCTION harness_shared.emit_work_item_dep_change_notify();
