-- 855 — exact work-item → immutable spec-revision coverage and evidence bindings.
--
-- Plan first-class-spec-clauses-and-prior-attempt-briefs-2026-08-20 P-005,
-- decisions D-001, D-003 and D-006. This is expand-only: the legacy coversVALs
-- projection remains readable through plan_spec_clauses.source_val_id, while new
-- evidence names an exact immutable revision and carries the fingerprints needed
-- to decide whether that historical proof is current.

-- work_items kept its pre-workspace PK (harness_slug, feature_id). The scoped
-- unique key lets new relations enforce the workspace too without replacing that
-- live PK or changing any existing writer.
CREATE UNIQUE INDEX IF NOT EXISTS work_items_scoped_identity
  ON harness_shared.work_items (workspace_id, harness_slug, feature_id);

-- A content hash is functionally determined by the immutable revision PK. Include
-- it in a unique key so the edge's spec_fingerprint is database-verified rather
-- than merely trusted application metadata.
CREATE UNIQUE INDEX IF NOT EXISTS plan_spec_clause_revisions_content_identity
  ON harness_shared.plan_spec_clause_revisions
    (workspace_id, harness_slug, plan_slug, spec_id, revision, content_hash);

CREATE TABLE IF NOT EXISTS harness_shared.work_item_spec_revision_edges (
  workspace_id    text        NOT NULL,
  harness_slug    text        NOT NULL,
  work_item_id    text        NOT NULL,
  plan_slug       text        NOT NULL,
  spec_id         text        NOT NULL,
  spec_revision   integer     NOT NULL CHECK (spec_revision > 0),
  spec_fingerprint text       NOT NULL CHECK (spec_fingerprint ~ '^[0-9a-f]{64}$'),
  created_by      text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (
    workspace_id, harness_slug, work_item_id,
    plan_slug, spec_id, spec_revision
  ),
  UNIQUE (
    workspace_id, harness_slug, work_item_id,
    plan_slug, spec_id, spec_revision, spec_fingerprint
  ),
  FOREIGN KEY (workspace_id, harness_slug, work_item_id)
    REFERENCES harness_shared.work_items (workspace_id, harness_slug, feature_id)
    ON DELETE RESTRICT,
  FOREIGN KEY (
    workspace_id, harness_slug, plan_slug, spec_id,
    spec_revision, spec_fingerprint
  ) REFERENCES harness_shared.plan_spec_clause_revisions
      (workspace_id, harness_slug, plan_slug, spec_id, revision, content_hash)
    ON DELETE RESTRICT
);

COMMENT ON TABLE harness_shared.work_item_spec_revision_edges IS
  'Append-only many-to-many coverage claims from execution work items to exact immutable plan spec revisions. A later spec revision does not rewrite an old edge; readers classify it stale against plan_spec_clauses.current_revision.';
COMMENT ON COLUMN harness_shared.work_item_spec_revision_edges.work_item_id IS
  'Canonical work-item id; references work_items.feature_id, whose legacy column name is retained after work-item unification.';
COMMENT ON COLUMN harness_shared.work_item_spec_revision_edges.spec_fingerprint IS
  'The referenced immutable revision content_hash, enforced by the composite FK. This is the spec freshness root (D-003).';

CREATE INDEX IF NOT EXISTS work_item_spec_revision_edges_by_spec
  ON harness_shared.work_item_spec_revision_edges
    (workspace_id, harness_slug, plan_slug, spec_id, spec_revision, work_item_id);

CREATE TABLE IF NOT EXISTS harness_shared.spec_evidence_bindings (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id          text        NOT NULL,
  harness_slug          text        NOT NULL,
  work_item_id          text        NOT NULL,
  plan_slug             text        NOT NULL,
  spec_id               text        NOT NULL,
  spec_revision         integer     NOT NULL CHECK (spec_revision > 0),
  spec_fingerprint      text        NOT NULL CHECK (spec_fingerprint ~ '^[0-9a-f]{64}$'),
  evidence_kind         text        NOT NULL CHECK (evidence_kind IN (
    'test', 'fixture', 'coverage-census', 'mutation', 'counterexample',
    'check', 'manual', 'operational'
  )),
  evidence_ref          text        NOT NULL CHECK (length(btrim(evidence_ref)) > 0),
  source_fingerprint    text        NOT NULL CHECK (length(btrim(source_fingerprint)) > 0),
  test_fingerprint      text        CHECK (test_fingerprint IS NULL OR length(btrim(test_fingerprint)) > 0),
  fixture_fingerprint   text        CHECK (fixture_fingerprint IS NULL OR length(btrim(fixture_fingerprint)) > 0),
  rubric_fingerprint    text        CHECK (rubric_fingerprint IS NULL OR length(btrim(rubric_fingerprint)) > 0),
  environment_fingerprint text      CHECK (environment_fingerprint IS NULL OR length(btrim(environment_fingerprint)) > 0),
  coverage_evidence_ref bigint,
  test_run_id           bigint,
  details               jsonb       NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details) = 'object'),
  observed_at           timestamptz NOT NULL DEFAULT now(),
  binding_fingerprint   text        NOT NULL CHECK (binding_fingerprint ~ '^[0-9a-f]{64}$'),
  created_by            text        NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (
    workspace_id, harness_slug, work_item_id,
    plan_slug, spec_id, spec_revision, spec_fingerprint
  ) REFERENCES harness_shared.work_item_spec_revision_edges
      (workspace_id, harness_slug, work_item_id,
       plan_slug, spec_id, spec_revision, spec_fingerprint)
    ON DELETE RESTRICT
);

COMMENT ON TABLE harness_shared.spec_evidence_bindings IS
  'Append-only proof bindings for exact work-item/spec-revision edges. Currentness is computed by comparing stored fingerprints and exact revision identity with current inputs; it is never stored as a drifting boolean.';
COMMENT ON COLUMN harness_shared.spec_evidence_bindings.coverage_evidence_ref IS
  'Optional historical reference to coverage_evidence.id. Validated for workspace/harness at insert time but deliberately not an FK: retiring a testing surface may prune that source row, while this immutable binding must retain the exact id it cited and then report it stale.';
COMMENT ON COLUMN harness_shared.spec_evidence_bindings.test_run_id IS
  'Optional historical reference to test_runs.id. Validated for workspace/harness at insert time but deliberately not an FK so ordinary run-ledger pruning cannot rewrite or delete historical proof.';
COMMENT ON COLUMN harness_shared.spec_evidence_bindings.binding_fingerprint IS
  'SHA-256 over the canonical semantic binding (edge, kind/ref, all fingerprints, linked evidence ids, and details). Exact replays are idempotent; changed proof appends a new row.';

CREATE UNIQUE INDEX IF NOT EXISTS spec_evidence_bindings_dedup
  ON harness_shared.spec_evidence_bindings (
    workspace_id, harness_slug, work_item_id,
    plan_slug, spec_id, spec_revision, binding_fingerprint
  );

CREATE INDEX IF NOT EXISTS spec_evidence_bindings_by_spec
  ON harness_shared.spec_evidence_bindings
    (workspace_id, harness_slug, plan_slug, spec_id, spec_revision, observed_at DESC);

CREATE INDEX IF NOT EXISTS spec_evidence_bindings_by_work_item
  ON harness_shared.spec_evidence_bindings
    (workspace_id, harness_slug, work_item_id, observed_at DESC);

-- Optional references are cross-table historical pointers. Validate their scope
-- on INSERT so a raw writer cannot bind another tenant's evidence, while leaving
-- the scalar intact if its source ledger is later pruned.
CREATE OR REPLACE FUNCTION harness_shared.validate_spec_evidence_binding_refs()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.coverage_evidence_ref IS NOT NULL AND NOT EXISTS (
    SELECT 1
      FROM harness_shared.coverage_evidence e
      JOIN harness_shared.testing_surfaces s ON s.id = e.surface_ref
     WHERE e.id = NEW.coverage_evidence_ref
       AND s.workspace_id = NEW.workspace_id
       AND s.harness_slug = NEW.harness_slug
  ) THEN
    RAISE EXCEPTION 'coverage evidence % does not belong to workspace % harness %',
      NEW.coverage_evidence_ref, NEW.workspace_id, NEW.harness_slug
      USING ERRCODE = '23503';
  END IF;

  IF NEW.test_run_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
      FROM harness_shared.test_runs r
     WHERE r.id = NEW.test_run_id
       AND r.workspace_id = NEW.workspace_id
       AND r.harness_slug = NEW.harness_slug
  ) THEN
    RAISE EXCEPTION 'test run % does not belong to workspace % harness %',
      NEW.test_run_id, NEW.workspace_id, NEW.harness_slug
      USING ERRCODE = '23503';
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS spec_evidence_bindings_validate_refs
  ON harness_shared.spec_evidence_bindings;
CREATE TRIGGER spec_evidence_bindings_validate_refs
  BEFORE INSERT ON harness_shared.spec_evidence_bindings
  FOR EACH ROW EXECUTE FUNCTION harness_shared.validate_spec_evidence_binding_refs();

CREATE OR REPLACE FUNCTION harness_shared.reject_spec_evidence_history_mutation()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  RAISE EXCEPTION '% is append-only; append a new exact evidence binding', TG_TABLE_NAME
    USING ERRCODE = '55000';
END;
$fn$;

DROP TRIGGER IF EXISTS work_item_spec_revision_edges_immutable
  ON harness_shared.work_item_spec_revision_edges;
CREATE TRIGGER work_item_spec_revision_edges_immutable
  BEFORE UPDATE OR DELETE ON harness_shared.work_item_spec_revision_edges
  FOR EACH ROW EXECUTE FUNCTION harness_shared.reject_spec_evidence_history_mutation();

DROP TRIGGER IF EXISTS spec_evidence_bindings_immutable
  ON harness_shared.spec_evidence_bindings;
CREATE TRIGGER spec_evidence_bindings_immutable
  BEFORE UPDATE OR DELETE ON harness_shared.spec_evidence_bindings
  FOR EACH ROW EXECUTE FUNCTION harness_shared.reject_spec_evidence_history_mutation();

ALTER TABLE harness_shared.work_item_spec_revision_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE harness_shared.spec_evidence_bindings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS work_item_spec_revision_edges_workspace_isolation
  ON harness_shared.work_item_spec_revision_edges;
CREATE POLICY work_item_spec_revision_edges_workspace_isolation
  ON harness_shared.work_item_spec_revision_edges
  FOR ALL TO public
  USING (workspace_id = current_setting('app.workspace_id', true))
  WITH CHECK (workspace_id = current_setting('app.workspace_id', true));

DROP POLICY IF EXISTS spec_evidence_bindings_workspace_isolation
  ON harness_shared.spec_evidence_bindings;
CREATE POLICY spec_evidence_bindings_workspace_isolation
  ON harness_shared.spec_evidence_bindings
  FOR ALL TO public
  USING (workspace_id = current_setting('app.workspace_id', true))
  WITH CHECK (workspace_id = current_setting('app.workspace_id', true));

GRANT SELECT, INSERT ON harness_shared.work_item_spec_revision_edges TO harness_app, harness_admin;
GRANT SELECT, INSERT ON harness_shared.spec_evidence_bindings TO harness_app, harness_admin;
GRANT USAGE, SELECT ON SEQUENCE harness_shared.spec_evidence_bindings_id_seq TO harness_app, harness_admin;
